	.align 2
voicegroup310::
	voice_keysplit_all voicegroup002
	voice_keysplit voicegroup005, KeySplitTable1
	voice_keysplit voicegroup193, KeySplitTable6
	voice_keysplit voicegroup194, KeySplitTable6
	voice_keysplit voicegroup195, KeySplitTable7
	voice_keysplit voicegroup196, KeySplitTable8
	voice_keysplit voicegroup197, KeySplitTable9
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_4, 1, 7, 15, 1
	voice_keysplit voicegroup199, KeySplitTable7
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 242
	voice_keysplit voicegroup005, KeySplitTable1
	voice_keysplit voicegroup202, KeySplitTable11
	voice_keysplit voicegroup203, KeySplitTable13
	voice_keysplit voicegroup204, KeySplitTable14
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 216, 90, 242
	voice_directsound 60, 0, DirectSoundWaveData_1000008, 255, 249, 0, 235
	voice_keysplit voicegroup206, KeySplitTable16
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 210
	voice_keysplit voicegroup208, KeySplitTable17
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 76, 154, 188
	voice_keysplit voicegroup211, KeySplitTable17
	voice_keysplit voicegroup212, KeySplitTable18
	voice_keysplit voicegroup213, KeySplitTable19
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 149
	voice_keysplit voicegroup215, KeySplitTable9
	voice_square_2 60, 0, 3, 0, 6, 0, 0
	voice_keysplit voicegroup217, KeySplitTable9
	voice_keysplit voicegroup218, KeySplitTable19
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 255, 127
	voice_keysplit voicegroup221, KeySplitTable22
	voice_keysplit voicegroup222, KeySplitTable16
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 99
	voice_keysplit voicegroup224, KeySplitTable10
	voice_keysplit voicegroup225, KeySplitTable20
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 99
	voice_keysplit voicegroup227, KeySplitTable23
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 216
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 7, 6, 2
	voice_keysplit voicegroup230, KeySplitTable24
	voice_keysplit voicegroup231, KeySplitTable22
	voice_keysplit voicegroup232, KeySplitTable22
	voice_keysplit voicegroup233, KeySplitTable25
	voice_keysplit voicegroup234, KeySplitTable25
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 226, 0, 38
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 246, 0, 226
	voice_keysplit voicegroup006, KeySplitTable2
	voice_keysplit voicegroup238, KeySplitTable12
	voice_keysplit voicegroup239, KeySplitTable12
	voice_keysplit voicegroup240, KeySplitTable18
	voice_keysplit voicegroup241, KeySplitTable18
	voice_keysplit voicegroup242, KeySplitTable16
	voice_keysplit voicegroup243, KeySplitTable24
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188
	voice_keysplit voicegroup007, KeySplitTable3
	voice_keysplit voicegroup245, KeySplitTable21
	voice_keysplit voicegroup008, KeySplitTable4
	voice_keysplit voicegroup247, KeySplitTable26
	voice_keysplit voicegroup009, KeySplitTable5
	voice_keysplit voicegroup249, KeySplitTable28
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 0, 255, 127	
	voice_keysplit voicegroup251, KeySplitTable19
	voice_keysplit voicegroup252, KeySplitTable29
	voice_keysplit voicegroup253, KeySplitTable27
	voice_keysplit voicegroup254, KeySplitTable25
	voice_keysplit voicegroup255, KeySplitTable26
	voice_keysplit voicegroup256, KeySplitTable19
	voice_keysplit voicegroup257, KeySplitTable20
	voice_keysplit voicegroup258, KeySplitTable27
	voice_keysplit voicegroup259, KeySplitTable29
	voice_keysplit voicegroup260, KeySplitTable30
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 165
	voice_keysplit voicegroup262, KeySplitTable27
	voice_keysplit voicegroup263, KeySplitTable30
	voice_keysplit voicegroup264, KeySplitTable31
	voice_keysplit voicegroup265, KeySplitTable31
	voice_keysplit voicegroup266, KeySplitTable13
	voice_keysplit voicegroup267, KeySplitTable7
	voice_square_2_alt 60, 0, 2, 0, 1, 4, 1
	voice_keysplit voicegroup269, KeySplitTable30
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 7, 15, 2
	voice_keysplit voicegroup271, KeySplitTable14
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 4, 4
	voice_keysplit voicegroup273, KeySplitTable15
	voice_keysplit voicegroup274, KeySplitTable33
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 0
	voice_keysplit voicegroup276, KeySplitTable14
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_7, 0, 7, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_7, 0, 7, 15, 1
	voice_keysplit voicegroup279, KeySplitTable8
	voice_directsound 60, 0, DirectSoundWaveData_1005b5c, 255, 0, 255, 235
	voice_keysplit voicegroup280, KeySplitTable8
	voice_keysplit voicegroup281, KeySplitTable7
	voice_keysplit voicegroup282, KeySplitTable15
	voice_keysplit voicegroup283, KeySplitTable18
	voice_keysplit voicegroup284, KeySplitTable31
	voice_keysplit voicegroup285, KeySplitTable33
	voice_keysplit voicegroup286, KeySplitTable33
	voice_keysplit voicegroup287, KeySplitTable34
	voice_keysplit voicegroup288, KeySplitTable34
	voice_directsound 60, 0, DirectSoundWaveData_1007514, 255, 0, 255, 235
	voice_keysplit voicegroup289, KeySplitTable15
	voice_keysplit voicegroup290, KeySplitTable32
	voice_square_2_alt 60, 0, 0, 1, 2, 4, 1
	voice_keysplit voicegroup292, KeySplitTable35
	voice_keysplit voicegroup293, KeySplitTable35
	voice_keysplit voicegroup294, KeySplitTable29
	voice_square_2_alt 60, 0, 0, 1, 1, 6, 1
	voice_keysplit voicegroup296, KeySplitTable30
	voice_keysplit voicegroup297, KeySplitTable25
	voice_keysplit voicegroup298, KeySplitTable35
	voice_directsound 60, 0, DirectSoundWaveData_1008da0, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1008e98, 255, 242, 0, 235
	voice_keysplit voicegroup299, KeySplitTable34
	voice_directsound 60, 0, DirectSoundWaveData_10094ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1009b80, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_100aeac, 255, 0, 255, 235
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_100ec2c, 255, 0, 255, 235
	voice_keysplit voicegroup300, KeySplitTable32
	voice_directsound 60, 0, DirectSoundWaveData_100f5f8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1012b70, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1013b38, 255, 0, 255, 235
	voice_noise_alt 60, 0, 0, 0, 1, 7, 1
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0


