CeladonCity_Casino2_MapScripts::
	.byte 0

CeladonCasino2_1::
lock     
faceplayer     
msgbox CeladonCity_Casino2_Text_1, MSGBOX_DEFAULT
release     
end

CeladonCity_Casino2_Text_1:
	.string "Ich will unbedingt ein PORYGON haben!\n"
	.string "Aber all die erforderlichen MÜNZEN zu\l"
	.string "sammeln, wird die Hölle!$"



CeladonCasino2_2::
lock     
faceplayer     
msgbox CeladonCity_Casino2_Text_2, MSGBOX_DEFAULT
release     
end

CeladonCity_Casino2_Text_2:
	.string "Hahahaha! Heute ist mein Tag! Wenn nur\n"
	.string "jeder Tag wie heute wäre {PAUSE 5}…{PAUSE 5}$"



CeladonCasino2_3::
lock     
faceplayer     
msgbox CeladonCity_Casino2_Text_3, MSGBOX_DEFAULT
release     
end

CeladonCity_Casino2_Text_3:
	.string "MITGLIEDERN VON TEAM ROCKET ist es\n"
	.string "nicht erlaubt, hier MÜNZEN zu kaufen.\p"
	.string "So sagen es die Regeln der SPIELHALLE.$"



CeladonCasino2_4::
lock     
faceplayer     
msgbox CeladonCity_Casino2_Text_4, MSGBOX_DEFAULT
release     
end

CeladonCity_Casino2_Text_4:
	.string "MITGLIEDERN VON TEAM ROCKET ist es\n"
	.string "nicht erlaubt, hier MÜNZEN zu kaufen.\n"
	.string "So sagen es die Regeln der SPIELHALLE.$"
