CeladonCity_Casino2_MapScripts::
	.byte 0

CeladonCasino2_1::
lock     
faceplayer     
msgbox CeladonCity_Casino2_Text_1, MSGBOX_DEFAULT
release     
end

CeladonCity_Casino2_Text_1:
	.string "I want a PORYGON! But getting all those\n"
	.string "TOKENS will be harsh!$"



CeladonCasino2_2::
lock     
faceplayer     
msgbox CeladonCity_Casino2_Text_2, MSGBOX_DEFAULT
release     
end

CeladonCity_Casino2_Text_2:
	.string "Hahahaha! Today is my day! Just if\n"
	.string "every other day were just like today…$"



CeladonCasino2_3::
lock     
faceplayer     
msgbox CeladonCity_Casino2_Text_3, MSGBOX_DEFAULT
release     
end

CeladonCity_Casino2_Text_3:
	.string "Selling TOKENS to ROCKETS is forbidden,\n"
	.string "CASINO rules.$"



CeladonCasino2_4::
lock     
faceplayer     
msgbox CeladonCity_Casino2_Text_4, MSGBOX_DEFAULT
release     
end

CeladonCity_Casino2_Text_4:
	.string "Selling TOKENS to ROCKETS is forbidden,\n"
	.string "CASINO rules.$"
