CeladonCity_House2_MapScripts::
	.byte 0

CeladonCityHouse2-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "¡El negocio va sobre ruedas\n"
.string "recluta!\l"
.string "¡Continuad así!$"



CeladonCityHouse2-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "¡Así que vienes de ISLA INTA!\n"
.string "¡Bienvenido a KANTO!$"



CeladonCityHouse2-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "¡Más de 2000 POKÉMON han sido\n"
.string "enviados como premios en el CASINO\l"
.string "en los últimos días!$"
