Goldenrod_Underground_MapScripts::
	.byte 0

GoldenrodUnderground1::
end



GoldenrodUnderground2::
end



GoldenrodUnderground3::
end



GoldenrodUnderground4::
end



GoldenrodUnderground5::
end



GoldenrodUnderground6::
end



GoldenrodUnderground7::
end



GoldenrodUnderground8::
end



GoldenrodUnderground9::
lock     
faceplayer     
msgbox Text_9, MSGBOX_DEFAULT
release     
end

Text_9:
.string "Aquí puedes llegar a encontrar\n"
.string "cosas incluso más interesantes que\l"
.string "en el CASINO y el CENTRO\l"
.string "COMERCIAL.\l"
.string "¡Es lo que tiene el mercado negro,\l"
.string "nunca sabes lo que puedes\l"
.string "llegar a ver por aquí!$"



GoldenrodUnderground10::
end



GoldenrodUnderground11::
end
