SafariZone_3F_MapScripts::
	.byte 0

SafariZone3F_1::
end



SafariZone3F_2::
end



SafariZone3F_3::
end



SafariZone3FDocumento_100::
msgbox SafariZone3FDocumento_Text_100, MSGBOX_SIGN   
end

SafariZone3FDocumento_Text_100:
	.string "TRAINER TIPS\p"
	.string "Bis zum GEHEIMEN HAUS ist es\n"
	.string "nicht mehr weit weg!$"




SafariZone3FDocumento_101::
msgbox SafariZone3FDocumento_Text_101, MSGBOX_SIGN   
end

SafariZone3FDocumento_Text_101:
	.string "AREA 2$"



SafariZone3FDocumento_102::
msgbox SafariZone3FDocumento_Text_102, MSGBOX_SIGN   
end

SafariZone3FDocumento_Text_102:
	.string "TIPPS FÜR TRAINER\p"
	.string "POKéMON verstecken sich in hohem Gras!\p"
	.string "Laufe durch das hohe Gras und scheuche\n"
	.string "sie auf!$"




SafariZone3FDocumento_103::
msgbox SafariZone3FDocumento_Text_103, MSGBOX_SIGN   
end

SafariZone3FDocumento_Text_103:
	.string "TIPPS FÜR TRAINER\p"
	.string "Finde das GEHEIME HAUS.\n"
	.string "Dann gewinnst du eine VM!$"



SafariZone3FDocumento_104::
msgbox SafariZone3FDocumento_Text_104, MSGBOX_SIGN   
end

SafariZone3FDocumento_Text_104:
	.string "RASTHAUS$"
