SafariZone_3F_MapScripts::
	.byte 0

SafariZone3F_1::
end



SafariZone3F_2::
end



SafariZone3F_3::
end



SafariZone3FDocumento_100::
msgbox SafariZone3FDocumento_Text_100, MSGBOX_SIGN   
end

SafariZone3FDocumento_Text_100:
	.string "TRAINER TIPS\p"
	.string "The SECRET HOUSE is still ahead.$"




SafariZone3FDocumento_101::
msgbox SafariZone3FDocumento_Text_101, MSGBOX_SIGN   
end

SafariZone3FDocumento_Text_101:
	.string "AREA 2$"



SafariZone3FDocumento_102::
msgbox SafariZone3FDocumento_Text_102, MSGBOX_SIGN   
end

SafariZone3FDocumento_Text_102:
	.string "TRAINER TIPS\p"
	.string "POKÉMON hide in tall grass.\p"
	.string "Zigzag through grassy areas to\n"
	.string "flush them out.$"




SafariZone3FDocumento_103::
msgbox SafariZone3FDocumento_Text_103, MSGBOX_SIGN   
end

SafariZone3FDocumento_Text_103:
	.string "TRAINER TIPS\p"
	.string "Win a free HM for finding the\n"
	.string "SECRET HOUSE.$"



SafariZone3FDocumento_104::
msgbox SafariZone3FDocumento_Text_104, MSGBOX_SIGN   
end

SafariZone3FDocumento_Text_104:
	.string "REST HOUSE$"
