CeladonCity_PokemonCenter_1F_MapScripts::
	.byte 0

CeladonCityPokemonCenter1::
end



CeladonCityPokemonCenter2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "La POKÉ FLAUTA despierta a los\n"
.string "POKÉMON dormidos.\l"
.string "Al parecer emite un sonido que\l"
.string "solo estos pueden escuchar.$"



CeladonCityPokemonCenter3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Si tuviera una BICI,¡iría al\n"
.string "CAMINO BICIS!$"



CeladonCityPokemonCenter4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "Llegué aquí desde FUCSIA por el\n"
.string "CAMINO BICIS.\l"
.string "¡Estoy exhausta de pedalear todo\l"
.string "cuesta arriba!$"
