Violet_SproutTowerP1_MapScripts::
	.byte 0

VioletSproutTowerP1_1::
end



VioletSproutTowerP1_2::
end


VioletSproutTowerP1_3::
lock     
faceplayer     
msgbox VioletCity_SproutTowerP1_Text_3, MSGBOX_DEFAULT
release     
end

VioletCity_SproutTowerP1_Text_3:
.string "Vine desde PUEBLO LAVANDA a\n"
.string "presentar mis respetos a las\l"
.string "pagodas de CIUDAD IRIS y CIUDAD\l"
.string "MALVA, aunque de eso hace ya\l"
.string "tiempo, hasta que no abran las\l"
.string "fronteras no podré volver…$"



VioletSproutTowerP1_4::
end
