SixIsland_House1_MapScripts::
	.byte 0

SixIslandHouse1_1::
lock     
faceplayer     
msgbox SixIsland_House1_Text_1, MSGBOX_DEFAULT
release     
end

SixIsland_House1_Text_1:
.string "There's nothing that young people'd\n"
    .string "find exciting here on this island.\p"
    .string "But, this is a good place in terms\n"
    .string "of nature and history.\p"
    .string "Relax and enjoy your stay.$"
