ThreeIsland_MapScripts::
	.byte 0

ThreeIsland1::
end


ThreeIsland2::
end


ThreeIsland3::
end


ThreeIsland4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "Voy a entrenar a mi DODUO en el\n"
.string "BOSQUE BAYA.\p"
.string "Cuando evolucione, participaré\n"
.string "en algún juego en ISLA SECUNDA.$"


ThreeIsland5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "ISLA TERA es la isla más poblada\n"
.string "de esta zona.\p"
.string "Vale que no sea la más animada,\n"
.string "pero mejor así que tener a los\l"
.string "salvajes de las motos por aquí.$"
