Cave_Regigigas_S7_MapScripts::
	.byte 0

Cave_Regigigas_S7_Doctor::
lock
msgbox Cave_Regigigas_S7_Doctor_Texto_1 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_2 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_3 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_4 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_5 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_6 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_7 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_8 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_9 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_10 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_11 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_12 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_13 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_14 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_15 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_16 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_17 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_18 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_19 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_20 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_21 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_22 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_23 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_24 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_25 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_26 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_27 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_28 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_29 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_30 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_31 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_32 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_33 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_34 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_35 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_36 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_37 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_38 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_39 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_40 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_41 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_42 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_43 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_44 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_45 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_46 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_47 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_48 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_49 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_50 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_51 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_52 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_53 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_54 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_55 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_56 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_57 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_58 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_59 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_60 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_61 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_62 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_63 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_64 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_65 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_66 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_67 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_68 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_69 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_70 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_71 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_72 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_73 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_74 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_75 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_76 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_77 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S7_Doctor_Texto_78 MSGBOX_AUTOCLOSE
release
end

Cave_Regigigas_S7_Doctor_Texto_1:
	.string "C.MIGUEL: ¡Vosotros! ¡¿Cómo…?!$"

Cave_Regigigas_S7_Doctor_Texto_2:
	.string "DR.RASMUS: {PLAYER}, {PLAYER}...$"

Cave_Regigigas_S7_Doctor_Texto_3:
	.string "DR.RASMUS: Te has vuelto todo un\n"
	.string "experto en hacer de lo improbable algo\l"
	.string "de lo más común.$"

Cave_Regigigas_S7_Doctor_Texto_4:
	.string "Y a su lado tenemos a ANDRA, quién si no.$"

Cave_Regigigas_S7_Doctor_Texto_5:
	.string "Alguien que precisamente aborrece que\n"
	.string "lo extraordinario se normalice, y sin\l"
	.string "embargo no ha dudado en dejar todo\l"
	.string "atrás para ir tras su búsqueda.$"

Cave_Regigigas_S7_Doctor_Texto_6:
	.string "ANDRA: No has entendido nada.$"

Cave_Regigigas_S7_Doctor_Texto_7:
	.string "DR.RASMUS: Puede que si se lo explicas a\n"
	.string "tu antiguo socio, todos podamos\l"
	.string "entenderlo.$"

Cave_Regigigas_S7_Doctor_Texto_8:
	.string "¿Qué me dices, MIGUEL? Es tu\n"
	.string "oportunidad.$"

Cave_Regigigas_S7_Doctor_Texto_9:
	.string "C.MIGUEL: … …$"

Cave_Regigigas_S7_Doctor_Texto_10:
	.string "ANDRA: MIGUEL… pude ver a ese POKÉMON\n"
	.string "en PUEBLO LAVANDA.$"

Cave_Regigigas_S7_Doctor_Texto_11:
	.string "Créeme, si estás intentando lo que creo\n"
	.string "que estás intentando, este no es el\l"
	.string "camin…$"

Cave_Regigigas_S7_Doctor_Texto_12:
	.string "DR.RASMUS: ¡Suficiente!$"

Cave_Regigigas_S7_Doctor_Texto_13:
	.string "Alguien bendecida tratando de dar\n"
	.string "consejos que aplicados a otros jamás\l"
	.string "servirán para tocar el mismo cielo.$"

Cave_Regigigas_S7_Doctor_Texto_14:
	.string "Te creía más inteligente\n"
	.string "que todo eso, ANDRA.$"

Cave_Regigigas_S7_Doctor_Texto_15:
	.string "¡MIGUEL! ¡Sabes que no hay otra manera!$"

Cave_Regigigas_S7_Doctor_Texto_16:
	.string "¡Tienes que humillar a aquellos que\n"
	.string "estuvieron por encima tuya por\l"
	.string "trivialidades del destino, aplastarlos\l"
	.string "en un combate para dejar claro que te\l"
	.string "sobre pusiste con todo en contra!$"

Cave_Regigigas_S7_Doctor_Texto_17:
	.string "¡Ellos no merecen más que tú, solo te\n"
	.string "queda un último paso para alcanzar lo\l"
	.string "que tanto tiempo llevas buscando!$"

Cave_Regigigas_S7_Doctor_Texto_18:
	.string "Y para eso yo estoy aquí, ¡para\n"
	.string "ayudarte a lograrlo!$"

Cave_Regigigas_S7_Doctor_Texto_19:
	.string "Conmigo y con la tecnología que DEVON\n"
	.string "te ha proporcionado, ¡lo conseguirás!$"

Cave_Regigigas_S7_Doctor_Texto_20:
	.string "MIGUEL: S… ¡Sí! ¡Tienes razón!$"

Cave_Regigigas_S7_Doctor_Texto_21:
	.string "Te confesaré algo, {PLAYER}. Cuando\n"
	.string "ese ROJO nos destrozó en el MT.MOON\l"
	.string "sentí una profunda rabia.$"

Cave_Regigigas_S7_Doctor_Texto_22:
	.string "Que alguien de cualidades innatas tan\n"
	.string "excepcionales existiera me causaba un\l"
	.string "enorme sentimiento de impotencia e\l"
	.string "injusticia.$"

Cave_Regigigas_S7_Doctor_Texto_23:
	.string "Ese tipo apenas sabía hablar, era nulo\n"
	.string "en el trato social y… sin embargo…\l"
	.string "dominaba con absoluta maestría a sus\l"
	.string "POKÉMON. No porque hubiera hecho algo\l"
	.string "diferente al resto, solo por… mero\l"
	.string "capricho del destino.$"

Cave_Regigigas_S7_Doctor_Texto_24:
	.string "Aún así… con el tiempo… tú has llegado a\n"
	.string "convertirte en algo incluso más odioso.$"

Cave_Regigigas_S7_Doctor_Texto_25:
	.string "Tenías también esas cualidades y…\n"
	.string "además… las has explotado al máximo…\l"
	.string "haciendo imposible alcanzarte por\l"
	.string "medios naturales, ¡hiciera lo que\l"
	.string "hiciera!$"

Cave_Regigigas_S7_Doctor_Texto_26:
	.string "ANDRA: ¡Te equivocas, MIGUEL! ¡Siempre\n"
	.string "hay formas de seguir progresando!$"

Cave_Regigigas_S7_Doctor_Texto_27:
	.string "¡Cada uno debe seguir su camino, no\n"
	.string "todos van al mismo ritmo!$"

Cave_Regigigas_S7_Doctor_Texto_28:
	.string "MIGUEL: ¿Mismo ritmo? Hace ya tiempo\n"
	.string "que advertí mis propios límites.$"

Cave_Regigigas_S7_Doctor_Texto_29:
	.string "Hubiera dado cualquier cosa por\n"
	.string "equivocarme, pero no: vi con\l"
	.string "resignación cómo se cumplían todas y\l"
	.string "cada una de las predicciones que\l"
	.string "marcaban el fin de mi propio progreso,\l"
	.string "cómo era insuficiente para cumplir mis\l"
	.string "expectativas.$"

Cave_Regigigas_S7_Doctor_Texto_30:
	.string "Sí… veía esa asquerosa línea que\n"
	.string "marcaba una tendencia tan injusta como\l"
	.string "inexorable.$"

Cave_Regigigas_S7_Doctor_Texto_31:
	.string "¡Antes incluso de que vosotros os\n"
	.string "planteárais su existencia!$"

Cave_Regigigas_S7_Doctor_Texto_32:
	.string "ANDRA: Puede que esa sea precisamente\n"
	.string "la razón de tu estancamiento.$"

Cave_Regigigas_S7_Doctor_Texto_33:
	.string "MIGUEL: ¿Razón? ¿A qué quieres que\n"
	.string "espere? ¿¡A un milagro!?$"

Cave_Regigigas_S7_Doctor_Texto_34:
	.string "ANDRA: En ocasiones ocurren. Pero… solo\n"
	.string "si esperas hasta el final, cuando todos\l"
	.string "ya se han ido.$"

Cave_Regigigas_S7_Doctor_Texto_35:
	.string "MIGUEL: ¡Silencio! ¡No eres más que otra\n"
	.string "privilegiada! ¡Ya os he oído suficiente!$"

Cave_Regigigas_S7_Doctor_Texto_36:
	.string "Siendo las condiciones de partida tan\n"
	.string "dispares, ¡no queda otra que tomarnos\l"
	.string "la justicia por nuestra mano!$"

Cave_Regigigas_S7_Doctor_Texto_37:
	.string "DR.RASMUS: Bien dicho. El con estos dos\n"
	.string "'elegidos' haciendo uso de POKÉMON\l"
	.string "injustos a ojos de la naturaleza…$"

Cave_Regigigas_S7_Doctor_Texto_38:
	.string "…es un acto de justicia en sí mismo.$"

Cave_Regigigas_S7_Doctor_Texto_39:
	.string "MIGUEL: ¡Un acto que al fin\n"
	.string "me dará lo que ansío!$"

Cave_Regigigas_S7_Doctor_Texto_40:
	.string "¿¡Qué tengo que hacer para\n"
	.string "derrotarte!?$"

Cave_Regigigas_S7_Doctor_Texto_41:
	.string "Ya veo, aún falta para romper tu límite.$"

Cave_Regigigas_S7_Doctor_Texto_42:
	.string "MIGUEL: No… esto no debería ser así…\n"
	.string "se suponía que…$"

Cave_Regigigas_S7_Doctor_Texto_43:
	.string "DR.RASMUS: MIGUEL…estoy harto de ti.\n"
	.string "Eres un fraude, además de un traidor\l"
	.string "incompente.$"

Cave_Regigigas_S7_Doctor_Texto_44:
	.string "MIGUEL: ¿Q-qué?$"

Cave_Regigigas_S7_Doctor_Texto_45:
	.string "Con tu gran habilidad para pertenecer a\n"
	.string "cualquier bando, al final has\l"
	.string "demostrado no ser nadie en realidad.$"

Cave_Regigigas_S7_Doctor_Texto_46:
	.string "La esencia de tu personalidad no\n"
	.string "existe. Estás vacío, no tienes una cara\l"
	.string "propia.$"

Cave_Regigigas_S7_Doctor_Texto_47:
	.string "Eres capaz de trabajar para SILPH, el\n"
	.string "TEAM ROCKET o DEVON porque ningún\l"
	.string "rasgo propio te define.$"

Cave_Regigigas_S7_Doctor_Texto_48:
	.string "MIGUEL: ¡¿Qué quieres decir con eso?!$"

Cave_Regigigas_S7_Doctor_Texto_49:
	.string "DR.RASMUS: Ya te he dado innumerables\n"
	.string "oportunidades a lo largo de estos\l"
	.string "meses.$"

Cave_Regigigas_S7_Doctor_Texto_50:
	.string "He reducido mi poder en este combate,\n"
	.string "con la esperanza de que al fin dieses un\l"
	.string "paso al frente respecto a WRONGSPARCE.\l"
	.string "Y has vuelto a fracasar.$"

Cave_Regigigas_S7_Doctor_Texto_51:
	.string "Ahora veo que de donde no hay, es\n"
	.string "imposible sacar algo: Esperaba poco de\l"
	.string "ti y aún así me has decepcionado.$"

Cave_Regigigas_S7_Doctor_Texto_52:
	.string "Has demostrado no ser digno de nuestra\n"
	.string "confianza, tampoco de las expectativas\l"
	.string "que habíamos depositado en ti. ¿Sabes\l"
	.string "lo que eso significa?$"

Cave_Regigigas_S7_Doctor_Texto_53:
	.string "Que eres un perdedor. Siempre lo fuiste.$"

Cave_Regigigas_S7_Doctor_Texto_54:
	.string "MIGUEL: ¡NO!$"

Cave_Regigigas_S7_Doctor_Texto_55:
	.string "DR.RASMUS: Tu contrato con nosotros ha\n"
	.string "expirado. Ya no nos eres útil.$"

Cave_Regigigas_S7_Doctor_Texto_56:
	.string "MIGUEL: … …$"

Cave_Regigigas_S7_Doctor_Texto_57:
	.string "DR.RASMUS: Ahora, entrégame a\n"
	.string "WRONGSPARCE. Si has llegado a tener a\l"
	.string "ese POKÉMON es por nosotros y solo\l"
	.string "gracias a nosotros.$"

Cave_Regigigas_S7_Doctor_Texto_58:
	.string "MIGUEL: Entonces… así va a ser… ¿no?$"

Cave_Regigigas_S7_Doctor_Texto_59:
	.string "En ese caso…$"

Cave_Regigigas_S7_Doctor_Texto_60:
	.string "¡Lo lograré yo solo! ¡Tampoco os\n"
	.string "necesito yo a vosotros!$"

Cave_Regigigas_S7_Doctor_Texto_61:
	.string "ANDRA: ¡MIGUEL esper…!$"

Cave_Regigigas_S7_Doctor_Texto_62:
	.string "DR.RASMUS: ¡No puedes huir, MIGUEL!$"

Cave_Regigigas_S7_Doctor_Texto_63:
	.string "¡Tu destino está sellado! ¡Te\n"
	.string "encontraremos y entonces…!$"

Cave_Regigigas_S7_Doctor_Texto_64:
	.string "…obtendremos lo que queremos sin\n"
	.string "importar la forma.$"

Cave_Regigigas_S7_Doctor_Texto_65:
	.string "En cuanto vosotros, no tengo nada que\n"
	.string "deciros.$"

Cave_Regigigas_S7_Doctor_Texto_66:
	.string "Seréis grandes entrenadores. Puede que\n"
	.string "creáis estar realizando algún tipo de\l"
	.string "acto heróico llegando hasta aquí con\l"
	.string "POKÉMON mortales.$"

Cave_Regigigas_S7_Doctor_Texto_67:
	.string "Pero, al final del día, solo formáis\n"
	.string "parte de una estadística. Una variable\l"
	.string "más cuyos rangos están sobradamente\l"
	.string "controlados.$"

Cave_Regigigas_S7_Doctor_Texto_68:
	.string "ANDRA: No dirás lo mismo cuando hayamos\n"
	.string "acabado con aquello por lo que habéis\l"
	.string "venido.$"

Cave_Regigigas_S7_Doctor_Texto_69:
	.string "DR.RASMUS: Cuanta ignorancia, chiquilla.\n"
	.string "Si supieras lo que te espera…$"

Cave_Regigigas_S7_Doctor_Texto_70:
	.string "Tu error es pensar que REGIGIGAS es el\n"
	.string "final cuando…$"

Cave_Regigigas_S7_Doctor_Texto_71:
	.string "…es solo el comienzo.$"

Cave_Regigigas_S7_Doctor_Texto_72:
	.string "ANDRA: ¿Qué habrá querido decir?$"

Cave_Regigigas_S7_Doctor_Texto_73:
	.string "Ese DOCTOR… No apruebo lo que ha hecho\n"
	.string "MIGUEL, pero esos niveles de crueldad\l"
	.string "son demasiado.$"

Cave_Regigigas_S7_Doctor_Texto_74:
	.string "Crueldad… parece ser lo único válido\n"
	.string "para mejorar en estos días.$"

Cave_Regigigas_S7_Doctor_Texto_75:
	.string "Mmm… no importa.$"

Cave_Regigigas_S7_Doctor_Texto_76:
	.string "Hicimos un trato, {PLAYER}.\n"
	.string "¿Recuerdas?$"

Cave_Regigigas_S7_Doctor_Texto_77:
	.string "Y presiento que nos acercamos al final.$"

Cave_Regigigas_S7_Doctor_Texto_78:
	.string "No importa lo que haya detrás de esta\n"
	.string "cueva, estamos preparados.$"

Cave_Regigigas_S8_Amatista::
lock
msgbox Cave_Regigigas_S8_Amatista_Texto_1 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_2 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_3 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_4 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_5 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_6 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_7 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_8 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_9 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_10 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_11 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_12 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_13 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_14 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_15 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_16 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_17 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_18 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_19 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_20 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_21 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_22 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_23 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_24 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_25 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_26 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_27 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_28 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_29 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_30 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_31 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_32 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_33 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_34 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_35 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_36 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_37 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_38 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_39 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_40 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_41 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_42 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_43 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_44 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_45 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_46 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_47 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_48 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_49 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_50 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_51 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_52 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_53 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_54 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_55 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_56 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_57 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_58 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_59 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_60 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_61 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_62 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_63 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_64 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_65 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_66 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_67 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_68 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_69 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_70 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_71 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_72 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_73 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_74 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_75 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_76 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_77 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_78 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_79 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_80 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_81 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_82 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_83 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_84 MSGBOX_AUTOCLOSE
msgbox Cave_Regigigas_S8_Amatista_Texto_85 MSGBOX_AUTOCLOSE
release
end

Cave_Regigigas_S8_Amatista_Texto_1:
	.string "ADM.AMATISTA: Qué interesante...$"

Cave_Regigigas_S8_Amatista_Texto_2:
	.string "El misterio, seguir órdenes del TEAM\n"
	.string "ROCKET, ver de lo que son capaces\l"
	.string "vuestros POKÉMON...$"

Cave_Regigigas_S8_Amatista_Texto_3:
	.string "No importan los motivos que os hayan\n"
	.string "llevado hasta aquí, lo que estáis al\l"
	.string "borde de presenciar no os dejará\l"
	.string "indiferentes.$"

Cave_Regigigas_S8_Amatista_Texto_4:
	.string "De todos los orbes, el ORBE MORADO ha\n"
	.string "sido el mejor guardado por la tradición\l"
	.string "del MONTE PÍRICO.$"

Cave_Regigigas_S8_Amatista_Texto_5:
	.string "ANDRA: Oh…$"

Cave_Regigigas_S8_Amatista_Texto_6:
	.string "ADM.AMATISTA: Y por una buena razón: el\n"
	.string "lugar en el que su brillo cobra sentido\l"
	.string "es mucho más ignoto e inaccesible, así\l"
	.string "como el POKÉMON que despierta más\l"
	.string "antiguo y sagrado…$"

Cave_Regigigas_S8_Amatista_Texto_7:
	.string "Cualquiera puede llegar a las\n"
	.string "profundidades de la CAVERNA ABISAL o\l"
	.string "el MONTE CENIZO, pero aquí…$"

Cave_Regigigas_S8_Amatista_Texto_8:
	.string "Aquí solo llegan los elegidos, ¡y me\n"
	.string "alegra que seáis vosotros los\l"
	.string "afortunados! ¡Observad!$"

Cave_Regigigas_S8_Amatista_Texto_9:
	.string "ANDRA: Ese POKÉMON… rebosa un poderío\n"
	.string "físico inmenso, puede que sea hasta…$"

Cave_Regigigas_S8_Amatista_Texto_10:
	.string "ADM.AMATISTA: ¿Inmedible?$"

Cave_Regigigas_S8_Amatista_Texto_11:
	.string "ANDRA: Sí, inmedible o al menos… una\n"
	.string "fuerza bruta mayor a todo lo demás.$"

Cave_Regigigas_S8_Amatista_Texto_12:
	.string "ADM.AMATISTA: Como no puede ser de\n"
	.string "otra forma, el mundo tal y como lo\l"
	.string "conocemos fue moldeado por REGIGIGAS.$"

Cave_Regigigas_S8_Amatista_Texto_13:
	.string "Esta es su verdadera forma, aquella\n"
	.string "capaz de mover continentes enteros.$"

Cave_Regigigas_S8_Amatista_Texto_14:
	.string "ANDRA: Es impresionante, pero…$"

Cave_Regigigas_S8_Amatista_Texto_15:
	.string "ADM.AMATISTA: Pero ya habéis\n"
	.string "enfrentado cosas más grandes antes,\l"
	.string "¿no?$"

Cave_Regigigas_S8_Amatista_Texto_16:
	.string "ANDRA: ¡¿Cómo sabes…?!$"

Cave_Regigigas_S8_Amatista_Texto_17:
	.string "ADM.AMATISTA: Permíteme discrepar. Ese\n"
	.string "POKÉMON ESENCIA podrá ser más\l"
	.string "poderoso en términos absolutos, aún\l"
	.string "así…$"

Cave_Regigigas_S8_Amatista_Texto_18:
	.string "Lo que de verdad importa en un combate\n"
	.string "es la eficiencia; aquello que puedes\l"
	.string "controlar y aplicar a tu favor.$"

Cave_Regigigas_S8_Amatista_Texto_19:
	.string "En este caso… ese poderío… ese ATAQUE\n"
	.string "FÍSICO… es tan descomunal que, a pesar\l"
	.string "de ser finito, sus límites superiores\l"
	.string "son desconocidos para todos nosotros.$"

Cave_Regigigas_S8_Amatista_Texto_20:
	.string "Algo que, en la práctica, lo convierte en\n"
	.string "algo infinito.$"

Cave_Regigigas_S8_Amatista_Texto_21:
	.string "ANDRA: ¿Infinito?$"

Cave_Regigigas_S8_Amatista_Texto_22:
	.string "ADM.AMATISTA: Así es. El tipo de poder\n"
	.string "que, bien reconducido, podría desbordar\l"
	.string "todo cuanto se le pusiera enfrente.$"

Cave_Regigigas_S8_Amatista_Texto_23:
	.string "ANDRA: ¿Incluso…?$"

Cave_Regigigas_S8_Amatista_Texto_24:
	.string "ADM.AMATISTA: Incluso al tan adorado\n"
	.string "'POKÉMON ESENCIA'.$"

Cave_Regigigas_S8_Amatista_Texto_25:
	.string "ANDRA: ¡Basta de palabrería! Lo que\n"
	.string "dices ya lo aplicó {PLAYER} en RUINAS\l"
	.string "ALFA, ¡sin necesidad de tanto poder!$"

Cave_Regigigas_S8_Amatista_Texto_26:
	.string "ADM.AMATISTA: Tienes razón, pero\n"
	.string "olvidas que, a igualdad de habilidades,\l"
	.string "será el poder lo que marque la\l"
	.string "diferencia.$"

Cave_Regigigas_S8_Amatista_Texto_27:
	.string "Demostré superarte en habilidad en\n"
	.string "PUEBLO LAVANDA, ANDRA.$"

Cave_Regigigas_S8_Amatista_Texto_28:
	.string "¿En serio crees que ahora, empleando un\n"
	.string "poder mucho mayor, tienes una sola\l"
	.string "oportunidad?$"

Cave_Regigigas_S8_Amatista_Texto_29:
	.string "ANDRA: Puede que yo sola no, pero…$"

Cave_Regigigas_S8_Amatista_Texto_30:
	.string "Si lo que dices es cierto, no deberías\n"
	.string "tener problema en aplastarnos a los\l"
	.string "dos, ¿verdad?$"

Cave_Regigigas_S8_Amatista_Texto_31:
	.string "ADM.AMATISTA: ¡Jua, ja, ja! ¡Parece que\n"
	.string "has ganado algo de sensatez!$"

Cave_Regigigas_S8_Amatista_Texto_32:
	.string "No tendré problema en derrotaros al\n"
	.string "mismo tiempo, será más rápido e\l"
	.string "indoloro.$"

Cave_Regigigas_S8_Amatista_Texto_33:
	.string "Después de todo, habéis olvidado\n"
	.string "que…seguís siendo finitos.$"

Cave_Regigigas_S8_Amatista_Texto_34:
	.string "Y ante algo infinito, como lo que tenéis\n"
	.string "delante…$"

Cave_Regigigas_S8_Amatista_Texto_35:
	.string "¡No importa cuantos vengan ni lo que\n"
	.string "hagan! ¡Nadie podrá detenerme!$"

Cave_Regigigas_S8_Amatista_Texto_36:
	.string "Parece que mis cálculos fallaron.$"

Cave_Regigigas_S8_Amatista_Texto_37:
	.string "ADM.AMATISTA: Mmm… muy interesante.$"

Cave_Regigigas_S8_Amatista_Texto_38:
	.string "Felicidades. Acabáis de definir un\n"
	.string "nuevo límite. Y este no creo que pueda\l"
	.string "superarse, al menos en cuanto a fuerza\l"
	.string "bruta.$"

Cave_Regigigas_S8_Amatista_Texto_39:
	.string "En base a ello podremos también definir\n"
	.string "el límite en el resto de parámetros que\l"
	.string "influyen en el poder de un POKÉMON.$"

Cave_Regigigas_S8_Amatista_Texto_40:
	.string "Esta expedición ha superado nuestros\n"
	.string "pronósticos. Os estoy agradecido:\l"
	.string "vuestros viajes y experiencias han\l"
	.string "proporcionado una valiosa información\l"
	.string "a DEVON, una vez más.$"

Cave_Regigigas_S8_Amatista_Texto_41:
	.string "ANDRA: ¿Agradecido? ¡No vas\n"
	.string "a ir a ninguna parte!$"

Cave_Regigigas_S8_Amatista_Texto_42:
	.string "Te hemos derrotado: REGIGIGAS y ese\n"
	.string "ORBE MORADO se vienen con nosotros.$"

Cave_Regigigas_S8_Amatista_Texto_43:
	.string "ADM.AMATISTA: Me temo que eso no va a\n"
	.string "ser posible.$"

Cave_Regigigas_S8_Amatista_Texto_44:
	.string "ANDRA: No estás en disposición de…$"

Cave_Regigigas_S8_Amatista_Texto_45:
	.string "Tú…$"

Cave_Regigigas_S8_Amatista_Texto_46:
	.string "TRISTANA: Ya os lo advertí.$"

Cave_Regigigas_S8_Amatista_Texto_47:
	.string "ADM.AMATISTA: Nada está por encima del\n"
	.string "plan, y eso implica contemplar todas las\l"
	.string "posibilidades.$"

Cave_Regigigas_S8_Amatista_Texto_48:
	.string "ANDRA: Qué curioso… no sabía que\n"
	.string "fuéramos tan importantes para\l"
	.string "vosotros.$"

Cave_Regigigas_S8_Amatista_Texto_49:
	.string "TRISTANA: Eres muy atrevida, teniendo\n"
	.string "en cuenta la situación.$"

Cave_Regigigas_S8_Amatista_Texto_50:
	.string "Tú adrenalina ya ha disminuido tras el\n"
	.string "combate y estás con la guardia baja.\l"
	.string "Eso quiere decir que…$"

Cave_Regigigas_S8_Amatista_Texto_51:
	.string "¡mur!$"

Cave_Regigigas_S8_Amatista_Texto_52:
	.string "ANDRA: ¡Eh! ¡Mis POKÉMON!$"

Cave_Regigigas_S8_Amatista_Texto_53:
	.string "TRISTANA: Tendrás que seguir a FELICIA\n"
	.string "si quieres recuperarlos.$"

Cave_Regigigas_S8_Amatista_Texto_54:
	.string "ANDRA: Maldita… Ya ajustaremos\n"
	.string "cuentas.$"

Cave_Regigigas_S8_Amatista_Texto_55:
	.string "ADM.AMATISTA: Buen trabajo. Después de\n"
	.string "todo, sabes mantener el orden cuando\l"
	.string "de verdad importa.$"

Cave_Regigigas_S8_Amatista_Texto_56:
	.string "Admiro tus cualidades, pero tu utilidad\n"
	.string "para con DEVON acaba aquí.$"

Cave_Regigigas_S8_Amatista_Texto_57:
	.string "Al final del día… sigues sin tener la\n"
	.string "menor idea de cuál es nuestro propósito\l"
	.string "y, a pesar de ello, has aportado a su\l"
	.string "consecución. Felicidades.$"

Cave_Regigigas_S8_Amatista_Texto_58:
	.string "TRISTANA: ¡Eh, tranquilo!$"

Cave_Regigigas_S8_Amatista_Texto_59:
	.string "Ahora quedamos tú y yo, {PLAYER}. Ji,\n"
	.string "ji, ji.$"

Cave_Regigigas_S8_Amatista_Texto_60:
	.string "Esa ANDRA es tan aburrida, siempre\n"
	.string "obsesionada con mejorar. ¿No prefieres\l"
	.string "bailar un poco conmigo?$"

Cave_Regigigas_S8_Amatista_Texto_61:
	.string "… …$"

Cave_Regigigas_S8_Amatista_Texto_62:
	.string "Aún podrías alcanzar a AMATISTA.\n"
	.string "Tendrás que bailar conmigo, ¡quieras o\l"
	.string "no!$"

Cave_Regigigas_S8_Amatista_Texto_63:
	.string "¡Bah! ¡Qué aburrido!$"

Cave_Regigigas_S8_Amatista_Texto_64:
	.string "Hmm… enfrentar a POKÉMON tan bien\n"
	.string "cuidados acaba siendo tedioso.$"

Cave_Regigigas_S8_Amatista_Texto_65:
	.string "Sorprende pero… desmotiva.$"

Cave_Regigigas_S8_Amatista_Texto_66:
	.string "Aún mermado has podido con un equipo\n"
	.string "lleno de POKÉMON singulares.$"

Cave_Regigigas_S8_Amatista_Texto_67:
	.string "ANDRA se llena la boca con los males que\n"
	.string "trae el abuso de POKÉMON ARTIFICALES.$"

Cave_Regigigas_S8_Amatista_Texto_68:
	.string "Pero, al final del día, ambos habéis\n"
	.string "llegado a un punto en el que vuestros\l"
	.string "propios estándares son de igual modo\l"
	.string "inalcanzables para el resto de\l"
	.string "'naturales'. ¿No es al final lo mismo?$"

Cave_Regigigas_S8_Amatista_Texto_69:
	.string "Supongo que tendré que volver a hablar\n"
	.string "con el DOCTOR para que actualice mi\l"
	.string "equipo…$"

Cave_Regigigas_S8_Amatista_Texto_70:
	.string "… …$"

Cave_Regigigas_S8_Amatista_Texto_71:
	.string "Yo no he elegido esto, ¿entiendes? Si\n"
	.string "quiero seguir ayudando a HOENN, debo\l"
	.string "adaptarme a los nuevos tiempos.$"

Cave_Regigigas_S8_Amatista_Texto_72:
	.string "En caso contrario… me convertiré en un\n"
	.string "lastre, y solo espero que…$"

Cave_Regigigas_S8_Amatista_Texto_73:
	.string "…no llegue el momento en el que mi\n"
	.string "SALAMENCE también lo acabe siendo.$"

Cave_Regigigas_S8_Amatista_Texto_74:
	.string "La MEGAEVOLUCIÓN de un\n"
	.string "PSEUDOLEGENDARIO… de mi pequeño\l"
	.string "BAGON… fuera del equipo por no estar a\l"
	.string "la altura, ¿puedes imaginártelo?$"

Cave_Regigigas_S8_Amatista_Texto_75:
	.string "Mmm… yo… no.$"

Cave_Regigigas_S8_Amatista_Texto_76:
	.string "ANDRA: ¿Derrotaste a TRISTANA?$"

Cave_Regigigas_S8_Amatista_Texto_77:
	.string "Mmm… hubiera preferido que ese WHISMUR\n"
	.string "robara tus POKÉMON, solo para ser yo\l"
	.string "quién derrotara a esa lunática.$"

Cave_Regigigas_S8_Amatista_Texto_78:
	.string "Diría que desde el principio todo: la\n"
	.string "posibilidad de que esto ocurriera,\l"
	.string "nuestra intervención y cómo usarla a su\l"
	.string "favor… entraban dentro de sus\l"
	.string "cálculos.$"

Cave_Regigigas_S8_Amatista_Texto_79:
	.string "Aún así, una expedición como esta\n"
	.string "nunca es en vano. Nosotros también nos\l"
	.string "hemos nutrido de ella.$"

Cave_Regigigas_S8_Amatista_Texto_80:
	.string "Muchas cosas rondan mi mente, pero\n"
	.string "recuerda: he cumplido mi parte de la\l"
	.string "promesa. Ahora te toca a ti.$"

Cave_Regigigas_S8_Amatista_Texto_81:
	.string "… …$"

Cave_Regigigas_S8_Amatista_Texto_82:
	.string "Aún conservo una copia de la LLAVE de\n"
	.string "mi Ex-DESPACHO en HOENN. Es un lugar\l"
	.string "perfecto para hablar con tranquilidad.$"

Cave_Regigigas_S8_Amatista_Texto_83:
	.string "Allí te contaré mi parte del trato,\n"
	.string "{PLAYER}.$"

Cave_Regigigas_S8_Amatista_Texto_84:
	.string "Solo espero que… nuestra rivalidad y…\n"
	.string "amistad… signifique para ti tanto o más\l"
	.string "que tu lealtad al TEAM ROCKET.$"

Cave_Regigigas_S8_Amatista_Texto_85:
	.string "Nos vemos allí.$"

