RocketHideout_2F_MapScripts::
	.byte 0

RocketHideout2F-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Si sirves a la justicia,\n"
.string "¡traicionas al TEAM ROCKET!$"



RocketHideout2F-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "La regla número 1 del negocio de\n"
.string "nuestro CASINO es: nunca consumas\l"
.string "lo que vendes, nuestros\l"
.string "científicos diseñaron las\l"
.string "tragaperras para que todas las\l"
.string "probabilidades estuvieran a favor\l"
.string "de nuestras ganancias.\l"
.string "¡La casa siempre gana no lo\l"
.string "olvides!$"



RocketHideout2F-3::
end



RocketHideout2F-4::
end



RocketHideout2F-5::
end
