Ecruteak_PkmnCenter_MapScripts::
	.byte 0

EcruteakPkmnCenter1::
end



EcruteakPkmnCenter2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Las CHICAS KIMONO son muy buenas\n"
.string "bailarinas, además de diestras\l"
.string "entrenadoras.\l"
.string "¡Son increíbles!$"



EcruteakPkmnCenter3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Aquí todos tenemos un EEVEE en\n"
.string "casa. Aunque algunos POKEMANÍACOS\l"
.string "quieran hacer creer a la gente que\l"
.string "es un POKÉMON muy raro, en CIUDAD\l"
.string "IRIS es de lo más común.$"



EcruteakPkmnCenter4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "Me pregunto si la TORRE QUEMADA\n"
.string "era aún más alta que la TORRE\l"
.string "CAMPANA. Dicen que eran similares\l"
.string "en altura[.]$"
