Goldenrod_RadioTowerP3_MapScripts::
	.byte 0

RadioTowerP3-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "La TORRE RADIO, el MAGNETOTREN, el\n"
.string "PUERTO OLIVO... La globalización\l"
.string "llega a JOHTO, y viene\l"
.string "para quedarse.$"



RadioTowerP3-2::
end



RadioTowerP3-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Eso es lo que necesitamos aquí,\n"
.string "gente importante y trajeada como\l"
.string "tú, no esos matones del\l"
.string "subterráneo.$"



RadioTowerP3-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "CIUDAD TRIGAL no solo es la más\n"
.string "poblada de JOHTO, tampoco en KANTO\l"
.string "hay ninguna ciudad con más\l"
.string "habitantes. Esta TORRE RADIO ha\l"
.string "tenido mucho que ver.$"



RadioTowerP3-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "Emitimos programas de\n"
.string "entretenimiento las 24 horas del\l"
.string "día.\l"
.string "¡Trataremos de hacerlo lo mejor\l"
.string "posible!$"



RadioTowerP3-6::
end



RadioTowerP3-7::
lock     
faceplayer     
msgbox Text_7, MSGBOX_DEFAULT
release     
end

Text_7:
.string "ROSA: Crear un programa junto con\n"
.string "el PROF.OAK[.]\l"
.string "Eso nos daría gran visibilidad\l"
.string "también en KANTO, ¿no crees?$"



RadioTowerP3-8::
end



RadioTowerP3-9::
lock     
faceplayer     
msgbox Text_9, MSGBOX_DEFAULT
release     
end

Text_9:
.string "Hemos grabado los gritos de todos\n"
.string "los POKÉMON conocidos en KANTO y\l"
.string "JOHTO.\l"
.string "¡Tenemos más de 200 gritos!$"



RadioTowerP3-10::
lock     
faceplayer     
msgbox Text_10, MSGBOX_DEFAULT
release     
end

Text_10:
.string "Desde aquí no, pero dicen que\n"
.string "desde el último piso pueden verse\l"
.string "tanto la TORRE CAMPANA DE CIUDAD\l"
.string "IRIS como el FARO de CIUDAD\l"
.string "OLIVO.$"



RadioTowerP3-11::
lock     
faceplayer     
msgbox Text_11, MSGBOX_DEFAULT
release     
end

Text_11:
.string "Estamos trabajando duro para que\n"
.string "pronto se pueda escuchar la radio\l"
.string "en cualquier lugar.\l"
.string "¡Sintoniza!$"



RadioTowerP3-12::
lock     
faceplayer     
msgbox Text_12, MSGBOX_DEFAULT
release     
end

Text_12:
.string "Pocos saben que si sintonizas la\n"
.string "radio a una determinada frecuencia\l"
.string "dentro de las RUINAS ALFA...\l"
.string "¡Escucharás ruidos muy\l"
.string "extraños!$"
