LavenderRadio_MapScripts::
	.byte 0


LavenderRadio_1::
lock     
faceplayer     
msgbox LavenderRadio_Text_1, MSGBOX_DEFAULT
release     
end

LavenderRadio_Text_1:
.string "¿Qué tal? Mira por donde quieras en\n"
.string "esta planta.$"



LavenderRadio_2::
lock     
faceplayer     
msgbox LavenderRadio_Text_2, MSGBOX_DEFAULT
release     
end

LavenderRadio_Text_2:
.string "¿Qué te parece la nueva TORRE RADIO?\n"
.string "¿Llegaste a visitar la TORRE POKÉMON\l"
.string "antes de que fuera demolida?$"




LavenderRadio_3::
lock     
faceplayer     
msgbox LavenderRadio_Text_3, MSGBOX_DEFAULT
release     
end

LavenderRadio_Text_3:
.string "Bienvenido, SR.ADMIN JEFE. Todos aquí\n"
.string "estamos a su disposición para lo que\l"
.string "usted necesite. Le escoltaré hasta los\l"
.string "pisos superiores si así lo desea.$"




LavenderRadio_4::
lock     
faceplayer     
msgbox LavenderRadio_Text_4, MSGBOX_DEFAULT
release     
end

LavenderRadio_Text_4:
.string "En la torre radio hay mucha gente que\n"
.string "trabaja duramente. Seguro que están\l"
.string "haciendo lo mejor para poder emitir\l"
.string "buenos programas, aunque nunca he\l"
.string "tenido ocasión de subir a los pisos de\l"
.string "arriba.$"
