Goldenrod_RadioTowerP4_MapScripts::
	.byte 0

RadioTowerP4_1::
end



RadioTowerP4_2::
end



RadioTowerP4_3:
lock     
faceplayer     
msgbox Goldenrod_RadioTowerP4_Text_3, MSGBOX_DEFAULT
release     
end

Goldenrod_RadioTowerP4_Text_3:
.string "NARDO: ¿Escuchas nuestra música?$"



RadioTowerP4_4::
lock     
faceplayer     
msgbox Goldenrod_RadioTowerP4_Text_4, MSGBOX_DEFAULT
release     
end

Goldenrod_RadioTowerP4_Text_4:
.string "Choca bastante ver un edificio de\n"
.string "estas dimensiones justo al lado\l"
.string "del mar, ¿no crees?\l"
.string "Si por algún casual se derrumbara\l"
.string "en dirección oeste, la gran altura\l"
.string "de la TORRE RADIO haría que los\l"
.string "que se encuentran en los pisos\l"
.string "superiores, como nosotros, cayeran\l"
.string "en pleno mar abierto.\l"
.string "¡Acabo de pensarlo y me parece\l"
.string "alucinante!$"



RadioTowerP4_5::
lock     
faceplayer     
msgbox Goldenrod_RadioTowerP4_Text_5, MSGBOX_DEFAULT
release     
end

Goldenrod_RadioTowerP4_Text_5:
.string "El despacho de nuestro PRESIDENTE\n"
.string "está justo al lado de esta sala,\l"
.string "es allí donde tienen lugar las\l"
.string "reuniones más importantes.$"



RadioTowerP4_6::
lock     
faceplayer     
msgbox Goldenrod_RadioTowerP4_Text_6, MSGBOX_DEFAULT
release     
end

Goldenrod_RadioTowerP4_Text_6:
.string "Aún no puedo creer todo lo que\n"
.string "TRIGAL ha crecido en los últimos\l"
.string "años, y todo lo que está por\l"
.string "venir. ¡Tiempos interesantes nos\l"
.string "ha tocado vivir!$"



RadioTowerP4_7::
end



RadioTowerP4_9::
end



GoldenrodRadioTowerP4Documento_100::
msgbox GoldenrodRadioTowerP4Documento_Text_100, MSGBOX_SIGN   
end

GoldenrodRadioTowerP4Documento_Text_100:
.string "P4 OFICINA DEL DIRECTOR$"



GoldenrodRadioTowerP4Documento_101::
msgbox GoldenrodRadioTowerP4Documento_Text_101, MSGBOX_SIGN   
end

GoldenrodRadioTowerP4Documento_Text_101:
.string "P4 ESTUDIO 1$"
