BlackthornCity_House2_MapScripts::
	.byte 0

BlackthornCityHouse2-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Creo que nuestro GRAN MAESTRO no\n"
.string "está del todo contento con su\l"
.string "nieta, DÉBORA, y razón no le\l"
.string "falta. Al igual que acabó\l"
.string "demostrando LANCE, no representa\l"
.string "para nada los valores que nuestro\l"
.string "GRAN MAESTRO trató de\l"
.string "transmitirles. El poder del TIPO\l"
.string "DRAGÓN acabó corrompiendo a LANCE,\l"
.string "DÉBORA va por el mismo camino.$"



BlackthornCityHouse2-2::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Muchos creen que criar dragones es\n"
.string "súper guay, por su potencial de\l"
.string "volverse tan fuertes, pero\l"
.string "necesitas mucha paciencia y\l"
.string "responsabilidad para de verdad\l"
.string "sacar lo mejor de ellos. Por eso\l"
.string "hay tan pocos con un DRAGONITE en\l"
.string "su equipo.$"