NeoLavandaCementerio_MapScripts::
	.byte 0

NeoLavandaCementerio_1::
lock     
faceplayer     
msgbox NeoLavandaCementerio_Text_1, MSGBOX_DEFAULT
release     
end

NeoLavandaCementerio_Text_1:
.string "Creo que aquí hay otras tumbas de\n"
.string "POKÉMON. Hay muchas cámaras en las que\l"
.string "solo el SR.FUJI y antiguos miembros de\l"
.string "PUEBLO LAVANDA pueden entrar.$"




NeoLavandaCementerio_2::
lock     
faceplayer     
msgbox NeoLavandaCementerio_Text_2, MSGBOX_DEFAULT
release     
end

NeoLavandaCementerio_Text_2:
.string "He venido a rendir homenaje a las\n"
.string "tumbas de los POKÉMON.$"




NeoLavandaCementerio_3::
lock     
faceplayer     
msgbox NeoLavandaCementerio_Text_3, MSGBOX_DEFAULT
release     
end

NeoLavandaCementerio_Text_3:
.string "A los POKÉMON que vivían conmigo… los\n"
.string "quería como a mis nietos.$"
