SsAnne_10F_MapScripts::
	.byte 0

SsAnne10F_1::
end



SsAnne10F_2::
end



SsAnne10F_3::
end



SsAnne10F_4::
lock     
faceplayer     
msgbox SsAnne10F_Text_4, MSGBOX_DEFAULT
release     
end

SsAnne10F_Text_4:
.string "El SS.ANNE supuestamente viaja a\n"
.string "lo largo de las regiones llevando\l"
.string "entrenadores de todo el mundo.\l"
.string "¡Pero aquí yo solo veo POKÉMON de\l"
.string "KANTO!$"
