Neo_TunelRoca_2F_MapScripts::
	.byte 0


Neo_TunelRoca_2F_Fuji::
lock
msgbox Neo_TunelRoca_2F_Fuji_Texto_1 MSGBOX_AUTOCLOSE
msgbox Neo_TunelRoca_2F_Fuji_Texto_2 MSGBOX_AUTOCLOSE
msgbox Neo_TunelRoca_2F_Fuji_Texto_3 MSGBOX_AUTOCLOSE
msgbox Neo_TunelRoca_2F_Fuji_Texto_4 MSGBOX_AUTOCLOSE
release
end

Neo_TunelRoca_2F_Fuji_Texto_1:
	.string "¡Bone!$"

Neo_TunelRoca_2F_Fuji_Texto_2:
	.string "Esta región nunca dejará de\n"
	.string "sorprenderme.$"

Neo_TunelRoca_2F_Fuji_Texto_3:
	.string "Parece que solo estábamos viendo una\n"
	.string "pequeña parte del TÚNEL ROCA. Esta\l"
	.string "pequeña grieta se adentra aún más bajo\l"
	.string "tierra.$"

Neo_TunelRoca_2F_Fuji_Texto_4:
	.string "Estoy intrigado, {PLAYER}. ¿Adónde\n"
	.string "llevará esto?$"