Route20_MapScripts::
	.byte 0

Route20-1::
end

Route20-2::
end

Route20-3::
end

Route20-4::
end


Route20-5::
end

Route20-6::
end

Route20-7::
lock     
faceplayer     
msgbox Text_7, MSGBOX_DEFAULT
release     
end

Text_7:
.string "Muchos entrenadores expertos en el\n"
.string "tipo agua suelen frecuentar este\l"
.string "lugar.\l"
.string "Dicen que MISTY, de CIUDAD\l"
.string "CELESTE, se entrena por aquí.$"

Route20-8::
end

Route20-9::
end

Route20-10::
end

Route20-11::
end
