Silph_1F_MapScripts::
	.byte 0

Silph1F_1::
end



Silph1F_2::
lock     
faceplayer     
msgbox Silph1F_Text_2, MSGBOX_DEFAULT
release     
end

Silph1F_Text_2:
.string "PETREL: Confío en vosotros\n"
.string "{PLAYER}, yo me quedaré aquí\l"
.string "asegurándome de que no entre nada\l"
.string "que pueda comprometer la misión,\l"
.string "¡date prisa!$"



Silph1F_3::
lock     
faceplayer     
msgbox Silph1F_Text_3, MSGBOX_DEFAULT
release     
end

Silph1F_Text_3:
.string "¡A sus órdenes, EJECUTIVO {PLAYER}!$"



Silph1F_4::
lock     
faceplayer     
msgbox Silph1F_Text_4, MSGBOX_DEFAULT
release     
end

Silph1F_Text_4:
.string "¡Este día será recordado en los\n"
.string "libros de historia como el día en\l"
.string "que el TEAM ROCKET se hizo con el\l"
.string "control de todo!$"



Silph1F_5::
lock     
faceplayer     
msgbox Silph1F_Text_5, MSGBOX_DEFAULT
release     
end

Silph1F_Text_5:
.string "¡Venid a mi seguridad de SILPH!$"



Silph1F_6::
lock     
faceplayer     
msgbox Silph1F_Text_6, MSGBOX_DEFAULT
release     
end

Silph1F_Text_6:
.string "Esa sensación de incertidumbre\n"
.string "antes de pasar a la acción, por\l"
.string "este tipo de misiones me uní al\l"
.string "TEAM ROCKET, ¡nunca te sentirás\l"
.string "tan vivo como ahora!$"



Silph1F_7::
lock     
faceplayer     
msgbox Silph1F_Text_7, MSGBOX_DEFAULT
release     
end

Silph1F_Text_7:
.string "¡Esta fuente es una verguenza\n"
.string "comparada con la nuestra!$"



Silph1F_8::
lock     
faceplayer     
msgbox Silph1F_Text_8, MSGBOX_DEFAULT
release     
end

Silph1F_Text_8:
.string "¡Vamos a demostrarle a SILPH quién\n"
.string "de verdad tiene el poder aquí!$"



Silph1F_9::
lock     
faceplayer     
msgbox Silph1F_Text_9, MSGBOX_DEFAULT
release     
end

Silph1F_Text_9:
.string "La verdad que desde fuera SILPH\n"
.string "impresiona, no hay otro lugar tan\l"
.string "alto como este en la región.$"



Silph1F_10::
lock     
faceplayer     
msgbox Silph1F_Text_10, MSGBOX_DEFAULT
release     
end

Silph1F_Text_10:
.string "La ÉLITE del TEAM ROCKET nada\n"
.string "tiene que ver con un RECLUTA\l"
.string "común, ahora mismo todos nuestros\l"
.string "POKÉMON oscilan los niveles 35-40,\l"
.string "por supuesto, tenemos órdenes\l"
.string "directas de GIOVANNI de\l"
.string "desaparecer en cuanto acabe de\l"
.string "decirle al PRESIDENTE lo que tiene\l"
.string "que decirle, más aún, tenemos\l"
.string "prohibido combatir contra ese tal\l"
.string "ROJO, no quiere que sepa de lo que\l"
.string "somos capaces.$"



Silph1F_11::
lock     
faceplayer     
msgbox Silph1F_Text_11, MSGBOX_DEFAULT
release     
end

Silph1F_Text_11:
.string "Me gusta el ambiente de este\n"
.string "lugar, creo que le da cierto aire\l"
.string "a nuestra BASE ROCKET PROFUNDA.$"



Silph1F_12::
lock     
faceplayer     
msgbox Silph1F_Text_12, MSGBOX_DEFAULT
release     
end

Silph1F_Text_12:
.string "La mentalidad de SILPH y el TEAM\n"
.string "ROCKET es parecida, más de lo que\l"
.string "creen, y usaremos eso para\l"
.string "convencer al PRESIDENTE.$"



Silph1F_13::
lock     
faceplayer     
msgbox Silph1F_Text_13, MSGBOX_DEFAULT
release     
end

Silph1F_Text_13:
.string "¡Seguro que SILPH y el TEAM ROCKET\n"
.string "pueden llegar a un buen acuerdo!$"



Silph1F_14::
lock     
faceplayer     
msgbox Silph1F_Text_14, MSGBOX_DEFAULT
release     
end

Silph1F_Text_14:
.string "Si nuestro LÍDER GIOVANNI\n"
.string "decidiese combatir usando todo su\l"
.string "poder, no creo que exista hoy en\l"
.string "día entrenador en toda la región\l"
.string "capaz de seguirle el ritmo, se ha\l"
.string "vuelto extraordinariamente fuerte,\l"
.string "todos estos años de apedreo\l"
.string "mediático no han servido más que\l"
.string "para endurecerlo aún más de lo que\l"
.string "era cuando ya obtuvo el título de\l"
.string "CAMPEÓN DE KANTO.$"



Silph1F_15::
lock     
faceplayer     
msgbox Silph1F_Text_15, MSGBOX_DEFAULT
release     
end

Silph1F_Text_15:
.string "Si todo sale bien estaremos una\n"
.string "temporada en la sombra, pero\l"
.string "volviéndonos cada vez más\l"
.string "fuertes…$"



Silph1F_16::
lock     
faceplayer     
msgbox Silph1F_Text_16, MSGBOX_DEFAULT
release     
end

Silph1F_Text_16:
.string "Cosas muy importantes van a\n"
.string "ocurrir aquí hoy.$"



Silph1F_17::
lock     
faceplayer     
msgbox Silph1F_Text_17, MSGBOX_DEFAULT
release     
end

Silph1F_Text_17:
.string "El poder de SILPH se extiende a\n"
.string "las ARCHI7, ¡el del TEAM ROCKET se\l"
.string "extenderá por todo el mundo!$"



Silph1F_18::
lock     
faceplayer     
msgbox Silph1F_Text_18, MSGBOX_DEFAULT
release     
end

Silph1F_Text_18:
.string "En el TEAM ROCKET actuamos como un\n"
.string "solo cuerpo, eso nos hace fuertes.$"



Silph1F_19::
lock     
faceplayer     
msgbox Silph1F_Text_19, MSGBOX_DEFAULT
release     
end

Silph1F_Text_19:
.string "Los trabajadores de aquí no están\n"
.string "acostumbrados a vernos, viven en\l"
.string "una ciudad ajena a la realidad, no\l"
.string "me extrañaría que muchos de ellos\l"
.string "se cagaran de miedo, aunque no les\l"
.string "haremos nada, por supuesto.$"



Silph1FDocumento_100::
msgbox Silph1FDocumento_Text_100, MSGBOX_SIGN   
end

Silph1FDocumento_Text_100:
.string "OFICINA CENTRAL DE SILPH S.A.\n"
	.string "PB$"



Silph_1F_Recepcionista_Pisos_Inferiores::
compare VAR_UNUSED_0x40F7, 102
goto_if_gt Silph_1F_Recepcionista_Pisos_Inferiores_3
compare VAR_UNUSED_0x40F7, 101
goto_if_gt Silph_1F_Recepcionista_Pisos_Inferiores_2
msgbox Silph_1F_Recepcionista_Pisos_Inferiores_Texto_1 MSGBOX_AUTOCLOSE
release
end

Silph_1F_Recepcionista_Pisos_Inferiores_3::
lock
faceplayer
msgbox Silph_1F_Recepcionista_Pisos_Inferiores_Texto_6 MSGBOX_AUTOCLOSE
release
end

Silph_1F_Recepcionista_Pisos_Inferiores_2::
delay 20
msgbox Silph_1F_Recepcionista_Pisos_Inferiores_Texto_2 MSGBOX_AUTOCLOSE
delay 20
playse SE_PIN
applymovement 1, Silph_1F_Recepcionista_Pisos_Inferiores_Move_1
waitmovement 0x0
msgbox Silph_1F_Recepcionista_Pisos_Inferiores_Texto_3 MSGBOX_AUTOCLOSE
applymovement 1, Silph_1F_Recepcionista_Pisos_Inferiores_Move_2
waitmovement 0x0
msgbox Silph_1F_Recepcionista_Pisos_Inferiores_Texto_4 MSGBOX_AUTOCLOSE
special SpawnCameraObject
applymovement OBJ_EVENT_ID_CAMERA, Silph_1F_Recepcionista_Pisos_Inferiores_Move_3
waitmovement 0x0
special RemoveCameraObject
playse SE_PC_ON
delay 40
playse SE_PC_LOGIN
delay 40
playse SE_CLICK
delay 40
playse SE_UNLOCK
setmetatile 10, 3, 0x346, TRUE
setmetatile 10, 2, 0x33E, TRUE
setmetatile 10, 1, 0x290, TRUE
setmetatile 10, 0, 0x288, TRUE
setmetatile 11, 3, 0x276, FALSE
setmetatile 11, 2, 0x26F, FALSE
setmetatile 11, 1, 0x271, TRUE
setmetatile 11, 0, 0x269, TRUE
setmetatile 12, 3, 0x266, TRUE
setmetatile 12, 2, 0x25E, TRUE
setmetatile 12, 1, 0x274, TRUE
setmetatile 12, 0, 0x330, TRUE
setmetatile 13, 3, 0x267, TRUE
setmetatile 13, 2, 0x25F, TRUE
setmetatile 13, 1, 0x275, TRUE
setmetatile 13, 0, 0x330, TRUE
setmetatile 14, 3, 0x347, TRUE
setmetatile 14, 2, 0x33F, TRUE
setmetatile 14, 1, 0x294, TRUE
setmetatile 14, 0, 0x28C, TRUE
special DrawWholeMapView
delay 60
playse SE_PIN
applymovement OBJ_EVENT_ID_CAMERA, Silph_1F_Recepcionista_Pisos_Inferiores_Move_1
waitmovement 0x0
delay 10
special SpawnCameraObject
applymovement OBJ_EVENT_ID_CAMERA, Silph_1F_Recepcionista_Pisos_Inferiores_Move_4
waitmovement 0x0
special RemoveCameraObject
applymovement 1, Silph_1F_Recepcionista_Pisos_Inferiores_Move_5
waitmovement 0x0
msgbox Silph_1F_Recepcionista_Pisos_Inferiores_Texto_5 MSGBOX_AUTOCLOSE
applymovement 1, Silph_1F_Recepcionista_Pisos_Inferiores_Move_6
waitmovement 0x0
msgbox Silph_1F_Recepcionista_Pisos_Inferiores_Texto_6 MSGBOX_AUTOCLOSE
setvar VAR_UNUSED_0x40F7, 103
release
end

Silph_1F_Recepcionista_Pisos_Inferiores_Move_1:
emote_exclamation_mark
step_end

Silph_1F_Recepcionista_Pisos_Inferiores_Move_2:
walk_right
walk_up
walk_right
step_end

Silph_1F_Recepcionista_Pisos_Inferiores_Move_3:
walk_up
walk_up
walk_up
walk_right
walk_right
walk_up
walk_up
walk_right
walk_right
walk_right
step_end

Silph_1F_Recepcionista_Pisos_Inferiores_Move_4:
walk_down
walk_down
walk_down
walk_left
walk_left
walk_down
walk_down
walk_left
walk_left
walk_left
step_end

Silph_1F_Recepcionista_Pisos_Inferiores_Move_5:
walk_left
walk_down
walk_left
walk_in_place_down
step_end

Silph_1F_Recepcionista_Pisos_Inferiores_Move_6:
walk_in_place_down
step_end

Silph_1F_Recepcionista_Pisos_Inferiores_Texto_1:
.string "¡Jamás olvidaré lo que habéis\n"
	.string "hecho aquí ROCKETS!$"

Silph_1F_Recepcionista_Pisos_Inferiores_Texto_2:
.string "...\n"
	.string "...$"

Silph_1F_Recepcionista_Pisos_Inferiores_Texto_3:
.string "¡Ah, sí!\n"
	.string "¡Tú eres el chico que iba a venir\l"
	.string "en nombre del TEAM ROCKET a\l"
	.string "visitar nuestra biblioteca!\l"
	.string "Eres muy afortunado, ¿lo sabías?$"

Silph_1F_Recepcionista_Pisos_Inferiores_Texto_4:
.string "Nadie de fuera de la empresa ha\n"
	.string "entrado jamás, y solo nuestros\l"
	.string "empleados más destacados tienen\l"
	.string "acceso a ella, pero nuestro\l"
	.string "PRESIDENTE...$"

Silph_1F_Recepcionista_Pisos_Inferiores_Texto_5:
.string "Me ha hecho saber expresamente su\n"
	.string "voluntad de que entres siempre que\l"
	.string "quieras.$"

Silph_1F_Recepcionista_Pisos_Inferiores_Texto_6:
.string "A partir de ahora podrás acceder a\n"
	.string "nuestros pisos inferiores solo con\l"
	.string "interactuar con mi ordenador,\l"
	.string "¡buena suerte en tu búsqueda!$"

Silph_1F_Activador_Entrada::
compare VAR_UNUSED_0x40F7, 102
goto_if_gt Silph_1F_Activador_Entrada_2
msgbox Silph_1F_Activador_Entrada_Texto_1 MSGBOX_AUTOCLOSE
release
end

Silph_1F_Activador_Entrada_2:
msgbox RocketHideout_4F_Warp_Text_YesNo, MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq RocketHideout_4F_Warp_No
playse SE_PC_ON
delay 40
playse SE_PC_LOGIN
delay 40
playse SE_CLICK
delay 40
playse SE_UNLOCK
setmetatile 10, 3, 0x346, TRUE
setmetatile 10, 2, 0x33E, TRUE
setmetatile 10, 1, 0x290, TRUE
setmetatile 10, 0, 0x288, TRUE
setmetatile 11, 3, 0x276, FALSE
setmetatile 11, 2, 0x26F, FALSE
setmetatile 11, 1, 0x271, TRUE
setmetatile 11, 0, 0x269, TRUE
setmetatile 12, 3, 0x266, TRUE
setmetatile 12, 2, 0x25E, TRUE
setmetatile 12, 1, 0x274, TRUE
setmetatile 12, 0, 0x330, TRUE
setmetatile 13, 3, 0x267, TRUE
setmetatile 13, 2, 0x25F, TRUE
setmetatile 13, 1, 0x275, TRUE
setmetatile 13, 0, 0x330, TRUE
setmetatile 14, 3, 0x347, TRUE
setmetatile 14, 2, 0x33F, TRUE
setmetatile 14, 1, 0x294, TRUE
setmetatile 14, 0, 0x28C, TRUE
special DrawWholeMapView
delay 60
release
end

Silph_1F_Activador_Entrada_Texto_1:
.string "Este ordenador parece que cumple\n"
	.string "una función de gran importancia...$"
