Cianwood_House2_MapScripts::
	.byte 0

CianwoodHouse2_1::
lock     
faceplayer     
msgbox Cianwood_House2_Text_1, MSGBOX_DEFAULT
release     
end

Cianwood_House2_Text_1:
.string "The peace this place brings me is irreplaceable.$"



CianwoodHouse2_2::
lock     
faceplayer     
msgbox Cianwood_House2_Text_2, MSGBOX_DEFAULT
release     
end

Cianwood_House2_Text_2:
	.string "Look how tan I am from soaking up the\n"
	.string "sun; sometimes, STARYU even stick to my\l"
	.string "body!$"
