Route35_MapScripts::
	.byte 0

Route35_1::
end



Route35_2::
lock     
faceplayer     
msgbox Route35_Text_2, MSGBOX_DEFAULT
release     
end

Route35_Text_2:
.string "Por esta ruta suele entrenar la\n"
.string "policía de TRIGAL, ¡esos ARCANINE\l"
.string "de KANTO imponen mucho!$"



Route35_3::
end



Route35_4::
end



Route35_5::
lock     
faceplayer     
msgbox Route35_Text_5, MSGBOX_DEFAULT
release     
end

Route35_Text_5:
.string "¿Sabes dónde podría encontrar un\n"
.string "MAGMAR?\l"
.string "¡Tranquilo!\l"
.string "¡No pienso quemar el PARQUE\l"
.string "NACIONAL!$"



Route35_6::
lock     
faceplayer     
msgbox Route35_Text_6, MSGBOX_DEFAULT
release     
end

Route35_Text_6:
.string "La policía es esencial para\n"
.string "mantener el orden y la seguridad,\l"
.string "pero no hay nada más seguro que\l"
.string "contar con POKÉMON bien\l"
.string "entrenados.$"



Route35_7::
end



Route35_8::
end



Route35_9::
end
