#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Poké Balls
#define ITEM_POKE_BALL 1
#define ITEM_GREAT_BALL 2
#define ITEM_ULTRA_BALL 3
#define ITEM_MASTER_BALL 4
#define ITEM_PREMIER_BALL 5
#define ITEM_HEAL_BALL 6
#define ITEM_NET_BALL 7
#define ITEM_NEST_BALL 8
#define ITEM_DIVE_BALL 9
#define ITEM_DUSK_BALL 10
#define ITEM_TIMER_BALL 11
#define ITEM_QUICK_BALL 12
#define ITEM_REPEAT_BALL 13
#define ITEM_LUXURY_BALL 14 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_LEVEL_BALL 15
#define ITEM_LURE_BALL 16
#define ITEM_MOON_BALL 17
#define ITEM_FRIEND_BALL 18
#define ITEM_LOVE_BALL 19 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_FAST_BALL 20
#define ITEM_HEAVY_BALL 21
#define ITEM_DREAM_BALL 22
#define ITEM_SAFARI_BALL 23 // VENTA EN BASE ROCKET PROFUNDA
#define ITEM_SPORT_BALL 24
#define ITEM_PARK_BALL 25
#define ITEM_BEAST_BALL 26
#define ITEM_CHERISH_BALL 27

// Note: If moving ball IDs around, updating FIRST_BALL/LAST_BALL is not sufficient
//       Several places expect the ball IDs to be first and contiguous (e.g. MON_DATA_POKEBALL)
//       If adding new balls, it's easiest to insert them after the last ball and increment the below IDs (and removing ITEM_034 for example)
#define FIRST_BALL ITEM_POKE_BALL
#define LAST_BALL  ITEM_CHERISH_BALL

// Medicine
#define ITEM_POTION 28
#define ITEM_SUPER_POTION 29
#define ITEM_HYPER_POTION 30
#define ITEM_MAX_POTION 31
#define ITEM_FULL_RESTORE 32
#define ITEM_REVIVE 33
#define ITEM_MAX_REVIVE 34
#define ITEM_FRESH_WATER 35
#define ITEM_SODA_POP 36
#define ITEM_LEMONADE 37
#define ITEM_MOOMOO_MILK 38
#define ITEM_ENERGY_POWDER 39 // VENTA EN FARMACIA ORQUIDEA
#define ITEM_ENERGY_ROOT 40 // VENTA EN FARMACIA ORQUIDEA
#define ITEM_HEAL_POWDER 41 // VENTA EN FARMACIA ORQUIDEA
#define ITEM_REVIVAL_HERB 42 // VENTA EN FARMACIA ORQUIDEA
#define ITEM_ANTIDOTE 43
#define ITEM_PARALYZE_HEAL 44
#define ITEM_BURN_HEAL 45
#define ITEM_ICE_HEAL 46
#define ITEM_AWAKENING 47
#define ITEM_FULL_HEAL 48
#define ITEM_ETHER 49
#define ITEM_MAX_ETHER 50
#define ITEM_ELIXIR 51
#define ITEM_MAX_ELIXIR 52
#define ITEM_BERRY_JUICE 53
#define ITEM_SACRED_ASH 54 // VENTA EN TIENDA CIUDAD IRIS
#define ITEM_SWEET_HEART 55
#define ITEM_MAX_HONEY 56

// Regional Specialties
#define ITEM_PEWTER_CRUNCHIES 57
#define ITEM_RAGE_CANDY_BAR 58
#define ITEM_LAVA_COOKIE 59
#define ITEM_OLD_GATEAU 60
#define ITEM_CASTELIACONE 61
#define ITEM_LUMIOSE_GALETTE 62 // TIENDA OCULTA ISLA SETIMA
#define ITEM_SHALOUR_SABLE 63
#define ITEM_BIG_MALASADA 64

// Vitamins
#define ITEM_HP_UP 65
#define ITEM_PROTEIN 66
#define ITEM_IRON 67
#define ITEM_CALCIUM 68
#define ITEM_ZINC 69
#define ITEM_CARBOS 70
#define ITEM_PP_UP 71
#define ITEM_PP_MAX 72

// EV Feathers
#define ITEM_HEALTH_FEATHER 73 // VENTA EN BASE ROCKET PROFUNDA SALA ENTRENAMIENTO
#define ITEM_MUSCLE_FEATHER 74 // VENTA EN BASE ROCKET PROFUNDA SALA ENTRENAMIENTO
#define ITEM_RESIST_FEATHER 75 // VENTA EN BASE ROCKET PROFUNDA SALA ENTRENAMIENTO
#define ITEM_GENIUS_FEATHER 76 // VENTA EN BASE ROCKET PROFUNDA SALA ENTRENAMIENTO
#define ITEM_CLEVER_FEATHER 77 // VENTA EN BASE ROCKET PROFUNDA SALA ENTRENAMIENTO
#define ITEM_SWIFT_FEATHER 78 // VENTA EN BASE ROCKET PROFUNDA SALA ENTRENAMIENTO

// Ability Modifiers
#define ITEM_ABILITY_CAPSULE 79 // VENTA EN BASE ROCKET PROFUNDA SALA ENTRENAMIENTO

// Mints
#define ITEM_LONELY_MINT 80
#define ITEM_ADAMANT_MINT 81
#define ITEM_NAUGHTY_MINT 82
#define ITEM_BRAVE_MINT 83
#define ITEM_BOLD_MINT 84
#define ITEM_IMPISH_MINT 85
#define ITEM_LAX_MINT 86
#define ITEM_RELAXED_MINT 87
#define ITEM_MODEST_MINT 88
#define ITEM_MILD_MINT 89
#define ITEM_RASH_MINT 90
#define ITEM_QUIET_MINT 91
#define ITEM_CALM_MINT 92
#define ITEM_GENTLE_MINT 93
#define ITEM_CAREFUL_MINT 94
#define ITEM_SASSY_MINT 95
#define ITEM_TIMID_MINT 96
#define ITEM_HASTY_MINT 97
#define ITEM_JOLLY_MINT 98
#define ITEM_NAIVE_MINT 99
#define ITEM_SERIOUS_MINT 100

// Candy 
#define ITEM_RARE_CANDY 101
#define ITEM_EXP_CANDY_XS 102 // Nivel 15, Base Ruta 5
#define ITEM_EXP_CANDY_S 103 // Nivel 30, Base Rocket Profunda
#define ITEM_EXP_CANDY_XM 104 // Nivel 45, Base Rocket Profunda, Sala Ejecutivos
#define ITEM_EXP_CANDY_M 105 // Nivel 65, Base Rocket Profunda, Sala Entrenamiento
#define ITEM_EXP_CANDY_L 106 // Nivel 75, Base Rocket Johto, P1
#define ITEM_EXP_CANDY_XL 107 // Nivel 85, Base Rocket Johto, P2
#define ITEM_DYNAMAX_CANDY 108 // Nivel 95, Base Rocket Hoenn
#define ITEM_DYNAMAX_CANDY2 109 // Nivel 105, Torre Radio Lavanda

// Medicinal Flutes
#define ITEM_BLUE_FLUTE 110
#define ITEM_YELLOW_FLUTE 111
#define ITEM_RED_FLUTE 112

// Encounter-modifying Flutes
#define ITEM_BLACK_FLUTE 113
#define ITEM_WHITE_FLUTE 114

// Encounter Modifiers
#define ITEM_REPEL 115
#define ITEM_SUPER_REPEL 116
#define ITEM_MAX_REPEL 117
#define ITEM_LURE 118 
#define ITEM_SUPER_LURE 119
#define ITEM_MAX_LURE 120

#define ITEM_ESCAPE_ROPE 121

// X Items
#define ITEM_X_ATTACK 122
#define ITEM_X_DEFENSE 123
#define ITEM_X_SP_ATK 124
#define ITEM_X_SP_DEF 125
#define ITEM_X_SPEED 126
#define ITEM_X_ACCURACY 127

#define ITEM_DIRE_HIT 128
#define ITEM_GUARD_SPEC 129

// Escape Items
#define ITEM_POKE_DOLL 130
#define ITEM_FLUFFY_TAIL 131
#define ITEM_POKE_TOY 132

#define ITEM_MAX_MUSHROOMS 133

// Treasures
#define ITEM_BOTTLE_CAP 134
#define ITEM_GOLD_BOTTLE_CAP 135
#define ITEM_NUGGET 136
#define ITEM_BIG_NUGGET 137
#define ITEM_TINY_MUSHROOM 138 // VENTA EN MERCADO RUTA 45
#define ITEM_BIG_MUSHROOM 139 // VENTA EN MERCADO RUTA 45
#define ITEM_BALM_MUSHROOM 140
#define ITEM_PEARL 141
#define ITEM_BIG_PEARL 142
#define ITEM_PEARL_STRING 143
#define ITEM_STARDUST 144
#define ITEM_STAR_PIECE 145
#define ITEM_COMET_SHARD 146
#define ITEM_SHOAL_SALT 147
#define ITEM_SHOAL_SHELL 148
#define ITEM_RED_SHARD 149
#define ITEM_BLUE_SHARD 150
#define ITEM_YELLOW_SHARD 151
#define ITEM_GREEN_SHARD 152
#define ITEM_HEART_SCALE 153
#define ITEM_HONEY 154
#define ITEM_RARE_BONE 155
#define ITEM_ODD_KEYSTONE 156
#define ITEM_PRETTY_FEATHER 157
#define ITEM_RELIC_COPPER 158
#define ITEM_RELIC_SILVER 159
#define ITEM_RELIC_GOLD 160
#define ITEM_RELIC_VASE 161
#define ITEM_RELIC_BAND 162
#define ITEM_RELIC_STATUE 163
#define ITEM_RELIC_CROWN 164
#define ITEM_STRANGE_SOUVENIR 165

// Fossils
#define ITEM_HELIX_FOSSIL 166
#define ITEM_DOME_FOSSIL 167
#define ITEM_OLD_AMBER 168
#define ITEM_ROOT_FOSSIL 169
#define ITEM_CLAW_FOSSIL 170
#define ITEM_ARMOR_FOSSIL 171
#define ITEM_SKULL_FOSSIL 172
#define ITEM_COVER_FOSSIL 173
#define ITEM_PLUME_FOSSIL 174
#define ITEM_JAW_FOSSIL 175
#define ITEM_SAIL_FOSSIL 176
#define ITEM_FOSSILIZED_BIRD 177
#define ITEM_FOSSILIZED_FISH 178
#define ITEM_FOSSILIZED_DRAKE 179
#define ITEM_FOSSILIZED_DINO 180

// Mulch
#define ITEM_GROWTH_MULCH 181
#define ITEM_DAMP_MULCH 182
#define ITEM_STABLE_MULCH 183
#define ITEM_GOOEY_MULCH 184
#define ITEM_RICH_MULCH 185
#define ITEM_SURPRISE_MULCH 186
#define ITEM_BOOST_MULCH 187
#define ITEM_AMAZE_MULCH 188

// Apricorns
#define ITEM_RED_APRICORN 189
#define ITEM_BLUE_APRICORN 190
#define ITEM_YELLOW_APRICORN 191
#define ITEM_GREEN_APRICORN 192
#define ITEM_PINK_APRICORN 193
#define ITEM_WHITE_APRICORN 194
#define ITEM_BLACK_APRICORN 195

#define ITEM_WISHING_PIECE 196 // ALA ARCOIRIS
#define ITEM_GALARICA_TWIG 197 // ALA PLATEADA
#define ITEM_ARMORITE_ORE 198
#define ITEM_DYNITE_ORE 199

// Mail
#define ITEM_ORANGE_MAIL 200
#define ITEM_HARBOR_MAIL 201
#define ITEM_GLITTER_MAIL 202
#define ITEM_MECH_MAIL 203
#define ITEM_WOOD_MAIL 204
#define ITEM_WAVE_MAIL 205
#define ITEM_BEAD_MAIL 206
#define ITEM_SHADOW_MAIL 207
#define ITEM_TROPIC_MAIL 208
#define ITEM_DREAM_MAIL 209
#define ITEM_FAB_MAIL 210
#define ITEM_RETRO_MAIL 211

#define FIRST_MAIL_INDEX ITEM_ORANGE_MAIL

// Evolution Items
#define ITEM_FIRE_STONE 212
#define ITEM_WATER_STONE 213
#define ITEM_THUNDER_STONE 214
#define ITEM_LEAF_STONE 215
#define ITEM_ICE_STONE 216 // VENTA EN BASE PROFUNDA SALA ENTRENAMIENTO
#define ITEM_SUN_STONE 217
#define ITEM_MOON_STONE 218
#define ITEM_SHINY_STONE 219 // VENTA EN BASE PROFUNDA SALA ENTRENAMIENTO
#define ITEM_DUSK_STONE 220 // VENTA EN BASE PROFUNDA SALA ENTRENAMIENTO
#define ITEM_DAWN_STONE 221 // VENTA EN MERCADO RUTA 45 - VENTA EN BASE PROFUNDA SALA ENTRENAMIENTO
#define ITEM_SWEET_APPLE 222
#define ITEM_TART_APPLE 223
#define ITEM_CRACKED_POT 224 // VENTA EN BASE PROFUNDA SALA ENTRENAMIENTO, CABLE LINK
#define ITEM_CHIPPED_POT 225 // PIEDRA ROCKET, VENTA EN ÚLTIMO PISO TORRE RADIO LAVANDA
#define ITEM_GALARICA_CUFF 226
#define ITEM_GALARICA_WREATH 227
#define ITEM_DRAGON_SCALE 228 // 
#define ITEM_KEY_TO_ROOM_6 229
#define ITEM_UPGRADE 230 // VENTA EN SUBTERRANEO TRIGAL
#define ITEM_PROTECTOR 231 // SECUNDARIA SUBTERRANEO TRIGAL
#define ITEM_ELECTIRIZER 232 // ITEM DE SUELO EN CARBON2
#define ITEM_MAGMARIZER 233 // ITEM DE SUELO EN LAB4
#define ITEM_DUBIOUS_DISC 234 // REGALO CIENTIFICO S3 SILPH - VENTA EN SUBTERRANEO TRIGAL
#define ITEM_REAPER_CLOTH 235 // CULTO LAVANDA DESPUES 7MA MEDALLA JOHTO
#define ITEM_PRISM_SCALE 236 // RUTA 51 - OESTE CEREZO, ZONA CORRIENTES
#define ITEM_WHIPPED_DREAM 237
#define ITEM_SACHET 238
#define ITEM_OVAL_STONE 239 // VENTA EN SUBTERRANEO TRIGAL
#define ITEM_STRAWBERRY_SWEET 240
#define ITEM_LOVE_SWEET 241
#define ITEM_BERRY_SWEET 242
#define ITEM_CLOVER_SWEET 243
#define ITEM_FLOWER_SWEET 244
#define ITEM_STAR_SWEET 245
#define ITEM_RIBBON_SWEET 246


#define ITEM_EVERSTONE 247 // VENTA EN CENTRO COMERCIAL TRIGAL

// Nectars
#define ITEM_RED_NECTAR 248
#define ITEM_YELLOW_NECTAR 249
#define ITEM_PINK_NECTAR 250
#define ITEM_PURPLE_NECTAR 251

// Plates
#define ITEM_FLAME_PLATE 252 // VOLCÁN CANELA DLC
#define ITEM_SPLASH_PLATE 253 // NAO ABANDONADA
#define ITEM_ZAP_PLATE 254 // MALVALANOVA
#define ITEM_MEADOW_PLATE 255 // CASA VACÍA RUTA 26
#define ITEM_ICICLE_PLATE 256 // TEMPLO PUNTANEVA
#define ITEM_FIST_PLATE 257 // MONTE MORTERO ZONA ANÍBAL
#define ITEM_TOXIC_PLATE 258 // CASA RUTA 48 EXCAMPEON VENENO
#define ITEM_EARTH_PLATE 259 // FOSA WRONGSPARCE S3
#define ITEM_SKY_PLATE 260 // PILAR CELESTE
#define ITEM_MIND_PLATE 261 // PILAR DUN CIMA
#define ITEM_INSECT_PLATE 262 // BOSQUE NORTE VÍAS TREN DLC
#define ITEM_STONE_PLATE 263 // CUEVA GRANITO, SALA INVESTIGACIÓN DEVON
#define ITEM_SPOOKY_PLATE 264 // SENDA CAMINO A CULTO LAVANDA
#define ITEM_DRACO_PLATE 265 // GUARIDA DRAGÓN
#define ITEM_DREAD_PLATE 266 // CULTO S8
#define ITEM_IRON_PLATE 267 // RUTA 120, RUINAS REGISTEEL
#define ITEM_PIXIE_PLATE 268 // ZONA NOROESTE CIUDAD CEREZO

// Drives
#define ITEM_DOUSE_DRIVE 269
#define ITEM_SHOCK_DRIVE 270
#define ITEM_BURN_DRIVE 271
#define ITEM_CHILL_DRIVE 272

// Memories
#define ITEM_FIRE_MEMORY 273
#define ITEM_WATER_MEMORY 274
#define ITEM_ELECTRIC_MEMORY 275
#define ITEM_GRASS_MEMORY 276
#define ITEM_ICE_MEMORY 277
#define ITEM_FIGHTING_MEMORY 278
#define ITEM_POISON_MEMORY 279
#define ITEM_GROUND_MEMORY 280
#define ITEM_FLYING_MEMORY 281
#define ITEM_PSYCHIC_MEMORY 282
#define ITEM_BUG_MEMORY 283
#define ITEM_ROCK_MEMORY 284
#define ITEM_GHOST_MEMORY 285
#define ITEM_DRAGON_MEMORY 286
#define ITEM_DARK_MEMORY 287
#define ITEM_STEEL_MEMORY 288
#define ITEM_FAIRY_MEMORY 289

#define ITEM_RUSTED_SWORD 290
#define ITEM_RUSTED_SHIELD 291

// Colored Orbs
#define ITEM_RED_ORB 292
#define ITEM_BLUE_ORB 293

// Mega Stones
#define ITEM_VENUSAURITE 294 // ZONA NORTE DE CIUDAD TRIGAL
#define ITEM_CHARIZARDITE_X 295 // CIENTIFICO EN BASE CAOBA, DESPUÉS DE RECUPERARLA
#define ITEM_CHARIZARDITE_Y 296 // MISION LADRONES KANTO EN JOHTO, EDIFICO OCULTO EN EL MAR AL ESTE DE OLIVO
#define ITEM_BLASTOISINITE 297 // ZONA DE LAPRAS EN CUEVA UNION
#define ITEM_BEEDRILLITE 298 // NORESTE DE PARQUE NACIONAL EN JOHTO
#define ITEM_PIDGEOTITE 299 // DISCIPULO PEGASO AL SUR DE CIUDAD CEREZO
#define ITEM_ALAKAZITE 300 // OCULTO DETRÁS DE TORRE BELLSPROUT
#define ITEM_SLOWBRONITE 301 // SUPERNECIO EN POZO SLOWPOKE
#define ITEM_GENGARITE 302 // REGALO AGATHA TRAS DERROTAR A LIDER IRIS
#define ITEM_KANGASKHANITE 303 // CUEVA OSCURA DE JOHTO (ACCESIBLE DESPUES 2-3ra medalla)
#define ITEM_PINSIRITE 304 // BALL JUSTO ARRIBA DEL GIMNASIO DE CIUDAD OLIVO
#define ITEM_GYARADOSITE 305 // BASE CAOBA, MESA EN LA QUE ESTABA EL BOSS FINAL
#define ITEM_AERODACTYLITE 306 // REGALO DE ELM AL DERROTARLO EN PUEBLO PRIMAVERA
#define ITEM_MEWTWONITE_X 307 // LABORATORIO OAK FIN HOENN PARTE 1
#define ITEM_MEWTWONITE_Y 308 // GIOVANNI TRAS SEGUNDO ENCUENTRO
#define ITEM_AMPHAROSITE 309 // REGALO DEL FARERO SI VUELVES DESPUES DE DERROTAR A CROM
#define ITEM_STEELIXITE 310 // ZONA DE VIAS DE TREN, AL OESTE DE LA CUEVA DE VALERIA
#define ITEM_SCIZORITE 311 // REGALO TRAS DERROTAR A LOS GRANJEROS DE GRANJA MUMU
#define ITEM_HERACRONITE 312 // REGALO DE LA MUJER DE ANIBAL TRAS TRAER A SU MARIDO
#define ITEM_HOUNDOOMINITE 313 // ZONA DE SURF, AL NORTE DE RUTA 26
#define ITEM_TYRANITARITE 314 // MT.PLATEADO, ZONA QUE REQUIERE CASCADA
#define ITEM_SCEPTILITE 315 // TRAS GANAR EL RETO DE FAMILIA ESTRATEGA
#define ITEM_BLAZIKENITE 316 // RUTA 133 ZONA SUR
#define ITEM_SWAMPERTITE 317 // NAO ABANDONADA ZONA NUEVA
#define ITEM_GARDEVOIRITE 318 // BASE ROCKET JOHTO PISO SUPERIOR
#define ITEM_SABLENITE 319 // CUEVA GRANITO
#define ITEM_MAWILITE 320 // S1 AZALEA CARBON
#define ITEM_AGGRONITE 321 // BASE ROCKET JOHTO PISO SUPERIOR
#define ITEM_MEDICHAMITE 322 // BASE ROCKET JOHTO PISO SUPERIOR
#define ITEM_MANECTITE 323 // TORRE RADIO LAVANDA P9
#define ITEM_SHARPEDONITE 324 // LABORATORIO SECUNDARIA CIUDAD IRIS
#define ITEM_CAMERUPTITE 325 // LABORATORIO DESTRUIDO CANELA 
#define ITEM_ALTARIANITE 326 // RUTA 119, ENCIMA DE LA CASCADA
#define ITEM_BANETTITE 327 // CIMA MONTE PÍRICO
#define ITEM_ABSOLITE 328 // BASE ROCKET JOHTO PISO SUPERIOR
#define ITEM_GLALITITE 329 // RUTA 125 AL LADO DE CUEVA CARMUNEN
#define ITEM_SALAMENCITE 330 // BASE ROCKET JOHTO PISO SUPERIOR
#define ITEM_METAGROSSITE 331 // NO OBTENIBLE POR AHORA
#define ITEM_LATIASITE 332 // NO OBTENIBLE POR AHORA
#define ITEM_LATIOSITE 333 // NO OBTENIBLE POR AHORA
#define ITEM_LOPUNNITE 334 // CASINO MALVALONA SOTANO
#define ITEM_GARCHOMPITE 335 // BASE ROCKET JOHTO PISO SUPERIOR
#define ITEM_LUCARIONITE 336 // EQUIPADO EN EL RIOLU DE CROM
#define ITEM_ABOMASITE 337 // TEMPLO PUNTANEVA SINNOH
#define ITEM_GALLADITE 338 // BASE ROCKET JOHTO PISO SUPERIOR
#define ITEM_AUDINITE 339 // CIUDAD CALAGUA NPC QUE DABA DESCANSO
#define ITEM_DIANCITE 340 // LABORATORIO OAK FIN HOENN PARTE 1
#define ITEM_FLYGONITE 341 // BASE ROCKET JOHTO PISO SUPERIOR
#define ITEM_MILOTICITE 342 // BASE ROCKET JOHTO PISO SUPERIOR
#define ITEM_STARMIETITE 343 // REGALO DE ENTRENADORA SINGULAR EN ZONA OESTE CEREZO
#define ITEM_BUTTERFRITA 344 // BASE ROCKET JOHTO PISO SUPERIOR
#define ITEM_DUSKNOIRITA 345 // CULTO LAVANDA, SALA PREVIA A JONES (2da visita con 7 medallas en Johto)
#define ITEM_NOIVERNITA  346 // EQUIPADO EN EL NOIBAT QUE NOS REGALA MIRTO
#define ITEM_TOXTRICITIT  347 // REFUGIOS GUERRA KANTO, ZONA FINAL (DLC)
#define ITEM_PORYGONITA  348 // NO OBTENIBLE POR EL MOMENTO

// Gems
#define ITEM_NORMAL_GEM 349 // BASE ROCKET HOENN
#define ITEM_FIRE_GEM 350 // BASE ROCKET HOENN
#define ITEM_WATER_GEM 351 // BASE ROCKET HOENN
#define ITEM_ELECTRIC_GEM 352 // BASE ROCKET HOENN
#define ITEM_GRASS_GEM 353 // BASE ROCKET HOENN
#define ITEM_ICE_GEM 354 // BASE ROCKET HOENN
#define ITEM_FIGHTING_GEM 355 // BASE ROCKET HOENN
#define ITEM_POISON_GEM 356 // BASE ROCKET HOENN
#define ITEM_GROUND_GEM 357 // BASE ROCKET HOENN
#define ITEM_FLYING_GEM 358 // BASE ROCKET HOENN
#define ITEM_PSYCHIC_GEM 359 // BASE ROCKET HOENN
#define ITEM_BUG_GEM 360 // BASE ROCKET HOENN
#define ITEM_ROCK_GEM 361 // BASE ROCKET HOENN
#define ITEM_GHOST_GEM 362 // BASE ROCKET HOENN
#define ITEM_DRAGON_GEM 363 // BASE ROCKET HOENN
#define ITEM_DARK_GEM 364 // BASE ROCKET HOENN
#define ITEM_STEEL_GEM 365 // BASE ROCKET HOENN
#define ITEM_FAIRY_GEM 366 // BASE ROCKET HOENN

// Z-Crystals
#define ITEM_NORMALIUM_Z 367 // TORRE RADIO LAVANDA
#define ITEM_FIRIUM_Z 368 // TORRE RADIO LAVANDA
#define ITEM_WATERIUM_Z 369 // TORRE RADIO LAVANDA
#define ITEM_ELECTRIUM_Z 370 // TORRE RADIO LAVANDA
#define ITEM_GRASSIUM_Z 371 // TORRE RADIO LAVANDA
#define ITEM_ICIUM_Z 372 // TORRE RADIO LAVANDA
#define ITEM_FIGHTINIUM_Z 373 // TORRE RADIO LAVANDA
#define ITEM_POISONIUM_Z 374 // TORRE RADIO LAVANDA
#define ITEM_GROUNDIUM_Z 375 // TORRE RADIO LAVANDA
#define ITEM_FLYINIUM_Z 376 // TORRE RADIO LAVANDA
#define ITEM_PSYCHIUM_Z 377 // TORRE RADIO LAVANDA
#define ITEM_BUGINIUM_Z 378 // TORRE RADIO LAVANDA
#define ITEM_ROCKIUM_Z 379 // TORRE RADIO LAVANDA
#define ITEM_GHOSTIUM_Z 380 // TORRE RADIO LAVANDA
#define ITEM_DRAGONIUM_Z 381 // TORRE RADIO LAVANDA
#define ITEM_DARKINIUM_Z 382 // TORRE RADIO LAVANDA
#define ITEM_STEELIUM_Z 383 // TORRE RADIO LAVANDA
#define ITEM_FAIRIUM_Z 384 // TORRE RADIO LAVANDA
#define ITEM_PIKANIUM_Z 385
#define ITEM_EEVIUM_Z 386
#define ITEM_SNORLIUM_Z 387
#define ITEM_MEWNIUM_Z 388
#define ITEM_DECIDIUM_Z 389
#define ITEM_INCINIUM_Z 390
#define ITEM_PRIMARIUM_Z 391
#define ITEM_LYCANIUM_Z 392
#define ITEM_MIMIKIUM_Z 393
#define ITEM_KOMMONIUM_Z 394
#define ITEM_TAPUNIUM_Z 395
#define ITEM_SOLGANIUM_Z 396
#define ITEM_LUNALIUM_Z 397
#define ITEM_MARSHADIUM_Z 398
#define ITEM_ALORAICHIUM_Z 399
#define ITEM_PIKASHUNIUM_Z 400
#define ITEM_ULTRANECROZIUM_Z 401

// Species-specific Held Items
#define ITEM_LIGHT_BALL 402 // VENTA EN SUBTERRANEO TRIGAL
#define ITEM_LEEK 403 // VENTA EN SUBTERRANEO TRIGAL
#define ITEM_THICK_CLUB 404 // VENTA EN SUBTERRANEO TRIGAL
#define ITEM_LUCKY_PUNCH 405
#define ITEM_METAL_POWDER 406 // VENTA EN SUBTERRANEO TRIGAL
#define ITEM_QUICK_POWDER 407 // VENTA EN SUBTERRANEO TRIGAL
#define ITEM_DEEP_SEA_SCALE 408 // NAO ABANDONADA ZONA NUEVA
#define ITEM_DEEP_SEA_TOOTH 409 // CUEVA REGIGIGAS S4
#define ITEM_SOUL_DEW 410
#define ITEM_ADAMANT_ORB 411
#define ITEM_LUSTROUS_ORB 412
#define ITEM_GRISEOUS_ORB 413

// Incenses
#define ITEM_SEA_INCENSE 414
#define ITEM_LAX_INCENSE 415
#define ITEM_ODD_INCENSE 416
#define ITEM_ROCK_INCENSE 417
#define ITEM_FULL_INCENSE 418
#define ITEM_WAVE_INCENSE 419
#define ITEM_ROSE_INCENSE 420
#define ITEM_LUCK_INCENSE 421
#define ITEM_PURE_INCENSE 422

// Contest Scarves
#define ITEM_RED_SCARF 423
#define ITEM_BLUE_SCARF 424
#define ITEM_PINK_SCARF 425
#define ITEM_GREEN_SCARF 426
#define ITEM_YELLOW_SCARF 427

// EV Gain Modifiers
#define ITEM_MACHO_BRACE 428 // OBJETO EN BASE ROCKET PROFUNDA
#define ITEM_POWER_WEIGHT 429 // VENTA EN BASE ROCKET PROFUNDA SALA ENTENAMIENTO
#define ITEM_POWER_BRACER 430 // VENTA EN BASE ROCKET PROFUNDA SALA ENTENAMIENTO
#define ITEM_POWER_BELT 431 // VENTA EN BASE ROCKET PROFUNDA SALA ENTENAMIENTO
#define ITEM_POWER_LENS 432 // VENTA EN BASE ROCKET PROFUNDA SALA ENTENAMIENTO
#define ITEM_POWER_BAND 433 // VENTA EN BASE ROCKET PROFUNDA SALA ENTENAMIENTO
#define ITEM_POWER_ANKLET 434 // VENTA EN BASE ROCKET PROFUNDA SALA ENTENAMIENTO

// Type-boosting Held Items
#define ITEM_SILK_SCARF 435 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_CHARCOAL 436 // VENTA EN TIENDA PUEBLO AZALEA
#define ITEM_MYSTIC_WATER 437 // VENTA EN TIENDA CIUDAD OLIVO
#define ITEM_MAGNET 438 // VENTA EN TORRE RADIO LAVANDA
#define ITEM_MIRACLE_SEED 439 // VENTA EN TIENDA GIMNASIO OCULTO
#define ITEM_NEVER_MELT_ICE 440 // ITEM DE SUELO EN CUEVA GLACIADA
#define ITEM_BLACK_BELT 441 // REGALO AL DERROTAR A TODOS EN EL DOJO KARATE
#define ITEM_POISON_BARB 442 // REGALO PETREL TRAS MISION MUSEO
#define ITEM_SOFT_SAND 443 // VENTA EN FARMACIA CIUDAD ORQUIDEA
#define ITEM_SHARP_BEAK 444 // VENTA EN TIENDA CIUDAD MALVA
#define ITEM_TWISTED_SPOON 445 // REGALO CIENTIFICO BASE PROFUNDA
#define ITEM_SILVER_POWDER 446 // VENTA EN TIENDA PUEBLO AZALEA
#define ITEM_HARD_STONE 447 // VENTA EN TIENDA CIUDAD ENDRINO
#define ITEM_SPELL_TAG 448 // VENTA EN TIENDA CIUDAD IRIS
#define ITEM_DRAGON_FANG 449 // VENTA EN BASE ROCKET PROFUNDA
#define ITEM_BLACK_GLASSES 450 // REGALO DE KOGA AL ENTRAR A CIUDAD FUCSIA
#define ITEM_METAL_COAT 451 // VENTA EN TORRE RADIO LAVANDA

// Choice Items
#define ITEM_CHOICE_BAND 452 // CASINO-SUBTERANEO TRIGAL - ENTRENADOR ESPECIAL MUSEO PLATEADA
#define ITEM_CHOICE_SPECS 453 // CASINO-SUBTERANEO TRIGAL - ENTRENADOR ESPECIAL AZAFRAN, COPIONA
#define ITEM_CHOICE_SCARF 454 // CASINO-SUBTERANEO TRIGAL - ENTRENADOR ESPECIAL ISLA SETIMA

// Status Orbs
#define ITEM_FLAME_ORB 455 // VENTA POR FICHAS EN SUBTERRANEO TRIGAL
#define ITEM_TOXIC_ORB 456 // VENTA POR FICHAS EN CASINO TRIGAL

// Weather Rocks
#define ITEM_DAMP_ROCK 457 // VENTA CENTRO COMERCIAL TRIGAL
#define ITEM_HEAT_ROCK 458 // VENTA CENTRO COMERCIAL TRIGAL
#define ITEM_SMOOTH_ROCK 459 // VENTA CENTRO COMERCIAL TRIGAL
#define ITEM_ICY_ROCK 460 // VENTA CENTRO COMERCIAL TRIGAL

// Terrain Seeds
#define ITEM_ELECTRIC_SEED 461 // VENTA TORRE RADIO LAVANDA
#define ITEM_PSYCHIC_SEED 462 // VENTA TORRE RADIO LAVANDA
#define ITEM_MISTY_SEED 463 // VENTA TORRE RADIO LAVANDA
#define ITEM_GRASSY_SEED 464 // VENTA TORRE RADIO LAVANDA

// Type-activated Stat Modifiers
#define ITEM_ABSORB_BULB 465 // VENTA TORRE RADIO LAVANDA
#define ITEM_CELL_BATTERY 466 // VENTA TORRE RADIO LAVANDA
#define ITEM_LUMINOUS_MOSS 467 // VENTA TORRE RADIO LAVANDA
#define ITEM_SNOWBALL 468 // VENTA TORRE RADIO LAVANDA

// Misc. Held Items
#define ITEM_BRIGHT_POWDER 469
#define ITEM_WHITE_HERB 470 // VENTA EN MERCADO RUTA 45
#define ITEM_EXP_SHARE 471 // CASA CONSUL DESPUES DE DERROTADA
#define ITEM_QUICK_CLAW 472 // BASE ISLA INTA
#define ITEM_SOOTHE_BELL 473 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_MENTAL_HERB 474 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_KINGS_ROCK 475 // CAÑON SETE
#define ITEM_AMULET_COIN 476 // VENTA EN BASE ROCKET PROFUNDA
#define ITEM_CLEANSE_TAG 477 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_SMOKE_BALL 478 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_FOCUS_BAND 479 // VENTA EN BASE ROCKET PROFUNDA
#define ITEM_LUCKY_EGG 480 // NO EXISTE EN EL JUEGO
#define ITEM_SCOPE_LENS 481 // VENTA EN TORRE RADIO LAVANDA
#define ITEM_LEFTOVERS 482 // SUBTERRANEO TRIGAL/SNORLAX INVISIBLE
#define ITEM_SHELL_BELL 483 // BASE ROCKET PROFUNDA
#define ITEM_WIDE_LENS 484 // VENTA EN TORRE RADIO LAVANDA
#define ITEM_MUSCLE_BAND 485 // VENTA EN TORRE RADIO LAVANDA
#define ITEM_WISE_GLASSES 486 // VENTA EN TORRE RADIO LAVANDA
#define ITEM_EXPERT_BELT 487 // VENTA CASINO TRIGAL - ENTRENADOR ESPECIAL CIUDAD FUCSIA
#define ITEM_LIGHT_CLAY 488 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_LIFE_ORB 489 // ENTRENADOR GUAY FINAL CALLE VICTORIA (DOBLE FILO)
#define ITEM_POWER_HERB 490 // VENTA SUBTERRANEO TRIGAL
#define ITEM_FOCUS_SASH 491 //VENTA EN BASE ROCKET PROFUNDA
#define ITEM_ZOOM_LENS 492 // VENTA EN TORRE RADIO LAVANDA
#define ITEM_METRONOME 493 // VENTA CASINO TRIGAL
#define ITEM_IRON_BALL 494
#define ITEM_LAGGING_TAIL 495
#define ITEM_DESTINY_KNOT 496
#define ITEM_BLACK_SLUDGE 497 // ENTRENADOR ESPECIAL CIUDAD VERDE
#define ITEM_GRIP_CLAW 498
#define ITEM_STICKY_BARB 499
#define ITEM_SHED_SHELL 500
#define ITEM_BIG_ROOT 501 // VENTA EN FARMACIA ORQUIDEA
#define ITEM_RAZOR_CLAW 502 // TORRE SECUNDA P1
#define ITEM_RAZOR_FANG 503 // PASS_ROUTE47
#define ITEM_EVIOLITE 504 // REGALO GIOVANNI TRAS MISIÓN PUEBLO PALETA
#define ITEM_FLOAT_STONE 505
#define ITEM_ROCKY_HELMET 506 // VENTA CASINO TRIGAL - ENTRENADOR ESPECIAL CASA ISLA CUARTA
#define ITEM_AIR_BALLOON 507 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_RED_CARD 508 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_RING_TARGET 509 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_BINDING_BAND 510 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_EJECT_BUTTON 511 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_WEAKNESS_POLICY 512 // VENTA EN CENTRO COMERCIAL TRIGAL
#define ITEM_ASSAULT_VEST 513 // CASINO CIUDAD TRIGAL - ENTRENADOR ESPECIAL LAB CANELA
#define ITEM_SAFETY_GOGGLES 514 // TORRE RADIO LAVANDA
#define ITEM_ADRENALINE_ORB 515 // TORRE RADIO LAVANDA
#define ITEM_TERRAIN_EXTENDER 516 // TORRE RADIO LAVANDA
#define ITEM_PROTECTIVE_PADS 517 // TORRE RADIO LAVANDA
#define ITEM_THROAT_SPRAY 518 // TORRE RADIO LAVANDA
#define ITEM_EJECT_PACK 519 // TORRE RADIO LAVANDA
#define ITEM_HEAVY_DUTY_BOOTS 520 // TORRE RADIO LAVANDA
#define ITEM_BLUNDER_POLICY 521 // TORRE RADIO LAVANDA
#define ITEM_ROOM_SERVICE 522 // TORRE RADIO LAVANDA
#define ITEM_UTILITY_UMBRELLA 523 // TORRE RADIO LAVANDA

// Berries
#define ITEM_CHERI_BERRY 524
#define ITEM_CHESTO_BERRY 525
#define ITEM_PECHA_BERRY 526
#define ITEM_RAWST_BERRY 527
#define ITEM_ASPEAR_BERRY 528
#define ITEM_LEPPA_BERRY 529
#define ITEM_ORAN_BERRY 530
#define ITEM_PERSIM_BERRY 531
#define ITEM_LUM_BERRY 532 // VENTA EN BASE ROCKET PROFUNDA
#define ITEM_SITRUS_BERRY 533 // VENTA EN BASE ROCKET PROFUNDA
#define ITEM_FIGY_BERRY 534
#define ITEM_WIKI_BERRY 535
#define ITEM_MAGO_BERRY 536
#define ITEM_AGUAV_BERRY 537
#define ITEM_IAPAPA_BERRY 538
#define ITEM_RAZZ_BERRY 539 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_BLUK_BERRY 540 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_NANAB_BERRY 541 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_WEPEAR_BERRY 542 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_PINAP_BERRY 543 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_POMEG_BERRY 544 // VENTA EN BASE ROCKET JOHTO PISOS SUPERIORES
#define ITEM_KELPSY_BERRY 545 // VENTA EN BASE ROCKET JOHTO PISOS SUPERIORES
#define ITEM_QUALOT_BERRY 546 // VENTA EN MERCADO RUTA 45 - B.ROCKET JOHTO P.SUPERIORES
#define ITEM_HONDEW_BERRY 547 // VENTA EN BASE ROCKET JOHTO PISOS SUPERIORES
#define ITEM_GREPA_BERRY 548 // VENTA EN BASE ROCKET JOHTO PISOS SUPERIORES
#define ITEM_TAMATO_BERRY 549 // VENTA EN BASE ROCKET JOHTO PISOS SUPERIORES
#define ITEM_CORNN_BERRY 550 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_MAGOST_BERRY 551 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_RABUTA_BERRY 552 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_NOMEL_BERRY 553 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_SPELON_BERRY 554 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_PAMTRE_BERRY 555 // VENTA EN FLORISTERIA TRIGAL
#define ITEM_WATMEL_BERRY 556 // VENTA EN FLORSITERIA TRIGAL
#define ITEM_DURIN_BERRY 557
#define ITEM_BELUE_BERRY 558
#define ITEM_CHILAN_BERRY 559 // VENTA TIENDA BOSQUE GYM
#define ITEM_OCCA_BERRY 560 // VENTA TIENDA BOSQUE GYM
#define ITEM_PASSHO_BERRY 561 // VENTA TIENDA BOSQUE GYM
#define ITEM_WACAN_BERRY 562 // VENTA TIENDA BOSQUE GYM
#define ITEM_RINDO_BERRY 563 // VENTA TIENDA BOSQUE GYM
#define ITEM_YACHE_BERRY 564 // VENTA TIENDA BOSQUE GYM
#define ITEM_CHOPLE_BERRY 565 // VENTA TIENDA BOSQUE GYM
#define ITEM_KEBIA_BERRY 566 // VENTA TIENDA BOSQUE GYM
#define ITEM_SHUCA_BERRY 567 // VENTA TIENDA BOSQUE GYM
#define ITEM_COBA_BERRY 568 // VENTA TIENDA BOSQUE GYM
#define ITEM_PAYAPA_BERRY 569 // VENTA TIENDA BOSQUE GYM
#define ITEM_TANGA_BERRY 570 // VENTA TIENDA BOSQUE GYM
#define ITEM_CHARTI_BERRY 571 // VENTA TIENDA BOSQUE GYM
#define ITEM_KASIB_BERRY 572 // VENTA TIENDA BOSQUE GYM
#define ITEM_HABAN_BERRY 573 // VENTA TIENDA BOSQUE GYM
#define ITEM_COLBUR_BERRY 574 // VENTA TIENDA BOSQUE GYM
#define ITEM_BABIRI_BERRY 575 // VENTA TIENDA BOSQUE GYM
#define ITEM_ROSELI_BERRY 576 // VENTA TIENDA BOSQUE GYM
#define ITEM_LIECHI_BERRY 577 // VENTA EN TIENDA CIUDAD MALVA
#define ITEM_GANLON_BERRY 578 // VENTA EN TIENDA PUEBLO AZALEA
#define ITEM_SALAC_BERRY 579
#define ITEM_PETAYA_BERRY 580 // VENTA EN TIENDA CIUDAD IRIS - VENTA TIENDA BOSQUE GYM
#define ITEM_APICOT_BERRY 581 // VENTA EN TIENDA CIUDAD OLIVO - VENTA TIENDA BOSQUE GYM
#define ITEM_LANSAT_BERRY 582 // VENTA TIENDA BOSQUE GYM
#define ITEM_STARF_BERRY 583 // VENTA TIENDA BOSQUE GYM
#define ITEM_ENIGMA_BERRY 584 // VENTA TIENDA BOSQUE GYM
#define ITEM_MICLE_BERRY 585 // VENTA TIENDA BOSQUE GYM
#define ITEM_CUSTAP_BERRY 586 // VENTA TIENDA BOSQUE GYM
#define ITEM_JABOCA_BERRY 587 // VENTA TIENDA BOSQUE GYM
#define ITEM_ROWAP_BERRY 588 // VENTA TIENDA BOSQUE GYM
#define ITEM_KEE_BERRY 589 // VENTA EN GYM OCULTO
#define ITEM_MARANGA_BERRY 590 // VENTA TIENDA BOSQUE GYM
#define ITEM_ENIGMA_BERRY_E_READER 591

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX  ITEM_ENIGMA_BERRY_E_READER

// TMs/HMs
#define ITEM_TM01 592
#define ITEM_TM02 593
#define ITEM_TM03 594
#define ITEM_TM04 595
#define ITEM_TM05 596 // CENTRO COMERCIAL AZULONA
#define ITEM_TM06 597
#define ITEM_TM07 598 // GRANIZO
#define ITEM_TM08 599
#define ITEM_TM09 600
#define ITEM_TM10 601
#define ITEM_TM11 602
#define ITEM_TM12 603
#define ITEM_TM13 604
#define ITEM_TM14 605
#define ITEM_TM15 606 // CENTRO COMERCIAL AZULONA
#define ITEM_TM16 607
#define ITEM_TM17 608 // PROTECCION - ROCKET SALA VIP
#define ITEM_TM18 609
#define ITEM_TM19 610
#define ITEM_TM20 611
#define ITEM_TM21 612
#define ITEM_TM22 613
#define ITEM_TM23 614
#define ITEM_TM24 615
#define ITEM_TM25 616
#define ITEM_TM26 617
#define ITEM_TM27 618
#define ITEM_TM28 619 // CENTRO COMERCIAL AZULONA
#define ITEM_TM29 620 // PSÍQUICO - ROCKET SALA VIP
#define ITEM_TM30 621 // BOLA SOMBRA - ROCKET SALA VIP
#define ITEM_TM31 622 // CENTRO COMERCIAL AZULONA
#define ITEM_TM32 623
#define ITEM_TM33 624
#define ITEM_TM34 625
#define ITEM_TM35 626
#define ITEM_TM36 627 // BOMBA LODO - SALA ENTRENAMIENTO 9F
#define ITEM_TM37 628
#define ITEM_TM38 629
#define ITEM_TM39 630
#define ITEM_TM40 631
#define ITEM_TM41 632
#define ITEM_TM42 633
#define ITEM_TM43 634 // CENTRO COMERCIAL AZULONA
#define ITEM_TM44 635
#define ITEM_TM45 636 // CENTRO COMERCIAL AZULONA
#define ITEM_TM46 637
#define ITEM_TM47 638
#define ITEM_TM48 639
#define ITEM_TM49 640
#define ITEM_TM50 641
#define ITEM_TM51 642 // ONDA CERTERA - SILPH S3
#define ITEM_TM52 643 // ACROBATA - RUTA 49
#define ITEM_TM53 644 // GIGA IMPACTO - TUTOR CENTRO COMERCIAL AZULONA
#define ITEM_TM54 645 // PULSO UMBRIO - SALA EJECUTIVOS
#define ITEM_TM55 646 // VOLTIO CRUEL - BASE HOENN
#define ITEM_TM56 647 // ROCA AFILADA - TUNEL ROCA
#define ITEM_TM57 648 // VENENO X - EXTERIOR FARO OLIVO
#define ITEM_TM58 649 // TIJERA X - MISION TRIGAL 3
#define ITEM_TM59 650 // AFILARGARRAS - JOHTO 3ER GYM
#define ITEM_TM60 651 // PSICOCARGA - JOHTO 6TO GYM
#define ITEM_TM61 652 // RESPIRO - JOHTO 1ER GYM
#define ITEM_TM62 653 // ANTIAEREO - RUTA 50
#define ITEM_TM63 654 // ONDA TOXICA - RADIO LAVANDA 5
#define ITEM_TM64 655 // NITRO CARGA - AZALEA CARBON
#define ITEM_TM65 656 // PUNTAPIE - JOHTO 5TO GYM
#define ITEM_TM66 657 // ECO VOZ - COMERCIAL TRIGAL
#define ITEM_TM67 658 // ENERGIBOLA - VIASTREN 5
#define ITEM_TM68 659 // FALSOTORTAZO - SUBTERRANEO TRIGAL
#define ITEM_TM69 660 // ESCALDAR - CUEVA TESORO 4
#define ITEM_TM70 661 // RAYO CARGA - NEO POWER PLANT
#define ITEM_TM71 662 // CAIDA LIBRE - RUTA 47
#define ITEM_TM72 663 // FUEGO FATUO - TORRE QUEMADA
#define ITEM_TM73 664 // EXPLOSION - LAB3
#define ITEM_TM74 665 // GARRA UMBRIA - SUBTERRANEO TRIGAL
#define ITEM_TM75 666 // VENDETA - CULTO S4
#define ITEM_TM76 667 // REPRESALIA - CEMENTERIO S2
#define ITEM_TM77 668 // PULIMENTO - JOHTO 4TO GYM
#define ITEM_TM78 669 // VOLTIOCAMBIO - FARO CIUDAD OLIVO
#define ITEM_TM79 670 // ONDA TRUENO - LAVANDA RADIO P6
#define ITEM_TM80 671 // GIRO BOLA - BASE HOENN S2
#define ITEM_TM81 672 // DANZA ESPADA - SEVII 1ER GYM
#define ITEM_TM82 673 // ESTOICISMO - JOHTO 2DO GYM
#define ITEM_TM83 674 // TERRATEMBLOR - MONTAÑERO ENTRADA ASCUAS
#define ITEM_TM84 675 // VAHO GELIDO - JOHTO 7MO GYM
#define ITEM_TM85 676 // AVALANCHA - SECUNDARIA ISLA CUARTA 
#define ITEM_TM86 677 // COLA DRAGON - DUNSPARCE P4
#define ITEM_TM87 678 // PUYA NOCIVA - JOHTO BASE
#define ITEM_TM88 679 // HIERBA LAZO - VIAS TREN 2
#define ITEM_TM89 680 // CONTONEO - SUBTERRANEO TRIGAL
#define ITEM_TM90 681 // PICOTEO - VIAS BOSQUE
#define ITEM_TM91 682 // IDA Y VUELTA - ENCINAR ANTÓN
#define ITEM_TM92 683 // SUSTITUTO - COMERCIAL TRIGAL
#define ITEM_TM93 684 // FOCO RESPLANDOR - TIN TOWER
#define ITEM_TM94 685 // ESPACIO RARO - SEVII 2DO GYM
#define ITEM_TM95 686 // TRAMPA ROCAS - VIAS SUR 4
#define ITEM_TM96 687 // ALUD - LAGO FURIA
#define ITEM_TM97 688 // SALMUERA - CUEVA UNION
#define ITEM_TM98 689 // PUÑO DRENAJE - LAGO FURIA
#define ITEM_TM99 690 // PULSO DRAGON - JOHTO 8VO GYM
#define ITEM_TM100 691 // BRILLO MAGICO - COMERCIAL TRIGAL
#define ITEM_TM101 692 // GIRO VIL - VIA SUBTERRANEA
#define ITEM_TM102 693 // CUERNO CERTERO - TORRE SECUNDA P4
#define ITEM_TM103 694 // VELO AURORA - BALL EN ICEFALLCAVE_LAPRAS
#define ITEM_TM104 695 // ACOSO - VIA SUBTERRANEA (zona norte después de que se vayan los moteros)
#define ITEM_TM105 696 // ALARIDO - REGALO ROCKET CEMENTERIO LAVANDA S1
#define ITEM_TM106 697 // PUÑO INCREMENTO - CAJA LLAVE VIA SUBTERRANEA (DLC)
#define ITEM_TM107 698 // PUÑO HIELO - COMERCIAL TRIGAL
#define ITEM_TM108 699 // PUÑO TRUENO - COMERCIAL TRIGAL
#define ITEM_TM109 700 // PUÑO FUEGO - COMERCIAL TRIGAL
#define ITEM_TM110 701 // ATAQUE AÉREO - CIMA MAPA ZAPDOS-P
#define ITEM_TM111 702 // PSICOONDA - TORRE RADIO LAVANDA P10
#define ITEM_TM112 703 // ESFERA AURAL - PAGODA RUTA 49 P2
#define ITEM_TM113 704 // VIENTO AFÍN - DUNSPARCE P4
#define ITEM_TM114 705 // LANZA MUGRE - CIENTÍFICO ROCKET HIDEOUT P1
#define ITEM_TM115 706 // CABEZAHIERRO - MISION7LAB2
#define ITEM_TM116 707 // CAMPO ELÉCTRICO
#define ITEM_TM117 708 // CAMPO DE HIERBA
#define ITEM_TM118 709 // CAMPO PSÍQUICO
#define ITEM_TM119 710 // CAMPO DE NIEBLA
#define ITEM_TM120 711
#define ITEM_TM121 712
#define ITEM_TM122 713
#define ITEM_TM123 714
#define ITEM_TM124 715
#define ITEM_TM125 716
#define ITEM_TM126 717
#define ITEM_TM127 718
#define ITEM_TM128 719
#define ITEM_TM129 720
#define ITEM_TM130 721
#define ITEM_TM131 722
#define ITEM_TM132 723
#define ITEM_TM133 724
#define ITEM_TM134 725
#define ITEM_TM135 726
#define ITEM_TM136 727
#define ITEM_TM137 728
#define ITEM_TM138 729
#define ITEM_TM139 730
#define ITEM_TM140 731
#define ITEM_TM141 732
#define ITEM_TM142 733
#define ITEM_TM143 734
#define ITEM_TM144 735
#define ITEM_TM145 736
#define ITEM_TM146 737
#define ITEM_TM147 738
#define ITEM_TM148 739
#define ITEM_TM149 740
#define ITEM_TM150 741
#define ITEM_TM151 742
#define ITEM_TM152 743
#define ITEM_TM153 744
#define ITEM_TM154 745
#define ITEM_TM155 746
#define ITEM_TM156 747
#define ITEM_TM157 748
#define ITEM_TM158 749
#define ITEM_TM159 750
#define ITEM_TM160 751
#define ITEM_TM161 752
#define ITEM_TM162 753
#define ITEM_TM163 754
#define ITEM_TM164 755
#define ITEM_TM165 756
#define ITEM_TM166 757
#define ITEM_TM167 758
#define ITEM_TM168 759
#define ITEM_TM169 760
#define ITEM_TM170 761
#define ITEM_TM171 762
#define ITEM_TM172 763
#define ITEM_TM173 764
#define ITEM_TM174 765
#define ITEM_TM175 766
#define ITEM_TM176 767
#define ITEM_TM177 768
#define ITEM_TM178 769
#define ITEM_TM179 770
#define ITEM_TM180 771
#define ITEM_TM181 772
#define ITEM_TM182 773
#define ITEM_TM183 774
#define ITEM_TM184 775
#define ITEM_TM185 776
#define ITEM_TM186 777
#define ITEM_TM187 778
#define ITEM_TM188 779
#define ITEM_TM189 780
#define ITEM_TM190 781
#define ITEM_TM191 782
#define ITEM_TM192 783
#define ITEM_TM193 784
#define ITEM_TM194 785
#define ITEM_TM195 786
#define ITEM_TM196 787
#define ITEM_TM197 788
#define ITEM_TM198 789
#define ITEM_TM199 790
#define ITEM_TM200 791
#define ITEM_TM201 792
#define ITEM_TM202 793
#define ITEM_TM203 794
#define ITEM_TM204 795
#define ITEM_TM205 796
#define ITEM_TM206 797
#define ITEM_TM207 798
#define ITEM_TM208 799
#define ITEM_TM209 800
#define ITEM_TM210 801
#define ITEM_TM211 802
#define ITEM_TM212 803
#define ITEM_TM213 804
#define ITEM_TM214 805
#define ITEM_TM215 806
#define ITEM_TM216 807
#define ITEM_TM217 808
#define ITEM_TM218 809
#define ITEM_TM219 810
#define ITEM_TM220 811
#define ITEM_TM221 812
#define ITEM_TM222 813
#define ITEM_TM223 814
#define ITEM_TM224 815
#define ITEM_TM225 816
#define ITEM_TM226 817
#define ITEM_TM227 818
#define ITEM_TM228 819
#define ITEM_TM229 820
#define ITEM_TM230 821
#define ITEM_TM231 822
#define ITEM_TM232 823
#define ITEM_TM233 824
#define ITEM_TM234 825
#define ITEM_TM235 826
#define ITEM_TM236 827
#define ITEM_TM237 828
#define ITEM_TM238 829
#define ITEM_TM239 830
#define ITEM_TM240 831
#define ITEM_TM241 832
#define ITEM_TM242 833
#define ITEM_TM243 834
#define ITEM_TM244 835
#define ITEM_TM245 836
#define ITEM_TM246 837

#define ITEM_HM01 838
#define ITEM_HM02 839
#define ITEM_HM03 840
#define ITEM_HM04 841
#define ITEM_HM05 842
#define ITEM_HM06 843
#define ITEM_HM07 844
#define ITEM_HM08 845

#define ITEM_TM01_FOCUS_PUNCH ITEM_TM01
#define ITEM_TM02_DRAGON_CLAW ITEM_TM02
#define ITEM_TM03_WATER_PULSE ITEM_TM03
#define ITEM_TM04_CALM_MIND ITEM_TM04
#define ITEM_TM05_ROAR ITEM_TM05
#define ITEM_TM06_TOXIC ITEM_TM06
#define ITEM_TM07_HAIL ITEM_TM07
#define ITEM_TM08_BULK_UP ITEM_TM08
#define ITEM_TM09_BULLET_SEED ITEM_TM09
#define ITEM_TM10_HIDDEN_POWER ITEM_TM10
#define ITEM_TM11_SUNNY_DAY ITEM_TM11
#define ITEM_TM12_TAUNT ITEM_TM12
#define ITEM_TM13_ICE_BEAM ITEM_TM13
#define ITEM_TM14_BLIZZARD ITEM_TM14
#define ITEM_TM15_HYPER_BEAM ITEM_TM15
#define ITEM_TM16_LIGHT_SCREEN ITEM_TM16
#define ITEM_TM17_PROTECT ITEM_TM17
#define ITEM_TM18_RAIN_DANCE ITEM_TM18
#define ITEM_TM19_GIGA_DRAIN ITEM_TM19
#define ITEM_TM20_SAFEGUARD ITEM_TM20
#define ITEM_TM21_FRUSTRATION ITEM_TM21
#define ITEM_TM22_SOLAR_BEAM ITEM_TM22
#define ITEM_TM23_IRON_TAIL ITEM_TM23
#define ITEM_TM24_THUNDERBOLT ITEM_TM24
#define ITEM_TM25_THUNDER ITEM_TM25
#define ITEM_TM26_EARTHQUAKE ITEM_TM26
#define ITEM_TM27_RETURN ITEM_TM27
#define ITEM_TM28_DIG ITEM_TM28
#define ITEM_TM29_PSYCHIC ITEM_TM29
#define ITEM_TM30_SHADOW_BALL ITEM_TM30
#define ITEM_TM31_BRICK_BREAK ITEM_TM31
#define ITEM_TM32_DOUBLE_TEAM ITEM_TM32
#define ITEM_TM33_REFLECT ITEM_TM33
#define ITEM_TM34_SHOCK_WAVE ITEM_TM34
#define ITEM_TM35_FLAMETHROWER ITEM_TM35
#define ITEM_TM36_SLUDGE_BOMB ITEM_TM36
#define ITEM_TM37_SANDSTORM ITEM_TM37
#define ITEM_TM38_FIRE_BLAST ITEM_TM38
#define ITEM_TM39_ROCK_TOMB ITEM_TM39
#define ITEM_TM40_AERIAL_ACE ITEM_TM40
#define ITEM_TM41_TORMENT ITEM_TM41
#define ITEM_TM42_FACADE ITEM_TM42
#define ITEM_TM43_SECRET_POWER ITEM_TM43
#define ITEM_TM44_REST ITEM_TM44
#define ITEM_TM45_ATTRACT ITEM_TM45
#define ITEM_TM46_THIEF ITEM_TM46
#define ITEM_TM47_STEEL_WING ITEM_TM47
#define ITEM_TM48_SKILL_SWAP ITEM_TM48
#define ITEM_TM49_SNATCH ITEM_TM49
#define ITEM_TM50_OVERHEAT ITEM_TM50
#define ITEM_TM51_FOCUS_BLAST ITEM_TM51
#define ITEM_TM52_ACROBATICS ITEM_TM52
#define ITEM_TM53_GIGA_IMPACT ITEM_TM53
#define ITEM_TM54_DARK_PULSE ITEM_TM54
#define ITEM_TM55_WILD_CHARGE ITEM_TM55
#define ITEM_TM56_STONE_EDGE ITEM_TM56
#define ITEM_TM57_CROSS_POISON ITEM_TM57
#define ITEM_TM58_X_SCISSOR ITEM_TM58
#define ITEM_TM59_HONE_CLAWS ITEM_TM59
#define ITEM_TM60_PSYSHOCK ITEM_TM60
#define ITEM_TM61_ROOST ITEM_TM61
#define ITEM_TM62_SMACK_DOWN ITEM_TM62
#define ITEM_TM63_SLUDGE_WAVE ITEM_TM63
#define ITEM_TM64_FLAME_CHARGE ITEM_TM64
#define ITEM_TM65_LOW_SWEEP ITEM_TM65
#define ITEM_TM66_ECHOED_VOICE ITEM_TM66
#define ITEM_TM67_ENERGY_BALL ITEM_TM67
#define ITEM_TM68_FALSE_SWIPE ITEM_TM68
#define ITEM_TM69_SCALD ITEM_TM69
#define ITEM_TM70_CHARGE_BEAM ITEM_TM70
#define ITEM_TM71_SKY_DROP ITEM_TM71
#define ITEM_TM72_WILL_O_WISP ITEM_TM72
#define ITEM_TM73_EXPLOSION ITEM_TM73
#define ITEM_TM74_SHADOW_CLAW ITEM_TM74
#define ITEM_TM75_PAYBACK ITEM_TM75
#define ITEM_TM76_RETALIATE ITEM_TM76
#define ITEM_TM77_ROCK_POLISH ITEM_TM77
#define ITEM_TM78_VOLT_SWITCH ITEM_TM78
#define ITEM_TM79_THUNDER_WAVE ITEM_TM79
#define ITEM_TM80_GYRO_BALL ITEM_TM80
#define ITEM_TM81_SWORDS_DANCE ITEM_TM81
#define ITEM_TM82_STRUGGLE_BUG ITEM_TM82
#define ITEM_TM83_BULLDOZE ITEM_TM83
#define ITEM_TM84_FROST_BREATH ITEM_TM84
#define ITEM_TM85_ROCK_SLIDE ITEM_TM85
#define ITEM_TM86_DRAGON_TAIL ITEM_TM86
#define ITEM_TM87_POISON_JAB ITEM_TM87
#define ITEM_TM88_GRASS_KNOT ITEM_TM88
#define ITEM_TM89_SWAGGER ITEM_TM89
#define ITEM_TM90_PLUCK ITEM_TM90
#define ITEM_TM91_U_TURN ITEM_TM91
#define ITEM_TM92_SUBSTITUTE ITEM_TM92
#define ITEM_TM93_FLASH_CANNON ITEM_TM93
#define ITEM_TM94_TRICK_ROOM ITEM_TM94
#define ITEM_TM95_STEALTH_ROCK ITEM_TM95
#define ITEM_TM96_AVALANCHE ITEM_TM96
#define ITEM_TM97_BRINE ITEM_TM97
#define ITEM_TM98_DRAIN_PUNCH ITEM_TM98
#define ITEM_TM99_DRAGON_PULSE ITEM_TM99
#define ITEM_TM100_DAZZLING_GLEAM ITEM_TM100
#define ITEM_TM101_BRUTAL_SWING ITEM_TM101
#define ITEM_TM102_SMART_STRIKE ITEM_TM102
#define ITEM_TM103_AURORA_VEIL ITEM_TM103
#define ITEM_TM104_INFESTATION ITEM_TM104
#define ITEM_TM105_SNARL ITEM_TM105
#define ITEM_TM106_POWER_UP_PUNCH ITEM_TM106
#define ITEM_TM107_ICE_PUNCH ITEM_TM107
#define ITEM_TM108_THUNDER_PUNCH ITEM_TM108
#define ITEM_TM109_FIRE_PUNCH ITEM_TM109
#define ITEM_TM110_SKY_ATTACK ITEM_TM110
#define ITEM_TM111_PSYWAVE ITEM_TM111
#define ITEM_TM112_AURA_SPHERE ITEM_TM112
#define ITEM_TM113_TAILWIND ITEM_TM113
#define ITEM_TM114_GUNK_SHOT ITEM_TM114
#define ITEM_TM115_IRON_HEAD ITEM_TM115
#define ITEM_TM116_ELECTRIC_TERRAIN ITEM_TM116
#define ITEM_TM117_GRASSY_TERRAIN ITEM_TM117
#define ITEM_TM118_PSYCHIC_TERRAIN ITEM_TM118
#define ITEM_TM119_MISTY_TERRAIN ITEM_TM119
#define ITEM_TM120_HEAVY_SLAM ITEM_TM120 // NAO ABANDONADA
#define ITEM_TM121_HYPER_VOICE ITEM_TM121 // VENTA CENTRO COMERCIAL CALAGUA
#define ITEM_TM122_EERIE_IMPULSE ITEM_TM122 // LABORATORIO OAK
#define ITEM_TM123_SOLAR_BLADE ITEM_TM123 // CUEVA RUTA 120
#define ITEM_TM124_THUNDER_FANG ITEM_TM124 // VENTA CENTRO COMERCIAL CALAGUA
#define ITEM_TM125_ICE_FANG ITEM_TM125 // VENTA CENTRO COMERCIAL CALAGUA
#define ITEM_TM126_FIRE_FANG ITEM_TM126 // VENTA CENTRO COMERCIAL CALAGUA
#define ITEM_TM127_ELECTROWEB ITEM_TM127 // VENTA COMERCIO PORTUAL
#define ITEM_TM128_FISSURE ITEM_TM128 // CUEVA DE GROUDON
#define ITEM_TM129_POISON_TAIL ITEM_TM129 // MALVALONA CASINO S2
#define ITEM_TM130_TRI_ATTACK ITEM_TM130 // LABORATORIO OAK, LO TOMAS EN ESCENA PREVIA A APARICIÓN BILL
#define ITEM_TM131_EARTH_POWER ITEM_TM131 // CUEVA REGIGIGAS
#define ITEM_TM132_NASTY_PLOT ITEM_TM132 // CIENTÍFICO S2 SILPH QUE DICE ESTAR MAQUINANDO POKÉMON ULTRAPODEROSOS
#define ITEM_TM133_HEAT_CRASH ITEM_TM133 // NPC LAVACALDA (EN EL BALNEARIO QUIZÁS)
#define ITEM_TM134_CURSE ITEM_TM134 // S3 TORRE POKEMON
#define ITEM_TM135_VACUUM_WAVE ITEM_TM135 // VENTA COMERCIO PORTUAL
#define ITEM_TM136_WEATHER_BALL ITEM_TM136 // CIENTÍFICO EN CENTRO METEOROLÓGICO
#define ITEM_TM137_SUPER_FANG ITEM_TM137 // PREMIO CASINO MALVALONA
#define ITEM_TM138_HIGH_HORSEPOWER ITEM_TM138 // RUTA 39 CRIADOR JOHTO
#define ITEM_TM139_SCORCHING_SANDS ITEM_TM139 // DESIERTO HOENN
#define ITEM_TM140_POLTERGEIST ITEM_TM140 // MONTE PÍRICO CIMA INTERIOR
#define ITEM_TM141_STEEL_BEAM ITEM_TM141 // SECUNDARIA JOHTO FORJA FUEGO
#define ITEM_TM142_TRICK ITEM_TM142 // VENTA CENTRO COMERCIAL CALAGUA
#define ITEM_TM143_LEECH_LIFE ITEM_TM143 // SECUNDARIA KANTO BAYAS
#define ITEM_TM144_ROCK_BLAST ITEM_TM144 // CUEVA GRANITO
#define ITEM_TM145_STORED_POWER ITEM_TM145 // ZONA CAMINO CULTO LAVANDA
#define ITEM_TM146_DRAINING_KISS ITEM_TM146 // VENTA CENTRO COMERCIAL TRIGAL
#define ITEM_TM147_SOFT_BOILED ITEM_TM147 // VENTA CENTRO COMERCIAL TRIGAL
#define ITEM_TM148_DREAM_EATER ITEM_TM148 // CEMENTERIO GIMNASIO
#define ITEM_TM149_ZAP_CANNON ITEM_TM149 // MALVALANOVA
#define ITEM_TM150_BODY_SLAM ITEM_TM150 // VENTA CENTRO COMERCIAL TRIGAL
#define ITEM_TM151_ICICLE_SPEAR ITEM_TM151 // TEMPLO PUNTANEVA
#define ITEM_TM152_MYSTICAL_FIRE ITEM_TM152 // MONTE PÍRICO CIMA EXTERIOR
#define ITEM_TM153_PSYCHO_CUT ITEM_TM153 // NPC EN CIUDAD ALGARIA
#define ITEM_TM154_SHEER_COLD ITEM_TM154 // CUEVA DE KYOGRE
#define ITEM_TM155_VENOSHOCK ITEM_TM155 // NEO FUCSIA ZONA NORTE ABANDONADA
#define ITEM_TM156_GUILLOTINE ITEM_TM156 // PREMIO CASINO MALVALONA
#define ITEM_TM157_PIN_MISSILE ITEM_TM157 // ZONA SAFARI HOENN
#define ITEM_TM158_ACID_SPRAY ITEM_TM158 // PREMIO CASINO MALVALONA
#define ITEM_TM159_FOUL_PLAY ITEM_TM159 // PREMIO CASINO MALVALONA
#define ITEM_TM160_HORN_DRILL ITEM_TM160 // ZONA SAFARI HOENN
#define ITEM_TM161_DRACO_METEOR ITEM_TM161
#define ITEM_TM162_HEAT_WAVE ITEM_TM162 // TORRE RADIO TRIGAL P7
#define ITEM_TM163_GRASSY_GLIDE ITEM_TM163
#define ITEM_TM164_RISING_VOLTAGE ITEM_TM164
#define ITEM_TM165_EXPANDING_FORCE ITEM_TM165
#define ITEM_TM166_AMNESIA ITEM_TM166 // CUEVA HYPNO
#define ITEM_TM167_FLIP_TURN ITEM_TM167 // MARES HOENN BUCEO
#define ITEM_TM168_ICY_WIND ITEM_TM168
#define ITEM_TM169_DUAL_WINGBEAT ITEM_TM169
#define ITEM_TM170_THOUSAND_WAVES ITEM_TM170 // TORRE RADIO TRIGAL P10
#define ITEM_TM171_TELEPORT ITEM_TM171
#define ITEM_TM172_SLEEP_TALK ITEM_TM172
#define ITEM_TM173_POWER_GEM ITEM_TM173
#define ITEM_TM174_REVERSAL ITEM_TM174
#define ITEM_TM175_CLOSE_COMBAT ITEM_TM175
#define ITEM_TM176_PHANTOM_FORCE ITEM_TM176
#define ITEM_TM177_SPIKES ITEM_TM177
#define ITEM_TM178_IRON_DEFENSE ITEM_TM178
#define ITEM_TM179_ENCORE ITEM_TM179 // MUSEO VERDEGAL
#define ITEM_TM180_SEED_BOMB ITEM_TM180
#define ITEM_TM181_PSYCHIC_FANGS ITEM_TM181
#define ITEM_TM182_RAZOR_WIND ITEM_TM182
#define ITEM_TM183_WORK_UP ITEM_TM183
#define ITEM_TM184_NIGHTMARE ITEM_TM184
#define ITEM_TM185_MAGICAL_LEAF ITEM_TM185
#define ITEM_TM186_KNOCK_OFF ITEM_TM186
#define ITEM_TM187_SCALE_SHOT ITEM_TM187
#define ITEM_TM188_METEOR_BEAM ITEM_TM188
#define ITEM_TM189_CHARGE ITEM_TM189
#define ITEM_TM190_LEAF_STORM ITEM_TM190
#define ITEM_TM191_TOXIC_SPIKES ITEM_TM191
#define ITEM_TM192_LOW_KICK ITEM_TM192
#define ITEM_TM193_MEGA_KICK ITEM_TM193
#define ITEM_TM194_SKULL_BASH ITEM_TM194
#define ITEM_TM195_DRAGON_RAGE ITEM_TM195 // FURIA DRAGON - GIMNASIO ENDRINO, HOENN PARTE 2
#define ITEM_TM196_DOUBLE_EDGE ITEM_TM196
#define ITEM_TM197_SUBMISSION ITEM_TM197
#define ITEM_TM198_MUD_SLAP ITEM_TM198 // BOFETÓN LODO - PRADO ISLA INTA
#define ITEM_TM199_AGILITY ITEM_TM199
#define ITEM_TM200_HYDRO_PUMP ITEM_TM200
#define ITEM_TM201_ANCIENT_POWER ITEM_TM201
#define ITEM_TM202_BODY_PRESS ITEM_TM202
#define ITEM_TM203_FUTURE_SIGHT ITEM_TM203
#define ITEM_TM204_COSMIC_POWER ITEM_TM204
#define ITEM_TM205_MAGNET_RISE ITEM_TM205
#define ITEM_TM206_OMINOUS_WIND ITEM_TM206
#define ITEM_TM207_ENDURE ITEM_TM207
#define ITEM_TM208_MACH_PUNCH ITEM_TM208
#define ITEM_TM209_DEFOG ITEM_TM209
#define ITEM_TM210_BOUNCE ITEM_TM210
#define ITEM_TM211_POISON_FANG ITEM_TM211
#define ITEM_TM212_INGRAIN ITEM_TM212
#define ITEM_TM213_ACID_ARMOR ITEM_TM213
#define ITEM_TM214_NEEDLE_ARM ITEM_TM214
#define ITEM_TM215_SKY_UPPERCUT ITEM_TM215
#define ITEM_TM216_AQUA_RING ITEM_TM216
#define ITEM_TM217_BULLET_PUNCH ITEM_TM217
#define ITEM_TM218_BRAVE_BIRD ITEM_TM218
#define ITEM_TM219_ATTACK_ORDER ITEM_TM219
#define ITEM_TM220_DEFEND_ORDER ITEM_TM220
#define ITEM_TM221_COIL ITEM_TM221
#define ITEM_TM222_HORN_LEECH ITEM_TM222
#define ITEM_TM223_COTTON_GUARD ITEM_TM223
#define ITEM_TM224_STICKY_WEB ITEM_TM224
#define ITEM_TM225_ICE_HAMMER ITEM_TM225
#define ITEM_TM226_RAPID_SPIN ITEM_TM226
#define ITEM_TM227_SUPERPOWER ITEM_TM227
#define ITEM_TM228_SILVER_WIND ITEM_TM228
#define ITEM_TM229_LEAF_BLADE ITEM_TM229
#define ITEM_TM230_STORM_THROW ITEM_TM230
#define ITEM_TM231_SHELL_SMASH ITEM_TM231
#define ITEM_TM232_DUAL_CHOP ITEM_TM232
#define ITEM_TM233_MUDDY_WATER ITEM_TM233
#define ITEM_TM234_METEOR_MASH ITEM_TM234
#define ITEM_TM235_CRABHAMMER ITEM_TM235
#define ITEM_TM236_ERUPTION ITEM_TM236
#define ITEM_TM237_WATER_SPOUT ITEM_TM237
#define ITEM_TM238_SIMPLE_BEAM ITEM_TM238
#define ITEM_TM239_POWER_WHIP ITEM_TM239
#define ITEM_TM240_MUD_SHOT ITEM_TM240
#define ITEM_TM241_BLAZE_KICK ITEM_TM241
#define ITEM_TM242_BIDE ITEM_TM242
#define ITEM_TM243_NATURE_POWER ITEM_TM243
#define ITEM_TM244_ELECTRO_BALL ITEM_TM244
#define ITEM_TM245_SHIFT_GEAR ITEM_TM245
#define ITEM_TM246_SACRED_SWORD ITEM_TM246

#define ITEM_HM01_CUT ITEM_HM01
#define ITEM_HM02_FLY ITEM_HM02
#define ITEM_HM03_SURF ITEM_HM03
#define ITEM_HM04_STRENGTH ITEM_HM04
#define ITEM_HM05_FLASH ITEM_HM05
#define ITEM_HM06_ROCK_SMASH ITEM_HM06
#define ITEM_HM07_WATERFALL ITEM_HM07
#define ITEM_HM08_DIVE ITEM_HM08

#define ITEM_OVAL_CHARM 846 // AMULETO SECUNDARIA MARSHADOW
#define ITEM_SHINY_CHARM 847
#define ITEM_CATCHING_CHARM 848
#define ITEM_EXP_CHARM 849

// Form-changing Key Items
#define ITEM_ROTOM_CATALOG 850
#define ITEM_GRACIDEA 851
#define ITEM_REVEAL_GLASS 852
#define ITEM_DNA_SPLICERS 853
#define ITEM_ZYGARDE_CUBE 854
#define ITEM_PRISON_BOTTLE 855
#define ITEM_N_SOLARIZER 856
#define ITEM_N_LUNARIZER 857
#define ITEM_REINS_OF_UNITY 858

// Battle Mechanic Key Items
#define ITEM_KEY_STONE 859
#define ITEM_MEGA_RING 860
#define ITEM_Z_POWER_RING 861
#define ITEM_DYNAMAX_BAND 862

// Misc. Key Items
#define ITEM_BICYCLE 863
#define ITEM_MACH_BIKE 864
#define ITEM_ACRO_BIKE 865
#define ITEM_OLD_ROD 866
#define ITEM_GOOD_ROD 867
#define ITEM_SUPER_ROD 868
#define ITEM_DOWSING_MACHINE 869
#define ITEM_TOWN_MAP 870 // REGALO GIOVANNI ANTES DE ENTRAR A JOHTO 
#define ITEM_VS_SEEKER 871 // REGALO GIOVANNI ANTES DE ENTRAR JOHTO DETECTOR VINCULO
#define ITEM_TM_CASE 872
#define ITEM_BERRY_POUCH 873
#define ITEM_POKEMON_BOX_LINK 874
#define ITEM_COIN_CASE 875
#define ITEM_POWDER_JAR 876
#define ITEM_WAILMER_PAIL 877
#define ITEM_POKE_RADAR 878
#define ITEM_POKEBLOCK_CASE 879
#define ITEM_SOOT_SACK 880
#define ITEM_POKE_FLUTE 881
#define ITEM_FAME_CHECKER 882
#define ITEM_TEACHY_TV 883

// Story Key Items
#define ITEM_SS_TICKET 884 // Ticket fiesta olivo crom
#define ITEM_EON_TICKET 885 // Pase élite torre radio
#define ITEM_MYSTIC_TICKET 886
#define ITEM_AURORA_TICKET 887
#define ITEM_OLD_SEA_MAP 888
#define ITEM_LETTER 889
#define ITEM_DEVON_PARTS 890
#define ITEM_GO_GOGGLES 891
#define ITEM_DEVON_SCOPE 892
#define ITEM_BASEMENT_KEY 893 // llave despacho privado johto
#define ITEM_SCANNER 894 // cruzacorrientes capitan ssaqua
#define ITEM_STORAGE_KEY 895
#define ITEM_KEY_TO_ROOM_1 896
#define ITEM_KEY_TO_ROOM_2 897
#define ITEM_KEY_TO_ROOM_4 898
#define ITEM_METEORITE 899
#define ITEM_MAGMA_EMBLEM 900
#define ITEM_CONTEST_PASS 901 // pase safari de koga
#define ITEM_OAKS_PARCEL 902
#define ITEM_SECRET_KEY 903
#define ITEM_BIKE_VOUCHER 904
#define ITEM_GOLD_TEETH 905
#define ITEM_CARD_KEY 906 // llave magnética de silph
#define ITEM_LIFT_KEY 907 // llave ascensor guarida rocket
#define ITEM_SILPH_SCOPE 908
#define ITEM_TRI_PASS 909 // Licencia entrenador de giovanni
#define ITEM_RAINBOW_PASS 910 // Pase radio Trigal
#define ITEM_TEA 911
#define ITEM_RUBY 912
#define ITEM_SAPPHIRE 913

#define ITEM_WEIRD_COSTUME 914

#define ITEM_PIEDRA_SAGRADA  915
#define ITEM_PIEDRA_LINK  916
#define ITEM_PIEDRA_ROCKET  917
#define ITEM_BLACK_AUGURITE 918
#define ITEM_RED_SCALE 919
#define ITEM_CONDENSADOR_GAS 920

#define ITEM_ABILITY_PATCH 921

#define ITEM_JADE_ORB 922

#define ITEMS_COUNT 923
#define ITEM_FIELD_ARROW ITEMS_COUNT

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId)(((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId)((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF

#define NUM_TECHNICAL_MACHINES 246
#define NUM_HIDDEN_MACHINES 8

#define MAX_BAG_ITEM_CAPACITY  255
#define MAX_PC_ITEM_CAPACITY   30
#define MAX_BERRY_CAPACITY     80

#define BAG_ITEM_CAPACITY_DIGITS 3
#define BERRY_CAPACITY_DIGITS 3
#define MAX_ITEM_DIGITS BERRY_CAPACITY_DIGITS

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL        0
#define ITEM_USE_PARTY_MENU  1
#define ITEM_USE_FIELD       2
#define ITEM_USE_PBLOCK_CASE 3
#define ITEM_USE_BAG_MENU    4 // No exit callback, stays in bag menu

// Item battle usage IDs (only checked to see if nonzero)
#define ITEM_B_USE_MEDICINE 1
#define ITEM_B_USE_OTHER    2

// Check if the item is one that can be used on a Pokemon.
#define ITEM_HAS_EFFECT(item) ((item) >= ITEM_POTION && (item) <= LAST_BERRY_INDEX)

#endif  // GUARD_CONSTANTS_ITEMS_H