#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_TownsAndRoutesHOENN
#define MAP_PETALBURG_CITY      (0 | (0 << 8))
#define MAP_SLATEPORT_CITY      (1 | (0 << 8))
#define MAP_MAUVILLE_CITY       (2 | (0 << 8))
#define MAP_RUSTBORO_CITY       (3 | (0 << 8))
#define MAP_FORTREE_CITY        (4 | (0 << 8))
#define MAP_LILYCOVE_CITY       (5 | (0 << 8))
#define MAP_MOSSDEEP_CITY       (6 | (0 << 8))
#define MAP_SOOTOPOLIS_CITY     (7 | (0 << 8))
#define MAP_EVER_GRANDE_CITY    (8 | (0 << 8))
#define MAP_LITTLEROOT_TOWN     (9 | (0 << 8))
#define MAP_OLDALE_TOWN         (10 | (0 << 8))
#define MAP_DEWFORD_TOWN        (11 | (0 << 8))
#define MAP_LAVARIDGE_TOWN      (12 | (0 << 8))
#define MAP_FALLARBOR_TOWN      (13 | (0 << 8))
#define MAP_VERDANTURF_TOWN     (14 | (0 << 8))
#define MAP_PACIFIDLOG_TOWN     (15 | (0 << 8))
#define MAP_ROUTE101            (16 | (0 << 8))
#define MAP_ROUTE102            (17 | (0 << 8))
#define MAP_ROUTE103            (18 | (0 << 8))
#define MAP_ROUTE104            (19 | (0 << 8))
#define MAP_ROUTE105            (20 | (0 << 8))
#define MAP_ROUTE106            (21 | (0 << 8))
#define MAP_ROUTE107            (22 | (0 << 8))
#define MAP_ROUTE108            (23 | (0 << 8))
#define MAP_ROUTE109            (24 | (0 << 8))
#define MAP_ROUTE110            (25 | (0 << 8))
#define MAP_ROUTE111            (26 | (0 << 8))
#define MAP_ROUTE112            (27 | (0 << 8))
#define MAP_ROUTE113            (28 | (0 << 8))
#define MAP_ROUTE114            (29 | (0 << 8))
#define MAP_ROUTE115            (30 | (0 << 8))
#define MAP_ROUTE116            (31 | (0 << 8))
#define MAP_ROUTE117            (32 | (0 << 8))
#define MAP_ROUTE118            (33 | (0 << 8))
#define MAP_ROUTE119            (34 | (0 << 8))
#define MAP_ROUTE120            (35 | (0 << 8))
#define MAP_ROUTE121            (36 | (0 << 8))
#define MAP_ROUTE122            (37 | (0 << 8))
#define MAP_ROUTE123            (38 | (0 << 8))
#define MAP_ROUTE124            (39 | (0 << 8))
#define MAP_ROUTE125            (40 | (0 << 8))
#define MAP_ROUTE126            (41 | (0 << 8))
#define MAP_ROUTE127            (42 | (0 << 8))
#define MAP_ROUTE128            (43 | (0 << 8))
#define MAP_ROUTE129            (44 | (0 << 8))
#define MAP_ROUTE130            (45 | (0 << 8))
#define MAP_ROUTE131            (46 | (0 << 8))
#define MAP_ROUTE132            (47 | (0 << 8))
#define MAP_ROUTE133            (48 | (0 << 8))
#define MAP_ROUTE134            (49 | (0 << 8))
#define MAP_UNDERWATER_ROUTE124 (50 | (0 << 8))
#define MAP_UNDERWATER_ROUTE126 (51 | (0 << 8))
#define MAP_UNDERWATER_ROUTE127 (52 | (0 << 8))
#define MAP_UNDERWATER_ROUTE128 (53 | (0 << 8))
#define MAP_UNDERWATER_ROUTE129 (54 | (0 << 8))
#define MAP_UNDERWATER_ROUTE105 (55 | (0 << 8))
#define MAP_UNDERWATER_ROUTE125 (56 | (0 << 8))

// gMapGroup_TownsAndRoutesKANTO
#define MAP_PALLET_TOWN     (0 | (1 << 8))
#define MAP_VIRIDIAN_CITY   (1 | (1 << 8))
#define MAP_PEWTER_CITY     (2 | (1 << 8))
#define MAP_CERULEAN_CITY   (3 | (1 << 8))
#define MAP_LAVENDER_TOWN   (4 | (1 << 8))
#define MAP_VERMILION_CITY  (5 | (1 << 8))
#define MAP_CELADON_CITY    (6 | (1 << 8))
#define MAP_FUCHSIA_CITY    (7 | (1 << 8))
#define MAP_CINNABAR_ISLAND (8 | (1 << 8))
#define MAP_INDIGO_PLATEAU  (9 | (1 << 8))
#define MAP_SAFFRON_CITY    (10 | (1 << 8))
#define MAP_ROUTE4          (11 | (1 << 8))
#define MAP_ROUTE10         (12 | (1 << 8))
#define MAP_ROUTE1          (13 | (1 << 8))
#define MAP_ROUTE2          (14 | (1 << 8))
#define MAP_NEW_MAP1        (15 | (1 << 8))
#define MAP_ROUTE5          (16 | (1 << 8))
#define MAP_ROUTE6          (17 | (1 << 8))
#define MAP_ROUTE7          (18 | (1 << 8))
#define MAP_ROUTE8          (19 | (1 << 8))
#define MAP_ROUTE9          (20 | (1 << 8))
#define MAP_ROUTE11         (21 | (1 << 8))
#define MAP_ROUTE12         (22 | (1 << 8))
#define MAP_ROUTE13         (23 | (1 << 8))
#define MAP_ROUTE14         (24 | (1 << 8))
#define MAP_ROUTE15         (25 | (1 << 8))
#define MAP_ROUTE16         (26 | (1 << 8))
#define MAP_ROUTE17         (27 | (1 << 8))
#define MAP_ROUTE18         (28 | (1 << 8))
#define MAP_ROUTE19         (29 | (1 << 8))
#define MAP_ROUTE20         (30 | (1 << 8))
#define MAP_ROUTE21         (31 | (1 << 8))
#define MAP_ROUTE22         (32 | (1 << 8))
#define MAP_ROUTE23         (33 | (1 << 8))
#define MAP_ROUTE24         (34 | (1 << 8))
#define MAP_ROUTE25         (35 | (1 << 8))

// gMapGroup_TownsAndRoutesSEVII
#define MAP_ONE_ISLAND        (0 | (2 << 8))
#define MAP_TWO_ISLAND        (1 | (2 << 8))
#define MAP_THREE_ISLAND      (2 | (2 << 8))
#define MAP_FOUR_ISLAND       (3 | (2 << 8))
#define MAP_FIVE_ISLAND       (4 | (2 << 8))
#define MAP_SIX_ISLAND        (5 | (2 << 8))
#define MAP_SEVEN_ISLAND      (6 | (2 << 8))
#define MAP_NAVEL_ROCK        (7 | (2 << 8))
#define MAP_BIRTH_ISLAND      (8 | (2 << 8))
#define MAP_KINDLE_ROAD       (9 | (2 << 8))
#define MAP_CAPE_BRINK        (10 | (2 << 8))
#define MAP_SOUTH_TWO_ISLAND  (11 | (2 << 8))
#define MAP_NAVEL_ROAD        (12 | (2 << 8))
#define MAP_THREE_ISLE_PORT   (13 | (2 << 8))
#define MAP_BOND_BRIDGE       (14 | (2 << 8))
#define MAP_WATER_LABYRINTH   (15 | (2 << 8))
#define MAP_RESORT_GORGEOUS   (16 | (2 << 8))
#define MAP_FILE_ISLE_MEADOW  (17 | (2 << 8))
#define MAP_MEMORIAL_PILLAR   (18 | (2 << 8))
#define MAP_WATER_PATH        (19 | (2 << 8))
#define MAP_GREEN_PATH        (20 | (2 << 8))
#define MAP_OUTCAST_ISLAND    (21 | (2 << 8))
#define MAP_RUIN_VALLEY       (22 | (2 << 8))
#define MAP_TRAINER_TOWER     (23 | (2 << 8))
#define MAP_CANYON_ENTRANCE   (24 | (2 << 8))
#define MAP_SEVAULT_CANYON    (25 | (2 << 8))
#define MAP_TANOBY_RUINS      (26 | (2 << 8))
#define MAP_WEST_BIRTH_ISLAND (27 | (2 << 8))

// gMapGroup_TownsAndRoutesJOHTO
#define MAP_NEW_BARK_TOWN    (0 | (3 << 8))
#define MAP_CHERRYGROVE_CITY (1 | (3 << 8))
#define MAP_VIOLET_CITY      (2 | (3 << 8))
#define MAP_GOLDENROD_CITY   (3 | (3 << 8))
#define MAP_ECRUTEAK_CITY    (4 | (3 << 8))
#define MAP_OLIVINE_CITY     (5 | (3 << 8))
#define MAP_CIANWOOD_CITY    (6 | (3 << 8))
#define MAP_MAHOGANY_TOWN    (7 | (3 << 8))
#define MAP_BLACKTHORN_CITY  (8 | (3 << 8))
#define MAP_MT_SILVER        (9 | (3 << 8))
#define MAP_SOUTH_ROUTE45    (10 | (3 << 8))
#define MAP_ROUTE26          (11 | (3 << 8))
#define MAP_ROUTE27          (12 | (3 << 8))
#define MAP_ROUTE28          (13 | (3 << 8))
#define MAP_ROUTE29          (14 | (3 << 8))
#define MAP_ROUTE30          (15 | (3 << 8))
#define MAP_ROUTE31          (16 | (3 << 8))
#define MAP_ROUTE32          (17 | (3 << 8))
#define MAP_ROUTE33          (18 | (3 << 8))
#define MAP_ROUTE34          (19 | (3 << 8))
#define MAP_ROUTE35          (20 | (3 << 8))
#define MAP_ROUTE36          (21 | (3 << 8))
#define MAP_ROUTE37          (22 | (3 << 8))
#define MAP_ROUTE38          (23 | (3 << 8))
#define MAP_ROUTE39          (24 | (3 << 8))
#define MAP_ROUTE40          (25 | (3 << 8))
#define MAP_ROUTE41          (26 | (3 << 8))
#define MAP_ROUTE42          (27 | (3 << 8))
#define MAP_ROUTE43          (28 | (3 << 8))
#define MAP_ROUTE44          (29 | (3 << 8))
#define MAP_ROUTE46          (30 | (3 << 8))
#define MAP_ROUTE47          (31 | (3 << 8))
#define MAP_ROUTE48          (32 | (3 << 8))
#define MAP_ROUTE49          (33 | (3 << 8))
#define MAP_ROUTE50          (34 | (3 << 8))
#define MAP_ROUTE51          (35 | (3 << 8))
#define MAP_ROUTE52          (36 | (3 << 8))
#define MAP_ROUTE53          (37 | (3 << 8))

// gMapGroup_IndoorCherryNewbark
#define MAP_NEWBARK_ELM_LABORATORY (0 | (4 << 8))
#define MAP_CHERRY_PKMN_CENTER     (1 | (4 << 8))
#define MAP_CHERRY_SHOP            (2 | (4 << 8))
#define MAP_CHERRY_HOUSE1          (3 | (4 << 8))
#define MAP_CHERRY_HOUSE2          (4 | (4 << 8))
#define MAP_CHERRY_HOUSE3          (5 | (4 << 8))

// gMapGroup_IndoorVioletCity
#define MAP_VIOLET_PKMN_CENTER     (0 | (5 << 8))
#define MAP_VIOLET_SHOP            (1 | (5 << 8))
#define MAP_VIOLET_GYM             (2 | (5 << 8))
#define MAP_VIOLET_HOUSE1          (3 | (5 << 8))
#define MAP_VIOLET_HOUSE2          (4 | (5 << 8))
#define MAP_VIOLET_TRAINER_SCHOOL  (5 | (5 << 8))
#define MAP_VIOLET_SPROT_TOWER     (6 | (5 << 8))
#define MAP_VIOLET_SPROUT_TOWER_P1 (7 | (5 << 8))
#define MAP_VIOLET_SPROUT_TOWER_P2 (8 | (5 << 8))

// gMapGroup_IndoorAzaleaTown
#define MAP_AZALEA_PKMN_CENTER      (0 | (6 << 8))
#define MAP_AZALEA_SHOP             (1 | (6 << 8))
#define MAP_AZALEA_HOUSE1           (2 | (6 << 8))
#define MAP_AZALEA_CESAR_HOUSE      (3 | (6 << 8))
#define MAP_AZALEA_GYM              (4 | (6 << 8))
#define MAP_AZALEA_SLOWPOKE_WELL    (5 | (6 << 8))
#define MAP_AZALEA_SLOWPOKE_WELL_S1 (6 | (6 << 8))

// gMapGroup_IndoorGoldenrodCity
#define MAP_GOLDENROD_PKMN_CENTER       (0 | (7 << 8))
#define MAP_GOLDENROD_SHOP_CENTER       (1 | (7 << 8))
#define MAP_GOLDENROD_SHOP_CENTER_P1    (2 | (7 << 8))
#define MAP_GOLDENROD_SHOP_CENTER_P2    (3 | (7 << 8))
#define MAP_GOLDENROD_SHOP_CENTER_P3    (4 | (7 << 8))
#define MAP_GOLDENROD_SHOP_CENTER_P4    (5 | (7 << 8))
#define MAP_GOLDENROD_SHOP_CENTER_P5    (6 | (7 << 8))
#define MAP_GOLDENROD_RADIO_TOWER       (7 | (7 << 8))
#define MAP_GOLDENROD_RADIO_TOWER_P1    (8 | (7 << 8))
#define MAP_GOLDENROD_RADIO_TOWER_P2    (9 | (7 << 8))
#define MAP_GOLDENROD_RADIO_TOWER_P3    (10 | (7 << 8))
#define MAP_GOLDENROD_RADIO_TOWER_P4    (11 | (7 << 8))
#define MAP_GOLDENROD_RADIO_TOWER_P5    (12 | (7 << 8))
#define MAP_GOLDENROD_GAME_CORNER       (13 | (7 << 8))
#define MAP_GOLDENROD_TRAIN_STATION     (14 | (7 << 8))
#define MAP_GOLDENROD_BIKE_SHOP         (15 | (7 << 8))
#define MAP_GOLDENROD_UNDERGROUND_NORTH (16 | (7 << 8))
#define MAP_GOLDENROD_UNDERGROUND_SOUTH (17 | (7 << 8))
#define MAP_GOLDENROD_UNDERGROUND       (18 | (7 << 8))
#define MAP_GOLDENROD_HOUSES            (19 | (7 << 8))

// gMapGroup_IndoorEcruteakCity
#define MAP_ECRUTEAK_PKMN_CENTER               (0 | (8 << 8))
#define MAP_ECRUTEAK_SHOP                      (1 | (8 << 8))
#define MAP_ECRUTEAK_BURNED_TOWER              (2 | (8 << 8))
#define MAP_ECRUTEAK_BURNED_TOWER_S1           (3 | (8 << 8))
#define MAP_ECRUTEAK_GYM                       (4 | (8 << 8))
#define MAP_ECRUTEAK_DANCE_THEATER             (5 | (8 << 8))
#define MAP_ECRUTEAK_HOUSE1                    (6 | (8 << 8))
#define MAP_ECRUTEAK_HOUSE2                    (7 | (8 << 8))
#define MAP_ECRUTEAK_BELLCHIME_TRAIL_ENTRANCE  (8 | (8 << 8))
#define MAP_ECRUTEAK_BELLCHIME_TRAIL_ENTRANCE2 (9 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER                 (10 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER_P1              (11 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER_P2              (12 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER_P3              (13 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER_P4              (14 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER_P5              (15 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER_P6              (16 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER_P7              (17 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER_P8              (18 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER_P9              (19 | (8 << 8))
#define MAP_ECRUTEAK_TIN_TOWER_ROOF            (20 | (8 << 8))

// gMapGroup_IndoorOlivineCity
#define MAP_OLIVINE_PKMN_CENTER  (0 | (9 << 8))
#define MAP_OLIVINE_SHOP         (1 | (9 << 8))
#define MAP_OLIVINE_GYM          (2 | (9 << 8))
#define MAP_OLIVINE_PUB          (3 | (9 << 8))
#define MAP_OLIVINE_NORMAN_HOUSE (4 | (9 << 8))
#define MAP_OLIVINE_LIGHTHOUSE   (5 | (9 << 8))
#define MAP_OLIVINE_HOUSE1       (6 | (9 << 8))
#define MAP_OLIVINE_HOUSE2       (7 | (9 << 8))
#define MAP_OLIVINE_HOUSE3       (8 | (9 << 8))
#define MAP_OLIVINE_PORT         (9 | (9 << 8))
#define MAP_OLIVINE_BOAT         (10 | (9 << 8))
#define MAP_OLIVINE_BOAT2        (11 | (9 << 8))
#define MAP_OLIVINE_BOAT3        (12 | (9 << 8))
#define MAP_OLIVINE_BOAT4        (13 | (9 << 8))

// gMapGroup_IndoorCianwoodCity
#define MAP_CIANWOOD_PKMN_CENTER (0 | (10 << 8))
#define MAP_CIANWOOD_PHARMACY    (1 | (10 << 8))
#define MAP_CIANWOOD_GYM         (2 | (10 << 8))
#define MAP_CIANWOOD_HOUSE1      (3 | (10 << 8))
#define MAP_CIANWOOD_HOUSE2      (4 | (10 << 8))
#define MAP_CIANWOOD_HOUSE3      (5 | (10 << 8))

// gMapGroup_IndoorMahoganyTown
#define MAP_MAHOGANY_TOWN_PKMN_CENTER   (0 | (11 << 8))
#define MAP_MAHOGANY_TOWN_GYM           (1 | (11 << 8))
#define MAP_MAHOGANY_TOWN_NINJA_BASE    (2 | (11 << 8))
#define MAP_MAHOGANY_TOWN_NINJA_BASE_S1 (3 | (11 << 8))
#define MAP_MAHOGANY_TOWN_NINJA_BASE_S2 (4 | (11 << 8))
#define MAP_MAHOGANY_TOWN_NINJA_BASE_S3 (5 | (11 << 8))

// gMapGroup_IndoorBlackthornCity
#define MAP_BLACKTHORN_CITY_PKMN_CENTER      (0 | (12 << 8))
#define MAP_BLACKTHORN_CITY_SHOP             (1 | (12 << 8))
#define MAP_BLACKTHORN_CITY_HOUSE1           (2 | (12 << 8))
#define MAP_BLACKTHORN_CITY_HOUSE2           (3 | (12 << 8))
#define MAP_BLACKTHORN_CITY_HOUSE3           (4 | (12 << 8))
#define MAP_BLACKTHORN_CITY_DRAGONSDEN       (5 | (12 << 8))
#define MAP_BLACKTHORN_CITY_DRAGONSDEN_S1    (6 | (12 << 8))
#define MAP_BLACKTHORN_CITY_DRAGONSDEN_HOUSE (7 | (12 << 8))
#define MAP_BLACKTHORN_CITY_DRAGONSDEN_S2    (8 | (12 << 8))
#define MAP_BLACKTHORN_CITY_DRAGONSDEN_S3    (9 | (12 << 8))
#define MAP_BLACKTHORN_CITY_DRAGONSDEN_S4    (10 | (12 << 8))

// gMapGroup_IndoorJOHTO
#define MAP_MT_SILVER1                     (0 | (13 << 8))
#define MAP_MT_SILVER2                     (1 | (13 << 8))
#define MAP_MT_SILVER3                     (2 | (13 << 8))
#define MAP_MT_SILVER_PKMN_CENTER          (3 | (13 << 8))
#define MAP_MT_SILVER_HOUSE                (4 | (13 << 8))
#define MAP_INDIGO_JOHTO                   (5 | (13 << 8))
#define MAP_ROUTE26_HOUSE                  (6 | (13 << 8))
#define MAP_ROUTE26_HOUSE2                 (7 | (13 << 8))
#define MAP_ROUTE27_HOUSE                  (8 | (13 << 8))
#define MAP_TOHJO_FALLS                    (9 | (13 << 8))
#define MAP_PASS_ROUTE29                   (10 | (13 << 8))
#define MAP_DARK_CAVE                      (11 | (13 << 8))
#define MAP_ROCKET_HIDEOUT_JOHTO           (12 | (13 << 8))
#define MAP_ROCKET_HIDEOUT_JOHTO_P1        (13 | (13 << 8))
#define MAP_ROCKET_HIDEOUT_JOHTO_P2        (14 | (13 << 8))
#define MAP_PASS_VIOLET_CITY               (15 | (13 << 8))
#define MAP_PASS_RUINS_OF_ALPH_EAST        (16 | (13 << 8))
#define MAP_PASS_RUINS_OF_ALPH_NORTH       (17 | (13 << 8))
#define MAP_RUINS_OF_ALPH                  (18 | (13 << 8))
#define MAP_RUINS_OF_ALPH_HOUSE            (19 | (13 << 8))
#define MAP_RUINS_OF_ALPH_CAVE1            (20 | (13 << 8))
#define MAP_RUINS_OF_ALPH_CAVE2            (21 | (13 << 8))
#define MAP_RUINS_OF_ALPH_CAVE3            (22 | (13 << 8))
#define MAP_RUINS_OF_ALPH_CAVE4            (23 | (13 << 8))
#define MAP_RUINS_OF_ALPH_CAVE5            (24 | (13 << 8))
#define MAP_RUINS_OF_ALPH_S1               (25 | (13 << 8))
#define MAP_RUINS_OF_ALPH_UNDERGROUND_PASS (26 | (13 << 8))
#define MAP_RUINS_OF_ALPH_S2               (27 | (13 << 8))
#define MAP_RUINS_OF_ALPH_S3               (28 | (13 << 8))
#define MAP_RUINS_OF_ALPH_S4               (29 | (13 << 8))
#define MAP_RUINS_OF_ALPH_S5               (30 | (13 << 8))
#define MAP_UNION_CAVE                     (31 | (13 << 8))
#define MAP_UNION_CAVE_S1                  (32 | (13 << 8))
#define MAP_UNION_CAVE_S2                  (33 | (13 << 8))
#define MAP_PASS_ILEX_FOREST               (34 | (13 << 8))
#define MAP_ILEX_FOREST                    (35 | (13 << 8))
#define MAP_PASS_ROUTE34                   (36 | (13 << 8))
#define MAP_PASS_ROUTE35                   (37 | (13 << 8))
#define MAP_ROUTE35_HOUSE                  (38 | (13 << 8))
#define MAP_PASS_NATIONAL_PARK             (39 | (13 << 8))
#define MAP_NATIONAL_PARK                  (40 | (13 << 8))
#define MAP_PASS_ROUTE36                   (41 | (13 << 8))
#define MAP_PASS_ROUTE38                   (42 | (13 << 8))
#define MAP_PASS_ROUTE42                   (43 | (13 << 8))
#define MAP_MOO_FARM                       (44 | (13 << 8))
#define MAP_WHIRL_ISLANDS                  (45 | (13 << 8))
#define MAP_WHIRL_ISLANDS2                 (46 | (13 << 8))
#define MAP_WHIRL_ISLANDS3                 (47 | (13 << 8))
#define MAP_MT_MORTAR                      (48 | (13 << 8))
#define MAP_MT_MORTAR2                     (49 | (13 << 8))
#define MAP_MT_MORTAR3                     (50 | (13 << 8))
#define MAP_MT_MORTAR4                     (51 | (13 << 8))
#define MAP_PASS_ROUTE43                   (52 | (13 << 8))
#define MAP_LAKEOF_RAGE                    (53 | (13 << 8))
#define MAP_LAKEOF_RAGE_HOUSE1             (54 | (13 << 8))
#define MAP_LAKEOF_RAGE_HOUSE2             (55 | (13 << 8))
#define MAP_ICE_PATH                       (56 | (13 << 8))
#define MAP_ICE_PATH2                      (57 | (13 << 8))
#define MAP_ICE_PATH3                      (58 | (13 << 8))
#define MAP_ICE_PATH4                      (59 | (13 << 8))
#define MAP_ICE_PATH5                      (60 | (13 << 8))
#define MAP_ROUTE51_HOUSE                  (61 | (13 << 8))
#define MAP_ROUTE52_MAZE                   (62 | (13 << 8))
#define MAP_ROUTE52_MAZE_P1                (63 | (13 << 8))
#define MAP_PASS_ROUTE47                   (64 | (13 << 8))
#define MAP_ROUTE49_MAZE                   (65 | (13 << 8))
#define MAP_ROUTE49_MAZE_P1                (66 | (13 << 8))
#define MAP_ROUTE49_MAZE_P2                (67 | (13 << 8))
#define MAP_ROUTE49_MAZE_P3                (68 | (13 << 8))
#define MAP_ROUTE49_MAZE_P4                (69 | (13 << 8))

// gMapGroup_IndoorPalletTown
#define MAP_PALLET_TOWN_RED_HOUSE_1F  (0 | (14 << 8))
#define MAP_PALLET_TOWN_RED_HOUSE_2F  (1 | (14 << 8))
#define MAP_PALLET_TOWN_BLUE_HOUSE_1F (2 | (14 << 8))
#define MAP_PALLET_TOWN_PROFESSOR_LAB (3 | (14 << 8))

// gMapGroup_IndoorViridianCity
#define MAP_VIRIDIAN_CITY_HOUSE1            (0 | (15 << 8))
#define MAP_VIRIDIAN_CITY_GYM               (1 | (15 << 8))
#define MAP_VIRIDIAN_CITY_SCHOOL            (2 | (15 << 8))
#define MAP_VIRIDIAN_CITY_MART              (3 | (15 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F (4 | (15 << 8))

// gMapGroup_IndoorPewterCity
#define MAP_PEWTER_CITY_MUSEUM_1F (0 | (16 << 8))
#define MAP_PEWTER_CITY_MUSEM_2F  (1 | (16 << 8))
#define MAP_PEWTER_CITY_GYM       (2 | (16 << 8))
#define MAP_PEWTER_CITY_MART      (3 | (16 << 8))
#define MAP_PEWTER_CITY_HOUSE1    (4 | (16 << 8))
#define MAP_NEW_MAP2              (5 | (16 << 8))
#define MAP_PEWTER_CITY_SCHOOL    (6 | (16 << 8))
#define MAP_PEWTER_CITY_HOUSE2    (7 | (16 << 8))

// gMapGroup_IndoorCeruleanCity
#define MAP_CERULEAN_CITY_HOUSE1            (0 | (17 << 8))
#define MAP_CERULEAN_CITY_HOUSE2            (1 | (17 << 8))
#define MAP_CERULEAN_CITY_HOUSE3            (2 | (17 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_1F (3 | (17 << 8))
#define MAP_CERULEAN_CITY_SCHOOL            (4 | (17 << 8))
#define MAP_CERULEAN_CITY_GYM               (5 | (17 << 8))
#define MAP_CERULEAN_CITY_BIKE_SHOP         (6 | (17 << 8))
#define MAP_CERULEAN_CITY_MART              (7 | (17 << 8))
#define MAP_CERULEAN_CITY_HOUSE4            (8 | (17 << 8))
#define MAP_CERULEAN_CITY_HOUSE5            (9 | (17 << 8))

// gMapGroup_IndoorVermilionCity
#define MAP_VERMILION_CITY_HOUSE1            (0 | (18 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_1F (1 | (18 << 8))
#define MAP_VERMILION_CITY_SCHOOL            (2 | (18 << 8))
#define MAP_VERMILION_CITY_CLUB              (3 | (18 << 8))
#define MAP_VERMILION_CITY_HOUSE2            (4 | (18 << 8))
#define MAP_VERMILION_CITY_MART              (5 | (18 << 8))
#define MAP_VERMILION_CITY_GYM               (6 | (18 << 8))
#define MAP_VERMILION_CITY_HOUSE3            (7 | (18 << 8))

// gMapGroup_IndoorLavenderTown
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_1F (0 | (19 << 8))
#define MAP_LAVENDER_TOWN_SCHOOL            (1 | (19 << 8))
#define MAP_LAVENDER_TOWN_FUJI_HOUSE        (2 | (19 << 8))
#define MAP_LAVENDER_TOWN_HOUSE1            (3 | (19 << 8))
#define MAP_LAVENDER_TOWN_HOUSE2            (4 | (19 << 8))
#define MAP_LAVENDER_TOWN_MART              (5 | (19 << 8))
#define MAP_LAVENDER_RADIO                  (6 | (19 << 8))
#define MAP_LAVENDER_RADIO_P1               (7 | (19 << 8))
#define MAP_LAVENDER_RADIO_P2               (8 | (19 << 8))
#define MAP_LAVENDER_RADIO_P3               (9 | (19 << 8))
#define MAP_LAVENDER_RADIO_P4               (10 | (19 << 8))

// gMapGroup_IndoorCeladonCity
#define MAP_CELADON_CITY_SHOP_1F           (0 | (20 << 8))
#define MAP_CELADON_CITY_SHOP_2F           (1 | (20 << 8))
#define MAP_CELADON_CITY_SHOP_3F           (2 | (20 << 8))
#define MAP_CELADON_CITY_SHOP_4F           (3 | (20 << 8))
#define MAP_CELADON_CITY_SHOP_5F           (4 | (20 << 8))
#define MAP_CELADON_CITY_SHOP_6F           (5 | (20 << 8))
#define MAP_CELADON_CITY_SHOP_ELEVATOR     (6 | (20 << 8))
#define MAP_CELADON_CITY_HOUSE1_1F         (7 | (20 << 8))
#define MAP_CELADON_CITY_HOUSE1_2F         (8 | (20 << 8))
#define MAP_CELADON_CITY_HOUSE1_3F         (9 | (20 << 8))
#define MAP_CELADON_CITY_HOUSE1_4F         (10 | (20 << 8))
#define MAP_CELADON_CITY_SCHOOL            (11 | (20 << 8))
#define MAP_CELADON_CITY_POKEMON_CENTER_1F (12 | (20 << 8))
#define MAP_CELADON_CITY_SCHOOL2           (13 | (20 << 8))
#define MAP_CELADON_CITY_CASINO            (14 | (20 << 8))
#define MAP_CELADON_CITY_CASINO2           (15 | (20 << 8))
#define MAP_CELADON_CITY_GYM               (16 | (20 << 8))
#define MAP_CELADON_CITY_RESTAURANT        (17 | (20 << 8))
#define MAP_CELADON_CITY_HOUSE2            (18 | (20 << 8))
#define MAP_CELADON_CITY_HOTEL             (19 | (20 << 8))

// gMapGroup_IndoorSaffronCity
#define MAP_SAFFRON_CITY_HOUSE1_1F         (0 | (21 << 8))
#define MAP_SAFFRON_CITY_HOUSE1_2F         (1 | (21 << 8))
#define MAP_SAFFRON_CITY_DOJO              (2 | (21 << 8))
#define MAP_SAFFRON_CITY_GYM               (3 | (21 << 8))
#define MAP_SAFFRON_CITY_HOUSE2            (4 | (21 << 8))
#define MAP_SAFFRON_CITY_MART              (5 | (21 << 8))
#define MAP_SAFFRON_CITY_POKEMON_CENTER_1F (6 | (21 << 8))
#define MAP_SAFFRON_CITY_SCHOOL            (7 | (21 << 8))
#define MAP_SAFFRON_CITY_HOUSE3            (8 | (21 << 8))
#define MAP_SAFFRON_CITY_HOUSE4            (9 | (21 << 8))

// gMapGroup_IndoorFuchsiaCity
#define MAP_FUCHSIA_CITY_PATH              (0 | (22 << 8))
#define MAP_FUCHSIA_CITY_MART              (1 | (22 << 8))
#define MAP_FUCHSIA_CITY_HOUSE1            (2 | (22 << 8))
#define MAP_FUCHSIA_CITY_GYM               (3 | (22 << 8))
#define MAP_FUCHSIA_CITY_HOUSE2            (4 | (22 << 8))
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_1F (5 | (22 << 8))
#define MAP_FUCHSIA_CITY_SCHOOL            (6 | (22 << 8))
#define MAP_FUCHSIA_CITY_HOUSE3            (7 | (22 << 8))
#define MAP_FUCHSIA_CITY_HOUSE4            (8 | (22 << 8))
#define MAP_FUCHSIA_CITY_HOUSE5            (9 | (22 << 8))

// gMapGroup_IndoorCinnabarIsland
#define MAP_CINNABAR_ISLAND_GYM               (0 | (23 << 8))
#define MAP_CINNABAR_ISLAND_LABORATORY1       (1 | (23 << 8))
#define MAP_CINNABAR_ISLAND_HOUSE1            (2 | (23 << 8))
#define MAP_CINNABAR_ISLAND_LABORATORY2       (3 | (23 << 8))
#define MAP_CINNABAR_ISLAND_LABORATORY3       (4 | (23 << 8))
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F (5 | (23 << 8))
#define MAP_CINNABAR_ISLAND_SCHOOL            (6 | (23 << 8))
#define MAP_CINNABAR_ISLAND_MART              (7 | (23 << 8))

// gMapGroup_IndoorIndigoPlateau
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F (0 | (24 << 8))
#define MAP_INDIGO_PLATEAU_SCHOOL            (1 | (24 << 8))

// gMapGroup_IndoorKANTO1
#define MAP_ROUTE2_PATH               (0 | (25 << 8))
#define MAP_ROUTE2_HOUSE1             (1 | (25 << 8))
#define MAP_ROUTE2_PATH2              (2 | (25 << 8))
#define MAP_ROUTE2_PATH3              (3 | (25 << 8))
#define MAP_ROUTE4_POKEMON_CENTER_1F  (4 | (25 << 8))
#define MAP_ROUTE5_HOUSE1             (5 | (25 << 8))
#define MAP_ROUTE5_PATH               (6 | (25 << 8))
#define MAP_ROUTE6_PATH               (7 | (25 << 8))
#define MAP_ROUTE7_PATH               (8 | (25 << 8))
#define MAP_ROUTE8_PATH               (9 | (25 << 8))
#define MAP_ROUTE10_POKEMON_CENTER_1F (10 | (25 << 8))
#define MAP_ROUTE11_PATH_1F           (11 | (25 << 8))
#define MAP_ROUTE11_PATH_2F           (12 | (25 << 8))
#define MAP_ROUTE12_PATH_1F           (13 | (25 << 8))
#define MAP_ROUTE12_PATH_2F           (14 | (25 << 8))
#define MAP_ROUTE12_HOUSE1            (15 | (25 << 8))
#define MAP_ROUTE15_PATH_1F           (16 | (25 << 8))
#define MAP_ROUTE15_PATH_2F           (17 | (25 << 8))
#define MAP_ROUTE16_HOUSE1            (18 | (25 << 8))
#define MAP_ROUTE16_PATH_1F           (19 | (25 << 8))
#define MAP_ROUTE16_PATH_2F           (20 | (25 << 8))
#define MAP_ROUTE18_PATH_1F           (21 | (25 << 8))
#define MAP_ROUTE18_PATH_2F           (22 | (25 << 8))
#define MAP_ROUTE19_HOUSE1            (23 | (25 << 8))
#define MAP_ROUTE22_PATH              (24 | (25 << 8))
#define MAP_ROUTE23_HOUSE1            (25 | (25 << 8))
#define MAP_ROUTE25_BILL_HOUSE        (26 | (25 << 8))
#define MAP_VIRIDIAN_FOREST           (27 | (25 << 8))
#define MAP_MT_MOON_1F                (28 | (25 << 8))
#define MAP_MT_MOON_2F                (29 | (25 << 8))
#define MAP_MT_MOON_3F                (30 | (25 << 8))
#define MAP_SS_ANNE_1F                (31 | (25 << 8))
#define MAP_SS_ANNE_2F                (32 | (25 << 8))
#define MAP_SS_ANNE_3F                (33 | (25 << 8))
#define MAP_SS_ANNE_4F                (34 | (25 << 8))
#define MAP_SS_ANNE_5F                (35 | (25 << 8))
#define MAP_SS_ANNE_6F                (36 | (25 << 8))
#define MAP_SS_ANNE_7F                (37 | (25 << 8))
#define MAP_SS_ANNE_8F                (38 | (25 << 8))
#define MAP_SS_ANNE_9F                (39 | (25 << 8))
#define MAP_SS_ANNE_10F               (40 | (25 << 8))
#define MAP_SS_ANNE_11F               (41 | (25 << 8))
#define MAP_SS_ANNE_12F               (42 | (25 << 8))
#define MAP_SS_ANNE_13F               (43 | (25 << 8))
#define MAP_SS_ANNE_14F               (44 | (25 << 8))
#define MAP_SS_ANNE_15F               (45 | (25 << 8))
#define MAP_SS_ANNE_16F               (46 | (25 << 8))
#define MAP_SS_ANNE_17F               (47 | (25 << 8))
#define MAP_SS_ANNE_18F               (48 | (25 << 8))
#define MAP_SS_ANNE_19F               (49 | (25 << 8))
#define MAP_SS_ANNE_20F               (50 | (25 << 8))
#define MAP_SS_ANNE_21F               (51 | (25 << 8))
#define MAP_SS_ANNE_22F               (52 | (25 << 8))
#define MAP_SS_ANNE_23F               (53 | (25 << 8))
#define MAP_SS_ANNE_24F               (54 | (25 << 8))
#define MAP_SS_ANNE_25F               (55 | (25 << 8))
#define MAP_SS_ANNE_26F               (56 | (25 << 8))
#define MAP_UNDERGROUND_PATH_1F       (57 | (25 << 8))
#define MAP_UNDERGROUND_PATH_2F       (58 | (25 << 8))
#define MAP_UNDERGROUND_PATH_3F       (59 | (25 << 8))
#define MAP_UNDERGROUND_PATH_4F       (60 | (25 << 8))
#define MAP_UNDERGROUND_PATH_5F       (61 | (25 << 8))
#define MAP_UNDERGROUND_PATH_6F       (62 | (25 << 8))
#define MAP_DIGLETT_CAVE_1F           (63 | (25 << 8))
#define MAP_DIGLETT_CAVE_2F           (64 | (25 << 8))
#define MAP_DIGLETT_CAVE_3F           (65 | (25 << 8))

// gMapGroup_IndoorKANTO2
#define MAP_NEW_MAP4                (0 | (26 << 8))
#define MAP_VICTORY_ROAD_2F         (1 | (26 << 8))
#define MAP_VICTORY_ROAD_3F         (2 | (26 << 8))
#define MAP_ROCKET_HIDEOUT_1F       (3 | (26 << 8))
#define MAP_ROCKET_HIDEOUT_2F       (4 | (26 << 8))
#define MAP_ROCKET_HIDEOUT_3F       (5 | (26 << 8))
#define MAP_ROCKET_HIDEOUT_4F       (6 | (26 << 8))
#define MAP_ROCKET_HIDEOUT_ELEVATOR (7 | (26 << 8))
#define MAP_SILPH_1F                (8 | (26 << 8))
#define MAP_SILPH_2F                (9 | (26 << 8))
#define MAP_SILPH_3F                (10 | (26 << 8))
#define MAP_SILPH_4F                (11 | (26 << 8))
#define MAP_SILPH_5F                (12 | (26 << 8))
#define MAP_SILPH_6F                (13 | (26 << 8))
#define MAP_SILPH_7F                (14 | (26 << 8))
#define MAP_SILPH_8F                (15 | (26 << 8))
#define MAP_SILPH_9F                (16 | (26 << 8))
#define MAP_SILPH_10F               (17 | (26 << 8))
#define MAP_SILPH_11F               (18 | (26 << 8))
#define MAP_SILPH_ELEVATOR          (19 | (26 << 8))
#define MAP_POKEMON_MANSION_1F      (20 | (26 << 8))
#define MAP_POKEMON_MANSION_2F      (21 | (26 << 8))
#define MAP_POKEMON_MANSION_3F      (22 | (26 << 8))
#define MAP_POKEMON_MANSION_4F      (23 | (26 << 8))
#define MAP_SAFARI_ZONE_1F          (24 | (26 << 8))
#define MAP_SAFARI_ZONE_2F          (25 | (26 << 8))
#define MAP_SAFARI_ZONE_3F          (26 | (26 << 8))
#define MAP_SAFARI_ZONE_4F          (27 | (26 << 8))
#define MAP_SAFARI_ZONE_HOUSE1      (28 | (26 << 8))
#define MAP_SAFARI_ZONE_HOUSE2      (29 | (26 << 8))
#define MAP_SAFARI_ZONE_HOUSE3      (30 | (26 << 8))
#define MAP_SAFARI_ZONE_HOUSE4      (31 | (26 << 8))
#define MAP_SAFARI_ZONE_HOUSE5      (32 | (26 << 8))
#define MAP_DRAGONS_DEN_1F          (33 | (26 << 8))
#define MAP_DRAGONS_DEN_2F          (34 | (26 << 8))
#define MAP_DRAGONS_DEN_3F          (35 | (26 << 8))
#define MAP_POKEMON_LEAGUE_1F       (36 | (26 << 8))
#define MAP_POKEMON_LEAGUE_2F       (37 | (26 << 8))
#define MAP_POKEMON_LEAGUE_3F       (38 | (26 << 8))
#define MAP_POKEMON_LEAGUE_4F       (39 | (26 << 8))
#define MAP_POKEMON_LEAGUE_5F       (40 | (26 << 8))
#define MAP_POKEMON_LEAGUE_6F       (41 | (26 << 8))
#define MAP_ROCK_TUNNEL_1F          (42 | (26 << 8))
#define MAP_ROCK_TUNNEL_2F          (43 | (26 << 8))
#define MAP_SEAFOAM_ISLANDS_1F      (44 | (26 << 8))
#define MAP_SEAFOAM_ISLANDS_2F      (45 | (26 << 8))
#define MAP_SEAFOAM_ISLANDS_3F      (46 | (26 << 8))
#define MAP_SEAFOAM_ISLANDS_4F      (47 | (26 << 8))
#define MAP_SEAFOAM_ISLANDS_5F      (48 | (26 << 8))
#define MAP_POKEMON_TOWER_1F        (49 | (26 << 8))
#define MAP_POKEMON_TOWER_2F        (50 | (26 << 8))
#define MAP_POKEMON_TOWER_3F        (51 | (26 << 8))
#define MAP_POKEMON_TOWER_4F        (52 | (26 << 8))
#define MAP_POKEMON_TOWER_5F        (53 | (26 << 8))
#define MAP_POKEMON_TOWER_6F        (54 | (26 << 8))
#define MAP_POKEMON_TOWER_7F        (55 | (26 << 8))
#define MAP_POWER_PLANT             (56 | (26 << 8))
#define MAP_ROCKET_HIDEOUT_5F       (57 | (26 << 8))
#define MAP_ROCKET_HIDEOUT_6F       (58 | (26 << 8))
#define MAP_BILL_GARDEN             (59 | (26 << 8))
#define MAP_BILL_GARDEN_HOUSE1      (60 | (26 << 8))
#define MAP_ROCKET_HIDEOUT_7F       (61 | (26 << 8))
#define MAP_ROCKET_HIDEOUT_8F       (62 | (26 << 8))
#define MAP_ROCKET_HIDEOUT_9F       (63 | (26 << 8))
#define MAP_CINNABAR_ISLAND_PATH    (64 | (26 << 8))

// gMapGroup_IndoorOneIsland
#define MAP_ONE_ISLAND_POKEMON_CENTER_1F (0 | (27 << 8))
#define MAP_ONE_ISLAND_HOUSE1            (1 | (27 << 8))
#define MAP_ONE_ISLAND_HOUSE2            (2 | (27 << 8))
#define MAP_ONE_ISLAND_PORT              (3 | (27 << 8))

// gMapGroup_IndoorTwoIsland
#define MAP_TWO_ISLAND_HOUSE1            (0 | (28 << 8))
#define MAP_TWO_ISLAND_HOUSE2            (1 | (28 << 8))
#define MAP_TWO_ISLAND_POKEMON_CENTER_1F (2 | (28 << 8))
#define MAP_TWO_ISLAND_PORT              (3 | (28 << 8))

// gMapGroup_IndoorThreeIsland
#define MAP_THREE_ISLAND_HOUSE1            (0 | (29 << 8))
#define MAP_THREE_ISLAND_POKEMON_CENTER_1F (1 | (29 << 8))
#define MAP_THREE_ISLAND_MART              (2 | (29 << 8))
#define MAP_THREE_ISLAND_HOUSE2            (3 | (29 << 8))
#define MAP_THREE_ISLAND_HOUSE3            (4 | (29 << 8))
#define MAP_THREE_ISLAND_HOUSE4            (5 | (29 << 8))
#define MAP_THREE_ISLAND_HOUSE5            (6 | (29 << 8))

// gMapGroup_IndoorFourIsland
#define MAP_FOUR_ISLAND_DAYCARE           (0 | (30 << 8))
#define MAP_FOUR_ISLAND_POKEMON_CENTER_1F (1 | (30 << 8))
#define MAP_FOUR_ISLAND_HOUSE1            (2 | (30 << 8))
#define MAP_FOUR_ISLAND_HOUSE2            (3 | (30 << 8))
#define MAP_FOUR_ISLAND_PORT              (4 | (30 << 8))
#define MAP_FOUR_ISLAND_HOUSE3            (5 | (30 << 8))
#define MAP_FOUR_ISLAND_MART              (6 | (30 << 8))

// gMapGroup_IndoorFiveIsland
#define MAP_FIVE_ISLAND_POKEMON_CENTER_1F (0 | (31 << 8))
#define MAP_FIVE_ISLAND_PORT              (1 | (31 << 8))
#define MAP_FIVE_ISLAND_HOUSE1            (2 | (31 << 8))
#define MAP_FIVE_ISLAND_HOUSE2            (3 | (31 << 8))

// gMapGroup_IndoorSixIsland
#define MAP_SIX_ISLAND_POKEMON_CENTER_1F (0 | (32 << 8))
#define MAP_SIX_ISLAND_PORT              (1 | (32 << 8))
#define MAP_SIX_ISLAND_HOUSE1            (2 | (32 << 8))
#define MAP_SIX_ISLAND_HOUSE2            (3 | (32 << 8))

// gMapGroup_IndoorSevenIsland
#define MAP_SEVEN_ISLAND_HOUSE1            (0 | (33 << 8))
#define MAP_SEVEN_ISLAND_MART              (1 | (33 << 8))
#define MAP_SEVEN_ISLAND_POKEMON_CENTER_1F (2 | (33 << 8))
#define MAP_NEW_MAP3                       (3 | (33 << 8))
#define MAP_SEVEN_ISLAND_PORT              (4 | (33 << 8))

// gMapGroup_IndoorSEVII
#define MAP_THREE_ISLAND_PORT                 (0 | (34 << 8))
#define MAP_RESORT_GEORGEOUS_HOUSE1           (1 | (34 << 8))
#define MAP_CAPE_BRINK_HOUSE1                 (2 | (34 << 8))
#define MAP_WATER_PATH_HOUSE1                 (3 | (34 << 8))
#define MAP_WATER_PATH_HOUSE2                 (4 | (34 << 8))
#define MAP_SEVAULT_CANYON_HOUSE1             (5 | (34 << 8))
#define MAP_MT_EMBER_B4F                      (6 | (34 << 8))
#define MAP_MT_EMBER_ENTRANCE                 (7 | (34 << 8))
#define MAP_MT_EMBER_1F                       (8 | (34 << 8))
#define MAP_MT_EMBER_2F                       (9 | (34 << 8))
#define MAP_MT_EMBER_3F                       (10 | (34 << 8))
#define MAP_MT_EMBER_SUMMIT                   (11 | (34 << 8))
#define MAP_MT_EMBER_B5F                      (12 | (34 << 8))
#define MAP_MT_EMBER_1F_PATH                  (13 | (34 << 8))
#define MAP_MT_EMBER_B1F                      (14 | (34 << 8))
#define MAP_MT_EMBER_B2F                      (15 | (34 << 8))
#define MAP_MT_EMBER_B3F                      (16 | (34 << 8))
#define MAP_MT_EMBER_B2F_EXIT                 (17 | (34 << 8))
#define MAP_MT_EMBER_B1F_EXIT                 (18 | (34 << 8))
#define MAP_BERRY_FOREST                      (19 | (34 << 8))
#define MAP_ICEFALL_CAVE_ENTRANCE             (20 | (34 << 8))
#define MAP_ICEFALL_CAVE_1F                   (21 | (34 << 8))
#define MAP_ICEFALL_CAVE_B1F                  (22 | (34 << 8))
#define MAP_ICEFALL_CAVE_BACK_CAVE            (23 | (34 << 8))
#define MAP_ROCKET_WAREHOUSE                  (24 | (34 << 8))
#define MAP_DOTTED_HOLE_GROUND_FLOOR          (25 | (34 << 8))
#define MAP_DOTTED_HOLE_B1F                   (26 | (34 << 8))
#define MAP_DOTTED_HOLE_B2F                   (27 | (34 << 8))
#define MAP_DOTTED_HOLE_B3F                   (28 | (34 << 8))
#define MAP_DOTTED_HOLE_B4F                   (29 | (34 << 8))
#define MAP_DOTTED_HOLE_SAPPHIRE_ROOM         (30 | (34 << 8))
#define MAP_PATTERN_BUSH                      (31 | (34 << 8))
#define MAP_ALTERING_CAVE_SEVII               (32 | (34 << 8))
#define MAP_LOST_CAVE_1F                      (33 | (34 << 8))
#define MAP_LOST_CAVE_B1F_LADDER_ROOM         (34 | (34 << 8))
#define MAP_LOST_CAVE_B1F_PATH1               (35 | (34 << 8))
#define MAP_LOST_CAVE_B1F_PATH2               (36 | (34 << 8))
#define MAP_LOST_CAVE_B1F_PATH3               (37 | (34 << 8))
#define MAP_LOST_CAVE_B1F_PATH4               (38 | (34 << 8))
#define MAP_LOST_CAVE_B1F_PATH5               (39 | (34 << 8))
#define MAP_LOST_CAVE_B1F_PATH6               (40 | (34 << 8))
#define MAP_LOST_CAVE_B1F_PATH7               (41 | (34 << 8))
#define MAP_LOST_CAVE_B1F_PATH8               (42 | (34 << 8))
#define MAP_LOST_CAVE_B1F_LAST_ROOM           (43 | (34 << 8))
#define MAP_LOST_CAVE_B1F_ITEM1               (44 | (34 << 8))
#define MAP_LOST_CAVE_B1F_ITEM2               (45 | (34 << 8))
#define MAP_LOST_CAVE_B1F_ITEM3               (46 | (34 << 8))
#define MAP_LOST_CAVE_B1F_ITEM4               (47 | (34 << 8))
#define MAP_MONEAN_CHAMBER                    (48 | (34 << 8))
#define MAP_LIPTOO_CHAMBER                    (49 | (34 << 8))
#define MAP_WEEPTH_CHAMBER                    (50 | (34 << 8))
#define MAP_DILFORD_CHAMBER                   (51 | (34 << 8))
#define MAP_SCUFIB_CHAMBER                    (52 | (34 << 8))
#define MAP_RIXY_CHAMBER                      (53 | (34 << 8))
#define MAP_VIAPOIS_CHAMBER                   (54 | (34 << 8))
#define MAP_THREE_ISLE_PATH                   (55 | (34 << 8))
#define MAP_TANOBY_KEY                        (56 | (34 << 8))
#define MAP_EMBER_SPA                         (57 | (34 << 8))
#define MAP_ROCKET_HIDEOUT_FIVE_ISLAND_MEADOW (58 | (34 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (35 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (35 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (35 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (35 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (35 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (36 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (36 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (36 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (36 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (36 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (37 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (37 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (37 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (37 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (37 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (37 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (38 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (38 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (38 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (38 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (38 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (38 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (38 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (39 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (39 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (39 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (39 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (39 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (39 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (39 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (39 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (40 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (40 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (40 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (40 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (40 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (40 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (40 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (40 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (40 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (41 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (41 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (41 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (41 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (41 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (41 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (41 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (42 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (42 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (42 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (42 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (42 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (42 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (42 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (43 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (43 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (43 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (43 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (43 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (43 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (43 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (43 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (43 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (43 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (43 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (43 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (43 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (43 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (44 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (44 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (44 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (44 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (44 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (44 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (44 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (44 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (45 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (45 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (45 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (45 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (45 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (45 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (45 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (45 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (45 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (45 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (45 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (45 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (45 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (45 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (45 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (45 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (45 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (46 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (46 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (46 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (46 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (46 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (46 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (46 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (46 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (46 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (46 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (47 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (47 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (47 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (47 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (47 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (47 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (47 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (47 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (47 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (47 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (47 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (47 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (47 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (47 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (47 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (47 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (47 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (47 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (47 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (47 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (47 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (47 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (47 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (48 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (48 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (48 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (48 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (48 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (48 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (48 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (48 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (48 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (48 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (48 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (48 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (48 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (49 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (49 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (50 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (50 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (51 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (51 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (52 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (52 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (53 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (53 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (54 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (54 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (54 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (55 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (56 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (57 << 8))

// gMapGroup_IndoorRoute2

// gMapGroup_IndoorRoute4

// gMapGroup_IndoorRoute5

// gMapGroup_IndoorRoute6

// gMapGroup_IndoorRoute7

// gMapGroup_IndoorRoute8

// gMapGroup_IndoorRoute10

// gMapGroup_IndoorRoute11

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (66 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (66 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (66 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (66 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (66 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (66 << 8))
#define MAP_DESERT_RUINS                             (6 | (66 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (66 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (66 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (66 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (66 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (66 << 8))
#define MAP_MT_CHIMNEY                               (12 | (66 << 8))
#define MAP_JAGGED_PASS                              (13 | (66 << 8))
#define MAP_FIERY_PATH                               (14 | (66 << 8))
#define MAP_MT_PYRE_1F                               (15 | (66 << 8))
#define MAP_MT_PYRE_2F                               (16 | (66 << 8))
#define MAP_MT_PYRE_3F                               (17 | (66 << 8))
#define MAP_MT_PYRE_4F                               (18 | (66 << 8))
#define MAP_MT_PYRE_5F                               (19 | (66 << 8))
#define MAP_MT_PYRE_6F                               (20 | (66 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (66 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (66 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (66 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (66 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (66 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (66 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (66 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (66 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (66 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (66 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (66 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (66 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (66 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (66 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (66 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (66 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (66 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (66 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (66 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (66 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (66 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (66 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (66 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (66 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (66 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (66 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (66 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (66 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (66 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (66 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (66 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (66 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (66 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (66 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (66 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (66 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (66 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (66 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (66 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (66 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (66 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (66 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (66 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (66 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (66 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (66 << 8))
#define MAP_ISLAND_CAVE                              (67 | (66 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (66 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (66 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (66 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (66 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (66 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (66 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (66 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (66 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (66 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (66 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (66 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (66 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (66 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (66 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (66 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (66 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (66 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (66 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (66 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (66 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (66 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (66 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (66 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (66 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (66 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (66 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (66 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (66 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (66 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (66 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (66 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (66 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (66 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (66 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (66 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (66 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (66 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (66 << 8))
#define MAP_ALTERING_CAVE                            (106 | (66 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (66 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (67 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (67 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (67 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (67 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (67 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (67 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (67 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (67 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (67 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (67 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (67 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (67 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (67 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (67 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (67 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (67 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (67 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (67 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (67 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (67 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (67 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (67 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (67 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (67 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (67 << 8))
#define MAP_TRADE_CENTER             (25 | (67 << 8))
#define MAP_RECORD_CORNER            (26 | (67 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (67 << 8))
#define MAP_CONTEST_HALL             (28 | (67 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (67 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (67 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (67 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (67 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (67 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (67 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (67 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (67 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (67 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (67 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (67 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (67 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (67 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (67 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (67 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (67 << 8))
#define MAP_UNION_ROOM               (60 | (67 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (68 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (68 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (68 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (68 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (68 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (68 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (68 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (68 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (68 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (68 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (68 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (68 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (68 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (68 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (68 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (68 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (68 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (68 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (68 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (68 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (68 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (68 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (68 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (68 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (68 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (68 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (68 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (68 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (68 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (68 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (68 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (68 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (68 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (68 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (68 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (68 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (68 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (68 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (68 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (68 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (68 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (68 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (68 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (68 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (68 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (68 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (68 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (68 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (68 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (68 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (68 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (69 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (69 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (70 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (71 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (71 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (71 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (71 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (71 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (71 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (71 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (71 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (71 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (71 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (71 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (71 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (71 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (72 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (73 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (74 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (74 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (74 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (75 << 8))

#define MAP_GROUPS_COUNT 76

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
