#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY                    (0 | (0 << 8))
#define MAP_SLATEPORT_CITY                    (1 | (0 << 8))
#define MAP_MAUVILLE_CITY                     (2 | (0 << 8))
#define MAP_RUSTBORO_CITY                     (3 | (0 << 8))
#define MAP_FORTREE_CITY                      (4 | (0 << 8))
#define MAP_LILYCOVE_CITY                     (5 | (0 << 8))
#define MAP_MOSSDEEP_CITY                     (6 | (0 << 8))
#define MAP_SOOTOPOLIS_CITY                   (7 | (0 << 8))
#define MAP_EVER_GRANDE_CITY                  (8 | (0 << 8))
#define MAP_LITTLEROOT_TOWN                   (9 | (0 << 8))
#define MAP_OLDALE_TOWN                       (10 | (0 << 8))
#define MAP_DEWFORD_TOWN                      (11 | (0 << 8))
#define MAP_LAVARIDGE_TOWN                    (12 | (0 << 8))
#define MAP_FALLARBOR_TOWN                    (13 | (0 << 8))
#define MAP_VERDANTURF_TOWN                   (14 | (0 << 8))
#define MAP_PACIFIDLOG_TOWN                   (15 | (0 << 8))
#define MAP_ROUTE101                          (16 | (0 << 8))
#define MAP_ROUTE102                          (17 | (0 << 8))
#define MAP_ROUTE103                          (18 | (0 << 8))
#define MAP_ROUTE104                          (19 | (0 << 8))
#define MAP_ROUTE105                          (20 | (0 << 8))
#define MAP_ROUTE106                          (21 | (0 << 8))
#define MAP_ROUTE107                          (22 | (0 << 8))
#define MAP_ROUTE108                          (23 | (0 << 8))
#define MAP_ROUTE109                          (24 | (0 << 8))
#define MAP_ROUTE110                          (25 | (0 << 8))
#define MAP_ROUTE111                          (26 | (0 << 8))
#define MAP_ROUTE112                          (27 | (0 << 8))
#define MAP_ROUTE113                          (28 | (0 << 8))
#define MAP_ROUTE114                          (29 | (0 << 8))
#define MAP_ROUTE115                          (30 | (0 << 8))
#define MAP_ROUTE116                          (31 | (0 << 8))
#define MAP_ROUTE117                          (32 | (0 << 8))
#define MAP_ROUTE118                          (33 | (0 << 8))
#define MAP_ROUTE119                          (34 | (0 << 8))
#define MAP_ROUTE120                          (35 | (0 << 8))
#define MAP_ROUTE121                          (36 | (0 << 8))
#define MAP_ROUTE122                          (37 | (0 << 8))
#define MAP_ROUTE123                          (38 | (0 << 8))
#define MAP_ROUTE124                          (39 | (0 << 8))
#define MAP_ROUTE125                          (40 | (0 << 8))
#define MAP_ROUTE126                          (41 | (0 << 8))
#define MAP_ROUTE127                          (42 | (0 << 8))
#define MAP_ROUTE128                          (43 | (0 << 8))
#define MAP_ROUTE129                          (44 | (0 << 8))
#define MAP_ROUTE130                          (45 | (0 << 8))
#define MAP_ROUTE131                          (46 | (0 << 8))
#define MAP_ROUTE132                          (47 | (0 << 8))
#define MAP_ROUTE133                          (48 | (0 << 8))
#define MAP_ROUTE134                          (49 | (0 << 8))
#define MAP_UNDERWATER_ROUTE124               (50 | (0 << 8))
#define MAP_UNDERWATER_ROUTE126               (51 | (0 << 8))
#define MAP_UNDERWATER_ROUTE127               (52 | (0 << 8))
#define MAP_UNDERWATER_ROUTE128               (53 | (0 << 8))
#define MAP_UNDERWATER_ROUTE129               (54 | (0 << 8))
#define MAP_UNDERWATER_ROUTE105               (55 | (0 << 8))
#define MAP_UNDERWATER_ROUTE125               (56 | (0 << 8))
#define MAP_PALLET_TOWN                       (57 | (0 << 8))
#define MAP_VIRIDIAN_CITY                     (58 | (0 << 8))
#define MAP_PEWTER_CITY                       (59 | (0 << 8))
#define MAP_CERULEAN_CITY                     (60 | (0 << 8))
#define MAP_LAVENDER_TOWN                     (61 | (0 << 8))
#define MAP_VERMILION_CITY                    (62 | (0 << 8))
#define MAP_CELADON_CITY                      (63 | (0 << 8))
#define MAP_FUCHSIA_CITY                      (64 | (0 << 8))
#define MAP_CINNABAR_ISLAND                   (65 | (0 << 8))
#define MAP_INDIGO_PLATEAU                    (66 | (0 << 8))
#define MAP_SAFFRON_CITY                      (67 | (0 << 8))
#define MAP_ONE_ISLAND                        (68 | (0 << 8))
#define MAP_TWO_ISLAND                        (69 | (0 << 8))
#define MAP_THREE_ISLAND                      (70 | (0 << 8))
#define MAP_FOUR_ISLAND                       (71 | (0 << 8))
#define MAP_FIVE_ISLAND                       (72 | (0 << 8))
#define MAP_SIX_ISLAND                        (73 | (0 << 8))
#define MAP_SEVEN_ISLAND                      (74 | (0 << 8))
#define MAP_NAVEL_ROCK                        (75 | (0 << 8))
#define MAP_BIRTH_ISLAND                      (76 | (0 << 8))
#define MAP_ROUTE4                            (77 | (0 << 8))
#define MAP_ROUTE10                           (78 | (0 << 8))
#define MAP_NEW_BARK_TOWN                     (79 | (0 << 8))
#define MAP_CHERRYGROVE_CITY                  (80 | (0 << 8))
#define MAP_VIOLET_CITY                       (81 | (0 << 8))
#define MAP_AZALEA_TOWN                       (82 | (0 << 8))
#define MAP_GOLDENROD_CITY                    (83 | (0 << 8))
#define MAP_ECRUTEAK_CITY                     (84 | (0 << 8))
#define MAP_OLIVINE_CITY                      (85 | (0 << 8))
#define MAP_CIANWOOD_CITY                     (86 | (0 << 8))
#define MAP_MAHOGANY_TOWN                     (87 | (0 << 8))
#define MAP_BLACKTHORN_CITY                   (88 | (0 << 8))
#define MAP_MT_SILVER                         (89 | (0 << 8))
#define MAP_SOUTH_ROUTE45                     (90 | (0 << 8))
#define MAP_ROUTE1                            (91 | (0 << 8))
#define MAP_ROUTE2                            (92 | (0 << 8))
#define MAP_NEW_MAP1                          (93 | (0 << 8))
#define MAP_ROUTE5                            (94 | (0 << 8))
#define MAP_ROUTE6                            (95 | (0 << 8))
#define MAP_ROUTE7                            (96 | (0 << 8))
#define MAP_ROUTE8                            (97 | (0 << 8))
#define MAP_ROUTE9                            (98 | (0 << 8))
#define MAP_ROUTE11                           (99 | (0 << 8))
#define MAP_ROUTE12                           (100 | (0 << 8))
#define MAP_ROUTE13                           (101 | (0 << 8))
#define MAP_ROUTE14                           (102 | (0 << 8))
#define MAP_ROUTE15                           (103 | (0 << 8))
#define MAP_ROUTE16                           (104 | (0 << 8))
#define MAP_ROUTE17                           (105 | (0 << 8))
#define MAP_ROUTE18                           (106 | (0 << 8))
#define MAP_ROUTE19                           (107 | (0 << 8))
#define MAP_ROUTE20                           (108 | (0 << 8))
#define MAP_ROUTE21                           (109 | (0 << 8))
#define MAP_ROUTE22                           (110 | (0 << 8))
#define MAP_ROUTE23                           (111 | (0 << 8))
#define MAP_ROUTE24                           (112 | (0 << 8))
#define MAP_ROUTE25                           (113 | (0 << 8))
#define MAP_KINDLE_ROAD                       (114 | (0 << 8))
#define MAP_CAPE_BRINK                        (115 | (0 << 8))
#define MAP_SOUTH_TWO_ISLAND                  (116 | (0 << 8))
#define MAP_NAVEL_ROAD                        (117 | (0 << 8))
#define MAP_THREE_ISLE_PORT                   (118 | (0 << 8))
#define MAP_BOND_BRIDGE                       (119 | (0 << 8))
#define MAP_WATER_LABYRINTH                   (120 | (0 << 8))
#define MAP_RESORT_GORGEOUS                   (121 | (0 << 8))
#define MAP_FILE_ISLE_MEADOW                  (122 | (0 << 8))
#define MAP_MEMORIAL_PILLAR                   (123 | (0 << 8))
#define MAP_WATER_PATH                        (124 | (0 << 8))
#define MAP_GREEN_PATH                        (125 | (0 << 8))
#define MAP_OUTCAST_ISLAND                    (126 | (0 << 8))
#define MAP_RUIN_VALLEY                       (127 | (0 << 8))
#define MAP_TRAINER_TOWER                     (128 | (0 << 8))
#define MAP_CANYON_ENTRANCE                   (129 | (0 << 8))
#define MAP_SEVAULT_CANYON                    (130 | (0 << 8))
#define MAP_TANOBY_RUINS                      (131 | (0 << 8))
#define MAP_WEST_BIRTH_ISLAND                 (132 | (0 << 8))
#define MAP_ROUTE2_PATH                       (133 | (0 << 8))
#define MAP_ROUTE2_HOUSE1                     (134 | (0 << 8))
#define MAP_ROUTE2_PATH2                      (135 | (0 << 8))
#define MAP_ROUTE2_PATH3                      (136 | (0 << 8))
#define MAP_ROUTE4_POKEMON_CENTER_1F          (137 | (0 << 8))
#define MAP_ROUTE5_HOUSE1                     (138 | (0 << 8))
#define MAP_ROUTE5_PATH                       (139 | (0 << 8))
#define MAP_ROUTE6_PATH                       (140 | (0 << 8))
#define MAP_ROUTE7_PATH                       (141 | (0 << 8))
#define MAP_ROUTE8_PATH                       (142 | (0 << 8))
#define MAP_ROUTE10_POKEMON_CENTER_1F         (143 | (0 << 8))
#define MAP_ROUTE11_PATH_1F                   (144 | (0 << 8))
#define MAP_ROUTE11_PATH_2F                   (145 | (0 << 8))
#define MAP_ROUTE12_PATH_1F                   (146 | (0 << 8))
#define MAP_ROUTE12_PATH_2F                   (147 | (0 << 8))
#define MAP_ROUTE12_HOUSE1                    (148 | (0 << 8))
#define MAP_ROUTE15_PATH_1F                   (149 | (0 << 8))
#define MAP_ROUTE15_PATH_2F                   (150 | (0 << 8))
#define MAP_ROUTE16_HOUSE1                    (151 | (0 << 8))
#define MAP_ROUTE16_PATH_1F                   (152 | (0 << 8))
#define MAP_ROUTE16_PATH_2F                   (153 | (0 << 8))
#define MAP_ROUTE18_PATH_1F                   (154 | (0 << 8))
#define MAP_ROUTE18_PATH_2F                   (155 | (0 << 8))
#define MAP_ROUTE19_HOUSE1                    (156 | (0 << 8))
#define MAP_ROUTE22_PATH                      (157 | (0 << 8))
#define MAP_ROUTE23_HOUSE1                    (158 | (0 << 8))
#define MAP_ROUTE25_BILL_HOUSE                (159 | (0 << 8))
#define MAP_THREE_ISLAND_PORT                 (160 | (0 << 8))
#define MAP_RESORT_GEORGEOUS_HOUSE1           (161 | (0 << 8))
#define MAP_CAPE_BRINK_HOUSE1                 (162 | (0 << 8))
#define MAP_WATER_PATH_HOUSE1                 (163 | (0 << 8))
#define MAP_WATER_PATH_HOUSE2                 (164 | (0 << 8))
#define MAP_SEVAULT_CANYON_HOUSE1             (165 | (0 << 8))
#define MAP_VIRIDIAN_FOREST                   (166 | (0 << 8))
#define MAP_MT_MOON_1F                        (167 | (0 << 8))
#define MAP_MT_MOON_2F                        (168 | (0 << 8))
#define MAP_MT_MOON_3F                        (169 | (0 << 8))
#define MAP_SS_ANNE_1F                        (170 | (0 << 8))
#define MAP_SS_ANNE_2F                        (171 | (0 << 8))
#define MAP_SS_ANNE_3F                        (172 | (0 << 8))
#define MAP_SS_ANNE_4F                        (173 | (0 << 8))
#define MAP_SS_ANNE_5F                        (174 | (0 << 8))
#define MAP_SS_ANNE_6F                        (175 | (0 << 8))
#define MAP_SS_ANNE_7F                        (176 | (0 << 8))
#define MAP_SS_ANNE_8F                        (177 | (0 << 8))
#define MAP_SS_ANNE_9F                        (178 | (0 << 8))
#define MAP_SS_ANNE_10F                       (179 | (0 << 8))
#define MAP_SS_ANNE_11F                       (180 | (0 << 8))
#define MAP_SS_ANNE_12F                       (181 | (0 << 8))
#define MAP_SS_ANNE_13F                       (182 | (0 << 8))
#define MAP_SS_ANNE_14F                       (183 | (0 << 8))
#define MAP_SS_ANNE_15F                       (184 | (0 << 8))
#define MAP_SS_ANNE_16F                       (185 | (0 << 8))
#define MAP_SS_ANNE_17F                       (186 | (0 << 8))
#define MAP_SS_ANNE_18F                       (187 | (0 << 8))
#define MAP_SS_ANNE_19F                       (188 | (0 << 8))
#define MAP_SS_ANNE_20F                       (189 | (0 << 8))
#define MAP_SS_ANNE_21F                       (190 | (0 << 8))
#define MAP_SS_ANNE_22F                       (191 | (0 << 8))
#define MAP_SS_ANNE_23F                       (192 | (0 << 8))
#define MAP_SS_ANNE_24F                       (193 | (0 << 8))
#define MAP_SS_ANNE_25F                       (194 | (0 << 8))
#define MAP_SS_ANNE_26F                       (195 | (0 << 8))
#define MAP_UNDERGROUND_PATH_1F               (196 | (0 << 8))
#define MAP_UNDERGROUND_PATH_2F               (197 | (0 << 8))
#define MAP_UNDERGROUND_PATH_3F               (198 | (0 << 8))
#define MAP_UNDERGROUND_PATH_4F               (199 | (0 << 8))
#define MAP_UNDERGROUND_PATH_5F               (200 | (0 << 8))
#define MAP_UNDERGROUND_PATH_6F               (201 | (0 << 8))
#define MAP_DIGLETT_CAVE_1F                   (202 | (0 << 8))
#define MAP_DIGLETT_CAVE_2F                   (203 | (0 << 8))
#define MAP_DIGLETT_CAVE_3F                   (204 | (0 << 8))
#define MAP_NEW_MAP4                          (205 | (0 << 8))
#define MAP_VICTORY_ROAD_2F                   (206 | (0 << 8))
#define MAP_VICTORY_ROAD_3F                   (207 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_1F                 (208 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_2F                 (209 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_3F                 (210 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_4F                 (211 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_ELEVATOR           (212 | (0 << 8))
#define MAP_SILPH_1F                          (213 | (0 << 8))
#define MAP_SILPH_2F                          (214 | (0 << 8))
#define MAP_SILPH_3F                          (215 | (0 << 8))
#define MAP_SILPH_4F                          (216 | (0 << 8))
#define MAP_SILPH_5F                          (217 | (0 << 8))
#define MAP_SILPH_6F                          (218 | (0 << 8))
#define MAP_SILPH_7F                          (219 | (0 << 8))
#define MAP_SILPH_8F                          (220 | (0 << 8))
#define MAP_SILPH_9F                          (221 | (0 << 8))
#define MAP_SILPH_10F                         (222 | (0 << 8))
#define MAP_SILPH_11F                         (223 | (0 << 8))
#define MAP_SILPH_ELEVATOR                    (224 | (0 << 8))
#define MAP_POKEMON_MANSION_1F                (225 | (0 << 8))
#define MAP_POKEMON_MANSION_2F                (226 | (0 << 8))
#define MAP_POKEMON_MANSION_3F                (227 | (0 << 8))
#define MAP_POKEMON_MANSION_4F                (228 | (0 << 8))
#define MAP_SAFARI_ZONE_1F                    (229 | (0 << 8))
#define MAP_SAFARI_ZONE_2F                    (230 | (0 << 8))
#define MAP_SAFARI_ZONE_3F                    (231 | (0 << 8))
#define MAP_SAFARI_ZONE_4F                    (232 | (0 << 8))
#define MAP_SAFARI_ZONE_HOUSE1                (233 | (0 << 8))
#define MAP_SAFARI_ZONE_HOUSE2                (234 | (0 << 8))
#define MAP_SAFARI_ZONE_HOUSE3                (235 | (0 << 8))
#define MAP_SAFARI_ZONE_HOUSE4                (236 | (0 << 8))
#define MAP_SAFARI_ZONE_HOUSE5                (237 | (0 << 8))
#define MAP_DRAGONS_DEN_1F                    (238 | (0 << 8))
#define MAP_DRAGONS_DEN_2F                    (239 | (0 << 8))
#define MAP_DRAGONS_DEN_3F                    (240 | (0 << 8))
#define MAP_POKEMON_LEAGUE_1F                 (241 | (0 << 8))
#define MAP_POKEMON_LEAGUE_2F                 (242 | (0 << 8))
#define MAP_POKEMON_LEAGUE_3F                 (243 | (0 << 8))
#define MAP_POKEMON_LEAGUE_4F                 (244 | (0 << 8))
#define MAP_POKEMON_LEAGUE_5F                 (245 | (0 << 8))
#define MAP_POKEMON_LEAGUE_6F                 (246 | (0 << 8))
#define MAP_ROCK_TUNNEL_1F                    (247 | (0 << 8))
#define MAP_ROCK_TUNNEL_2F                    (248 | (0 << 8))
#define MAP_SEAFOAM_ISLANDS_1F                (249 | (0 << 8))
#define MAP_SEAFOAM_ISLANDS_2F                (250 | (0 << 8))
#define MAP_SEAFOAM_ISLANDS_3F                (251 | (0 << 8))
#define MAP_SEAFOAM_ISLANDS_4F                (252 | (0 << 8))
#define MAP_SEAFOAM_ISLANDS_5F                (253 | (0 << 8))
#define MAP_POKEMON_TOWER_1F                  (254 | (0 << 8))
#define MAP_POKEMON_TOWER_2F                  (255 | (0 << 8))
#define MAP_POKEMON_TOWER_3F                  (256 | (0 << 8))
#define MAP_POKEMON_TOWER_4F                  (257 | (0 << 8))
#define MAP_POKEMON_TOWER_5F                  (258 | (0 << 8))
#define MAP_POKEMON_TOWER_6F                  (259 | (0 << 8))
#define MAP_POKEMON_TOWER_7F                  (260 | (0 << 8))
#define MAP_POWER_PLANT                       (261 | (0 << 8))
#define MAP_MT_EMBER_B4F                      (262 | (0 << 8))
#define MAP_MT_EMBER_ENTRANCE                 (263 | (0 << 8))
#define MAP_MT_EMBER_1F                       (264 | (0 << 8))
#define MAP_MT_EMBER_2F                       (265 | (0 << 8))
#define MAP_MT_EMBER_3F                       (266 | (0 << 8))
#define MAP_MT_EMBER_SUMMIT                   (267 | (0 << 8))
#define MAP_MT_EMBER_B5F                      (268 | (0 << 8))
#define MAP_MT_EMBER_1F_PATH                  (269 | (0 << 8))
#define MAP_MT_EMBER_B1F                      (270 | (0 << 8))
#define MAP_MT_EMBER_B2F                      (271 | (0 << 8))
#define MAP_MT_EMBER_B3F                      (272 | (0 << 8))
#define MAP_MT_EMBER_B2F_EXIT                 (273 | (0 << 8))
#define MAP_MT_EMBER_B1F_EXIT                 (274 | (0 << 8))
#define MAP_BERRY_FOREST                      (275 | (0 << 8))
#define MAP_ICEFALL_CAVE_ENTRANCE             (276 | (0 << 8))
#define MAP_ICEFALL_CAVE_1F                   (277 | (0 << 8))
#define MAP_ICEFALL_CAVE_B1F                  (278 | (0 << 8))
#define MAP_ICEFALL_CAVE_BACK_CAVE            (279 | (0 << 8))
#define MAP_ROCKET_WAREHOUSE                  (280 | (0 << 8))
#define MAP_DOTTED_HOLE_GROUND_FLOOR          (281 | (0 << 8))
#define MAP_DOTTED_HOLE_B1F                   (282 | (0 << 8))
#define MAP_DOTTED_HOLE_B2F                   (283 | (0 << 8))
#define MAP_DOTTED_HOLE_B3F                   (284 | (0 << 8))
#define MAP_DOTTED_HOLE_B4F                   (285 | (0 << 8))
#define MAP_DOTTED_HOLE_SAPPHIRE_ROOM         (286 | (0 << 8))
#define MAP_PATTERN_BUSH                      (287 | (0 << 8))
#define MAP_ALTERING_CAVE_SEVII               (288 | (0 << 8))
#define MAP_LOST_CAVE_1F                      (289 | (0 << 8))
#define MAP_LOST_CAVE_B1F_LADDER_ROOM         (290 | (0 << 8))
#define MAP_LOST_CAVE_B1F_PATH1               (291 | (0 << 8))
#define MAP_LOST_CAVE_B1F_PATH2               (292 | (0 << 8))
#define MAP_LOST_CAVE_B1F_PATH3               (293 | (0 << 8))
#define MAP_LOST_CAVE_B1F_PATH4               (294 | (0 << 8))
#define MAP_LOST_CAVE_B1F_PATH5               (295 | (0 << 8))
#define MAP_LOST_CAVE_B1F_PATH6               (296 | (0 << 8))
#define MAP_LOST_CAVE_B1F_PATH7               (297 | (0 << 8))
#define MAP_LOST_CAVE_B1F_PATH8               (298 | (0 << 8))
#define MAP_LOST_CAVE_B1F_LAST_ROOM           (299 | (0 << 8))
#define MAP_LOST_CAVE_B1F_ITEM1               (300 | (0 << 8))
#define MAP_LOST_CAVE_B1F_ITEM2               (301 | (0 << 8))
#define MAP_LOST_CAVE_B1F_ITEM3               (302 | (0 << 8))
#define MAP_LOST_CAVE_B1F_ITEM4               (303 | (0 << 8))
#define MAP_MONEAN_CHAMBER                    (304 | (0 << 8))
#define MAP_LIPTOO_CHAMBER                    (305 | (0 << 8))
#define MAP_WEEPTH_CHAMBER                    (306 | (0 << 8))
#define MAP_DILFORD_CHAMBER                   (307 | (0 << 8))
#define MAP_SCUFIB_CHAMBER                    (308 | (0 << 8))
#define MAP_RIXY_CHAMBER                      (309 | (0 << 8))
#define MAP_VIAPOIS_CHAMBER                   (310 | (0 << 8))
#define MAP_THREE_ISLE_PATH                   (311 | (0 << 8))
#define MAP_TANOBY_KEY                        (312 | (0 << 8))
#define MAP_EMBER_SPA                         (313 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_5F                 (314 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_6F                 (315 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_FIVE_ISLAND_MEADOW (316 | (0 << 8))
#define MAP_BILL_GARDEN                       (317 | (0 << 8))
#define MAP_BILL_GARDEN_HOUSE1                (318 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_7F                 (319 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_8F                 (320 | (0 << 8))
#define MAP_ROCKET_HIDEOUT_9F                 (321 | (0 << 8))

// gMapGroup_IndoorPalletTown
#define MAP_PALLET_TOWN_RED_HOUSE_1F  (0 | (1 << 8))
#define MAP_PALLET_TOWN_RED_HOUSE_2F  (1 | (1 << 8))
#define MAP_PALLET_TOWN_BLUE_HOUSE_1F (2 | (1 << 8))
#define MAP_PALLET_TOWN_PROFESSOR_LAB (3 | (1 << 8))

// gMapGroup_IndoorViridianCity
#define MAP_VIRIDIAN_CITY_HOUSE1            (0 | (2 << 8))
#define MAP_VIRIDIAN_CITY_GYM               (1 | (2 << 8))
#define MAP_VIRIDIAN_CITY_SCHOOL            (2 | (2 << 8))
#define MAP_VIRIDIAN_CITY_MART              (3 | (2 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F (4 | (2 << 8))

// gMapGroup_IndoorPewterCity
#define MAP_PEWTER_CITY_MUSEUM_1F (0 | (3 << 8))
#define MAP_PEWTER_CITY_MUSEM_2F  (1 | (3 << 8))
#define MAP_PEWTER_CITY_GYM       (2 | (3 << 8))
#define MAP_PEWTER_CITY_MART      (3 | (3 << 8))
#define MAP_PEWTER_CITY_HOUSE1    (4 | (3 << 8))
#define MAP_NEW_MAP2              (5 | (3 << 8))
#define MAP_PEWTER_CITY_SCHOOL    (6 | (3 << 8))
#define MAP_PEWTER_CITY_HOUSE2    (7 | (3 << 8))

// gMapGroup_IndoorCeruleanCity
#define MAP_CERULEAN_CITY_HOUSE1            (0 | (4 << 8))
#define MAP_CERULEAN_CITY_HOUSE2            (1 | (4 << 8))
#define MAP_CERULEAN_CITY_HOUSE3            (2 | (4 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_1F (3 | (4 << 8))
#define MAP_CERULEAN_CITY_SCHOOL            (4 | (4 << 8))
#define MAP_CERULEAN_CITY_GYM               (5 | (4 << 8))
#define MAP_CERULEAN_CITY_BIKE_SHOP         (6 | (4 << 8))
#define MAP_CERULEAN_CITY_MART              (7 | (4 << 8))
#define MAP_CERULEAN_CITY_HOUSE4            (8 | (4 << 8))
#define MAP_CERULEAN_CITY_HOUSE5            (9 | (4 << 8))

// gMapGroup_IndoorVermilionCity
#define MAP_VERMILION_CITY_HOUSE1            (0 | (5 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_1F (1 | (5 << 8))
#define MAP_VERMILION_CITY_SCHOOL            (2 | (5 << 8))
#define MAP_VERMILION_CITY_CLUB              (3 | (5 << 8))
#define MAP_VERMILION_CITY_HOUSE2            (4 | (5 << 8))
#define MAP_VERMILION_CITY_MART              (5 | (5 << 8))
#define MAP_VERMILION_CITY_GYM               (6 | (5 << 8))
#define MAP_VERMILION_CITY_HOUSE3            (7 | (5 << 8))

// gMapGroup_IndoorLavenderTown
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_1F (0 | (6 << 8))
#define MAP_LAVENDER_TOWN_SCHOOL            (1 | (6 << 8))
#define MAP_LAVENDER_TOWN_FUJI_HOUSE        (2 | (6 << 8))
#define MAP_LAVENDER_TOWN_HOUSE1            (3 | (6 << 8))
#define MAP_LAVENDER_TOWN_HOUSE2            (4 | (6 << 8))
#define MAP_LAVENDER_TOWN_MART              (5 | (6 << 8))

// gMapGroup_IndoorCeladonCity
#define MAP_CELADON_CITY_SHOP_1F           (0 | (7 << 8))
#define MAP_CELADON_CITY_SHOP_2F           (1 | (7 << 8))
#define MAP_CELADON_CITY_SHOP_3F           (2 | (7 << 8))
#define MAP_CELADON_CITY_SHOP_4F           (3 | (7 << 8))
#define MAP_CELADON_CITY_SHOP_5F           (4 | (7 << 8))
#define MAP_CELADON_CITY_SHOP_6F           (5 | (7 << 8))
#define MAP_CELADON_CITY_SHOP_ELEVATOR     (6 | (7 << 8))
#define MAP_CELADON_CITY_HOUSE1_1F         (7 | (7 << 8))
#define MAP_CELADON_CITY_HOUSE1_2F         (8 | (7 << 8))
#define MAP_CELADON_CITY_HOUSE1_3F         (9 | (7 << 8))
#define MAP_CELADON_CITY_HOUSE1_4F         (10 | (7 << 8))
#define MAP_CELADON_CITY_SCHOOL            (11 | (7 << 8))
#define MAP_CELADON_CITY_POKEMON_CENTER_1F (12 | (7 << 8))
#define MAP_CELADON_CITY_SCHOOL2           (13 | (7 << 8))
#define MAP_CELADON_CITY_CASINO            (14 | (7 << 8))
#define MAP_CELADON_CITY_CASINO2           (15 | (7 << 8))
#define MAP_CELADON_CITY_GYM               (16 | (7 << 8))
#define MAP_CELADON_CITY_RESTAURANT        (17 | (7 << 8))
#define MAP_CELADON_CITY_HOUSE2            (18 | (7 << 8))
#define MAP_CELADON_CITY_HOTEL             (19 | (7 << 8))

// gMapGroup_IndoorSaffronCity
#define MAP_SAFFRON_CITY_HOUSE1_1F         (0 | (8 << 8))
#define MAP_SAFFRON_CITY_HOUSE1_2F         (1 | (8 << 8))
#define MAP_SAFFRON_CITY_DOJO              (2 | (8 << 8))
#define MAP_SAFFRON_CITY_GYM               (3 | (8 << 8))
#define MAP_SAFFRON_CITY_HOUSE2            (4 | (8 << 8))
#define MAP_SAFFRON_CITY_MART              (5 | (8 << 8))
#define MAP_SAFFRON_CITY_POKEMON_CENTER_1F (6 | (8 << 8))
#define MAP_SAFFRON_CITY_SCHOOL            (7 | (8 << 8))
#define MAP_SAFFRON_CITY_HOUSE3            (8 | (8 << 8))
#define MAP_SAFFRON_CITY_HOUSE4            (9 | (8 << 8))

// gMapGroup_IndoorFuchsiaCity
#define MAP_FUCHSIA_CITY_PATH              (0 | (9 << 8))
#define MAP_FUCHSIA_CITY_MART              (1 | (9 << 8))
#define MAP_FUCHSIA_CITY_HOUSE1            (2 | (9 << 8))
#define MAP_FUCHSIA_CITY_GYM               (3 | (9 << 8))
#define MAP_FUCHSIA_CITY_HOUSE2            (4 | (9 << 8))
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_1F (5 | (9 << 8))
#define MAP_FUCHSIA_CITY_SCHOOL            (6 | (9 << 8))
#define MAP_FUCHSIA_CITY_HOUSE3            (7 | (9 << 8))
#define MAP_FUCHSIA_CITY_HOUSE4            (8 | (9 << 8))
#define MAP_FUCHSIA_CITY_HOUSE5            (9 | (9 << 8))

// gMapGroup_IndoorCinnabarIsland
#define MAP_CINNABAR_ISLAND_GYM               (0 | (10 << 8))
#define MAP_CINNABAR_ISLAND_LABORATORY1       (1 | (10 << 8))
#define MAP_CINNABAR_ISLAND_HOUSE1            (2 | (10 << 8))
#define MAP_CINNABAR_ISLAND_LABORATORY2       (3 | (10 << 8))
#define MAP_CINNABAR_ISLAND_LABORATORY3       (4 | (10 << 8))
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F (5 | (10 << 8))
#define MAP_CINNABAR_ISLAND_SCHOOL            (6 | (10 << 8))
#define MAP_CINNABAR_ISLAND_MART              (7 | (10 << 8))

// gMapGroup_IndoorIndigoPlateau
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F (0 | (11 << 8))
#define MAP_INDIGO_PLATEAU_SCHOOL            (1 | (11 << 8))

// gMapGroup_IndoorOneIsland
#define MAP_ONE_ISLAND_POKEMON_CENTER_1F (0 | (12 << 8))
#define MAP_ONE_ISLAND_HOUSE1            (1 | (12 << 8))
#define MAP_ONE_ISLAND_HOUSE2            (2 | (12 << 8))
#define MAP_ONE_ISLAND_PORT              (3 | (12 << 8))

// gMapGroup_IndoorTwoIsland
#define MAP_TWO_ISLAND_HOUSE1            (0 | (13 << 8))
#define MAP_TWO_ISLAND_HOUSE2            (1 | (13 << 8))
#define MAP_TWO_ISLAND_POKEMON_CENTER_1F (2 | (13 << 8))
#define MAP_TWO_ISLAND_PORT              (3 | (13 << 8))

// gMapGroup_IndoorThreeIsland
#define MAP_THREE_ISLAND_HOUSE1            (0 | (14 << 8))
#define MAP_THREE_ISLAND_POKEMON_CENTER_1F (1 | (14 << 8))
#define MAP_THREE_ISLAND_MART              (2 | (14 << 8))
#define MAP_THREE_ISLAND_HOUSE2            (3 | (14 << 8))
#define MAP_THREE_ISLAND_HOUSE3            (4 | (14 << 8))
#define MAP_THREE_ISLAND_HOUSE4            (5 | (14 << 8))
#define MAP_THREE_ISLAND_HOUSE5            (6 | (14 << 8))

// gMapGroup_IndoorFourIsland
#define MAP_FOUR_ISLAND_DAYCARE           (0 | (15 << 8))
#define MAP_FOUR_ISLAND_POKEMON_CENTER_1F (1 | (15 << 8))
#define MAP_FOUR_ISLAND_HOUSE1            (2 | (15 << 8))
#define MAP_FOUR_ISLAND_HOUSE2            (3 | (15 << 8))
#define MAP_FOUR_ISLAND_PORT              (4 | (15 << 8))
#define MAP_FOUR_ISLAND_HOUSE3            (5 | (15 << 8))
#define MAP_FOUR_ISLAND_MART              (6 | (15 << 8))

// gMapGroup_IndoorFiveIsland
#define MAP_FIVE_ISLAND_POKEMON_CENTER_1F (0 | (16 << 8))
#define MAP_FIVE_ISLAND_PORT              (1 | (16 << 8))
#define MAP_FIVE_ISLAND_HOUSE1            (2 | (16 << 8))
#define MAP_FIVE_ISLAND_HOUSE2            (3 | (16 << 8))

// gMapGroup_IndoorSixIsland
#define MAP_SIX_ISLAND_POKEMON_CENTER_1F (0 | (17 << 8))
#define MAP_SIX_ISLAND_PORT              (1 | (17 << 8))
#define MAP_SIX_ISLAND_HOUSE1            (2 | (17 << 8))
#define MAP_SIX_ISLAND_HOUSE2            (3 | (17 << 8))

// gMapGroup_IndoorSevenIsland
#define MAP_SEVEN_ISLAND_HOUSE1            (0 | (18 << 8))
#define MAP_SEVEN_ISLAND_MART              (1 | (18 << 8))
#define MAP_SEVEN_ISLAND_POKEMON_CENTER_1F (2 | (18 << 8))
#define MAP_NEW_MAP3                       (3 | (18 << 8))
#define MAP_SEVEN_ISLAND_PORT              (4 | (18 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (19 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (19 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (20 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (20 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (20 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (20 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (20 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (21 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (21 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (21 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (21 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (21 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (21 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (22 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (22 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (23 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (23 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (23 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (23 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (23 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (23 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (23 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (23 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (24 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (24 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (24 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (24 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (24 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (24 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (24 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (24 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (24 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (25 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (25 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (26 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (26 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (26 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (26 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (26 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (26 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (26 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (27 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (27 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (27 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (27 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (27 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (27 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (27 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (27 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (27 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (27 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (27 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (27 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (27 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (27 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (28 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (28 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (28 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (28 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (28 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (28 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (28 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (28 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (29 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (29 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (29 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (29 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (29 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (29 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (29 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (29 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (29 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (29 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (29 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (29 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (29 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (30 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (30 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (30 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (30 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (30 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (30 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (30 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (31 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (31 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (31 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (31 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (31 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (31 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (31 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (31 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (31 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (31 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (31 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (31 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (31 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (31 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (32 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (32 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (32 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (32 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (32 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (32 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (32 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (32 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (32 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (32 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (33 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (33 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (34 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (34 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (35 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (35 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (36 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (36 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (37 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (37 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (38 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (38 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (38 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (39 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (40 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (41 << 8))

// gMapGroup_IndoorRoute2

// gMapGroup_IndoorRoute4

// gMapGroup_IndoorRoute5

// gMapGroup_IndoorRoute6

// gMapGroup_IndoorRoute7

// gMapGroup_IndoorRoute8

// gMapGroup_IndoorRoute10

// gMapGroup_IndoorRoute11

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (50 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (50 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (50 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (50 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (50 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (50 << 8))
#define MAP_DESERT_RUINS                             (6 | (50 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (50 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (50 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (50 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (50 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (50 << 8))
#define MAP_MT_CHIMNEY                               (12 | (50 << 8))
#define MAP_JAGGED_PASS                              (13 | (50 << 8))
#define MAP_FIERY_PATH                               (14 | (50 << 8))
#define MAP_MT_PYRE_1F                               (15 | (50 << 8))
#define MAP_MT_PYRE_2F                               (16 | (50 << 8))
#define MAP_MT_PYRE_3F                               (17 | (50 << 8))
#define MAP_MT_PYRE_4F                               (18 | (50 << 8))
#define MAP_MT_PYRE_5F                               (19 | (50 << 8))
#define MAP_MT_PYRE_6F                               (20 | (50 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (50 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (50 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (50 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (50 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (50 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (50 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (50 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (50 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (50 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (50 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (50 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (50 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (50 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (50 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (50 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (50 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (50 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (50 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (50 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (50 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (50 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (50 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (50 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (50 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (50 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (50 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (50 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (50 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (50 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (50 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (50 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (50 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (50 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (50 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (50 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (50 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (50 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (50 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (50 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (50 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (50 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (50 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (50 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (50 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (50 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (50 << 8))
#define MAP_ISLAND_CAVE                              (67 | (50 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (50 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (50 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (50 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (50 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (50 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (50 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (50 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (50 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (50 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (50 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (50 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (50 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (50 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (50 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (50 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (50 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (50 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (50 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (50 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (50 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (50 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (50 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (50 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (50 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (50 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (50 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (50 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (50 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (50 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (50 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (50 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (50 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (50 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (50 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (50 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (50 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (50 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (50 << 8))
#define MAP_ALTERING_CAVE                            (106 | (50 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (50 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (51 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (51 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (51 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (51 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (51 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (51 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (51 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (51 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (51 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (51 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (51 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (51 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (51 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (51 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (51 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (51 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (51 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (51 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (51 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (51 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (51 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (51 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (51 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (51 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (51 << 8))
#define MAP_TRADE_CENTER             (25 | (51 << 8))
#define MAP_RECORD_CORNER            (26 | (51 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (51 << 8))
#define MAP_CONTEST_HALL             (28 | (51 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (51 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (51 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (51 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (51 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (51 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (51 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (51 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (51 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (51 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (51 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (51 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (51 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (51 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (51 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (51 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (51 << 8))
#define MAP_UNION_ROOM               (60 | (51 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (52 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (52 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (52 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (52 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (52 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (52 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (52 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (52 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (52 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (52 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (52 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (52 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (52 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (52 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (52 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (52 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (52 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (52 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (52 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (52 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (52 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (52 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (52 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (52 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (52 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (52 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (52 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (52 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (52 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (52 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (52 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (52 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (52 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (52 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (52 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (52 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (52 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (52 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (52 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (52 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (52 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (52 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (52 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (52 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (52 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (52 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (52 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (52 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (52 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (52 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (52 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (53 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (53 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (54 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (55 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (55 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (55 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (55 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (55 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (55 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (55 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (55 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (55 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (55 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (55 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (55 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (55 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (56 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (57 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (58 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (58 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (58 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (59 << 8))

#define MAP_GROUPS_COUNT 60

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
