#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_ANDRA_1                       2
#define TRAINER_CONSUL                        3
#define TRAINER_ANDRA_2                       4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_MEGAPUNO                      6
#define TRAINER_MEGAPATADA                    7
#define TRAINER_ROJO_1                        8
#define TRAINER_ALTORANGO                     9
#define TRAINER_GRUNT_PETALBURG_WOODS        10
#define TRAINER_MARCEL                       11
#define TRAINER_ALBERTO                      12
#define TRAINER_BILL_1                       13
#define TRAINER_ANDRA_3                      14
#define TRAINER_DOMADOR                      15
#define TRAINER_GURU                         16
#define TRAINER_VERO                         17
#define TRAINER_CMIGUEL_1                    18
#define TRAINER_FUJI_1                       19
#define TRAINER_GHOST                        20
#define TRAINER_GRUNT_MUSEUM_2               21
#define TRAINER_GRUNT_SPACE_CENTER_1         22
#define TRAINER_GRUNT_MT_PYRE_1              23
#define TRAINER_GRUNT_MT_PYRE_2              24
#define TRAINER_GRUNT_MT_PYRE_3              25
#define TRAINER_GRUNT_WEATHER_INST_4         26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         27
#define TRAINER_ANDRA_4                      28
#define TRAINER_CMIGUEL_2                    29
#define TRAINER_VERO_2                       30
#define TRAINER_ZANDER                       31
#define TRAINER_DALIA                        32
#define TRAINER_LUGIA                        33
#define TRAINER_SURGE_1                      34
#define TRAINER_LEAH                         35
#define TRAINER_DAISY                        36
#define TRAINER_ROSE_1                       37
#define TRAINER_ATLAS_2                      38
#define TRAINER_VIOLET                       39
#define TRAINER_ROSE_2                       40
#define TRAINER_ROSE_3                       41
#define TRAINER_ROSE_4                       42
#define TRAINER_ROSE_5                       43
#define TRAINER_BRUNO_1                      44
#define TRAINER_ZAPDOS                       45
#define TRAINER_ARTICUNO                     46
#define TRAINER_ANDRA_5                      47
#define TRAINER_BILL_2                       48
#define TRAINER_SILPH                        49
#define TRAINER_OAK_1                        50
#define TRAINER_BLAINE_2                     51
#define TRAINER_MIRTO                        52
#define TRAINER_VUELO                        53
#define TRAINER_TERREMOTO                    54
#define TRAINER_LUPA                         55
#define TRAINER_CASCO                        56
#define TRAINER_PANUELO                      57
#define TRAINER_CONTADOR                     58
#define TRAINER_ANDRA_7                      59
#define TRAINER_LOLA_2                       60
#define TRAINER_LOLA_3                       61
#define TRAINER_LOLA_4                       62
#define TRAINER_LOLA_5                       63
#define TRAINER_RICKY_1                      64
#define TRAINER_SIMON                        65
#define TRAINER_CHARLIE                      66
#define TRAINER_CMIGUEL_3                    67
#define TRAINER_RICKY_3                      68
#define TRAINER_RICKY_4                      69
#define TRAINER_RICKY_5                      70
#define TRAINER_RANDALL                      71
#define TRAINER_AQUILES                      72
#define TRAINER_MAGNO                        73
#define TRAINER_PEGASO                       74
#define TRAINER_CESAR                        75
#define TRAINER_SALAZAR                      76
#define TRAINER_ANIBAL                       77
#define TRAINER_JADEN                        78
#define TRAINER_FREDO                        79
#define TRAINER_CROM                         80
#define TRAINER_VALERIA                      81
#define TRAINER_ZEUS_1                       82
#define TRAINER_ZEUS_2                       83
#define TRAINER_ZEUS_3                       84
#define TRAINER_MAGMAADMIN                   85
#define TRAINER_AQUAADMIN                    86
#define TRAINER_GIOVANNI_1                   87
#define TRAINER_CULTISTA                     88
#define TRAINER_MARY                         89
#define TRAINER_ALEXIA                       90
#define TRAINER_JODY                         91
#define TRAINER_WENDY                        92
#define TRAINER_KEIRA                        93
#define TRAINER_BROOKE_1                     94
#define TRAINER_JENNIFER                     95
#define TRAINER_HOPE                         96
#define TRAINER_SHANNON                      97
#define TRAINER_MICHELLE                     98
#define TRAINER_CAROLINE                     99
#define TRAINER_JULIE                       100
#define TRAINER_BROOKE_2                    101
#define TRAINER_BROOKE_3                    102
#define TRAINER_BROOKE_4                    103
#define TRAINER_BROOKE_5                    104
#define TRAINER_PATRICIA                    105
#define TRAINER_KINDRA                      106
#define TRAINER_TAMMY                       107
#define TRAINER_VALERIE_1                   108
#define TRAINER_TASHA                       109
#define TRAINER_VALERIE_2                   110
#define TRAINER_VALERIE_3                   111
#define TRAINER_VALERIE_4                   112
#define TRAINER_VALERIE_5                   113
#define TRAINER_CINDY_1                     114
#define TRAINER_DAPHNE                      115
#define TRAINER_GRUNT_SPACE_CENTER_2        116
#define TRAINER_CINDY_2                     117
#define TRAINER_BRIANNA                     118
#define TRAINER_NAOMI                       119
#define TRAINER_CINDY_3                     120
#define TRAINER_CINDY_4                     121
#define TRAINER_CINDY_5                     122
#define TRAINER_CINDY_6                     123
#define TRAINER_MELISSA                     124
#define TRAINER_SHEILA                      125
#define TRAINER_SHIRLEY                     126
#define TRAINER_JESSICA_1                   127
#define TRAINER_CONNIE                      128
#define TRAINER_BRIDGET                     129
#define TRAINER_OLIVIA                      130
#define TRAINER_TIFFANY                     131
#define TRAINER_JESSICA_2                   132
#define TRAINER_JESSICA_3                   133
#define TRAINER_JESSICA_4                   134
#define TRAINER_JESSICA_5                   135
#define TRAINER_WINSTON_1                   136
#define TRAINER_MOLLIE                      137
#define TRAINER_GARRET                      138
#define TRAINER_WINSTON_2                   139
#define TRAINER_WINSTON_3                   140
#define TRAINER_WINSTON_4                   141
#define TRAINER_WINSTON_5                   142
#define TRAINER_STEVE_1                     143
#define TRAINER_THALIA_1                    144
#define TRAINER_MARK                        145
#define TRAINER_GRUNT_MT_CHIMNEY_1          146
#define TRAINER_STEVE_2                     147
#define TRAINER_STEVE_3                     148
#define TRAINER_STEVE_4                     149
#define TRAINER_STEVE_5                     150
#define TRAINER_LUIS                        151
#define TRAINER_DOMINIK                     152
#define TRAINER_DOUGLAS                     153
#define TRAINER_DARRIN                      154
#define TRAINER_TONY_1                      155
#define TRAINER_JEROME                      156
#define TRAINER_MATTHEW                     157
#define TRAINER_DAVID                       158
#define TRAINER_SPENCER                     159
#define TRAINER_ROLAND                      160
#define TRAINER_NOLEN                       161
#define TRAINER_STAN                        162
#define TRAINER_BARRY                       163
#define TRAINER_DEAN                        164
#define TRAINER_RODNEY                      165
#define TRAINER_RICHARD                     166
#define TRAINER_HERMAN                      167
#define TRAINER_SANTIAGO                    168
#define TRAINER_GILBERT                     169
#define TRAINER_FRANKLIN                    170
#define TRAINER_KEVIN                       171
#define TRAINER_JACK                        172
#define TRAINER_DUDLEY                      173
#define TRAINER_CHAD                        174
#define TRAINER_TONY_2                      175
#define TRAINER_TONY_3                      176
#define TRAINER_TONY_4                      177
#define TRAINER_TONY_5                      178
#define TRAINER_TAKAO                       179
#define TRAINER_HITOSHI                     180
#define TRAINER_KIYO                        181
#define TRAINER_KOICHI                      182
#define TRAINER_NOB_1                       183
#define TRAINER_NOB_2                       184
#define TRAINER_NOB_3                       185
#define TRAINER_NOB_4                       186
#define TRAINER_NOB_5                       187
#define TRAINER_YUJI                        188
#define TRAINER_DAISUKE                     189
#define TRAINER_ATSUSHI                     190
#define TRAINER_KIRK                        191
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        192
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        193
#define TRAINER_SHAWN                       194
#define TRAINER_FERNANDO_1                  195
#define TRAINER_DALTON_1                    196
#define TRAINER_DALTON_2                    197
#define TRAINER_DALTON_3                    198
#define TRAINER_DALTON_4                    199
#define TRAINER_DALTON_5                    200
#define TRAINER_COLE                        201
#define TRAINER_JEFF                        202
#define TRAINER_AXLE                        203
#define TRAINER_JACE                        204
#define TRAINER_KEEGAN                      205
#define TRAINER_BERNIE_1                    206
#define TRAINER_BERNIE_2                    207
#define TRAINER_BERNIE_3                    208
#define TRAINER_BERNIE_4                    209
#define TRAINER_BERNIE_5                    210
#define TRAINER_DREW                        211
#define TRAINER_BEAU                        212
#define TRAINER_LARRY                       213
#define TRAINER_SHANE                       214
#define TRAINER_JUSTIN                      215
#define TRAINER_ETHAN_1                     216
#define TRAINER_AUTUMN                      217
#define TRAINER_TRAVIS                      218
#define TRAINER_ETHAN_2                     219
#define TRAINER_ETHAN_3                     220
#define TRAINER_ETHAN_4                     221
#define TRAINER_ETHAN_5                     222
#define TRAINER_BRENT                       223
#define TRAINER_DONALD                      224
#define TRAINER_TAYLOR                      225
#define TRAINER_JEFFREY_1                   226
#define TRAINER_DEREK                       227
#define TRAINER_JEFFREY_2                   228
#define TRAINER_JEFFREY_3                   229
#define TRAINER_JEFFREY_4                   230
#define TRAINER_JEFFREY_5                   231
#define TRAINER_EDWARD                      232
#define TRAINER_PRESTON                     233
#define TRAINER_VIRGIL                      234
#define TRAINER_BLAKE                       235
#define TRAINER_WILLIAM                     236
#define TRAINER_JOSHUA                      237
#define TRAINER_CAMERON_1                   238
#define TRAINER_CAMERON_2                   239
#define TRAINER_CAMERON_3                   240
#define TRAINER_CAMERON_4                   241
#define TRAINER_CAMERON_5                   242
#define TRAINER_JACLYN                      243
#define TRAINER_HANNAH                      244
#define TRAINER_SAMANTHA                    245
#define TRAINER_MAURA                       246
#define TRAINER_KAYLA                       247
#define TRAINER_ALEXIS                      248
#define TRAINER_JACKI_1                     249
#define TRAINER_JACKI_2                     250
#define TRAINER_JACKI_3                     251
#define TRAINER_JACKI_4                     252
#define TRAINER_JACKI_5                     253
#define TRAINER_WALTER_1                    254
#define TRAINER_MICAH                       255
#define TRAINER_THOMAS                      256
#define TRAINER_WALTER_2                    257
#define TRAINER_WALTER_3                    258
#define TRAINER_WALTER_4                    259
#define TRAINER_WALTER_5                    260
#define TRAINER_SIDNEY                      261
#define TRAINER_PHOEBE                      262
#define TRAINER_GLACIA                      263
#define TRAINER_DRAKE                       264
#define TRAINER_ROXANNE_1                   265
#define TRAINER_BRAWLY_1                    266
#define TRAINER_WATTSON_1                   267
#define TRAINER_FLANNERY_1                  268
#define TRAINER_NORMAN_1                    269
#define TRAINER_WINONA_1                    270
#define TRAINER_TATE_AND_LIZA_1             271
#define TRAINER_JUAN_1                      272
#define TRAINER_JERRY_1                     273
#define TRAINER_TED                         274
#define TRAINER_PAUL                        275
#define TRAINER_JERRY_2                     276
#define TRAINER_JERRY_3                     277
#define TRAINER_JERRY_4                     278
#define TRAINER_JERRY_5                     279
#define TRAINER_KAREN_1                     280
#define TRAINER_GEORGIA                     281
#define TRAINER_KAREN_2                     282
#define TRAINER_KAREN_3                     283
#define TRAINER_KAREN_4                     284
#define TRAINER_KAREN_5                     285
#define TRAINER_KATE_AND_JOY                286
#define TRAINER_ANNA_AND_MEG_1              287
#define TRAINER_ANNA_AND_MEG_2              288
#define TRAINER_ANNA_AND_MEG_3              289
#define TRAINER_ANNA_AND_MEG_4              290
#define TRAINER_ANNA_AND_MEG_5              291
#define TRAINER_VICTOR                      292
#define TRAINER_MIGUEL_1                    293
#define TRAINER_COLTON                      294
#define TRAINER_MIGUEL_2                    295
#define TRAINER_MIGUEL_3                    296
#define TRAINER_MIGUEL_4                    297
#define TRAINER_MIGUEL_5                    298
#define TRAINER_VICTORIA                    299
#define TRAINER_VANESSA                     300
#define TRAINER_BETHANY                     301
#define TRAINER_ISABEL_1                    302
#define TRAINER_ISABEL_2                    303
#define TRAINER_ISABEL_3                    304
#define TRAINER_ISABEL_4                    305
#define TRAINER_ISABEL_5                    306
#define TRAINER_TIMOTHY_1                   307
#define TRAINER_TIMOTHY_2                   308
#define TRAINER_TIMOTHY_3                   309
#define TRAINER_TIMOTHY_4                   310
#define TRAINER_TIMOTHY_5                   311
#define TRAINER_VICKY                       312
#define TRAINER_SHELBY_1                    313
#define TRAINER_SHELBY_2                    314
#define TRAINER_SHELBY_3                    315
#define TRAINER_SHELBY_4                    316
#define TRAINER_SHELBY_5                    317
#define TRAINER_CALVIN_1                    318
#define TRAINER_BILLY                       319
#define TRAINER_JOSH                        320
#define TRAINER_TOMMY                       321
#define TRAINER_JOEY                        322
#define TRAINER_BEN                         323
#define TRAINER_QUINCY                      324
#define TRAINER_KATELYNN                    325
#define TRAINER_JAYLEN                      326
#define TRAINER_AZUL_2                      327
#define TRAINER_CALVIN_2                    328
#define TRAINER_CINTAELEGIDA                329
#define TRAINER_ROCAAFILADA                 330
#define TRAINER_GAFASELEGIDAS               331
#define TRAINER_LLAMASFERA                  332
#define TRAINER_CINTAEXPERTO                333
#define TRAINER_CHALECOASALTO               334
#define TRAINER_WALLACE                     335
#define TRAINER_ANDREW                      336
#define TRAINER_IVAN                        337
#define TRAINER_CLAUDE                      338
#define TRAINER_ELLIOT_1                    339
#define TRAINER_NED                         340
#define TRAINER_DALE                        341
#define TRAINER_NOLAN                       342
#define TRAINER_BARNY                       343
#define TRAINER_WADE                        344
#define TRAINER_CARTER                      345
#define TRAINER_ELLIOT_2                    346
#define TRAINER_ELLIOT_3                    347
#define TRAINER_ELLIOT_4                    348
#define TRAINER_ELLIOT_5                    349
#define TRAINER_RONALD                      350
#define TRAINER_JACOB                       351
#define TRAINER_ANTHONY                     352
#define TRAINER_BENJAMIN_1                  353
#define TRAINER_BENJAMIN_2                  354
#define TRAINER_BENJAMIN_3                  355
#define TRAINER_BENJAMIN_4                  356
#define TRAINER_BENJAMIN_5                  357
#define TRAINER_ABIGAIL_1                   358
#define TRAINER_JASMINE                     359
#define TRAINER_ABIGAIL_2                   360
#define TRAINER_ABIGAIL_3                   361
#define TRAINER_ABIGAIL_4                   362
#define TRAINER_ABIGAIL_5                   363
#define TRAINER_PROTON                      364
#define TRAINER_PETREL                      365
#define TRAINER_ANDRA_6                     366
#define TRAINER_AZUL_3                      367
#define TRAINER_DYLAN_5                     368
#define TRAINER_MARIA_1                     369
#define TRAINER_MARIA_2                     370
#define TRAINER_MARIA_3                     371
#define TRAINER_MARIA_4                     372
#define TRAINER_MARIA_5                     373
#define TRAINER_CAMDEN                      374
#define TRAINER_DEMETRIUS                   375
#define TRAINER_ISAIAH_1                    376
#define TRAINER_PABLO_1                     377
#define TRAINER_CHASE                       378
#define TRAINER_ISAIAH_2                    379
#define TRAINER_ISAIAH_3                    380
#define TRAINER_ISAIAH_4                    381
#define TRAINER_ISAIAH_5                    382
#define TRAINER_ISOBEL                      383
#define TRAINER_DONNY                       384
#define TRAINER_TALIA                       385
#define TRAINER_KATELYN_1                   386
#define TRAINER_ALLISON                     387
#define TRAINER_KATELYN_2                   388
#define TRAINER_KATELYN_3                   389
#define TRAINER_KATELYN_4                   390
#define TRAINER_KATELYN_5                   391
#define TRAINER_NICOLAS_1                   392
#define TRAINER_NICOLAS_2                   393
#define TRAINER_NICOLAS_3                   394
#define TRAINER_NICOLAS_4                   395
#define TRAINER_NICOLAS_5                   396
#define TRAINER_AARON                       397
#define TRAINER_PERRY                       398
#define TRAINER_HUGH                        399
#define TRAINER_PHIL                        400
#define TRAINER_JARED                       401
#define TRAINER_HUMBERTO                    402
#define TRAINER_PRESLEY                     403
#define TRAINER_EDWARDO                     404
#define TRAINER_COLIN                       405
#define TRAINER_ROBERT_1                    406
#define TRAINER_BENNY                       407
#define TRAINER_CHESTER                     408
#define TRAINER_ROBERT_2                    409
#define TRAINER_ROBERT_3                    410
#define TRAINER_ANDRA_9                     411
#define TRAINER_BRUNO_2                     412
#define TRAINER_AGATHA                      413
#define TRAINER_LANCE_1                     414
#define TRAINER_BROCK                       415
#define TRAINER_MISTY                       416
#define TRAINER_SURGE_2                     417
#define TRAINER_ERIKA                       418
#define TRAINER_KOGA                        419
#define TRAINER_BLAINE_1                    420
#define TRAINER_SABRINA                     421
#define TRAINER_LAO_3                       422
#define TRAINER_LAO_4                       423
#define TRAINER_LAO_5                       424
#define TRAINER_JOCELYN                     425
#define TRAINER_LAURA                       426
#define TRAINER_AZUL_1                      427
#define TRAINER_CAPITAN_1                   428
#define TRAINER_SAFARI                      429
#define TRAINER_AYUDANTE_1                  430
#define TRAINER_AYUDANTE_2                  431
#define TRAINER_AYUDANTE_3                  432
#define TRAINER_AYUDANTE_4                  433
#define TRAINER_AYUDANTE_5                  434
#define TRAINER_CLUBFANS                    435
#define TRAINER_BONOBICI                    436
#define TRAINER_GUARDA                      437
#define TRAINER_ATLAS_1                     438
#define TRAINER_ANDRA_8                     439
#define TRAINER_BILL_3                      440
#define TRAINER_CULTO_1                     441
#define TRAINER_IMANI                       442
#define TRAINER_KYLA                        443
#define TRAINER_DENISE                      444
#define TRAINER_BETH                        445
#define TRAINER_TARA                        446
#define TRAINER_MISSY                       447
#define TRAINER_ALICE                       448
#define TRAINER_JENNY_1                     449
#define TRAINER_GRACE                       450
#define TRAINER_TANYA                       451
#define TRAINER_SHARON                      452
#define TRAINER_NIKKI                       453
#define TRAINER_BRENDA                      454
#define TRAINER_KATIE                       455
#define TRAINER_SUSIE                       456
#define TRAINER_KARA                        457
#define TRAINER_DANA                        458
#define TRAINER_SIENNA                      459
#define TRAINER_DEBRA                       460
#define TRAINER_LINDA                       461
#define TRAINER_KAYLEE                      462
#define TRAINER_LAUREL                      463
#define TRAINER_CARLEE                      464
#define TRAINER_JENNY_2                     465
#define TRAINER_JENNY_3                     466
#define TRAINER_JENNY_4                     467
#define TRAINER_JENNY_5                     468
#define TRAINER_HEIDI                       469
#define TRAINER_BECKY                       470
#define TRAINER_CAROL                       471
#define TRAINER_NANCY                       472
#define TRAINER_MARTHA                      473
#define TRAINER_DIANA_1                     474
#define TRAINER_CEDRIC                      475
#define TRAINER_IRENE                       476
#define TRAINER_DIANA_2                     477
#define TRAINER_DIANA_3                     478
#define TRAINER_DIANA_4                     479
#define TRAINER_DIANA_5                     480
#define TRAINER_AMY_AND_LIV_1               481
#define TRAINER_AMY_AND_LIV_2               482
#define TRAINER_GINA_AND_MIA_1              483
#define TRAINER_MIU_AND_YUKI                484
#define TRAINER_AMY_AND_LIV_3               485
#define TRAINER_GINA_AND_MIA_2              486
#define TRAINER_AMY_AND_LIV_4               487
#define TRAINER_AMY_AND_LIV_5               488
#define TRAINER_AMY_AND_LIV_6               489
#define TRAINER_HUEY                        490
#define TRAINER_EDMOND                      491
#define TRAINER_ERNEST_1                    492
#define TRAINER_ENTRENAMIENTO_1             493
#define TRAINER_ENTRENAMIENTO_2             494
#define TRAINER_ENTRENAMIENTO_3             495
#define TRAINER_ENTRENAMIENTO_4             496
#define TRAINER_ENTRENAMIENTO_5             497
#define TRAINER_ENTRENAMIENTO_6             498
#define TRAINER_ENTRENAMIENTO_7             499
#define TRAINER_ERNEST_5                    500
#define TRAINER_ELI                         501
#define TRAINER_ANNIKA                      502
#define TRAINER_JAZMYN                      503
#define TRAINER_JONAS                       504
#define TRAINER_KAYLEY                      505
#define TRAINER_AURON                       506
#define TRAINER_KELVIN                      507
#define TRAINER_MARLEY                      508
#define TRAINER_REYNA                       509
#define TRAINER_HUDSON                      510
#define TRAINER_CONOR                       511
#define TRAINER_EDWIN_1                     512
#define TRAINER_HECTOR                      513
#define TRAINER_AZUL_4                      514
#define TRAINER_EDWIN_2                     515
#define TRAINER_EDWIN_3                     516
#define TRAINER_EDWIN_4                     517
#define TRAINER_EDWIN_5                     518
#define TRAINER_WALLY_VR_1                  519
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    520
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    521
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    522
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   523
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   524
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   526
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   527
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   528
#define TRAINER_MAY_ROUTE_103_MUDKIP        529
#define TRAINER_MAY_ROUTE_110_MUDKIP        530
#define TRAINER_MAY_ROUTE_119_MUDKIP        531
#define TRAINER_MAY_ROUTE_103_TREECKO       532
#define TRAINER_MAY_ROUTE_110_TREECKO       533
#define TRAINER_MAY_ROUTE_119_TREECKO       534
#define TRAINER_MAY_ROUTE_103_TORCHIC       535
#define TRAINER_MAY_ROUTE_110_TORCHIC       536
#define TRAINER_MAY_ROUTE_119_TORCHIC       537
#define TRAINER_ISAAC_1                     538
#define TRAINER_DAVIS                       539
#define TRAINER_MITCHELL                    540
#define TRAINER_ISAAC_2                     541
#define TRAINER_ISAAC_3                     542
#define TRAINER_ISAAC_4                     543
#define TRAINER_ISAAC_5                     544
#define TRAINER_LYDIA_1                     545
#define TRAINER_HALLE                       546
#define TRAINER_GARRISON                    547
#define TRAINER_LYDIA_2                     548
#define TRAINER_LYDIA_3                     549
#define TRAINER_LYDIA_4                     550
#define TRAINER_LYDIA_5                     551
#define TRAINER_JACKSON_1                   552
#define TRAINER_LORENZO                     553
#define TRAINER_SEBASTIAN                   554
#define TRAINER_JACKSON_2                   555
#define TRAINER_JACKSON_3                   556
#define TRAINER_JACKSON_4                   557
#define TRAINER_JACKSON_5                   558
#define TRAINER_CATHERINE_1                 559
#define TRAINER_JENNA                       560
#define TRAINER_SOPHIA                      561
#define TRAINER_CATHERINE_2                 562
#define TRAINER_CATHERINE_3                 563
#define TRAINER_CATHERINE_4                 564
#define TRAINER_CATHERINE_5                 565
#define TRAINER_JULIO                       566
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     567
#define TRAINER_GRUNT_UNUSED                568
#define TRAINER_GRUNT_MT_PYRE_4             569
#define TRAINER_GRUNT_JAGGED_PASS           570
#define TRAINER_MARC                        571
#define TRAINER_BRENDEN                     572
#define TRAINER_LILITH                      573
#define TRAINER_CRISTIAN                    574
#define TRAINER_SYLVIA                      575
#define TRAINER_LEONARDO                    576
#define TRAINER_ATHENA                      577
#define TRAINER_HARRISON                    578
#define TRAINER_GRUNT_MT_CHIMNEY_2          579
#define TRAINER_CLARENCE                    580
#define TRAINER_TERRY                       581
#define TRAINER_NATE                        582
#define TRAINER_KATHLEEN                    583
#define TRAINER_CLIFFORD                    584
#define TRAINER_NICHOLAS                    585
#define TRAINER_GRUNT_SPACE_CENTER_3        586
#define TRAINER_GRUNT_SPACE_CENTER_4        587
#define TRAINER_GRUNT_SPACE_CENTER_5        588
#define TRAINER_GRUNT_SPACE_CENTER_6        589
#define TRAINER_GRUNT_SPACE_CENTER_7        590
#define TRAINER_MACEY                       591
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    592
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     593
#define TRAINER_PAXTON                      594
#define TRAINER_ISABELLA                    595
#define TRAINER_GRUNT_WEATHER_INST_5        596
#define TRAINER_BRUNO_1_MT_CHIMNEY          597
#define TRAINER_JONATHAN                    598
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    599
#define TRAINER_MAY_RUSTBORO_MUDKIP         600
#define TRAINER_MAXIE_MAGMA_HIDEOUT         601
#define TRAINER_MAXIE_MT_CHIMNEY            602
#define TRAINER_TIANA                       603
#define TRAINER_HALEY_1                     604
#define TRAINER_JANICE                      605
#define TRAINER_VIVI                        606
#define TRAINER_HALEY_2                     607
#define TRAINER_HALEY_3                     608
#define TRAINER_HALEY_4                     609
#define TRAINER_HALEY_5                     610
#define TRAINER_SALLY                       611
#define TRAINER_ROBIN                       612
#define TRAINER_ANDREA                      613
#define TRAINER_CRISSY                      614
#define TRAINER_RICK                        615
#define TRAINER_LYLE                        616
#define TRAINER_JOSE                        617
#define TRAINER_DOUG                        618
#define TRAINER_GREG                        619
#define TRAINER_KENT                        620
#define TRAINER_JAMES_1                     621
#define TRAINER_JAMES_2                     622
#define TRAINER_JAMES_3                     623
#define TRAINER_JAMES_4                     624
#define TRAINER_JAMES_5                     625
#define TRAINER_BRICE                       626
#define TRAINER_TRENT_1                     627
#define TRAINER_LENNY                       628
#define TRAINER_LUCAS_1                     629
#define TRAINER_ALAN                        630
#define TRAINER_CLARK                       631
#define TRAINER_ERIC                        632
#define TRAINER_LUCAS_2                     633
#define TRAINER_MAESTRO_BELLSPROUT          634
#define TRAINER_MIKE_2                      635
#define TRAINER_TRENT_2                     636
#define TRAINER_TRENT_3                     637
#define TRAINER_TRENT_4                     638
#define TRAINER_TRENT_5                     639
#define TRAINER_DEZ_AND_LUKE                640
#define TRAINER_LEA_AND_JED                 641
#define TRAINER_KIRA_AND_DAN_1              642
#define TRAINER_KIRA_AND_DAN_2              643
#define TRAINER_KIRA_AND_DAN_3              644
#define TRAINER_KIRA_AND_DAN_4              645
#define TRAINER_KIRA_AND_DAN_5              646
#define TRAINER_JOHANNA                     647
#define TRAINER_GERALD                      648
#define TRAINER_VIVIAN                      649
#define TRAINER_DANIELLE                    650
#define TRAINER_HIDEO                       651
#define TRAINER_KEIGO                       652
#define TRAINER_RILEY                       653
#define TRAINER_FLINT                       654
#define TRAINER_ASHLEY                      655
#define TRAINER_WALLY_MAUVILLE              656
#define TRAINER_WALLY_VR_2                  657
#define TRAINER_WALLY_VR_3                  658
#define TRAINER_WALLY_VR_4                  659
#define TRAINER_WALLY_VR_5                  660
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     661
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    662
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    663
#define TRAINER_MAY_LILYCOVE_MUDKIP         664
#define TRAINER_MAY_LILYCOVE_TREECKO        665
#define TRAINER_MAY_LILYCOVE_TORCHIC        666
#define TRAINER_JONAH                       667
#define TRAINER_HENRY                       668
#define TRAINER_ROGER                       669
#define TRAINER_ALEXA                       670
#define TRAINER_RUBEN                       671
#define TRAINER_KOJI_1                      672
#define TRAINER_WAYNE                       673
#define TRAINER_AIDAN                       674
#define TRAINER_REED                        675
#define TRAINER_TISHA                       676
#define TRAINER_TORI_AND_TIA                677
#define TRAINER_KIM_AND_IRIS                678
#define TRAINER_TYRA_AND_IVY                679
#define TRAINER_MEL_AND_PAUL                680
#define TRAINER_JOHN_AND_JAY_1              681
#define TRAINER_JOHN_AND_JAY_2              682
#define TRAINER_JOHN_AND_JAY_3              683
#define TRAINER_JOHN_AND_JAY_4              684
#define TRAINER_JOHN_AND_JAY_5              685
#define TRAINER_RELI_AND_IAN                686
#define TRAINER_LILA_AND_ROY_1              687
#define TRAINER_LILA_AND_ROY_2              688
#define TRAINER_LILA_AND_ROY_3              689
#define TRAINER_SLOWBRO                     690
#define TRAINER_LILA_AND_ROY_5              691
#define TRAINER_LISA_AND_RAY                692
#define TRAINER_CHRIS                       693
#define TRAINER_DAWSON                      694
#define TRAINER_SARAH                       695
#define TRAINER_DARIAN                      696
#define TRAINER_HAILEY                      697
#define TRAINER_CHANDLER                    698
#define TRAINER_KALEB                       699
#define TRAINER_JOSEPH                      700
#define TRAINER_ALYSSA                      701
#define TRAINER_MARCOS                      702
#define TRAINER_RHETT                       703
#define TRAINER_TYRON                       704
#define TRAINER_CELINA                      705
#define TRAINER_BIANCA                      706
#define TRAINER_HAYDEN                      707
#define TRAINER_SOPHIE                      708
#define TRAINER_COBY                        709
#define TRAINER_LAWRENCE                    710
#define TRAINER_WYATT                       711
#define TRAINER_ANGELINA                    712
#define TRAINER_KAI                         713
#define TRAINER_CHARLOTTE                   714
#define TRAINER_DEANDRE                     715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      726
#define TRAINER_CAPITAN_2                   727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      731
#define TRAINER_ROJO_3                      732
#define TRAINER_ELM                         733
#define TRAINER_MAXIE_MOSSDEEP              734
#define TRAINER_PETE                        735
#define TRAINER_ISABELLE                    736
#define TRAINER_LADRON_3                    737
#define TRAINER_LADRON_2                    738
#define TRAINER_LADRON_1                    739
#define TRAINER_ATLAS_3                     740
#define TRAINER_ROJO_2                      741
#define TRAINER_LANCE_2                     742
#define TRAINER_CELIA                       743
#define TRAINER_BRYAN                       744
#define TRAINER_BRANDEN                     745
#define TRAINER_BRYANT                      746
#define TRAINER_SHAYLA                      747
#define TRAINER_KYRA                        748
#define TRAINER_JAIDEN                      749
#define TRAINER_ALIX                        750
#define TRAINER_HELENE                      751
#define TRAINER_FARERO                      752
#define TRAINER_DEVAN                       753
#define TRAINER_JOHNSON                     754
#define TRAINER_MELINA                      755
#define TRAINER_BRANDI                      756
#define TRAINER_AISHA                       757
#define TRAINER_MAKAYLA                     758
#define TRAINER_FABIAN                      759
#define TRAINER_DAYTON                      760
#define TRAINER_RACHEL                      761
#define TRAINER_LEONEL                      762
#define TRAINER_CALLIE                      763
#define TRAINER_CALE                        764
#define TRAINER_MYLES                       765
#define TRAINER_PAT                         766
#define TRAINER_CRISTIN_1                   767
#define TRAINER_MAY_RUSTBORO_TREECKO        768
#define TRAINER_MAY_RUSTBORO_TORCHIC        769
#define TRAINER_ROXANNE_2                   770
#define TRAINER_ROXANNE_3                   771
#define TRAINER_ROXANNE_4                   772
#define TRAINER_ROXANNE_5                   773
#define TRAINER_BRAWLY_2                    774
#define TRAINER_BRAWLY_3                    775
#define TRAINER_AGATHA_2                    776
#define TRAINER_CULTO_3                     777
#define TRAINER_ZEUS_4                      778
#define TRAINER_WATTSON_3                   779
#define TRAINER_WATTSON_4                   780
#define TRAINER_WATTSON_5                   781
#define TRAINER_CULTO_2                     782
#define TRAINER_ESENCIA_HOOH                783
#define TRAINER_ESENCIA_LUGIA               784
#define TRAINER_ESENCIA_ZIGARDE             785
#define TRAINER_NORMAN_2                    786
#define TRAINER_ESENCIA_1                   787
#define TRAINER_ESENCIA_2                   788
#define TRAINER_ESENCIA_3                   789
#define TRAINER_ESENCIA_4                   790
#define TRAINER_ESENCIA_5                   791
#define TRAINER_ESENCIA_6                   792
#define TRAINER_RECLUTA_BALL_1              793
#define TRAINER_RECLUTA_BALL_2              794
#define TRAINER_TATE_AND_LIZA_3             795
#define TRAINER_GRANJERO_1                  796
#define TRAINER_GRANJERO_2                  797
#define TRAINER_LADRON_4                    798
#define TRAINER_LADRON_5                    799
#define TRAINER_LADRON_6                    800
#define TRAINER_SHAKURA                     801
#define TRAINER_ANGELO                      802
#define TRAINER_DARIUS                      803
#define TRAINER_STEVEN                      804
#define TRAINER_ANABEL                      805
#define TRAINER_PEGASO_DISCIPULO            806
#define TRAINER_ELM_2                       807
#define TRAINER_AQUILES_2                   808
#define TRAINER_PRESIDENTE_SILPH            809
#define TRAINER_MAGNO_2                     810
#define TRAINER_HELIO                       811
#define TRAINER_LYSSON                      812
#define TRAINER_LUSAMINE                    813
#define TRAINER_CHAIRMAN_ROSE               814
#define TRAINER_GIOVANNI_2                  815
#define TRAINER_PRESIDENTE_DEVON_2          816
#define TRAINER_CMIGUEL_4                   817
#define TRAINER_BILL_4                      818
#define TRAINER_EUSINE                      819
#define TRAINER_LORELEI                     820
#define TRAINER_DIANTA                      821
#define TRAINER_CINTIA                      822
#define TRAINER_PABLO_5                     823
#define TRAINER_KOJI_2                      824
#define TRAINER_KOJI_3                      825
#define TRAINER_KOJI_4                      826
#define TRAINER_KOJI_5                      827
#define TRAINER_CRISTIN_2                   828
#define TRAINER_CRISTIN_3                   829
#define TRAINER_CRISTIN_4                   830
#define TRAINER_CRISTIN_5                   831
#define TRAINER_CAMPEON_FANTASMA            832
#define TRAINER_CAMPEON_VENENO              833
#define TRAINER_FERNANDO_4                  834
#define TRAINER_FERNANDO_5                  835
#define TRAINER_SAWYER_2                    836
#define TRAINER_SAWYER_3                    837
#define TRAINER_SAWYER_4                    838
#define TRAINER_SAWYER_5                    839
#define TRAINER_GABRIELLE_2                 840
#define TRAINER_GABRIELLE_3                 841
#define TRAINER_GABRIELLE_4                 842
#define TRAINER_GABRIELLE_5                 843
#define TRAINER_THALIA_2                    844
#define TRAINER_THALIA_3                    845
#define TRAINER_THALIA_4                    846
#define TRAINER_THALIA_5                    847
#define TRAINER_MARIELA                     848
#define TRAINER_ALVARO                      849
#define TRAINER_EVERETT                     850
#define TRAINER_RED                         851
#define TRAINER_LEAF                        852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854
#define TRAINER_CIENTIFICO_1                855
#define TRAINER_CRIMINAL                    856
#define TRAINER_CIENTIFICO_3                857
#define TRAINER_EJECUTIVO_DEVON_1           858
#define TRAINER_TRAINER_1                   859
#define TRAINER_TRAINER_2                   860
#define TRAINER_TRAINER_3                   861
#define TRAINER_EJECUTIVO_DEVON_2           862
#define TRAINER_PEGASO_2                    863
#define TRAINER_PETRA                       864
#define TRAINER_MARCIAL                     865
#define TRAINER_ERICO                       866
#define TRAINER_CANDELA                     867
#define TRAINER_NORMAN                      868
#define TRAINER_ALANA                       869
#define TRAINER_VITOLETI                    870
#define TRAINER_GALANO                      871
#define TRAINER_TRAINER_14                   872
#define TRAINER_TRAINER_15                   873
#define TRAINER_TRAINER_16                   874
#define TRAINER_TRAINER_17                   875
#define TRAINER_TRAINER_18                   876
#define TRAINER_TRAINER_19                   877
#define TRAINER_TRAINER_20                   878
#define TRAINER_TRAINER_21                   879
#define TRAINER_TRAINER_22                   880
#define TRAINER_TRAINER_23                   881
#define TRAINER_TRAINER_24                   882
#define TRAINER_TRAINER_25                   883
#define TRAINER_TRAINER_26                   884
#define TRAINER_TRAINER_27                   885
#define TRAINER_TRAINER_28                   886
#define TRAINER_TRAINER_29                   887
#define TRAINER_TRAINER_30                   888
#define TRAINER_TRAINER_31                   889
#define TRAINER_TRAINER_32                   890
#define TRAINER_TRAINER_33                   891
#define TRAINER_TRAINER_34                   892
#define TRAINER_TRAINER_35                   893
#define TRAINER_TRAINER_36                   894
#define TRAINER_TRAINER_37                   895
#define TRAINER_TRAINER_38                   896
#define TRAINER_TRAINER_39                   897
#define TRAINER_TRAINER_40                   898
#define TRAINER_TRAINER_41                   899
#define TRAINER_TRAINER_42                   900
#define TRAINER_TRAINER_43                   901
#define TRAINER_TRAINER_44                   902
#define TRAINER_TRAINER_45                   903
#define TRAINER_TRAINER_46                   904
#define TRAINER_TRAINER_47                   905
#define TRAINER_TRAINER_48                   906
#define TRAINER_TRAINER_49                   907
#define TRAINER_TRAINER_50                   908
#define TRAINER_TRAINER_51                   909
#define TRAINER_TRAINER_52                   910
#define TRAINER_TRAINER_53                   911
#define TRAINER_TRAINER_54                   912
#define TRAINER_TRAINER_55                   913
#define TRAINER_TRAINER_56                   914
#define TRAINER_TRAINER_57                   915
#define TRAINER_TRAINER_58                   916
#define TRAINER_TRAINER_59                   917
#define TRAINER_TRAINER_60                   918
#define TRAINER_TRAINER_61                   919
#define TRAINER_TRAINER_62                   920
#define TRAINER_TRAINER_63                   921
#define TRAINER_TRAINER_64                   922
#define TRAINER_TRAINER_65                   923
#define TRAINER_TRAINER_66                   924
#define TRAINER_TRAINER_67                   925
#define TRAINER_TRAINER_68                   926
#define TRAINER_TRAINER_69                   927
#define TRAINER_TRAINER_70                   928
#define TRAINER_TRAINER_71                   929
#define TRAINER_TRAINER_72                   930
#define TRAINER_TRAINER_73                   931
#define TRAINER_TRAINER_74                   932
#define TRAINER_TRAINER_75                   933
#define TRAINER_TRAINER_76                   934
#define TRAINER_TRAINER_77                   935
#define TRAINER_TRAINER_78                   936
#define TRAINER_TRAINER_79                   937
#define TRAINER_TRAINER_80                   938
#define TRAINER_TRAINER_81                   939
#define TRAINER_TRAINER_82                   940
#define TRAINER_TRAINER_83                   941
#define TRAINER_TRAINER_84                   942
#define TRAINER_TRAINER_85                   943
#define TRAINER_TRAINER_86                   944
#define TRAINER_TRAINER_87                   945
#define TRAINER_TRAINER_88                   946
#define TRAINER_TRAINER_89                   947
#define TRAINER_TRAINER_90                   948 // LIBRE
#define TRAINER_TRAINER_91                   949
#define TRAINER_TRAINER_92                   950
#define TRAINER_TRAINER_93                   951
#define TRAINER_TRAINER_94                   952
#define TRAINER_TRAINER_95                   953
#define TRAINER_TRAINER_96                   954
#define TRAINER_TRAINER_97                   955
#define TRAINER_TRAINER_98                   956
#define TRAINER_TRAINER_99                   957
#define TRAINER_TRAINER_100                   958
#define TRAINER_TRAINER_101                   959
#define TRAINER_TRAINER_102                   960
#define TRAINER_TRAINER_103                   961
#define TRAINER_TRAINER_104                   962
#define TRAINER_TRAINER_105                   963
#define TRAINER_TRAINER_106                   964
#define TRAINER_TRAINER_107                   965
#define TRAINER_TRAINER_108                   966
#define TRAINER_TRAINER_109                   967
#define TRAINER_TRAINER_110                   968
#define TRAINER_TRAINER_111                   969
#define TRAINER_TRAINER_112                   970
#define TRAINER_TRAINER_113                   971
#define TRAINER_TRAINER_114                   972
#define TRAINER_TRAINER_115                   973
#define TRAINER_TRAINER_116                   974
#define TRAINER_TRAINER_117                   975
#define TRAINER_TRAINER_118                   976
#define TRAINER_TRAINER_119                   977
#define TRAINER_TRAINER_120                   978
#define TRAINER_TRAINER_121                   979
#define TRAINER_TRAINER_122                   980
#define TRAINER_TRAINER_123                   981
#define TRAINER_TRAINER_124                   982
#define TRAINER_TRAINER_125                   983
#define TRAINER_TRAINER_126                   984
#define TRAINER_TRAINER_127                   985
#define TRAINER_TRAINER_128                   986
#define TRAINER_TRAINER_129                   987
#define TRAINER_TRAINER_130                   988
#define TRAINER_TRAINER_131                   989
#define TRAINER_TRAINER_132                   990
#define TRAINER_TRAINER_133                   991
#define TRAINER_TRAINER_134                   992
#define TRAINER_TRAINER_135                   993
#define TRAINER_TRAINER_136                   994
#define TRAINER_TRAINER_137                   995
#define TRAINER_TRAINER_138                   996
#define TRAINER_TRAINER_139                   997
#define TRAINER_TRAINER_140                   998
#define TRAINER_TRAINER_141                   999
#define TRAINER_TRAINER_142                   1000
#define TRAINER_TRAINER_143                   1001
#define TRAINER_TRAINER_144                   1002
#define TRAINER_TRAINER_145                   1003
#define TRAINER_TRAINER_146                   1004
#define TRAINER_TRAINER_147                   1005
#define TRAINER_TRAINER_148                   1006
#define TRAINER_TRAINER_149                   1007
#define TRAINER_TRAINER_150                   1008
#define TRAINER_TRAINER_151                   1009
#define TRAINER_TRAINER_152                   1010
#define TRAINER_TRAINER_153                   1011
#define TRAINER_TRAINER_154                   1012
#define TRAINER_TRAINER_155                   1013
#define TRAINER_TRAINER_156                   1014
#define TRAINER_TRAINER_157                   1015
#define TRAINER_TRAINER_158                   1016
#define TRAINER_TRAINER_159                   1017
#define TRAINER_TRAINER_160                   1018
#define TRAINER_TRAINER_161                   1019
#define TRAINER_TRAINER_162                   1020
#define TRAINER_TRAINER_163                   1021
#define TRAINER_TRAINER_164                   1022
#define TRAINER_TRAINER_165                   1023
#define TRAINER_TRAINER_166                   1024
#define TRAINER_TRAINER_167                   1025
#define TRAINER_TRAINER_168                   1026
#define TRAINER_TRAINER_169                   1027
#define TRAINER_TRAINER_170                   1028
#define TRAINER_TRAINER_171                   1029
#define TRAINER_TRAINER_172                   1030
#define TRAINER_TRAINER_173                   1031
#define TRAINER_TRAINER_174                   1032
#define TRAINER_TRAINER_175                   1033
#define TRAINER_TRAINER_176                   1034
#define TRAINER_TRAINER_177                   1035
#define TRAINER_TRAINER_178                   1036
#define TRAINER_TRAINER_179                   1037
#define TRAINER_TRAINER_180                   1038
#define TRAINER_TRAINER_181                   1039
#define TRAINER_TRAINER_182                   1040
#define TRAINER_TRAINER_183                   1041
#define TRAINER_TRAINER_184                   1042
#define TRAINER_TRAINER_185                   1043
#define TRAINER_TRAINER_186                   1044
#define TRAINER_TRAINER_187                   1045
#define TRAINER_TRAINER_188                   1046
#define TRAINER_TRAINER_189                   1047
#define TRAINER_TRAINER_190                   1048
#define TRAINER_TRAINER_191                   1049
#define TRAINER_TRAINER_192                   1050
#define TRAINER_TRAINER_193                   1051
#define TRAINER_TRAINER_194                   1052
#define TRAINER_TRAINER_195                   1053
#define TRAINER_TRAINER_196                   1054
#define TRAINER_TRAINER_197                   1055
#define TRAINER_TRAINER_198                   1056
#define TRAINER_TRAINER_199                   1057
#define TRAINER_TRAINER_200                   1058
#define TRAINER_TRAINER_201                   1059
#define TRAINER_TRAINER_202                   1060
#define TRAINER_TRAINER_203                   1061
#define TRAINER_TRAINER_204                   1062
#define TRAINER_TRAINER_205                   1063
#define TRAINER_TRAINER_206                   1064
#define TRAINER_TRAINER_207                   1065
#define TRAINER_TRAINER_208                   1066
#define TRAINER_TRAINER_209                   1067
#define TRAINER_TRAINER_210                   1068
#define TRAINER_TRAINER_211                   1069
#define TRAINER_TRAINER_212                   1070
#define TRAINER_TRAINER_213                   1071
#define TRAINER_TRAINER_214                   1072
#define TRAINER_TRAINER_215                   1073
#define TRAINER_TRAINER_216                   1074
#define TRAINER_TRAINER_217                   1075
#define TRAINER_TRAINER_218                   1076
#define TRAINER_TRAINER_219                   1077
#define TRAINER_TRAINER_220                   1078
#define TRAINER_TRAINER_221                   1079
#define TRAINER_TRAINER_222                   1080
#define TRAINER_TRAINER_223                   1081
#define TRAINER_TRAINER_224                   1082
#define TRAINER_TRAINER_225                   1083
#define TRAINER_TRAINER_226                   1084
#define TRAINER_TRAINER_227                   1085
#define TRAINER_TRAINER_228                   1086
#define TRAINER_TRAINER_229                   1087
#define TRAINER_TRAINER_230                   1088
#define TRAINER_TRAINER_231                   1089
#define TRAINER_TRAINER_232                   1090
#define TRAINER_TRAINER_233                   1091
#define TRAINER_TRAINER_234                   1092
#define TRAINER_TRAINER_235                   1093
#define TRAINER_TRAINER_236                   1094
#define TRAINER_TRAINER_237                   1095
#define TRAINER_TRAINER_238                   1096
#define TRAINER_TRAINER_239                   1097
#define TRAINER_TRAINER_240                   1098
#define TRAINER_TRAINER_241                   1099
#define TRAINER_TRAINER_242                   1100
#define TRAINER_TRAINER_243                   1101
#define TRAINER_TRAINER_244                   1102
#define TRAINER_TRAINER_245                   1103
#define TRAINER_TRAINER_246                   1104
#define TRAINER_TRAINER_247                   1105
#define TRAINER_TRAINER_248                   1106
#define TRAINER_TRAINER_249                   1107
#define TRAINER_TRAINER_250                   1108
#define TRAINER_TRAINER_251                   1109
#define TRAINER_TRAINER_252                   1110
#define TRAINER_TRAINER_253                   1111
#define TRAINER_TRAINER_254                   1112
#define TRAINER_TRAINER_255                   1113
#define TRAINER_TRAINER_256                   1114
#define TRAINER_TRAINER_257                   1115
#define TRAINER_TRAINER_258                   1116
#define TRAINER_TRAINER_259                   1117
#define TRAINER_TRAINER_260                   1118
#define TRAINER_TRAINER_261                   1119
#define TRAINER_TRAINER_262                   1120
#define TRAINER_TRAINER_263                   1121
#define TRAINER_TRAINER_264                   1122
#define TRAINER_TRAINER_265                   1123
#define TRAINER_TRAINER_266                   1124
#define TRAINER_TRAINER_267                   1125
#define TRAINER_TRAINER_268                   1126
#define TRAINER_TRAINER_269                   1127
#define TRAINER_TRAINER_270                   1128
#define TRAINER_TRAINER_271                   1129
#define TRAINER_TRAINER_272                   1130
#define TRAINER_TRAINER_273                   1131
#define TRAINER_TRAINER_274                   1132
#define TRAINER_TRAINER_275                   1133
#define TRAINER_TRAINER_276                   1134
#define TRAINER_TRAINER_277                   1135
#define TRAINER_TRAINER_278                   1136
#define TRAINER_TRAINER_279                   1137
#define TRAINER_TRAINER_280                   1138
#define TRAINER_TRAINER_281                   1139
#define TRAINER_TRAINER_282                   1140
#define TRAINER_TRAINER_283                   1141
#define TRAINER_TRAINER_284                   1142
#define TRAINER_TRAINER_285                   1143
#define TRAINER_TRAINER_286                   1144
#define TRAINER_TRAINER_287                   1145
#define TRAINER_TRAINER_288                   1146
#define TRAINER_TRAINER_289                   1147
#define TRAINER_TRAINER_290                   1148
#define TRAINER_TRAINER_291                   1149
#define TRAINER_TRAINER_292                   1150
#define TRAINER_TRAINER_293                   1151
#define TRAINER_TRAINER_294                   1152
#define TRAINER_TRAINER_295                   1153
#define TRAINER_TRAINER_296                   1154
#define TRAINER_TRAINER_297                   1155
#define TRAINER_TRAINER_298                   1156
#define TRAINER_TRAINER_299                   1157
#define TRAINER_TRAINER_300                   1158
#define TRAINER_TRAINER_301                   1159
#define TRAINER_TRAINER_302                   1160
#define TRAINER_TRAINER_303                   1161
#define TRAINER_TRAINER_304                   1162
#define TRAINER_TRAINER_305                   1163
#define TRAINER_TRAINER_306                   1164
#define TRAINER_TRAINER_307                   1165
#define TRAINER_TRAINER_308                   1166
#define TRAINER_TRAINER_309                   1167
#define TRAINER_TRAINER_310                   1168
#define TRAINER_TRAINER_311                   1169
#define TRAINER_TRAINER_312                   1170
#define TRAINER_TRAINER_313                   1171
#define TRAINER_TRAINER_314                   1172
#define TRAINER_TRAINER_315                   1173
#define TRAINER_TRAINER_316                   1174
#define TRAINER_TRAINER_317                   1175
#define TRAINER_TRAINER_318                   1176
#define TRAINER_TRAINER_319                   1177
#define TRAINER_TRAINER_320                   1178
#define TRAINER_TRAINER_321                   1179
#define TRAINER_TRAINER_322                   1180
#define TRAINER_TRAINER_323                   1181
#define TRAINER_TRAINER_324                   1182
#define TRAINER_TRAINER_325                   1183
#define TRAINER_TRAINER_326                   1184
#define TRAINER_TRAINER_327                   1185
#define TRAINER_TRAINER_328                   1186
#define TRAINER_TRAINER_329                   1187
#define TRAINER_TRAINER_330                   1188
#define TRAINER_TRAINER_331                   1189
#define TRAINER_TRAINER_332                   1190
#define TRAINER_TRAINER_333                   1191
#define TRAINER_TRAINER_334                   1192
#define TRAINER_TRAINER_335                   1193
#define TRAINER_TRAINER_336                   1194
#define TRAINER_TRAINER_337                   1195
#define TRAINER_TRAINER_338                   1196
#define TRAINER_TRAINER_339                   1197
#define TRAINER_TRAINER_340                   1198
#define TRAINER_TRAINER_341                   1199
#define TRAINER_TRAINER_342                   1200
#define TRAINER_TRAINER_343                   1201
#define TRAINER_TRAINER_344                   1202
#define TRAINER_TRAINER_345                   1203
#define TRAINER_TRAINER_346                   1204
#define TRAINER_TRAINER_347                   1205
#define TRAINER_TRAINER_348                   1206
#define TRAINER_TRAINER_349                   1207
#define TRAINER_TRAINER_350                   1208
#define TRAINER_TRAINER_351                   1209
#define TRAINER_TRAINER_352                   1210
#define TRAINER_TRAINER_353                   1211
#define TRAINER_TRAINER_354                   1212
#define TRAINER_TRAINER_355                   1213
#define TRAINER_TRAINER_356                   1214
#define TRAINER_TRAINER_357                   1215
#define TRAINER_TRAINER_358                   1216
#define TRAINER_TRAINER_359                   1217
#define TRAINER_TRAINER_360                   1218
#define TRAINER_TRAINER_361                   1219
#define TRAINER_TRAINER_362                   1220
#define TRAINER_TRAINER_363                   1221
#define TRAINER_TRAINER_364                   1222
#define TRAINER_TRAINER_365                   1223
#define TRAINER_TRAINER_366                   1224
#define TRAINER_TRAINER_367                   1225
#define TRAINER_TRAINER_368                   1226
#define TRAINER_TRAINER_369                   1227
#define TRAINER_TRAINER_370                   1228
#define TRAINER_TRAINER_371                   1229
#define TRAINER_TRAINER_372                   1230
#define TRAINER_TRAINER_373                   1231
#define TRAINER_TRAINER_374                   1232
#define TRAINER_TRAINER_375                   1233
#define TRAINER_TRAINER_376                   1234
#define TRAINER_TRAINER_377                   1235
#define TRAINER_TRAINER_378                   1236
#define TRAINER_TRAINER_379                   1237
#define TRAINER_TRAINER_380                   1238
#define TRAINER_TRAINER_381                   1239
#define TRAINER_TRAINER_382                   1240
#define TRAINER_TRAINER_383                   1241
#define TRAINER_TRAINER_384                   1242
#define TRAINER_TRAINER_385                   1243
#define TRAINER_TRAINER_386                   1244
#define TRAINER_TRAINER_387                   1245
#define TRAINER_TRAINER_388                   1246
#define TRAINER_TRAINER_389                   1247
#define TRAINER_TRAINER_390                   1248
#define TRAINER_TRAINER_391                   1249
#define TRAINER_TRAINER_392                   1250
#define TRAINER_TRAINER_393                   1251
#define TRAINER_TRAINER_394                   1252
#define TRAINER_TRAINER_395                   1253
#define TRAINER_TRAINER_396                   1254
#define TRAINER_TRAINER_397                   1255
#define TRAINER_TRAINER_398                   1256
#define TRAINER_TRAINER_399                   1257
#define TRAINER_TRAINER_400                   1258

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      1259
#define MAX_TRAINERS_COUNT                  1259

#endif  // GUARD_CONSTANTS_OPPONENTS_H
