BlackthornCity_House1_MapScripts::
	.byte 0

BlackthornCityHouse1_1::
end


BlackthornCityHouse1_2::
lock     
faceplayer     
msgbox BlackthornCity_House1_Text_2, MSGBOX_DEFAULT
release     
end

BlackthornCity_House1_Text_2:
.string "Logré ver al POKÉMON estrella de\n"
.string "nuestro LÍDER, un dragón\l"
.string "magnífico, de un poder, dicen,\l"
.string "superior al de cualquier\l"
.string "LEGENDARIO. Tan extraordinario que\l"
.string "ni el propio TIPO DRAGÓN le\l"
.string "afecta…$"
