BlackthornCity_House1_MapScripts::
	.byte 0

BlackthornCityHouse1_1::
lock
faceplayer
msgbox BlackthornCityHouse1_1_Texto_1, MSGBOX_DEFAULT
release
end

BlackthornCityHouse1_1_Texto_1:
.string "Las nuevas generaciones se lo tienen\n"
	.string "muy creído, y subestiman sobremanera a\l"
	.string "las anteriores. Esa DÉBORA cree que\l"
	.string "cuando tenga un KINGDRA y un\l"
	.string "DRAGONITE habrá resuelto todos los\l"
	.string "misterios del TIPO DRAGÓN. Si viera los\l"
	.string "POKÉMON más fuertes del maestro...$"


BlackthornCityHouse1_2::
lock     
faceplayer     
msgbox BlackthornCity_House1_Text_2, MSGBOX_DEFAULT
release     
end

BlackthornCity_House1_Text_2:
.string "Logré ver al POKÉMON estrella de\n"
.string "nuestro LÍDER, un dragón\l"
.string "magnífico, de un poder, dicen,\l"
.string "superior al de cualquier\l"
.string "LEGENDARIO. Tan extraordinario que\l"
.string "ni el propio TIPO DRAGÓN le\l"
.string "afecta…$"
