BlackthornCity_House1_MapScripts::
	.byte 0

BlackthornCityHouse1-1::
end


BlackthornCityHouse1-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Logré ver al POKÉMON estrella de\n"
.string "nuestro LÍDER, un dragón\l"
.string "magnífico, de un poder, dicen,\l"
.string "superior al de cualquier\l"
.string "LEGENDARIO. Tan extraordinario que\l"
.string "ni el propio TIPO DRAGÓN le\l"
.string "afecta[.]$"
