Goldenrod_ShopCenterP1_MapScripts::
	.byte 0

GoldenrodShopCenterP1-1::
end



GoldenrodShopCenterP1-2::
end



GoldenrodShopCenterP1-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Poca gente lo sabe, pero las\n"
.string "bebidas de estas máquinas\l"
.string "expendedoras son mucho más\l"
.string "económicas que las POCIONES\l"
.string "corrientes.\l"
.string "¡He oído que la LECHE-MU-MU lo es\l"
.string "aún más!$"



GoldenrodShopCenterP1-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "Compré un LARVITAR en el CASINO,\n"
.string "ahora estoy pagando a un experto\l"
.string "para que lo convierta en\l"
.string "TYRANITAR. Dicen que es el POKÉMON\l"
.string "más fuerte de JOHTO, sin tener en\l"
.string "cuenta LEGENDARIOS.\l"
.string "¡Todos me respetarán!$"



GoldenrodShopCenterP1-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "Dicen que el CENTRO COMERCIAL de\n"
.string "AZULONA es aún más grande que\l"
.string "este.\l"
.string "¿Será cierto?$"
