NeoViridianCity_MapScripts::
	.byte 0

NeoViridianCity_Primer_Npc::
lock
faceplayer
msgbox NeoViridianCity_Primer_Npc_Texto_1 MSGBOX_NPC
release
end

NeoViridianCity_Primer_Npc_Texto_1:
.string "Dicen que en el suelo del BOSQUE VERDE\n"
	.string "hay muchos objetos.$"



NeoViridianCity_Segundo_Npc::
lock
faceplayer
msgbox NeoViridianCity_Segundo_Npc_Texto_1 MSGBOX_NPC
release
end

NeoViridianCity_Segundo_Npc_Texto_1:
.string "Dicen que en el suelo del BOSQUE VERDE\n"
	.string "hay muchos objetos.$"



NeoViridianCity_Tercer_Npc::
lock
faceplayer
msgbox NeoViridianCity_Tercer_Npc_Texto_1 MSGBOX_NPC
release
end

NeoViridianCity_Tercer_Npc_Texto_1:
.string "Dicen que en el suelo del BOSQUE VERDE\n"
	.string "hay muchos objetos.$"


