CultoS4_MapScripts::
	.byte 0

CultoS4_2::
lock     
faceplayer     
msgbox CultoS4_2_Text_2, MSGBOX_DEFAULT
release     
end

CultoS4_2_Text_2:
.string "Las formas nacen y mueren, pero tú eres\n"
.string "consciente de lo eterno que está\l"
.string "detrás de esas formas. Nada real puede\l"
.string "ser amenazado.$"



CultoS4_5::
lock     
faceplayer     
msgbox CultoS4_5_Text_5, MSGBOX_DEFAULT
release     
end

CultoS4_5_Text_5:
.string "Tu principal tarea no es buscar la\n"
.string "salvación mediante la creación de un\l"
.string "mundo mejor, sino despertar de la\l"
.string "identificación con la forma.$"