PewterCity_Musem_2F_MapScripts::
	.byte 0

PewterMuseum2F-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "¡Quiero un PIKACHU!\n"
.string "¡Es tan mono!\l"
.string "¡Le diré a mi padre que me atrape\l"
.string "uno!$"



PewterMuseum2F-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "¡Si hija, te prometo que tendrás\n"
.string "un PIKACHU!$"



PewterMuseum2F-3::
end



PewterMuseum2F-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "Esa PIEDRA LUNAR está\n"
.string "sobrevalorada, si se ve igual que\l"
.string "una vulgar roca.$"



PewterMuseum2F-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "Este mes daremos una exhibición\n"
.string "espacial, a la que tú, por\l"
.string "supuesto, no estás invitado.$"
