Snowpoint_Shop_MapScripts::
	.byte 0

Snowpoint_Shop_Primer_Npc::
lock
faceplayer
msgbox Snowpoint_Shop_Primer_Npc_Texto_1 MSGBOX_DEFAULT
release
end

Snowpoint_Shop_Primer_Npc_Texto_1:
	.string "Estoy usando Máquina Técnicas para\n"
	.string "enseñar movimientos a mis POKÉMON.\l"
	.string "Prueba distintas combinaciones de\l"
	.string "movimientos con tipos diferentes. Lo\l"
	.string "hago para cuando me toque luchar\l"
	.string "contra el ALTO MANDO de la LIGA\l"
	.string "POKÉMON. He oído que son mucho más\l"
	.string "duros que todos los LÍDERES DE\l"
	.string "GIMNASIO juntos.$"

Snowpoint_Shop_Segundo_Npc::
lock
faceplayer
msgbox Snowpoint_Shop_Segundo_Npc_Texto_1 MSGBOX_DEFAULT
release
end

Snowpoint_Shop_Segundo_Npc_Texto_1:
	.string "Si congelan a tu POKÉMON, no te\n"
	.string "preocupes, se le pasará en un rato.\l"
	.string "Pero, si yo fuera tú, tendría siempre\l"
	.string "algunos ANTIHIELO a mano.$"
