Cianwood_House1_MapScripts::
	.byte 0

CianwoodHouse1_1::
lock     
faceplayer     
msgbox Cianwood_House1_Text_1, MSGBOX_DEFAULT
release     
end

Cianwood_House1_Text_1:
	.string "I know CHUCK well; since he was young,\n"
	.string "he made a promise to always be one with\l"
	.string "his POKÉMON team, something he has\l"
	.string "steadfastly upheld until now.\l"
	.string "Surprisingly, he has managed to\l"
	.string "maintain his physical peak well into his\l"
	.string "forties, but time catches up with\l"
	.string "everyone sooner or later… Now that he's\l"
	.string "passed 50 years old, he'll have to make\l"
	.string "a decision regarding his faithful\l"
	.string "POKÉMON.$"



CianwoodHouse1_2::
lock     
faceplayer     
msgbox Cianwood_House1_Text_2, MSGBOX_DEFAULT
release     
end

Cianwood_House1_Text_2:
	.string "One of the three roaming beasts\n"
	.string "blessed this city with the fruits of the\l"
	.string "sea. It had been over half a decade\l"
	.string "since I last spotted the lord of the\l"
	.string "northern winds until finally, one fine\l"
	.string "morning, days after all the commotion\l"
	.string "at the POKÉMON LEAGUE, I saw him return\l"
	.string "to his beloved CIANWOOD CITY.$"



CianwoodHouse1_3::
lock     
faceplayer     
msgbox Cianwood_House1_Text_3, MSGBOX_DEFAULT
release     
end

Cianwood_House1_Text_3:
	.string "My grandparents know so much about\n"
	.string "this city and JOHTO… It will be a shame\l"
	.string "to lose all that knowledge forever when\l"
	.string "they're gone.$"
