Ecruteak_DanceTheater_MapScripts::
	.byte 0

DanceTheater1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Solo una persona noble cuyo\n"
.string "vínculo con sus POKÉMON sea\l"
.string "inquebrantable podrá hacer\l"
.string "regresar al LEGENDARIO HO-OH a\l"
.string "TORRE CAMPANA una vez más.$"



DanceTheater2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Los monjes de TORRE CAMPANA son\n"
.string "fascinantes. Desde el momento en\l"
.string "que se levantan, se entregan a la\l"
.string "perfección sea cual fuere el\l"
.string "propósito que persigan. No\l"
.string "encontrarás esa disciplina en\l"
.string "ningún otro lugar.$"



DanceTheater3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "¿Cómo?\n"
.string "¡Ah, si!\l"
.string "Tenemos varias evoluciones de\l"
.string "EEVEE, según el rival usamos las\l"
.string "mejor o peor entrenadas, ademas\l"
.string "algunos se enfadan si pierden, esa\l"
.string "gente no nos interesa así que les\l"
.string "damos lo que buscan, y a otra\l"
.string "cosa.$"



DanceTheater4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "Todos los EEVEE tienen su origen\n"
.string "en uno solo.\l"
.string "¿Cuál es?\l"
.string "Solo nuestro LÍDER DE GIMNASIO\l"
.string "tiene la respuesta a eso.$"



DanceTheater5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "Dicen que cada evolución de los 7\n"
.string "EEVEE representa cada uno los\l"
.string "7 colores del arco iris de HO-OH,\l"
.string "aunque creo que hay más de 7\l"
.string "evoluciones diferentes de EEVEE[.]$"



DanceTheater6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "Las CHICAS KIMONO no solo bailan,\n"
.string "también son extraordinarias con\l"
.string "los POKÉMON.\l"
.string "Yo siempre las desafio pero nunca\l"
.string "les he hecho ni un rasguño[.]\l"
.string "Ojalá mis POKÉMON fueran tan\l"
.string "elegantes como las CHICAS KIMONO[.]$"



DanceTheater7::
lock     
faceplayer     
msgbox Text_7, MSGBOX_DEFAULT
release     
end

Text_7:
.string "Cada CHICA KIMONO representa una\n"
.string "forma de EEVEE, pero también a su\l"
.string "TIPO concreto. Eso se ve reflejado\l"
.string "en el estilo de baile.$"



DanceTheater8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "Estas chicas llevan el arte de la\n"
.string "danza en las venas.\l"
.string "¡Las inmortalizaré en mi próximo\l"
.string "lienzo!$"



DanceTheater9::
lock     
faceplayer     
msgbox Text_9, MSGBOX_DEFAULT
release     
end

Text_9:
.string "Las CHICAS KIMONO son tan guapas[.]\n"
.string "Pero tienen que entrenar mucho.\l"
.string "Y deben de aprender los distintos\l"
.string "bailes antes de actuar.\l"
.string "Pero si te gusta algo, todo es\l"
.string "posible.$"



DanceTheater11::
lock     
faceplayer     
msgbox Text_11, MSGBOX_DEFAULT
release     
end

Text_11:
.string "¡Espectáculos como este mantienen\n"
.string "a JOHTO viva en su esencia!$"
