gText_Birch_Welcome::
	.string "¡Bienvenido al TEAM ROCKET!\p"
	.string "De modo que eres uno de los\n"
	.string "seleccionados para formar parte del\l"
	.string "pelotón de ISLA INTA, ¿eh?\p"
	.string "Soy Atlas, ejecutivo principal y mano\n"
	.string "derecha de Giovanni…\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Esto…”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "…es un Pokémon de verdad y a lo que\n"
	.string "debes aspirar.\p"
	.string "Bien… {PAUSE 60}espero que no seas uno de esos\n"
	.string "mediocres que se conforman con tener\l"
	.string "al EKANS ó RATTATA de turno.\p"
	.string "Las insubordinaciones y faltas de\n"
	.string "actitud aquí se pagan muy caras…\l"
	.string "tenlo presente.\p"
	.string "Dicho esto, hora del papeleo.\p"
	.string "No te preocupes… {PAUSE 45} no pedimos\n"
	.string "documentación.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"	

gText_Birch_BoyOrGirl::
	.string "Sólo debes inscribirte con un nombre\n"
	.string "que será tu seña de identidad aquí.$"

gText_Birch_WhatsYourName::
	.string "Sólo debes inscribirte con un nombre\n"
	.string "que será tu seña de identidad aquí.$"

gText_Birch_SoItsPlayer::
	.string "Bien… {PAUSE 60} ¿Así que te llamas\n{PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PAUSE 50}Este es nuestro LÍDER, Giovanni.\p"
	.string "No encontrarás mejor ni más sabio\n"
	.string "entrenador en todo KANTO…\p"
	.string "Sólo los mejores ROCKETS tienen acceso\n"
	.string "a él.\p"
	.string "Si de verdad quieres subir en esta\n"
	.string "organización, deberás de hacer\l"
	.string "méritos con cada misión que se te\l"
	.string "confíe, sin atajos ni favoritismos.\p"
	.string "Sólo entonces quizás puedas algún día\n"
	.string "conocer en persona a nuestro LÍDER.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "¡{PLAYER}!\p"
	.string "Quedas convocado para la presentación\n"
	.string "y entrega de iniciales en el cuartel\l"
	.string "de ISLA INTA a las 17 en punto.\p"
	.string "Un mundo de corrupción, fraude e\n"
	.string "hipocresía te espera.\p"
	.string "Prepárate para ver a tu querida KANTO\n"
	.string "desde otro prisma.\p"
	.string "¡Que dé comienzo!\p"
	.string "$"
