gText_PkmnTransferredSomeonesPC::
	.string	"{STR_VAR_2} fue enviado al PC\n"
	.string	"de BILL.\p"
	.string	"Se ha guardado en la CAJA\n"
	.string	"“{STR_VAR_1}”.$"
	
gText_PkmnTransferredLanettesPC::
	.string	"{STR_VAR_2} fue enviado al PC\n"
	.string	"de BILL.\p"
	.string	"Se ha guardado en la CAJA\n"
	.string	"“{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string	"La CAJA “{STR_VAR_3}” del PC\n"
	.string	"de alguien estaba llena.\p"
	.string	"{STR_VAR_2} fue enviado a la CAJA\n"
	.string	"“{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string	"La CAJA “{STR_VAR_3}” del PC\n"
	.string	"de BILL estaba llena.\p"
	.string	"{STR_VAR_2} fue enviado a la CAJA\n"
	.string	"“{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
	.string	"¡No queda sitio para más POKÉMON!\p"
	.string	"¡Las CAJAS POKÉMON están llenas!$"

gText_NicknameThisPokemon::
	.string	"¿Quieres darle un mote\n"
	.string	"a tu {STR_VAR_1}?$"
