gText_WouldYouLikeToRestYourPkmn::
    .string "¡Éste es el CENTRO POKÉMON!\p"
    .string "Nosotros curamos a los POKÉMON.\n"
    .string "debilitados.\l"
    .string "¿Quieres que nos ocupemos de los\l"
    .string "POKÉMON de tu equipo?$"

gText_IllTakeYourPkmn::
    .string "Muy bien. Ten un poco de\n"
    .string "paciencia. Será solo un momento.$"

gText_RestoredPkmnToFullHealth::
    .string "Misión cumplida. Somos especialistas\p"
    .string "en devolver la forma a los\n"
    .string "POKÉMON.$"

gText_WeHopeToSeeYouAgain::
    .string "¡Vuelve siempre que quieras!$"

gText_WelcomeCutShort::
    .string "Hello, and welcome to\n"
    .string "the POKéMON CENTER.\p"
    .string "We restore your tired POKéMON\n"
    .string "to full health.\p"
    .string "Would you like to…$"

gText_NoticesGoldCard::
    .string "Th-that card…\n"
    .string "Could it be… The GOLD CARD?!\p"
    .string "Oh, the gold color is brilliant!\n"
    .string "The four stars seem to sparkle!\p"
    .string "I've seen several TRAINERS with\n"
    .string "a SILVER CARD before, but, {PLAYER},\l"
    .string "you're the first TRAINER I've ever\l"
    .string "seen with a GOLD CARD!\p"
    .string "Okay, {PLAYER}, please allow me\n"
    .string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
    .string "I'm delighted to see you, {PLAYER}!\n"
    .string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
    .string "Okay, I'll take your POKéMON\n"
    .string "for a few seconds.$"

gText_ThankYouForWaiting::
    .string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
    .string "We hope to see you again!$"
