MtMoon_3F_MapScripts::
	.byte 0

MtMoon3F_2::
end



MtMoon3F_3::
end



MtMoon3F_4::
end



MtMoon3F_5::
lock     
faceplayer     
msgbox MtMoon3F_Text_5, MSGBOX_DEFAULT
release     
end

MtMoon3F_Text_5:
.string "¡Nada por aquí camarada!$"



MtMoon3F_6::
lock     
faceplayer     
msgbox MtMoon3F_Text_6, MSGBOX_DEFAULT
release     
end

MtMoon3F_Text_6:
.string "ANDRA: Parece que aquí no hay nada\n"
.string "importante, tal vez en las\l"
.string "escaleras que llevan a otra\l"
.string "entrada…$"



MtMoon3F_7::
end



MtMoon3F_9::
end



MtMoon3F_10::
end



MtMoon3F_11::
end
