SsAnne_7F_MapScripts::
	.byte 0

SsAnne7F_1::
end



SsAnne7F_2::
lock     
faceplayer     
msgbox SsAnne7F_Text_2, MSGBOX_DEFAULT
release     
end

SsAnne7F_Text_2:
.string "Order up! Galician-style Octillery!$"



SsAnne7F_3::
lock     
faceplayer     
msgbox SsAnne7F_Text_3, MSGBOX_DEFAULT
release     
end

SsAnne7F_Text_3:
	.string "Our CAPTAIN loves HOENN POKÉMON,\n"
	.string "especially Water types!$"



SsAnne7F_4::
lock     
faceplayer     
msgbox SsAnne7F_Text_4, MSGBOX_DEFAULT
release     
end

SsAnne7F_Text_4:
.string "'Join as a sailor,' they said…\n"
	.string "'You'll have grand adventures,' they said…$"



SsAnne7F_5::
lock     
faceplayer     
msgbox SsAnne7F_Text_5, MSGBOX_DEFAULT
release     
end

SsAnne7F_Text_5:
.string "Sniff…\n"
.string "Sniff…\l"
.string "Look man, I'm just peeling onions…$"



SsAnne7F_6::
lock     
faceplayer     
msgbox SsAnne7F_Text_6, MSGBOX_DEFAULT
release     
end

SsAnne7F_Text_6:
.string "Hum-de-hum-de-ho…\n"
.string "I peel spuds every day!\l"
.string "Hum-hum…$"



SsAnne7F_7::
lock     
faceplayer     
msgbox SsAnne7F_Text_7, MSGBOX_DEFAULT
release     
end

SsAnne7F_Text_7:
	.string "You should be at the party, but since\n"
	.string "you're here, I'll let you in on a secret:\l"
	.string "the real party is happening right here.\l"
	.string "Without our work, that celebration out\l"
	.string "there wouldn't even be possible.\l"
	.string "Honestly, I find it way more satisfying\l"
	.string "to enjoy the process that makes things\l"
	.string "happen rather than just reaching the\l"
	.string "end goal.$"



SsAnne7F_8::
lock     
faceplayer     
msgbox SsAnne7F_Text_8, MSGBOX_DEFAULT
release     
end

SsAnne7F_Text_8:
	.string "We're swamped! We've got to serve all the\n"
	.string "party guests in record time!$"
