SsAnne_7F_MapScripts::
	.byte 0

SsAnne7F-1::
end



SsAnne7F-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "¡Marchando el OCTILLERY a la\n"
.string "gallega!$"



SsAnne7F-3::
end



SsAnne7F-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "Enrólate de marinero decían[.]\n"
.string "Vivirás grandes aventuras\l"
.string "decían[.]$"



SsAnne7F-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "Sniff[.]\n"
.string "Sniff[.]\l"
.string "Yo solo pelo cebollas[.]$"



SsAnne7F-6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "¡Yo solo pelo patatas!\n"
.string "¡Tengo las manos llenas de tierra!$"



SsAnne7F-7::
lock     
faceplayer     
msgbox Text_7, MSGBOX_DEFAULT
release     
end

Text_7:
.string "Deberías de estar en la fiesta,\n"
.string "pero ya que has venido te contaré\l"
.string "un secreto: la fiesta de verdad\l"
.string "está aquí, sin nuestro trabajo la\l"
.string "celebración de ahí fuera no sería\l"
.string "posible, me resulta mucho más\l"
.string "satisfactorio el hecho de\l"
.string "disfrutar del proceso que hace\l"
.string "algo posible que llegar al fin en\l"
.string "sí mismo.$"



SsAnne7F-8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "¡Estamos muy ocupados!\n"
.string "¡Tenemos que abastecer a todos los\l"
.string "invitados a la fiesta en un tiempo\l"
.string "récord!$"
