Goldenrod_ShopCenterP4_MapScripts::
	.byte 0

GoldenrodShopCenterP4-1::
end



GoldenrodShopCenterP4-2::
end



GoldenrodShopCenterP4-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Vaya, pensaba que aquí enseñaban\n"
.string "PUÑO DRENAJE. Me temo que tendré\l"
.string "que irme a lo más profundo del\l"
.string "MONTE MORTERO para que mi\l"
.string "POLIWRATH pueda aprenderlo.$"



GoldenrodShopCenterP4-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "¿¡50000 por BOMBA LODO!?\n"
.string "¿Sabes cuántos pantalones cortos\l"
.string "tendría que vender para reunir esa\l"
.string "cantidad?\l"
.string "Y lo duro que pegaría mi VENOMOTH\l"
.string "con ese movimiento también[.]$"



GoldenrodShopCenterP4-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "A este lugar le falta un ascensor,\n"
.string "me parece que construirán uno\l"
.string "pronto.$"



GoldenrodShopCenterP4-6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "¡Jah!\n"
.string "¡GOLPE CUERPO dice!\l"
.string "¡Mi GOLEM ni se inmuta con eso!$"
