Route18_Path_1F_MapScripts::
	.byte 0

Route18Path1F_1::
lock     
faceplayer     
msgbox Route18_Path1F_Text_1, MSGBOX_DEFAULT
release     
end

Route18_Path1F_Text_1:
	.string "I don't give a damn if you use a bike to\n"
	.string "get into the CYCLING ROAD or not;\l"
	.string "you're already on the blacklist. You're a\l"
	.string "lost cause, and I'm not going to bother\l"
	.string "trying to help you fit back into\l"
	.string "society.$"
