SsAnne_19F_MapScripts::
	.byte 0

SsAnne19F-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "¡A la gente como tú, un período de\n"
.string "reflexión bajo 4 paredes no le\l"
.string "vendría mal!$"



SsAnne19F-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Mi papá dice que vosotros sois\n"
.string "malos y deberíais de estar en la\l"
.string "cárcel.\l"
.string "¿Es verdad?$"
