BlackthornCity_Gym_MapScripts::
	.byte 0

BlackthornCity_Gym_Primer_Npc::
lock
faceplayer
msgbox BlackthornCity_Gym_Primer_Npc_Texto_1 MSGBOX_AUTOCLOSE
release
end

BlackthornCity_Gym_Primer_Npc_Texto_1:
	.string "Los miembros del clan de los dragones\n"
	.string "solo pueden usar POKÉMON del TIPO\l"
	.string "DRAGÓN si el MAESTRO se lo permite.$"

BlackthornCity_Gym_Segundo_Npc::
lock
faceplayer
msgbox BlackthornCity_Gym_Segundo_Npc_Texto_1 MSGBOX_AUTOCLOSE
release
end

BlackthornCity_Gym_Segundo_Npc_Texto_1:
	.string "Los dragones son POKÉMON sagrados.\n"
	.string "Están llenos de energía vital. Si no\l"
	.string "mantienes la seriedad, no podrás acabar\l"
	.string "con ellos.$"

BlackthornCity_Gym_Tercer_Npc::
lock
faceplayer
msgbox BlackthornCity_Gym_Tercer_Npc_Texto_1 MSGBOX_AUTOCLOSE
release
end

BlackthornCity_Gym_Tercer_Npc_Texto_1:
	.string "¿Dices que ya has conocido a LANCE el\n"
	.string "DOMADRAGONES? No es posible…$"

BlackthornCity_Gym_Cuarto_Npc::
lock
faceplayer
msgbox BlackthornCity_Gym_Cuarto_Npc_Texto_1 MSGBOX_AUTOCLOSE
release
end

BlackthornCity_Gym_Cuarto_Npc_Texto_1:
	.string "Sigo un entrenamiento muy estricto con\n"
	.string "DÉBORA. ¡Tienes suerte de haber ganado\l"
	.string "antes la MEDALLA DRAGÓN!$"

BlackthornCity_Gym_Quinto_Npc::
lock
faceplayer
msgbox BlackthornCity_Gym_Quinto_Npc_Texto_1 MSGBOX_AUTOCLOSE
release
end

BlackthornCity_Gym_Quinto_Npc_Texto_1:
	.string "Pareces haber combatido ya mucho\n"
	.string "frente a dragones. La mayoría que pisa\l"
	.string "este GIMNASIO ve un dragón aquí por\l"
	.string "primera vez. Es un tipo raro y poderoso.$"

BlackthornCity_Gym_Gym_Dude::
lock
faceplayer
msgbox BlackthornCity_Gym_Gym_Dude_Texto_1 MSGBOX_AUTOCLOSE
msgbox BlackthornCity_Gym_Gym_Dude_Texto_2 MSGBOX_AUTOCLOSE
release
end

BlackthornCity_Gym_Gym_Dude_Texto_1:
	.string "Oh, un aspirante. ¡Espera! ¡Ya tienes la\n"
	.string "MEDALLA DRAGÓN!$"

BlackthornCity_Gym_Gym_Dude_Texto_2:
	.string "Juraría que no ha habido aspirantes\n"
	.string "que hayan logrado derrotar a DÉBORA, y\l"
	.string "nuestro MAESTRO ANCIANO se retiró\l"
	.string "invicto, ¿cómo es eso posible?$"

BlackthornCity_Bald::
lock
faceplayer
msgbox BlackthornCity_Bald_Texto_1 MSGBOX_NPC
msgbox BlackthornCity_Bald_Texto_2 MSGBOX_NPC
msgbox BlackthornCity_Bald_Texto_3 MSGBOX_NPC
release
end

BlackthornCity_Bald_Texto_1:
	.string "DÉBORA ha desobedecido las órdenes del\n"
	.string "MAESTRO DRAGÓN y abierto el GIMNASIO\l"
	.string "financiado por LANCE.$"

BlackthornCity_Bald_Texto_2:
	.string "Nuestro MAESTRO ha perdido toda\n"
	.string "esperanza en su futuro, se ha vuelto\l"
	.string "engreída, arrogante y egoísta. Por\l"
	.string "fortuna, no es tan buena entrenadora\l"
	.string "como LANCE, a pesar de que crea tener\l"
	.string "madera de CAMPEONA.$"

BlackthornCity_Bald_Texto_3:
	.string "Algún día aparecerá alguien que le dé\n"
	.string "una cura de humildad.$"



