NaoAbandonada_3_MapScripts::
	.byte 0

NaoAbandonada_3_Naufragio::
lock
msgbox NaoAbandonada_3_Naufragio_Texto_1 MSGBOX_SIGN
msgbox NaoAbandonada_3_Naufragio_Texto_2 MSGBOX_SIGN
msgbox NaoAbandonada_3_Naufragio_Texto_3 MSGBOX_SIGN
msgbox NaoAbandonada_3_Naufragio_Texto_4 MSGBOX_SIGN
msgbox NaoAbandonada_3_Naufragio_Texto_5 MSGBOX_SIGN
msgbox NaoAbandonada_3_Naufragio_Texto_6 MSGBOX_SIGN
msgbox NaoAbandonada_3_Naufragio_Texto_7 MSGBOX_SIGN
msgbox NaoAbandonada_3_Naufragio_Texto_8 MSGBOX_SIGN
msgbox NaoAbandonada_3_Naufragio_Texto_9 MSGBOX_SIGN
release
end

NaoAbandonada_3_Naufragio_Texto_1:
	.string "… …$"

NaoAbandonada_3_Naufragio_Texto_2:
	.string "Es una hoja de papel muy desgastada\n"
	.string "por el paso del tiempo.$"

NaoAbandonada_3_Naufragio_Texto_3:
	.string "¿Quieres leerla?$"

NaoAbandonada_3_Naufragio_Texto_4:
	.string "…la noche era tranquila y estrellada.\n"
	.string "Con el mar en plena calma el viaje hacia\l"
	.string "PORTUAL estaba siendo muy placentero.\l"
	.string "Nada podía hacernos presagiar lo que\l"
	.string "estábamos a punto de vivir…$"

NaoAbandonada_3_Naufragio_Texto_5:
	.string "¿Seguir leyendo?$"

NaoAbandonada_3_Naufragio_Texto_6:
	.string "…todo empezó con el grito de un\n"
	.string "poderoso POKÉMON marino. A este grito\l"
	.string "le siguió un resplandor azul que, en\l"
	.string "contraste con la ausencia de luz,\l"
	.string "iluminó todo el cielo y dejó a todos los\l"
	.string "presentes impresionados…$"

NaoAbandonada_3_Naufragio_Texto_7:
	.string "…segundos después el resplandor azul\n"
	.string "desapareció, y de nuevo se hizo el\l"
	.string "silencio absoluto, pero eso duró poco…$"

NaoAbandonada_3_Naufragio_Texto_8:
	.string "…de repente, el grito del POKÉMON se\n"
	.string "escuchó de nuevo, era el mismo pero…\l"
	.string "esta vez distorsionado y en un tono\l"
	.string "desgarrador… todo el barco se tambaleó,\l"
	.string "como si un terremoto lo hubiera\l"
	.string "sacudido.$"

NaoAbandonada_3_Naufragio_Texto_9:
	.string "…después de ese grito, todo se\n"
	.string "convirtió en una lucha por sobrevivir.\l"
	.string "El POKÉMON sacudía el barco con una\l"
	.string "fuerza que ni un WAILORD adulto\l"
	.string "tendría. Quedamos encallados,\l"
	.string "atrapados aquí…$"
