Pass_RuinsOfAlphEast_MapScripts::
	.byte 0

RuinsOfAlphEast1::
lock     
faceplayer     
msgbox RuinsOfAlphEast_Text_1, MSGBOX_DEFAULT
release     
end

RuinsOfAlphEast_Text_1:
.string "Esos investigadores de las RUINAS\n"
.string "ALFA son unos incompetentes,\l"
.string "podrían tirarse 10 años de\l"
.string "investigación sin llegar a ninguna\l"
.string "conclusión.$"



RuinsOfAlphEast2::
lock     
faceplayer     
msgbox RuinsOfAlphEast_Text_2, MSGBOX_DEFAULT
release     
end

RuinsOfAlphEast_Text_2:
.string "Pensé que en este lugar\n"
.string "encontraría algún POKÉMON raro,\l"
.string "pero no hay nada, solo los restos\l"
.string "de lo que una vez fue.\l"
.string "¡Con eso no puedo presumir delante\l"
.string "de mis amigos en CIUDAD TRIGAL!$"



RuinsOfAlphEast3::
lock     
faceplayer     
msgbox RuinsOfAlphEast_Text_3, MSGBOX_DEFAULT
release     
end

RuinsOfAlphEast_Text_3:
.string "¿No te imaginas quién pudo hacer\n"
.string "algo así?\l"
.string "¿Y por qué?$"
