RocketHideout_5F_MapScripts::
	.byte 0

RocketHideout5F-2::
end



RocketHideout5F-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Nos interesa que KANTO crea que\n"
.string "somos una manada de inútiles sin\l"
.string "cerebro, no puedes defenderte\l"
.string "adecuadamente de algo que no\l"
.string "conoces.$"



RocketHideout5F-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "GIOVANNI es el mejor líder que\n"
.string "podemos tener, nunca dejará que el\l"
.string "TEAM ROCKET caiga.$"



RocketHideout5F-5::
end



RocketHideout5F-6::
end



RocketHideout5F-7::
end



RocketHideout5F-8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "Todo gran negocio se construye en\n"
.string "torno a un gran secreto oculto al\l"
.string "exterior chico, este lugar es uno\l"
.string "de nuestros grandes secretos\l"
.string "ocultos.$"



RocketHideout5F-9::
lock     
faceplayer     
msgbox Text_9, MSGBOX_DEFAULT
release     
end

Text_9:
.string "Estás en el ÁREA 1 de la verdadera\n"
.string "BASE ROCKET, aquí tratamos de\l"
.string "entender y extraer el máximo\l"
.string "potencial latente que los POKÉMON\l"
.string "NO LEGENDARIOS pueden ofrecernos,\l"
.string "lo que en algunos casos no es\l"
.string "poco.$"



RocketHideout5F-10::
lock     
faceplayer     
msgbox Text_10, MSGBOX_DEFAULT
release     
end

Text_10:
.string "Dicen que -Los 7 hábitos de la\n"
.string "gente altamente efectiva-, del\l"
.string "doctor Stephen Covey, hicieron que\l"
.string "GIOVANNI incrementase un 20% el\l"
.string "rendimiento palpable de la\l"
.string "organización.$"



RocketHideout5F-11::
lock     
faceplayer     
msgbox Text_11, MSGBOX_DEFAULT
release     
end

Text_11:
.string "-1984-, de George Orwell, -Un\n"
.string "mundo Feliz-, de Aldous Huxley y\l"
.string "-El hombre en busca de sentido-,\l"
.string "de Victor Frankl, son libros base\l"
.string "que recomendaría a cualquiera,\l"
.string "camarada.$"



RocketHideout5F-12::
end



RocketHideout5F-13::
end



RocketHideout5F-14::
lock     
faceplayer     
msgbox Text_14, MSGBOX_DEFAULT
release     
end

Text_14:
.string "Procura automatizar lo máximo\n"
.string "posible las transiciones entre\l"
.string "actividades, no les des respiro o\l"
.string "te perderás en ellas, y con ello\l"
.string "horas de tu tiempo cada día.$"



RocketHideout5F-15::
lock     
faceplayer     
msgbox Text_15, MSGBOX_DEFAULT
release     
end

Text_15:
.string "Los que gobiernan se conocen tan\n"
.string "bien las leyes que parece que\l"
.string "hacen trampas, es más, han\l"
.string "dispuesto las leyes para hacer\l"
.string "trampas, de modo que la única\l"
.string "alternativa es revelarse por la\l"
.string "fuerza, puesto que no existe tal\l"
.string "cosa como justicia.$"



RocketHideout5F-16::
lock     
faceplayer     
msgbox Text_16, MSGBOX_DEFAULT
release     
end

Text_16:
.string "El confort encarcela a la gente en\n"
.string "un miedo al dolor de umbral muy\l"
.string "bajo, es por eso que la población\l"
.string "de KANTO está como está.$"



RocketHideout5F-17::
lock     
faceplayer     
msgbox Text_17, MSGBOX_DEFAULT
release     
end

Text_17:
.string "El último siglo ha demostrado la\n"
.string "gran dependencia económica de la\l"
.string "ciencia, sea como sea, debemos\l"
.string "aceptar las reglas del juego, y si\l"
.string "tenemos que vender PORYGONS a\l"
.string "200000 POKÉS el ejemplar se\l"
.string "venden.$"



RocketHideout5F-18::
lock     
faceplayer     
msgbox Text_18, MSGBOX_DEFAULT
release     
end

Text_18:
.string "A veces las leyes de la naturaleza\n"
.string "pueden llegar a ser más fuertes\l"
.string "que nuestros anhelos personales,\l"
.string "PIDGEOT es el ave referencia de\l"
.string "KANTO entre los NO LEGENDARIOS, la\l"
.string "de mayor poder, con 479 STATS BASE\l"
.string "en su haber, ha debido de pasar\l"
.string "por un largo proceso hasta verse\l"
.string "convertido en un majestuoso\l"
.string "PIDGEOT, el cual, haciendo gala de\l"
.string "todo su poder latente y máximo\l"
.string "potencial, puede llegar a\l"
.string "experimentar el fenómeno de la\l"
.string "MEGA-EVOLUCIÓN, que lo catapulta\l"
.string "hasta los 579 STATS BASE[.]1 solo\l"
.string "punto menos que los 580\l"
.string "característicos de los 3 PÁJAROS\l"
.string "LEGENDARIOS, ¿coincidencia?, no lo\l"
.string "creo.\l"
.string "Es como si estos legendarios le\l"
.string "estuvieran diciendo: -no importa\l"
.string "lo que hagas, nosotros estamos\l"
.string "hechos de otra pasta, somos los\l"
.string "elegidos, haz lo que quieras que\l"
.string "nunca nos alcanzarás-, a pesar de\l"
.string "que aquí creemos que el potencial\l"
.string "puede amplificarse hasta límites\l"
.string "insospechados, también admitimos\l"
.string "la existencia de un tope marcado\l"
.string "por las propias leyes del\l"
.string "universo.$"



RocketHideout5F-19::
lock     
faceplayer     
msgbox Text_19, MSGBOX_DEFAULT
release     
end

Text_19:
.string "La ley de Parkinson sostiene que\n"
.string "el trabajo se expande hasta llenar\l"
.string "el tiempo del que se dispone para\l"
.string "su realización, de modo que si\l"
.string "tienes 12 horas para realizar una\l"
.string "tarea, la tendencia será acabarla\l"
.string "en 12, mientras que si te dieran 9\l"
.string "horas para esa misma tarea,\l"
.string "igualmente podrías acabarla en 9.\l"
.string "Por eso yo digo: págate a ti\l"
.string "primero, comienza el día con esa\l"
.string "clase de tareas importantes, pero\l"
.string "no urgentes, que a largo plazo\l"
.string "supondrían una gran diferencia\l"
.string "para ti, de este modo te servirías\l"
.string "de esta ley, ya que te verás\l"
.string "forzado a realizar esas tareas\l"
.string "importantes a la vez que urgentes\l"
.string "en menos tiempo, y créeme que lo\l"
.string "harás, cuando a un humano se le\l"
.string "obliga a activar todos sus\l"
.string "sentidos, su intuición, se le pone\l"
.string "contra las cuerdas, rinde más de\l"
.string "lo que nunca imaginaría, de lo\l"
.string "contrario la ley de Parkinson no\l"
.string "existiría.$"



RocketHideout5F-20::
end



RocketHideout5F-21::
lock     
faceplayer     
msgbox Text_21, MSGBOX_DEFAULT
release     
end

Text_21:
.string "¿Destino o libre albedrío?\n"
.string "La respuesta a esa pregunta no\l"
.string "depende de ti, así que cállate la\l"
.string "maldita boca y mueve el culo de\l"
.string "una vez, eso quizás si dependa de\l"
.string "ti, con eso basta.$"



RocketHideout5F-22::
end



RocketHideout5F-23::
lock     
faceplayer     
msgbox Text_23, MSGBOX_DEFAULT
release     
end

Text_23:
.string "El gobierno de LANCE está muy\n"
.string "cómodo en su posición, y ese es\l"
.string "precisamente su punto débil, se\l"
.string "han dormido en los laureles y lo\l"
.string "pagarán.$"



RocketHideout5F-24::
lock     
faceplayer     
msgbox Text_24, MSGBOX_DEFAULT
release     
end

Text_24:
.string "Genética, una palabra crucial.\n"
.string "¿Por qué un MAGIKARP es tan débil?\l"
.string "¿Por qué las aves sagradas son tan\l"
.string "fuertes?\l"
.string "Todo está en los genes, aquí\l"
.string "investigamos los límites de la\l"
.string "genética tratando de extraer el\l"
.string "máximo potencial posible de los\l"
.string "Pokémon más fuertes de la región.$"




RocketHideout5F-25::
lock     
faceplayer     
msgbox Text_25, MSGBOX_DEFAULT
release     
end

Text_25:
.string "Esta sala estaba reservada a hacer\n"
.string "balance de nuestros progresos y\l"
.string "establecer nuevos objetivos, sin\l"
.string "embargo de eso ya se encargan\l"
.string "otras áreas, supongo que ese es un\l"
.string "riesgo que corres al construir un\l"
.string "lugar así, cuanto más grande,\l"
.string "más espacio prescindible, aunque\l"
.string "mejor equivocarse por pasarse que\l"
.string "por no llegar.$"



RocketHideout5F-26::
end



RocketHideout5F-27::
lock     
faceplayer     
msgbox Text_27, MSGBOX_DEFAULT
release     
end

Text_27:
.string "No verás muchos entrenadores con\n"
.string "Pokémon como PINSIR, SCYTHER,\l"
.string "TAUROS, KANGASKHAN o las\l"
.string "evoluciones de EEVEE, todos\l"
.string "considerados Pokémon fuertes y\l"
.string "raros, y los 4 primeros\l"
.string "capturables en la ZONA SAFARI, lo\l"
.string "que en buena parte es razón de su\l"
.string "éxito.$"



RocketHideout5F-28::
lock     
faceplayer     
msgbox Text_28, MSGBOX_DEFAULT
release     
end

Text_28:
.string "La sensación de expectativas,\n"
.string "optimismo, planificación y grandes\l"
.string "planes de futuro que se respira\l"
.string "por aquí es única, ¿no la sientes?\l"
.string "Pasa una semana aquí y tendrás la\l"
.string "absoluta certeza de que podrás\l"
.string "lograr todo cuanto te propongas.$"



RocketHideout5F-29::
lock     
faceplayer     
msgbox Text_29, MSGBOX_DEFAULT
release     
end

Text_29:
.string "Alguien dijo una vez que obsesión\n"
.string "es la palabra que emplean los\l"
.string "perezosos para describir a los\l"
.string "dedicados, es casi un hecho que en\l"
.string "cuanto empiezes a destacar en algo\l"
.string "en mayor o menor medida van a\l"
.string "llamarte obsesionado, pero, ¿qué\l"
.string "hay de malo en querer explorar tus\l"
.string "límites sobre cualquier aspecto?,\l"
.string "eso solo puede fortalecerte y\l"
.string "hacerte más consciente de los\l"
.string "parámetros que rijen este mundo.$"



RocketHideout5F-30::
lock     
faceplayer     
msgbox Text_30, MSGBOX_DEFAULT
release     
end

Text_30:
.string "Desde aquí abogamos por el\n"
.string "progreso constante y gradual, pero\l"
.string "sabemos también del potencial\l"
.string "inigualable de la intuición y la\l"
.string "espontaneidad, solo tienes que ver\l"
.string "a un deportista inspirado para\l"
.string "darte cuenta de ese potencial,\l"
.string "cuando alguien está en el llamado\l"
.string "-estado de flujo-, es capaz de\l"
.string "marcar 5 goles en 10 minutos, o\l"
.string "destrozar con un parcial de 7\l"
.string "juegos a 0 al 11 veces campeón del\l"
.string "campeonato, controlar toda la\l"
.string "serie de variables que llevan a\l"
.string "esos estados es brutalmente\l"
.string "complicado, pero si pudiéramos\l"
.string "acceder a ese estado de forma\l"
.string "sostenida en el tiempo, sacaríamos\l"
.string "a relucir prácticamente el 100%\l"
.string "del potencial humano.$"



RocketHideout5F-31::
end



RocketHideout5F-32::
lock     
faceplayer     
msgbox Text_32, MSGBOX_DEFAULT
release     
end

Text_32:
.string "Pocos saben que el TEAM ROCKET no\n"
.string "fue fundado realmente por\l"
.string "GIOVANNI, sino que fue su madre,\l"
.string "MADAME BOSS, la fundadora inicial,\l"
.string "invirtió todos sus esfuerzos en\l"
.string "atrapar al legendario MEW, el\l"
.string "ancestro de todos los Pokémon allá\l"
.string "por 1975, si viera todo lo logrado\l"
.string "hasta ahora[.]$"



RocketHideout5F-33::
lock     
faceplayer     
msgbox Text_33, MSGBOX_DEFAULT
release     
end

Text_33:
.string "Ahí fuera se deforma la realidad\n"
.string "de tantas formas posibles, y es\l"
.string "entendible que lo hagan, en la\l"
.string "política o la religión, dos y dos\l"
.string "pueden sumar cinco, en este lugar\l"
.string "sin embargo es imposible pasar por\l"
.string "alto los hechos físicos, no puedes\l"
.string "engañar a las leyes fundamentales\l"
.string "de este mundo, si quieres\l"
.string "optimizar el rendimiento de un\l"
.string "Pokémon, o hallar el reparto\l"
.string "óptimo de STATS BASE, dos y dos\l"
.string "deben de sumar 4.$"



RocketHideout5F-34::
lock     
faceplayer     
msgbox Text_34, MSGBOX_DEFAULT
release     
end

Text_34:
.string "¿Por qué le damos tanta\n"
.string "importancia a los números y a los\l"
.string "resultados?\l"
.string "Tenemos la creencia de que todo,\l"
.string "desde esta ciudad a toda la\l"
.string "región, pasando por las estaciones\l"
.string "del año, el paso de las\l"
.string "generaciones y la propia vida,\l"
.string "todo eso existe precisamente para\l"
.string "que veamos que se puede hacer con\l"
.string "ello, que cambios podemos llevar a\l"
.string "cabo y hasta dónde se puede\l"
.string "estirar la potencialidad de todas\l"
.string "estas leyes naturales, el hacer un\l"
.string "progreso perceptible en un periodo\l"
.string "de tiempo razonable es uno de los\l"
.string "mayores propósitos con los que\l"
.string "podemos entrar en contacto con lo\l"
.string "que muchos en PUEBLO LAVANDA\l"
.string "llaman -la esencia-, eso hará que\l"
.string "apreciemos más tanto nuestro\l"
.string "entorno como el tiempo del que\l"
.string "disponemos, y para cumplir esto\l"
.string "hacen falta evaluaciones\l"
.string "constantes y periódicas, los\l"
.string "números son fundamentales.$"



RocketHideout5F-35::
lock     
faceplayer     
msgbox Text_35, MSGBOX_DEFAULT
release     
end

Text_35:
.string "La competencia hoy en día es\n"
.string "enorme chico, nunca más en la\l"
.string "historia volverá ningún otro\l"
.string "sector a ser tan importante como\l"
.string "para que el mero hecho de\l"
.string "participar en él sea suficiente\l"
.string "para construir una gran compañía.$"



RocketHideout5F-36::
lock     
faceplayer     
msgbox Text_36, MSGBOX_DEFAULT
release     
end

Text_36:
.string "Si la gente supiera los beneficios\n"
.string "que tiene sostener una pequeña\l"
.string "mejora a largo plazo, comenzarían\l"
.string "a ser constantes con todo cuanto\l"
.string "hicieren, ¿crees que mejorar 2 KG\l"
.string "al mes tu press de banca es una\l"
.string "mejora pésima?, sostén eso un año\l"
.string "y habrás mejorado 24 KG, si ya\l"
.string "levantabas 130 KG, de 130 KG a 154\l"
.string "la diferencia es muy notable,\l"
.string "ahora pareces más dificil, ¿eh?\l"
.string "Si realizas unos 10 entrenamientos\l"
.string "al mes, puedes ver cada uno de\l"
.string "esos entrenos como una oportunidad\l"
.string "de o construir o materializar esos\l"
.string "2 KG, viéndolo desde esta\l"
.string "perspectiva, psicológicamente da\l"
.string "la impresión de que pueda\l"
.string "progresarse hasta el infinito\l"
.string "aunque en la práctica no sea así[.]$"



RocketHideout5F-37::
lock     
faceplayer     
msgbox Text_37, MSGBOX_DEFAULT
release     
end

Text_37:
.string "¡Buajajajajajajjaja!\n"
.string "Tiene gracia, estamos a 40 metros\l"
.string "bajo tierra, pero tenemos a CIUDAD\l"
.string "AZULONA bajo nuestros pies, ¡desde\l"
.string "aquí lograremos controlarlo todo!$"



RocketHideout5F-38::
lock     
faceplayer     
msgbox Text_38, MSGBOX_DEFAULT
release     
end

Text_38:
.string "En el pasado nada se pierde, para\n"
.string "bien o para mal nada puede\l"
.string "deshacer tus acciones pasadas,\l"
.string "todo queda almacenado para\l"
.string "siempre, no es aniquilado por la\l"
.string "transitoriedad[.]y esa también es\l"
.string "otra forma de inmortalidad.$"



RocketHideout5F-39::
lock     
faceplayer     
msgbox Text_39, MSGBOX_DEFAULT
release     
end

Text_39:
.string "Dicen que pensar es gratis, que\n"
.string "irónico.\l"
.string "¡Le está saliendo carísimo a la\l"
.string "población de KANTO no hacerlo!$"



RocketHideout5F-40::
lock     
faceplayer     
msgbox Text_40, MSGBOX_DEFAULT
release     
end

Text_40:
.string "Tu equipo es imperfecto, puedo\n"
.string "verlo, aunque he de admitir que\l"
.string "para tus recursos, es un mucho\l"
.string "mejor equipo que el de toda esa\l"
.string "escoria que circula por las rutas\l"
.string "y ciudades comunes y se hacen\l"
.string "llamar entrenadores[.]los mejores\l"
.string "entrenadores de esta región no se\l"
.string "dejan ver tan facilmente.$"



RocketHideout5F-41::
end



RocketHideout5F-42::
lock     
faceplayer     
msgbox Text_42, MSGBOX_DEFAULT
release     
end

Text_42:
.string "NIDOKING y NIDOQUEEN, son dos de\n"
.string "los Pokémon más preciados por\l"
.string "nuestra organización, si te haces\l"
.string "con cualquiera de los dos todos\l"
.string "aquí te respetarán.$"



RocketHideout5F-43::
lock     
faceplayer     
msgbox Text_43, MSGBOX_DEFAULT
release     
end

Text_43:
.string "La fuente es un gran símbolo de\n"
.string "poder, abundancia de recursos y\l"
.string "jerarquía, nadie puede superar al\l"
.string "TEAM ROCKET, es por eso que\l"
.string "ordenamos construir una fuente 1,5\l"
.string "veces más grande que la de SILPH.$"



RocketHideout5F-44::
lock     
faceplayer     
msgbox Text_44, MSGBOX_DEFAULT
release     
end

Text_44:
.string "Este lugar es uno de los mayores\n"
.string "ejemplos del poder de la ciencia,\l"
.string "¿perdemos rendimiento, capacidad y\l"
.string "salud al estar desconectados de la\l"
.string "naturaleza?\l"
.string "Pues traemos la naturaleza hasta\l"
.string "nuestras oficinas, ¡SALVE\l"
.string "GIOVANNI!$"



RocketHideout5F-45::
lock     
faceplayer     
msgbox Text_45, MSGBOX_DEFAULT
release     
end

Text_45:
.string "El PRESIDENTE de SILPH y GIOVANNI\n"
.string "han mantenido siempre una intensa\l"
.string "rivalidad, si en SILPH se\l"
.string "enteraran de la existencia de esta\l"
.string "piscina, su PRESIDENTE es capaz de\l"
.string "construir una aún más grande con\l"
.string "tal de quedar mejor, aunque sea\l"
.string "colocándola en la azotea, pero la\l"
.string "construiría[.]$"



RocketHideout5F-46::
end



RocketHideout5F-47::
lock     
faceplayer     
msgbox Text_47, MSGBOX_DEFAULT
release     
end

Text_47:
.string "El precio de los objetos\n"
.string "incrementadores del nivel de\l"
.string "esfuerzo del POKÉMON (PROTEÍNA,\l"
.string "HIERRO[.])y la diferencia de\l"
.string "precios entre este lugar y el\l"
.string "exterior resume todo: aquí se dan\l"
.string "facilidades para que los soldados\l"
.string "de élite saquen lo mejor de sí,\l"
.string "allá afuera ponen todo tipo de\l"
.string "trabas al entrenador medio que no\l"
.string "puede permitirse esos precios\l"
.string "exhorbitantes, en cualquier caso,\l"
.string "si entrenas adecuadamente a tus\l"
.string "POKÉMON, a largo plazo no\l"
.string "necesitarás esos objetos, aunque\l"
.string "sí son útiles para ser más\l"
.string "selectivos con la estadística que\l"
.string "se quiera incrementar.$"



RocketHideout5F-48::
end



RocketHideout5F-49::
end



RocketHideout5F-50::
lock     
faceplayer     
msgbox Text_50, MSGBOX_DEFAULT
release     
end

Text_50:
.string "Lo cierto es que nuestra región no\n"
.string "tiene nada de especial, muchos\l"
.string "piensan que tenemos a los mejores\l"
.string "Pokémon, otros hasta creen que\l"
.string "solo existen los 150 de Kanto,\l"
.string "pero la realidad es que otras\l"
.string "regiones cuentan con Pokémon mucho\l"
.string "más poderosos de lo que aquí en\l"
.string "KANTO se pueda imaginar, algunas\l"
.string "como HOENN poseen 2\l"
.string "pseudolegendarios, en JOHTO LUGIA\l"
.string "y HO-OH tienen un poder que aquí\l"
.string "no vemos ni de cerca, HOENN\l"
.string "también, aquí sin embargo nuestro\l"
.string "único pseudolegendario, DRAGONITE,\l"
.string "y la leyenda MEW son nuestro tope,\l"
.string "con 600 de base, la única arma que\l"
.string "puede emplear KANTO para competir\l"
.string "en ese sentido con otras regiones\l"
.string "es el uso de su tecnología[.]$"



RocketHideout5F-51::
lock     
faceplayer     
msgbox Text_51, MSGBOX_DEFAULT
release     
end

Text_51:
.string "Esta gran mesa recopila los datos\n"
.string "fundamentales de los 15 Pokémon no\l"
.string "legendarios más poderosos de\l"
.string "nuestra región, es esencial\l"
.string "disponer de información acerca de\l"
.string "las herramientas disponibles,\l"
.string "tanto para ti como para tu\l"
.string "enemigo, ¿no crees?$"



RocketHideout5F-52::
lock     
faceplayer     
msgbox Text_52, MSGBOX_DEFAULT
release     
end

Text_52:
.string "¡Ilusos!\n"
.string "¡Creían que iban a limitarnos a\l"
.string "los servicios de curación básicos\l"
.string "y tenemos un sistema de recursos\l"
.string "privado 10 veces mejor que ese\l"
.string "despropósito de tiendas públicas!\l"
.string "¡Sírvete recluta, estás en tu casa\l"
.string "no encontrarás en ningún otro\l"
.string "lugar mayor variedad de productos\l"
.string "y a mejor precio!\l"
.string "¡Uajajajajja!\l"
.string "¡HAIL GIOVANNI!$"



RocketHideout5F-53::
lock     
faceplayer     
msgbox Text_53, MSGBOX_DEFAULT
release     
end

Text_53:
.string "No verás muchos entrenadores con\n"
.string "Pokémon como PINSIR, SCYTHER,\l"
.string "TAUROS, KANGASKHAN o las\l"
.string "evoluciones de EEVEE, todos\l"
.string "considerados Pokémon fuertes y\l"
.string "raros, y los 4 primeros\l"
.string "capturables en la ZONA SAFARI, lo\l"
.string "que en buena parte es razón de su\l"
.string "éxito.$"



RocketHideout5F-54::
lock     
faceplayer     
msgbox Text_54, MSGBOX_DEFAULT
release     
end

Text_54:
.string "El miedo es el peor enemigo del\n"
.string "progreso chico.$"



RocketHideout5F-55::
lock     
faceplayer     
msgbox Text_55, MSGBOX_DEFAULT
release     
end

Text_55:
.string "Nos lo hemos sabido montar\n"
.string "realmente bien, esos ricachones\l"
.string "que se pasan por el centro de\l"
.string "AZULONA y creen estar comprando\l"
.string "productos exclusivos no saben lo\l"
.string "que tenemos aquí, ¡quedáos con\l"
.string "vuestras tiendas no las\l"
.string "necesitamos!$"



RocketHideout5F-56::
lock     
faceplayer     
msgbox Text_56, MSGBOX_DEFAULT
release     
end

Text_56:
.string "A más de uno le explotaría la\n"
.string "cabeza si viera la que tenemos\l"
.string "aquí montada.$"



RocketHideout5F-57::
lock     
faceplayer     
msgbox Text_57, MSGBOX_DEFAULT
release     
end

Text_57:
.string "EXEGGUTOR o KINGLER son dos\n"
.string "Pokémon con estadísticas base\l"
.string "formidables que suelen pasar\l"
.string "desapercibidas, nadie diría que\l"
.string "KINGLER cuenta con 130 de base en\l"
.string "ataque físico, o EXEGGUTOR con 125\l"
.string "en ataque especial, sin embargo\l"
.string "ahí estan y a más de uno\l"
.string "sorprenden.$"



RocketHideout5F-58::
end



RocketHideout5F-59::
end



RocketHideout5F-60::
end
