LavenderRadioP4_MapScripts::
	.byte 0

LavenderRadioP4_1::
lock     
faceplayer     
msgbox LavenderRadioP4_Text_1, MSGBOX_DEFAULT
release     
end

LavenderRadioP4_Text_1:
.string "La MEGAEVOLUCIÓN incrementa en 100 los\n"
.string "STATS BASE de un POKÉMON. El FUERTE\l"
.string "VÍNCULO en 110, además de, por lo\l"
.string "general, un mejor reparto. Con las\l"
.string "modificaciones vía ondas de radio no\l"
.string "hay límite, pueden incrementarse en\l"
.string "menos de 100, pero es posible que\l"
.string "podamos sobrepasar esos +110 del\l"
.string "FUERTE VÍNCULO.$"




LavenderRadioP4_2::
lock     
faceplayer     
msgbox LavenderRadioP4_Text_2, MSGBOX_DEFAULT
release     
end

LavenderRadioP4_Text_2:
.string "Una idea empieza a ser interesante\n"
.string "cuando te asusta llevarla a su\l"
.string "conclusión lógica.$"




LavenderRadioP4_3::
lock     
faceplayer     
msgbox LavenderRadioP4_Text_3, MSGBOX_DEFAULT
release     
end

LavenderRadioP4_Text_3:
.string "La diferencia entre tecnología y\n"
.string "esclavitud es que los esclavos son\l"
.string "plenamente conscientes de que no son\l"
.string "libres.$"




LavenderRadioP4_5::
lock     
faceplayer     
msgbox LavenderRadioP4_Text_5, MSGBOX_DEFAULT
release     
end

LavenderRadioP4_Text_5:
.string "Oí que queríamos hacer ciertas pruebas\n"
.string "sobre estas ondas en el LAGO DE LA\l"
.string "FURIA, en JOHTO. ¿Será cierto?$"



LavenderRadioP4Documento_100::
msgbox LavenderRadioP4Documento_Text_100, MSGBOX_SIGN   
end

LavenderRadioP4Documento_Text_100:
.string "5to Optimización Ondas$"



LavenderRadioP4Documento_101::
msgbox LavenderRadioP4Documento_Text_101, MSGBOX_SIGN   
end

LavenderRadioP4Documento_Text_101:
.string "-Hay infinitas variaciones en cada\n"
	.string "generación, todas creadas por\l"
	.string "mutaciones-.$"

LavenderRadioP4_Devon_Combates::
msgbox LavenderRadioP4_Devon_Combates_Texto_1 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_2 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_3 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_4 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_5 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_6 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_7 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_8 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_9 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_10 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_11 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_12 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_13 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_14 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_15 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_16 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_17 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_18 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_19 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_20 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_21 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_22 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_23 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_24 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_25 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_26 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_27 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_28 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_29 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_30 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_31 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_32 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_33 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_34 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_35 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_36 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_37 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_38 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_39 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_40 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_41 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_42 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_43 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_44 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_45 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_46 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_47 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_48 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_49 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_50 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_51 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_52 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_53 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_54 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_55 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_56 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_57 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_58 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_59 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_60 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_61 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_62 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_63 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_64 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_65 MSGBOX_AUTOCLOSE
msgbox LavenderRadioP4_Devon_Combates_Texto_66 MSGBOX_AUTOCLOSE
release
end

LavenderRadioP4_Devon_Combates_Texto_1:
.string "OAK: Bienvenidos a todos los invitados\n"
	.string "a la apertura de TORRE RADIO, me\l"
	.string "hubiera gustado hacer de esta\l"
	.string "celebración algo más… del pueblo. Pero,\l"
	.string "como sabéis, los verdaderos propósitos\l"
	.string "de este lugar no son de dominio público.\l"
	.string "Después de años de disputas entre\l"
	.string "nosotros, al fin tenemos todos los\l"
	.string "recursos necesarios para alcanzar lo\l"
	.string "óptimo. La construcción de este lugar\l"
	.string "es prueba de ello. ELM, por favor.$"

LavenderRadioP4_Devon_Combates_Texto_2:
.string "ELM: Así es, OAK. Aquí hacemos lo\n"
	.string "prometido, sintonizamos para toda\l"
	.string "KANTO… en el primer y segundo piso.$"

LavenderRadioP4_Devon_Combates_Texto_3:
.string "El resto de pisos, desde el tercero al\n"
	.string "séptimo, están 100% dedicados a\l"
	.string "incrementar el rendimiento de un\l"
	.string "POKÉMON a través de explotar las ondas\l"
	.string "de radio.$"

LavenderRadioP4_Devon_Combates_Texto_4:
.string "Sus efectos pueden ser muy diversos.$"

LavenderRadioP4_Devon_Combates_Texto_5:
.string "La gran mayoría conducen a mutaciones\n"
	.string "que no nos interesan para el combate.$"

LavenderRadioP4_Devon_Combates_Texto_6:
.string "Determinadas frecuencias provocan un\n"
	.string "cambio de color en el POKÉMON\l"
	.string "expuesto, algo que sin duda agradará a\l"
	.string "aquellos POKEMANÍACOS que quieran\l"
	.string "fardar de algo sin ninguna aplicación\l"
	.string "real.$"

LavenderRadioP4_Devon_Combates_Texto_7:
.string "BILL: …$"

LavenderRadioP4_Devon_Combates_Texto_8:
.string "ELM: Aquí, por supuesto, vamos tras\n"
	.string "algo más grande. Vamos tras ese\l"
	.string "minúsculo porcentaje de mutaciones\l"
	.string "que benefician a un POKÉMON, que\l"
	.string "exprimen al máximo todas las\l"
	.string "combinaciones posibles por las cuales\l"
	.string "su potencial como especie alcance el\l"
	.string "100% de su potencial.$"

LavenderRadioP4_Devon_Combates_Texto_9:
.string "Aquí lograremos la combinación\n"
	.string "estadísticamente imposible, que la\l"
	.string "naturaleza habría otorgado durante un\l"
	.string "proceso de evolución de miles de años,\l"
	.string "a una especie que se hubiera adaptado\l"
	.string "de la mejor forma posible para\l"
	.string "incrementar su poder bruto. Sin\l"
	.string "disruptores, sin agentes externos que\l"
	.string "malogren la eficiencia del proceso.$"

LavenderRadioP4_Devon_Combates_Texto_10:
.string "OAK: NIDOKING-X, NIDOQUEEN-Y,\n"
	.string "PORYGON3… son ejemplos de lo obtenido\l"
	.string "por procesos similares a este, aunque\l"
	.string "no tan eficientes como los descritos\l"
	.string "por ELM aquí.$"

LavenderRadioP4_Devon_Combates_Texto_11:
.string "ELM: Así es, ahora disponemos de los\n"
	.string "medios para alcanzar la máxima pureza\l"
	.string "en cuanto prototipos se refiere.$"

LavenderRadioP4_Devon_Combates_Texto_12:
.string "OAK: MEWTWO supuso una mejora de 80\n"
	.string "STATS BASE respecto a MEW.\l"
	.string "Recientemente, las MEGAS y prototipos\l"
	.string "convencionales han supuesto un\l"
	.string "incremento de +100 respecto a los\l"
	.string "originales. El FUERTE VÍNCULO supone\l"
	.string "un +110… ¿Qué podemos esperar de esta\l"
	.string "nueva tecnología, ELM?$"

LavenderRadioP4_Devon_Combates_Texto_13:
.string "ELM: Es obvio que ya nos encontrábamos\n"
	.string "en un punto cercano al límite, en el que\l"
	.string "cualquier mejora significativa era\l"
	.string "prácticamente un espejismo.$"

LavenderRadioP4_Devon_Combates_Texto_14:
.string "Sin embargo, debido a estos procesos,\n"
	.string "estamos convencidos de poder\l"
	.string "incrementar en al menos 120 STATS BASE\l"
	.string "el poder inicial del POKÉMON objetivo.$"

LavenderRadioP4_Devon_Combates_Texto_15:
.string "BILL: Así de reservada es la naturaleza\n"
	.string "con sus mejores frutos, aquí solo\l"
	.string "crearemos POKÉMON que potencialmente\l"
	.string "podrían existir en estado salvaje,\l"
	.string "pero nunca lo harán por mera cuestión\l"
	.string "de probabilidad.$"

LavenderRadioP4_Devon_Combates_Texto_16:
.string "OAK: Exacto BILL, deberían de\n"
	.string "sucederse sendos milagros para que\l"
	.string "eso ocurriera.$"

LavenderRadioP4_Devon_Combates_Texto_17:
.string "ELM: Fin de la presentación. Hagamos\n"
	.string "una pequeña demostración de su\l"
	.string "funcionamiento, solo necesitamos\l"
	.string "activar el ordenador, y…$"

LavenderRadioP4_Devon_Combates_Texto_18:
.string "????: Ejecutivos, recopilad toda\n"
	.string "información disponible. Ocupáos de ELM,\l"
	.string "BILL y ANDRA. Yo me encargaré de OAK.$"

LavenderRadioP4_Devon_Combates_Texto_19:
.string "BILL: ¡Tú! ¿Cómo has podido? ¡Te\n"
	.string "rescaté cuando no tenías nada, te di\l"
	.string "trabajo en SILPH y así nos lo\l"
	.string "agradeces!$"

LavenderRadioP4_Devon_Combates_Texto_20:
.string "MIGUEL: Y eso querías, ¿no BILL? Que me\n"
	.string "sometiese a tus órdenes, creías que\l"
	.string "estaba destinado a ser <el ayudante de\l"
	.string "BILL>, y nada más. Eso se acabó.$"

LavenderRadioP4_Devon_Combates_Texto_21:
.string "Todos vosotros me habéis despreciado,\n"
	.string "habéis ignorado la MEGA PIEDRA de\l"
	.string "AERODACTYL que yo creé$"

LavenderRadioP4_Devon_Combates_Texto_22:
.string "OAK: BLAINE extrajo ya su poder\n"
	.string "primigenio sin necesidad de MEGA\l"
	.string "PIEDRA.$"

LavenderRadioP4_Devon_Combates_Texto_23:
.string "MIGUEL: ¿Y qué hay de GENESECT? ¿El\n"
	.string "resto de FÓSILES? Habéis pasado por\l"
	.string "alto todas mis investigaciones.$"

LavenderRadioP4_Devon_Combates_Texto_24:
.string "Hasta tú, {PLAYER}, con esa mirada de\n"
	.string "condescendencia que me echaste en la\l"
	.string "reunión. ¿Crees que no estoy a tu\l"
	.string "altura?$"

LavenderRadioP4_Devon_Combates_Texto_25:
.string "OAK: Ya es suficiente, ¿qué es lo que\n"
	.string "quieres?$"

LavenderRadioP4_Devon_Combates_Texto_26:
.string "MIGUEL: Hacer de DEVON la corporación\n"
	.string "más poderosa, y veros caer a todos. No\l"
	.string "os imagináis la de POKÉMON antiguos y\l"
	.string "ancestrales que habitan en HOENN. Es\l"
	.string "allí donde debí haber nacido, no en\l"
	.string "este asqueroso corporativismo que va\l"
	.string "en contra de mis intereses.$"

LavenderRadioP4_Devon_Combates_Texto_27:
.string "????: No puedes evitar que obtengamos\n"
	.string "lo que queremos de aquí, OAK. Solo te\l"
	.string "queda pelear.$"

LavenderRadioP4_Devon_Combates_Texto_28:
.string "MIGUEL: {PLAYER} es mío. Vas a ser\n"
	.string "derrotado, voy a desgastarte hasta\l"
	.string "que debas arrodillarte ante mí por pura\l"
	.string "probabilidad.$"

LavenderRadioP4_Devon_Combates_Texto_29:
.string "¡Científicos! ¡A él!$"

LavenderRadioP4_Devon_Combates_Texto_30:
.string "Se acabaron las reverencias, el honor y\n"
	.string "demás sandeces. Te derrotaré sin\l"
	.string "importar los medios ni la forma.$"

LavenderRadioP4_Devon_Combates_Texto_31:
.string "Así que el famoso {PLAYER}. ¿Qué se\n"
	.string "sentirá al pelear contra ti?$"

LavenderRadioP4_Devon_Combates_Texto_32:
.string "Solo eres un ENTRENADOR más.$"

LavenderRadioP4_Devon_Combates_Texto_33:
.string "¡Te mostraré que ese vínculo del que\n"
	.string "habláis no son más que pamplinas!$"

LavenderRadioP4_Devon_Combates_Texto_34:
.string "¿Entonces ese fenómeno es real?$"

LavenderRadioP4_Devon_Combates_Texto_35:
.string "MIGUEL: Esperable, pero mis nuevos\n"
	.string "ayudantes te han desgastado lo\l"
	.string "suficiente.$"

LavenderRadioP4_Devon_Combates_Texto_36:
.string "Solo espera a ver el nuevo equipo que\n"
	.string "mis investigaciones, y DEVON, me han\l"
	.string "procurado.$"

LavenderRadioP4_Devon_Combates_Texto_37:
.string "¡Seré yo quién al fin derrote al gran\n"
	.string "ADMIN.JEFE {PLAYER}!$"

LavenderRadioP4_Devon_Combates_Texto_38:
.string "¿¡Otra vez!? ¿Por qué sigue ocurriendo?$"

LavenderRadioP4_Devon_Combates_Texto_39:
.string "????: Entonces este es tu nivel, OAK.\n"
	.string "Gracias, me has proporcionado una\l"
	.string "valiosa información, aparte de las\l"
	.string "ondas de radio.$"

LavenderRadioP4_Devon_Combates_Texto_40:
.string "OAK: …$"

LavenderRadioP4_Devon_Combates_Texto_41:
.string "EJECUTIVO: Ya hemos transferido todos\n"
	.string "sus datos a la SEDE DEVON: S12,\l"
	.string "PRESIDENTE.$"

LavenderRadioP4_Devon_Combates_Texto_42:
.string "????: Ha sido un placer, OAK. Gracias\n"
	.string "por vuestra colaboración.$"

LavenderRadioP4_Devon_Combates_Texto_43:
.string "MIGUEL: Grrrr… Espera a ver, {PLAYER}.\n"
	.string "Este es solo el inicio de una gran\l"
	.string "generación de FÓSILES ante los que\l"
	.string "acabarás sucumbiendo. Más te vale no\l"
	.string "volver a cruzarte conmigo.$"

LavenderRadioP4_Devon_Combates_Texto_44:
.string "BILL: ¡Maldición! ¿Qué acaba de ocurrir\n"
	.string "aquí?$"

LavenderRadioP4_Devon_Combates_Texto_45:
.string "OAK: Que tu ayudante nos ha\n"
	.string "traicionado, BILL. A saber cuánto\l"
	.string "tiempo llevaba asociado con DEVON,\l"
	.string "debimos prestarle más atención.$"

LavenderRadioP4_Devon_Combates_Texto_46:
.string "ELM: Pero… Él estuvo en la II GRAN\n"
	.string "REUNIÓN, sabe de prácticamente todos\l"
	.string "nuestros proyectos, de los prototipos,\l"
	.string "MEWTWO…$"

LavenderRadioP4_Devon_Combates_Texto_47:
.string "OAK: Así es, DEVON estará al tanto de\n"
	.string "todo a estas alturas. Solo nos queda\l"
	.string "informar a GIOVANNI de esto, yo lo\l"
	.string "haré.$"

LavenderRadioP4_Devon_Combates_Texto_48:
.string "ELM: Debemos actuar rápido, GIOVANNI\n"
	.string "es experto en ello. Vosotros dos, ANDRA\l"
	.string "y {PLAYER}, seguro que desempeñaréis\l"
	.string "un papel esencial en la respuesta a\l"
	.string "DEVON.$"

LavenderRadioP4_Devon_Combates_Texto_49:
.string "ANDRA: …$"

LavenderRadioP4_Devon_Combates_Texto_50:
.string "OAK: BILL, ELM, esto no puede hacer más\n"
	.string "que unirnos, en la búsqueda del límite\l"
	.string "biológico que acabamos de resaltar\l"
	.string "aquí.$"

LavenderRadioP4_Devon_Combates_Texto_51:
.string "ANDRA: ¿Qué te ha parecido, {PLAYER}?$"

LavenderRadioP4_Devon_Combates_Texto_52:
.string "…$"

LavenderRadioP4_Devon_Combates_Texto_53:
.string "No… no me refería al ataque de DEVON,\n"
	.string "más bien… a todo lo expuesto por ELM y\l"
	.string "OAK. Desde que derrotaste al POKÉMON\l"
	.string "ESENCIA, y ya en la I GRAN REUNIÓN, me\l"
	.string "temía todo esto.$"

LavenderRadioP4_Devon_Combates_Texto_54:
.string "Si te digo la verdad, choca\n"
	.string "completamente con mi ideal de cómo\l"
	.string "deberían funcionar las cosas en un\l"
	.string "combate POKÉMON.$"

LavenderRadioP4_Devon_Combates_Texto_55:
.string "El vínculo e interacciones que has ido\n"
	.string "forjando con los tuyos, debería ser el\l"
	.string "elemento más importante a la hora de\l"
	.string "determinar el rendimiento de tu equipo,\l"
	.string "sin embargo…$"

LavenderRadioP4_Devon_Combates_Texto_56:
.string "El futuro nos impulsa a esa dictadura\n"
	.string "de lo mecánico, el rendimiento de un\l"
	.string "POKÉMON va a estar programado de\l"
	.string "antemano, y lo que es peor…$"

LavenderRadioP4_Devon_Combates_Texto_57:
.string "Anulará completamente a cualquier otro\n"
	.string "ENTRENADOR, al menos en cuanto\l"
	.string "potencial de STATS BASE. Le hará ver\l"
	.string "ridículo ante esa perfección creada\l"
	.string "artificialmente.$"

LavenderRadioP4_Devon_Combates_Texto_58:
.string "Supongo que al final buscamos lo mismo\n"
	.string "que ZEUS o LANCE, pero haciendo uso de\l"
	.string "la tecnología.$"

LavenderRadioP4_Devon_Combates_Texto_59:
.string "Pero no, el FUERTE VÍNCULO ha\n"
	.string "demostrado que el potencial de un\l"
	.string "POKÉMON, desde su más profunda\l"
	.string "esencia, puede ser moldeable si crees\l"
	.string "en ello. Tú llevaste eso al extremo en\l"
	.string "RUINAS ALFA.$"

LavenderRadioP4_Devon_Combates_Texto_60:
.string "Me niego a pensar que ese potencial ya\n"
	.string "ha mostrado todo lo que tiene. Más aún\l"
	.string "en resignarme a que puede ser\l"
	.string "procesado y mecanizado, tal y cómo\l"
	.string "están haciendo con los PERROS\l"
	.string "LEGENDARIOS y los EEVEE FUERTE\l"
	.string "VÍNCULO.$"

LavenderRadioP4_Devon_Combates_Texto_61:
.string "…$"

LavenderRadioP4_Devon_Combates_Texto_62:
.string "Si existe o no un poder mayor, accesible\n"
	.string "mediante el entrenamiento y que hemos\l"
	.string "pasado por alto, me es imposible\l"
	.string "hallarlo en medio de este ambiente.$"

LavenderRadioP4_Devon_Combates_Texto_63:
.string "Es por ello que desapareceré por una\n"
	.string "temporada, y me centraré\l"
	.string "completamente en esa búsqueda.$"

LavenderRadioP4_Devon_Combates_Texto_64:
.string "Sé que puedo estar yendo tras un\n"
	.string "fantasma, un ideal creado en mi cabeza,\l"
	.string "que ni siquiera existe. Pero ante este\l"
	.string "panorama, siento la obligación de\l"
	.string "hacerlo.$"

LavenderRadioP4_Devon_Combates_Texto_65:
.string "Incluso tú, {PLAYER}, has aunado\n"
	.string "tecnología con tradición. Quizás ahí\l"
	.string "esté tu virtud, no como OAK o BILL,\l"
	.string "incapaces de ver más allá de sus\l"
	.string "experimentos, o yo misma, en el otro\l"
	.string "extremo.$"

LavenderRadioP4_Devon_Combates_Texto_66:
.string "Aún así… me mantendré fiel a mis\n"
	.string "ideales.$"
