Goldenrod_RadioTowerP6_MapScripts::
	.byte 0


Goldenrod_RadioTowerP6_Cartel::
lock
msgbox Goldenrod_RadioTowerP6_Cartel_Texto_1 MSGBOX_SIGN
release
end

Goldenrod_RadioTowerP6_Cartel_Texto_1:
	.string "F5 - RADIO WAVES APPLIED TO A\n"
	.string "POKÉMON'S PERFORMANCE$"

Goldenrod_RadioTowerP7_Cartel::
lock
msgbox Goldenrod_RadioTowerP7_Cartel_Texto_1 MSGBOX_SIGN
release
end

Goldenrod_RadioTowerP7_Cartel_Texto_1:
	.string "F6 - MAXIMIZING OF PERFORMANCE OF\n"
	.string "RADIO WAVES$"

Goldenrod_RadioTowerP8_Cartel::
lock
msgbox Goldenrod_RadioTowerP8_Cartel_Texto_1 MSGBOX_SIGN
release
end

Goldenrod_RadioTowerP8_Cartel_Texto_1:
	.string "F7 - OPTIMIZATION OF PERFORMANCE OF\n"
	.string "RADIO WAVES$"

Goldenrod_RadioTowerP9_Cartel::
lock
msgbox Goldenrod_RadioTowerP9_Cartel_Texto_1 MSGBOX_SIGN
release
end

Goldenrod_RadioTowerP9_Cartel_Texto_1:
	.string "F8 - EFFICIENCY IN THE USAGE OF\n"
	.string "RADIO WAVES$"

Goldenrod_RadioTowerP10_Cartel::
lock
msgbox Goldenrod_RadioTowerP10_Cartel_Texto_1 MSGBOX_SIGN
release
end

Goldenrod_RadioTowerP10_Cartel_Texto_1:
	.string "F9 - APPLIED THEORY:\p"
	.string "FUNCTIONING OF RADIO WAVES$"


Goldenrod_RadioTowerP6_NPC_1::
lock
faceplayer
msgbox Goldenrod_RadioTowerP6_NPC_1_Texto_1 MSGBOX_NPC
delay 10
msgbox Goldenrod_RadioTowerP6_NPC_1_Texto_2 MSGBOX_NPC
release
end

Goldenrod_RadioTowerP6_NPC_1_Texto_1:
	.string "The first ever radio wave was\n"
	.string "transmitted back in 1897.$"

Goldenrod_RadioTowerP6_NPC_1_Texto_2:
	.string "It's been a long road, yet we're far from\n"
	.string "reaching its end.$"

Goldenrod_RadioTowerP6_NPC_2::
lock
faceplayer
msgbox Goldenrod_RadioTowerP6_NPC_2_Texto_1 MSGBOX_NPC
delay 10
msgbox Goldenrod_RadioTowerP6_NPC_2_Texto_2 MSGBOX_NPC
release
end

Goldenrod_RadioTowerP6_NPC_2_Texto_1:
	.string "The RADIO TOWER has hired some\n"
	.string "security experts, some from KANTO.$"

Goldenrod_RadioTowerP6_NPC_2_Texto_2:
	.string "We're learning a lot from them.$"

Goldenrod_RadioTowerP6_NPC_3::
lock
faceplayer
msgbox Goldenrod_RadioTowerP6_NPC_3_Texto_1 MSGBOX_NPC
release
end

Goldenrod_RadioTowerP6_NPC_3_Texto_1:
	.string "There's power in the unknown, and many\n"
	.string "pervert it for evil.$"

Goldenrod_RadioTowerP6_NPC_4::
lock
faceplayer
msgbox Goldenrod_RadioTowerP6_NPC_4_Texto_1 MSGBOX_NPC
delay 10
msgbox Goldenrod_RadioTowerP6_NPC_4_Texto_2 MSGBOX_NPC
release
end

Goldenrod_RadioTowerP6_NPC_4_Texto_1:
	.string "Not anyone can get in here.$"

Goldenrod_RadioTowerP6_NPC_4_Texto_2:
	.string "Standing here, talking to me, means you\n"
	.string "could only be among the elite, no?$"

