RocketHideout_JohtoP1_MapScripts::
	.byte 0

RocketHideoutP1_1::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_1, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_1:
	.string "Dealing with occasional, sharp spikes in\n"
	.string "stress's way better than having it\l"
	.string "prick in the back of your head every\l"
	.string "waking moment.$"



RocketHideoutP1_2::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_2, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_2:
	.string "With our technology, we've been able to\n"
	.string "replicate several of the MEGA STONES\l"
	.string "that are very rarely found in nature.\l"
	.string "We've even created some new ones for\l"
	.string "POKÉMON with MEGA EVOLUTION potential,\l"
	.string "such as FLYGON or MILOTIC.$"



RocketHideoutP1_3::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_3, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_3:
	.string "Here we are turning excellence and\n"
	.string "perfection into the norm. Don't you find\l"
	.string "that demotivating? If everyone's\l"
	.string "super… then no one will be, and our\l"
	.string "achievements, no matter how good they\l"
	.string "are, will just be another drop in the\l"
	.string "bucket.$"



RocketHideoutP1_4::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_4, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_4:
	.string "How does it feel to be the\n"
	.string "administrator of all this?$"



RocketHideoutP1_5::
end



RocketHideoutP1_6::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_6, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_6:
	.string "BUTTERFREE is the only known POKÉMON\n"
	.string "to have both a MEGA EVOLUTION and a\l"
	.string "DEEP BOND form, which we were able to\l"
	.string "study after your battle with KURT. This\l"
	.string "allowed us to compare the differences\l"
	.string "between a MEGA and a DEEP BOND within a\l"
	.string "species. The conclusion was as\l"
	.string "expected: the DEEP BOND yields an even\l"
	.string "more drastic performance improvement\l"
	.string "than the MEGA EVOLUTION. With its +110\l"
	.string "BASE and only 5 in PHYSICAL ATTACK,\l"
	.string "KURT's BUTTERFREE surpasses the MEGA\l"
	.string "BUTTERFREE by 20 BASE points. It's much\l"
	.string "more resilient and has similar offensive\l"
	.string "capabilities, although the MEGA form\l"
	.string "manages to be slightly faster.$"



RocketHideoutP1_7::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_7, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_7:
	.string "Creating custom MEGA STONES for\n"
	.string "FLYGON and MILOTIC was an arduous\l"
	.string "task, but we finally succeeded. It's a\l"
	.string "significant step toward potentially\l"
	.string "developing even more powerful MEGA\l"
	.string "STONES.$"



RocketHideoutP1_8::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_8, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_8:
	.string "The natural world discourages\n"
	.string "excessive specialization because it\l"
	.string "hampers evolution and renders POKÉMON\l"
	.string "more susceptible. Luckily,\l"
	.string "advancements in technology and\l"
	.string "science enable us to circumvent this\l"
	.string "fundamental principle.$"



RocketHideoutP1_9::
end



RocketHideoutP1_10::
end



RocketHideoutP1_11::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_11, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_11:
	.string "Many would consider the power levels we\n"
	.string "are dealing with here absurd. A\l"
	.string "NON-LEGENDARY POKÉMON with 700 BASE\l"
	.string "STATS. Who would have thought!$"



RocketHideoutP1_12::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_12, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_12:
	.string "What's in this room is impossible for 99%\n"
	.string "of the common population; I doubt they\l"
	.string "would even understand the power\l"
	.string "written in these documents. For them,\l"
	.string "the best NON-LEGENDARY will continue\l"
	.string "to be DRAGONITE.$"



RocketHideoutP1_13::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_13, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_13:
	.string "Imagine having a MEGA HOUNDOOM!\n"
	.string "Everyone would kneel to me the moment\l"
	.string "I release it from its POKÉ BALL!$"



RocketHideoutP1_14::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_14, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_14:
	.string "GIOVANNI always refused to be a puppet\n"
	.string "manipulated by LANCE's strings, which is\l"
	.string "the reason why TEAM ROCKET is where it\l"
	.string "is today.$"



RocketHideoutP1_15::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_15, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_15:
	.string "Occasionally tell the truth so that\n"
	.string "your lies are more believable. TEAM\l"
	.string "ROCKET RULES!$"



RocketHideoutP1_16::
end



RocketHideoutP1_17::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_17, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_17:
	.string "Usually, it's not enough to have\n"
	.string "success. The rest must fail!$"



RocketHideoutP1_18::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_18, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_18:
	.string "Do you think POKÉMON will lose their\n"
	.string "true essence if we modify their IVs?$"



RocketHideoutP1_19::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_19, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_19:
	.string "In JOHTO, there's more than one TRAINER\n"
	.string "who could have brought down the\l"
	.string "dictator LANCE, but they're very well\l"
	.string "hidden.$"



RocketHideoutP1_20::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_20, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_20:
	.string "The IVs of any POKÉMON are no longer a\n"
	.string "mystery to us; you can max them all out\l"
	.string "to 31 thanks to the system we've\l"
	.string "created.$"



RocketHideoutP1_21::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_21, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_21:
	.string "The POKÉMON of CHIEF ADMIN. ANDRA are\n"
	.string "incredibly strong; it's as if knowing\l"
	.string "they have a lower limit than a\l"
	.string "LEGENDARY has had the opposite effect,\l"
	.string "making them feel unrestricted.$"



RocketHideoutP1_22::
end



RocketHideoutP1_23::
lock
faceplayer
msgbox RocketHideoutP1_23_Texto_1, MSGBOX_NPC
release
end

RocketHideoutP1_23_Texto_1:
	.string "It's wiser to avoid pain out of prudence\n"
	.string "than to seek pleasure out of\l"
	.string "impatience.$"



RocketHideoutP1_24::
end



RocketHideoutP1_25::
lock
faceplayer
msgbox RocketHideoutP1_25_Texto_1, MSGBOX_NPC
release
end

RocketHideoutP1_25_Texto_1:
	.string "The highest risk is to not take any risk.$"



RocketHideoutP1_26::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_26, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_26:
	.string "Claiming the existence of a limit\n"
	.string "without actually knowing where it is\l"
	.string "and saying such a limit doesn't exist\l"
	.string "are effectively the same in practice.\l"
	.string "This is the dilemma encapsulated in the\l"
	.string "famous phrase: there is no limit.$"



RocketHideoutP1_27::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_27, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_27:
	.string "Here is where the variables of nature\n"
	.string "have transformed into an open book for\l"
	.string "us.$"



RocketHideoutP1_28::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_28, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_28:
	.string "In the darkness, imagination operates\n"
	.string "more actively than in broad daylight.$"



RocketHideoutP1_29::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_29, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_29:
	.string "Randomness isn't always bad; it can be\n"
	.string "much fairer than intelligence, even. If\l"
	.string "people were strictly rewarded based on\l"
	.string "their abilities, things would be even\l"
	.string "more unfair because we don't choose our\l"
	.string "abilities. Chance produces the\l"
	.string "beneficial effect of reshuffling the\l"
	.string "cards of society, enabling the\l"
	.string "perennially fortunate to be defeated.$"



RocketHideoutP1_30::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_30, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_30:
	.string "Our psychology conspires against\n"
	.string "ourselves: people prefer to head\l"
	.string "toward a specific destination rather\l"
	.string "than face a certain degree of\l"
	.string "uncertainty, even if it's beneficial.$"



RocketHideoutP1_31::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_31, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_31:
	.string "In practice, there is no long term; what\n"
	.string "matters is what happens before that\l"
	.string "long term. The problem with using the\l"
	.string "notion of the long term is that it tends\l"
	.string "to make us blind to what occurs before\l"
	.string "the long term.$"



RocketHideoutP1_32::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_32, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_32:
	.string "Libraries are filled with books about\n"
	.string "how someone achieved success; there\l"
	.string "are barely any with titles like 'What I\l"
	.string "Learned from Ruining Myself.' We have a\l"
	.string "preference for doing something rather\l"
	.string "than doing nothing, even in cases where\l"
	.string "taking action is harmful.$"



RocketHideoutP1_33::
end



RocketHideoutP1_34::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_34, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_34:
	.string "GIOVANNI rebelled against his own fate,\n"
	.string "the one that said he would always lose\l"
	.string "against the 10-year-old kid in charge,\l"
	.string "and the best part is that all those\l"
	.string "fools out there believe it's true.$"



RocketHideoutJohtoP1Documento_100::
lock        
msgbox RocketHideoutJohtoP1Documento_Text_100, MSGBOX_DEFAULT
msgbox RocketHideoutJohtoP1Documento_Text_101, MSGBOX_DEFAULT
release     
end

RocketHideoutJohtoP1Documento_Text_100:
.string "TECHNIQUES USED BY OAK:\n"
	.string "… Our support for LANCE was rooted in\l"
	.string "two things. Information flow and\l"
	.string "bolstered prestige by association with\l"
	.string "the POKÉMON LEAGUE, the entity that\l"
	.string "would snuff the war that nearly ended\l"
	.string "the region. Once that first domino\l"
	.string "toppled, the masses' newfound trust\l"
	.string "gave us leeway to clean up information\l"
	.string "as desired, from libraries to mere\l"
	.string "posters. To blot the outside world and\l"
	.string "guide our people's thoughts.$"


RocketHideoutJohtoP1Documento_Text_101:
	.string "It's a self-feeding cycle, and the\n"
	.string "further it goes, the less evidence\l"
	.string "there'll be to fight it. Regulating\l"
	.string "foreign species like CYNDAQUIL and\l"
	.string "MARILL in KANTO is undoubtedly\l"
	.string "fruitless, but we can make it impossible\l"
	.string "to prove that these POKÉMON belong to\l"
	.string "another region. Without a POKÉDEX or an\l"
	.string "official compilation of KANTO POKÉMON,\l"
	.string "the masses will just assume they're\l"
	.string "part of KANTO's 151 without bothering\l"
	.string "to actually list them one by one to\l"
	.string "check against that number.$"



RocketHideoutJohtoP1Documento_102::
lock       
msgbox RocketHideoutJohtoP1Documento_Text_102, MSGBOX_DEFAULT
release     
end

RocketHideoutJohtoP1Documento_Text_102:
.string "OPTIMAL INVESTMENT AND FINANCING\n"
	.string "DECISIONS IN THE COMPANY$"



RocketHideoutJohtoP1Documento_103::
lock        
showmonpic SPECIES_BUTTERFREE_MEGA, 10, 3 
playmoncry SPECIES_BUTTERFREE, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_103, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_103:
.string "MEGA BUTTERFREE:\p"
	.string "HP: 60\n"
	.string "ATTACK: 15\l"
	.string "DEFENSE: 50\l"
	.string "SPECIAL ATTACK: 140\l"
	.string "SPECIAL DEFENSE: 108\l"
	.string "SPEED: 122\l"
	.string "TOTAL: 495\p"
	.string "MEGA BEEDRILL's counterpart with\n"
	.string "respect to the SPECIAL STATs. It bears\l"
	.string "less potency, but boasts superior\l"
	.string "DEFENSEs. It also has the ABILITY\l"
	.string "ADAPTABILITY and more powerful moves\l"
	.string "like PSYCHIC and BUG BUZZ.$"



RocketHideoutJohtoP1Documento_104::
lock        
showmonpic SPECIES_VENUSAUR_MEGA, 10, 3 
playmoncry SPECIES_VENUSAUR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_104, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_104:
.string "MEGA VENUSAUR:\p"
	.string "HP: 90\n"
	.string "ATTACK: 100\l"
	.string "DEFENSE: 123\l"
	.string "SPECIAL ATTACK: 123\l"
	.string "SPECIAL DEFENSE: 132\l"
	.string "SPEED: 80\l"
	.string "TOTAL: 648\p"
	.string "Among the bulkiest tanks exceeding 120\n"
	.string "in three STATs. Its ABILITY THICK FAT\l"
	.string "allows it to neutrally endure FIRE and\l"
	.string "ICE. Only FLYING and PSYCHIC remain as\l"
	.string "its sole weaknesses.$"



RocketHideoutJohtoP1Documento_105::
lock        
showmonpic SPECIES_CHARIZARD_MEGA_X, 10, 3 
playmoncry SPECIES_CHARIZARD, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_105, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_105:
.string "CHARIZARD-X:\p"
	.string "HP: 78\n"
	.string "ATTACK: 135\l"
	.string "DEFENSE: 111\l"
	.string "SPECIAL ATTACK: 130\l"
	.string "SPECIAL DEFENSE: 95\l"
	.string "SPEED: 100\l"
	.string "TOTAL: 649\p"
	.string "Its existence demonstrates the DRAGON\n"
	.string "latent in CHARIZARD's evolutionary\l"
	.string "line. Its toughened flesh boasts an\l"
	.string "extreme ATTACK and DEFENSE exceeding\l"
	.string "those of even PSEUDO-LEGENDARY\l"
	.string "DRAGONs. And it maintains a base of 100\l"
	.string "SPEED while retaining an all-around\l"
	.string "neutrally effective FIRE-DRAGON pair.$"



RocketHideoutJohtoP1Documento_106::
lock        
showmonpic SPECIES_CHARIZARD_MEGA_Y, 10, 3 
playmoncry SPECIES_CHARIZARD, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_106, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_106:
.string "CHARIZARD-Y:\p"
	.string "HP: 78\n"
	.string "ATTACK: 104\l"
	.string "DEFENSE: 83\l"
	.string "SPECIAL ATTACK: 159\l"
	.string "SPECIAL DEFENSE: 115\l"
	.string "SPEED: 110\l"
	.string "TOTAL: 649\p"
	.string "The best example of the power gained\n"
	.string "through MEGA EVOLUTION. Its DROUGHT\l"
	.string "rivals KYOGRE's PRIMORDIAL SEA, and its\l"
	.string "SPECIAL ATTACK exceeds that of that\l"
	.string "beast of HOENN. Its FIRE attacks will\l"
	.string "wreak untold destruction, and the light\l"
	.string "of its DROUGHT empowers its SOLAR BEAM\l"
	.string "fry any opposing WATER POKÉMON.\l"
	.string "However, an AERODACTYL could readily\l"
	.string "crush it with its doubled weakness to\l"
	.string "ROCK and its reduced DEFENSE.$"



RocketHideoutJohtoP1Documento_107::
lock        
showmonpic SPECIES_BLASTOISE_MEGA, 10, 3 
playmoncry SPECIES_BLASTOISE, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_107, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_107:
.string "MEGA BLASTOISE:\p"
	.string "HP: 99\n"
	.string "ATTACK: 103\l"
	.string "DEFENSE: 120\l"
	.string "SPECIAL ATTACK: 135\l"
	.string "SPECIAL DEFENSE: 115\l"
	.string "SPEED: 78\l"
	.string "TOTAL: 650\p"
	.string "The immense defensive capacity of\n"
	.string "BLASTOISE is now concentrated in a\l"
	.string "POKÉMON with 135 SPECIAL ATTACK. Its\l"
	.string "massive cannon empowers moves like\l"
	.string "WATER PULSE, DARK PULSE, and AURA\l"
	.string "SPHERE by half. An armed fortress now\l"
	.string "equipped with the artillery to bombard\l"
	.string "its foes.$"



RocketHideoutJohtoP1Documento_108::
lock        
showmonpic SPECIES_BEEDRILL_MEGA, 10, 3 
playmoncry SPECIES_BEEDRILL, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_108, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_108:
.string "MEGA BEEDRILL:\p"
	.string "HP: 65\n"
	.string "ATTACK: 150\l"
	.string "DEFENSE: 40\l"
	.string "SPECIAL ATTACK: 15\l"
	.string "SPECIAL DEFENSE: 80\l"
	.string "SPEED: 145\l"
	.string "TOTAL: 495\p"
	.string "This is proof of how the adaptations\n"
	.string "brought about by MEGA EVOLUTION can\l"
	.string "radically change a mediocre POKÉMON\l"
	.string "like BEEDRILL. Its extreme frailty is\l"
	.string "matched by its sheer offensive\l"
	.string "capabilities-a product of bearing the\l"
	.string "most efficient distribution of its 495\l"
	.string "BASE STAT TOTAL. Though it crumbles to\l"
	.string "any offense itself, it will have\l"
	.string "shredded squadrons before then.$"



RocketHideoutJohtoP1Documento_109::
lock        
showmonpic SPECIES_PIDGEOT_MEGA, 10, 3 
playmoncry SPECIES_PIDGEOT, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_109, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_109:
.string "MEGA PIDGEOT:\p"
	.string "HP: 83\n"
	.string "ATTACK: 80\l"
	.string "DEFENSE: 80\l"
	.string "SPECIAL ATTACK: 135\l"
	.string "SPECIAL DEFENSE: 80\l"
	.string "SPEED: 121\l"
	.string "TOTAL: 579\p"
	.string "PIDGEOT's MEGA form revolutionizes its\n"
	.string "SPECIAL ATTACK to empower moves like\l"
	.string "HURRICANE and HEAT WAVE-such moves\l"
	.string "that will never miss due to its ABILITY.\l"
	.string "Despite that and its SPEED, it falls\l"
	.string "just one point short of the 580 BASE\l"
	.string "STAT TOTAL of KANTO's LEGENDARY BIRDS.\l"
	.string "However, its STATS bear a more\l"
	.string "effective distribution.$"



RocketHideoutJohtoP1Documento_110::
lock        
showmonpic SPECIES_ALAKAZAM_MEGA, 10, 3 
playmoncry SPECIES_ALAKAZAM, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_110, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_110:
.string "MEGA ALAKAZAM:\p"
	.string "HP: 55\n"
	.string "ATTACK: 50\l"
	.string "DEFENSE: 65\l"
	.string "SPECIAL ATTACK: 175\l"
	.string "SPECIAL DEFENSE: 105\l"
	.string "SPEED: 150\l"
	.string "TOTAL: 600\p"
	.string "Its reality-defying 175 SPECIAL\n"
	.string "ATTACK and 150 SPEED shatter the\l"
	.string "notion that a non-LEGENDARY POKÉMON\l"
	.string "could ever match the original MEWTWO.\l"
	.string "It bears a surprising resilience with\l"
	.string "its now passable SPECIAL DEFENSE and\l"
	.string "its no longer utterly egregious\l"
	.string "DEFENSE, even considering its\l"
	.string "offensive capabilities.$"



RocketHideoutJohtoP1Documento_111::
lock        
showmonpic SPECIES_SLOWBRO_MEGA, 10, 3 
playmoncry SPECIES_SLOWBRO, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_111, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_111:
.string "MEGA SLOWBRO:\p"
	.string "HP: 95\n"
	.string "ATTACK: 75\l"
	.string "DEFENSE: 180\l"
	.string "SPECIAL ATTACK: 130\l"
	.string "SPECIAL DEFENSE: 80\l"
	.string "SPEED: 30\l"
	.string "TOTAL: 590\p"
	.string "Its 180 DEFENSE matches that of\n"
	.string "CLOYSTER without completely\l"
	.string "sacrificing its SPECIAL DEFENSE to\l"
	.string "compensate. This and the additional 45\l"
	.string "SPECIAL ATTACK to achieve 130 in all\l"
	.string "demonstrate MEGA EVOLUTION's ability\l"
	.string "to defy the laws of balance among BASE\l"
	.string "STATs. Altogether, the things described\l"
	.string "here are sheer madness.$"



RocketHideoutJohtoP1Documento_112::
lock        
showmonpic SPECIES_GENGAR_MEGA, 10, 3 
playmoncry SPECIES_GENGAR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_112, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_112:
.string "MEGA GENGAR:\p"
	.string "HP: 70\n"
	.string "ATTACK: 75\l"
	.string "DEFENSE: 90\l"
	.string "SPECIAL ATTACK: 170\l"
	.string "SPECIAL DEFENSE: 117\l"
	.string "SPEED: 130\l"
	.string "TOTAL: 652\p"
	.string "Terrifying. Only that could\n"
	.string "characterize this POKÉMON. Only a\l"
	.string "modest DEFENSE hampers its\l"
	.string "exceptional SPECIAL ATTACK, remarkable\l"
	.string "SPECIAL DEFENSE, and a SPEED to match\l"
	.string "AERODACTYL. Its BASE STAT TOTAL of 652\l"
	.string "puts it just 28 points short of MAJOR\l"
	.string "LEGENDARIES like HO-OH and LUGIA and\l"
	.string "gives it the greatest overall power\l"
	.string "among all known non-PSEUDO-LEGENDARY\l"
	.string "MEGAs.$"



RocketHideoutJohtoP1Documento_113::
lock        
showmonpic SPECIES_KANGASKHAN_MEGA, 10, 3 
playmoncry SPECIES_KANGASKHAN, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_113, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_113:
.string "MEGA KANGASKHAN:\p"
	.string "HP: 105\n"
	.string "ATTACK: 125\l"
	.string "DEFENSE: 100\l"
	.string "SPECIAL ATTACK: 60\l"
	.string "SPECIAL DEFENSE: 100\l"
	.string "SPEED: 100\l"
	.string "TOTAL: 590\p"
	.string "Joining together with its young enables\n"
	.string "it to fight uninhibited-a demonstration\l"
	.string "of the power of familial bonds. Its\l"
	.string "caliber of a 590 BASE STAT TOTAL offset\l"
	.string "by only its unused 60 SPECIAL ATTACK is\l"
	.string "still further bolstered by the\l"
	.string "additional blows its offspring deals to\l"
	.string "the opponent each turn.$"



RocketHideoutJohtoP1Documento_114::
lock        
showmonpic SPECIES_PINSIR_MEGA, 10, 3 
playmoncry SPECIES_PINSIR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_114, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_114:
.string "MEGA PINSIR:\p"
	.string "HP: 65\n"
	.string "ATTACK: 155\l"
	.string "DEFENSE: 120\l"
	.string "SPECIAL ATTACK: 55\l"
	.string "SPECIAL DEFENSE: 90\l"
	.string "SPEED: 115\l"
	.string "TOTAL: 600\p"
	.string "An offensive juggernaut despite the\n"
	.string "numerous weaknesses provided by its\l"
	.string "BUG-FLYING TYPE. AERILATE converts\l"
	.string "powerful NORMAL moves like RETURN and\l"
	.string "DOUBLE-EDGE into FLYING ones and\l"
	.string "provides them an additional 20% boost\l"
	.string "apart from the standard STAB yield. It\l"
	.string "is seen as a legend. It's regarded as\l"
	.string "such by the BUG CATCHERs of KANTO and\l"
	.string "JOHTO.$"



RocketHideoutJohtoP1Documento_115::
lock        
showmonpic SPECIES_GYARADOS_MEGA, 10, 3 
playmoncry SPECIES_GYARADOS, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_115, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_115:
.string "MEGA GYARADOS:\p"
	.string "HP: 95\n"
	.string "ATTACK: 155\l"
	.string "DEFENSE: 109\l"
	.string "SPECIAL ATTACK: 70\l"
	.string "SPECIAL DEFENSE: 130\l"
	.string "SPEED: 81\l"
	.string "TOTAL: 640\p"
	.string "Its CRUNCH is as a wood chipper to\n"
	.string "everything before it. Its 150 ATTACK,\l"
	.string "newly acquired DARK TYPE, and ABILITY\l"
	.string "of STRONG JAW makes its maw lethal to\l"
	.string "all POKÉMON-and the most potent known.$"



RocketHideoutJohtoP1Documento_116::
lock        
showmonpic SPECIES_AMPHAROS_MEGA, 10, 3 
playmoncry SPECIES_AMPHAROS, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_116, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_116:
.string "MEGA AMPHAROS:\p"
	.string "HP: 90\n"
	.string "ATTACK: 95\l"
	.string "DEFENSE: 105\l"
	.string "SPECIAL ATTACK: 165\l"
	.string "SPECIAL DEFENSE: 110\l"
	.string "SPEED: 45\l"
	.string "TOTAL: 610\p"
	.string "Its ADAPTABILITY and 165 SPECIAL\n"
	.string "ATTACK empowers its THUNDERBOLT and\l"
	.string "DRAGON PULSE to destructive levels.\l"
	.string "Its excellent durability and AGILITY\l"
	.string "compensate for its abysmal SPEED-and\l"
	.string "allow it to show off its extraordinary\l"
	.string "offensive power.$"



RocketHideoutJohtoP1Documento_117::
lock        
showmonpic SPECIES_STEELIX_MEGA, 10, 3 
playmoncry SPECIES_STEELIX, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_117, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_117:
.string "MEGA STEELIX:\p"
	.string "HP: 75\n"
	.string "ATTACK: 125\l"
	.string "DEFENSE: 230\l"
	.string "SPECIAL ATTACK: 55\l"
	.string "SPECIAL ATTACK: 95\l"
	.string "SPEED: 30\l"
	.string "TOTAL: 610\p"
	.string "An impregnable fortress with its\n"
	.string "unyielding DEFENSE and 125 ATTACK\l"
	.string "bolstering its EARTHQUAKE and IRON\l"
	.string "HEAD. Its passable SPECIAL DEFENSE is\l"
	.string "extraordinary in a GROUND TYPE. Albeit a\l"
	.string "boost of 30, it has resulted in a BASE\l"
	.string "of 95.$"



RocketHideoutJohtoP1Documento_118::
lock        
showmonpic SPECIES_SCIZOR_MEGA, 10, 3 
playmoncry SPECIES_SCIZOR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_118, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_118:
.string "MEGA SCIZOR:\p"
	.string "HP: 80\n"
	.string "ATTACK: 155\l"
	.string "DEFENSE: 145\l"
	.string "SPECIAL ATTACK: 65\l"
	.string "SPECIAL DEFENSA: 100\l"
	.string "SPEED: 85\l"
	.string "TOTAL: 630\p"
	.string "By hierarchy and numbers, the BUG TYPE\n"
	.string "with the highest overall power\l"
	.string "throughout KANTO and JOHTO. Few things\l"
	.string "could melt this juggernaut without\l"
	.string "FIRE. Its physical prowess matches up\l"
	.string "to the likes of GROUDON, and its\l"
	.string "SPECIAL DEFENSE only furthers its\l"
	.string "resilience. Together with priority\l"
	.string "moves like BULLET PUNCH, it's among the\l"
	.string "most complete and lethal beings in\l"
	.string "existence.$"



RocketHideoutJohtoP1Documento_119::
lock        
showmonpic SPECIES_HERACROSS_MEGA, 10, 3 
playmoncry SPECIES_HERACROSS, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_119, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_119:
.string "MEGA HERACROSS:\p"
	.string "HP: 80\n"
	.string "ATTACK: 185\l"
	.string "DEFENSE: 115\l"
	.string "SPECIAL ATTACK: 40\l"
	.string "SPECIAL DEFENSE: 105\l"
	.string "SPEED: 75\l"
	.string "TOTAL: 600\p"
	.string "The POKÉMON with the highest PHYSICAL\n"
	.string "ATTACK ever recorded, with a base of\l"
	.string "185. Its final total can exceed 510 at\l"
	.string "LEVEL 100. Its thickened exoskeleton\l"
	.string "weighs it down somewhat, and FLYING\l"
	.string "can readily pluck at its doubled\l"
	.string "weakness. However, its SKILL LINK\l"
	.string "maximizes moves like PIN MISSILE, ROCK\l"
	.string "BLAST, and BULLET SEED to break apart\l"
	.string "legions of POKÉMON if it can just have\l"
	.string "that chance.$"



RocketHideoutJohtoP1Documento_120::
lock        
showmonpic SPECIES_HOUNDOOM_MEGA, 10, 3 
playmoncry SPECIES_HOUNDOOM, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_120, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_120:
.string "MEGA HOUNDOOM:\p"
	.string "HP: 85\n"
	.string "ATTACK: 80\l"
	.string "DEFENSE: 90\l"
	.string "SPECIAL ATTACK: 145\l"
	.string "SPECIAL DEFENSE: 95\l"
	.string "SPEED: 115\l"
	.string "TOTAL: 610\p"
	.string "Its SHEER FORCE magnifies moves like\n"
	.string "SHADOW BALL, FLAMETHROWER, and SLUDGE\l"
	.string "BOMB by 30%, significantly amplifying\l"
	.string "the effectiveness of its already\l"
	.string "impressive 145 SPECIAL ATTACK. Its 90\l"
	.string "DEFENSE shores up HOUNDOOM's most\l"
	.string "glaring weakness.$"



RocketHideoutJohtoP1Documento_121::
lock        
showmonpic SPECIES_TYRANITAR_MEGA, 10, 3 
playmoncry SPECIES_TYRANITAR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_121, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_121:
.string "MEGA TYRANITAR:\p"
	.string "HP: 100\n"
	.string "ATTACK: 164\l"
	.string "DEFENSE: 150\l"
	.string "SPECIAL ATTACK: 95\l"
	.string "SPECIAL DEFENSE: 120\l"
	.string "SPEED: 71\l"
	.string "TOTAL: 700\p"
	.string "A behemoth capable of terraforming the\n"
	.string "land itself. Its newfound DRAGON TYPE\l"
	.string "replaces DARK to mitigate its\l"
	.string "weaknesses while its SOLID ROCK shores\l"
	.string "up its remaining ones. Its moniker rings\l"
	.string "true as the tyrant of JOHTO, and legend\l"
	.string "has it that only a POKÉMON from the\l"
	.string "depths of the DRAGON'S DEN can exceed\l"
	.string "its overall STATs.$"



RocketHideoutJohtoP1Documento_122::
lock        
showmonpic SPECIES_GARDEVOIR_MEGA, 10, 3 
playmoncry SPECIES_GARDEVOIR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_122, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_122:
.string "MEGA GARDEVOIR:\p"
	.string "HP: 68\n"
	.string "ATTACK: 65\l"
	.string "DEFENSE: 85\l"
	.string "SPECIAL ATTACK: 165\l"
	.string "SPECIAL DEFENSE: 135\l"
	.string "SPEED: 100\l"
	.string "TOTAL: 618\p"
	.string "Immune to DRAGONs and resistant to\n"
	.string "DARK. Its PIXILATE empowers its HYPER\l"
	.string "VOICE, and that's before considering\l"
	.string "its array of moves like THUNDERBOLT and\l"
	.string "MYSTICAL FIRE. Moves that its KANTO\l"
	.string "counterpart MEGA ALAKAZAM cannot\l"
	.string "attain. In addition to its offensive\l"
	.string "prowess, it boasts a worthy SPEED and\l"
	.string "excellent SPECIAL DEFENSE.$"



RocketHideoutJohtoP1Documento_123::
lock        
showmonpic SPECIES_GALLADE_MEGA, 10, 3 
playmoncry SPECIES_GALLADE, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_123, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_123:
.string "MEGA GALLADE:\p"
	.string "HP: 68\n"
	.string "ATTACK: 165\l"
	.string "DEFENSE: 95\l"
	.string "SPECIAL ATTACK: 65\l"
	.string "SPECIAL DEFENSE: 115\l"
	.string "SPEED: 110\l"
	.string "TOTAL: 618\p"
	.string "The FIGHTING counterpart to\n"
	.string "GARDEVOIR. Its ADAPTABILITY\l"
	.string "compensates for the overall lower\l"
	.string "power of its moves. For instance, DRAIN\l"
	.string "PUNCH's improved power also maximizes\l"
	.string "its healing potential as a byproduct.\l"
	.string "Its greater emphasis on its DEFENSEs\l"
	.string "over its HP magnifies the weight of this\l"
	.string "healing effect.$"



RocketHideoutJohtoP1Documento_124::
lock        
showmonpic SPECIES_AGGRON_MEGA, 10, 3 
playmoncry SPECIES_AGGRON, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_124, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_124:
.string "MEGA AGGRON:\p"
	.string "HP: 70\n"
	.string "ATTACK: 140\l"
	.string "DEFENSE: 230\l"
	.string "SPECIAL ATTACK: 60\l"
	.string "SPECIAL DEFENSE: 80\l"
	.string "SPEED: 50\l"
	.string "TOTAL: 630\p"
	.string "Inferior to MEGA STEELIX in two ways:\n"
	.string "its comparatively lower DEFENSE and\l"
	.string "inaccessibility to STAB-enhanced\l"
	.string "EARTHQUAKE, though it boasts greater\l"
	.string "ATTACK. However, its weakness to WATER\l"
	.string "is washed away with its altered TYPE,\l"
	.string "and it gains new resistances to TYPEs\l"
	.string "like GRASS and ICE.$"



RocketHideoutJohtoP1Documento_125::
lock        
showmonpic SPECIES_ABSOL_MEGA, 10, 3 
playmoncry SPECIES_ABSOL, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_125, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_125:
.string "MEGA ABSOL:\p"
	.string "HP: 65\n"
	.string "ATTACK: 150\l"
	.string "DEFENSE: 100\l"
	.string "SPECIAL ATTACK: 115\l"
	.string "SPECIAL DEFENSE: 100\l"
	.string "SPEED: 115\l"
	.string "TOTAL: 645\p"
	.string "Its MAGIC BOUNCE deflects all incoming\n"
	.string "status conditions. And despite bearing\l"
	.string "a defensive ABILITY, its 150 ATTACK\l"
	.string "and 115 SPEED are more than enough to\l"
	.string "compensate, making it not only\l"
	.string "ferocious, but also hard to pin down.$"



RocketHideoutJohtoP1Documento_126::
lock        
showmonpic SPECIES_MEDICHAM_MEGA, 10, 3 
playmoncry SPECIES_MEDICHAM, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_126, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_126:
.string "MEGA MEDICHAM:\p"
	.string "HP: 60\n"
	.string "ATTACK: 100\l"
	.string "DEFENSE: 85\l"
	.string "SPECIAL ATTACK: 80\l"
	.string "SPECIAL DEFENSE: 85\l"
	.string "SPEED: 100\l"
	.string "TOTAL: 510\p"
	.string "Its PURE POWER effectively doubles its\n"
	.string "immense ATTACK to 245. Beyond this\l"
	.string "incredible anomaly, however, its\l"
	.string "middling STAT distribution makes it\l"
	.string "more akin to an average POKÉMON than a\l"
	.string "MEGA EVOLUTION.$"



RocketHideoutJohtoP1Documento_127::
lock        
showmonpic SPECIES_SALAMENCE_MEGA, 10, 3 
playmoncry SPECIES_SALAMENCE, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_127, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_127:
.string "MEGA SALAMENCE:\p"
	.string "HP: 95\n"
	.string "ATTACK: 145\l"
	.string "DEFENSE: 130\l"
	.string "SPECIAL ATTACK: 120\l"
	.string "SPECIAL DEFENSE: 90\l"
	.string "SPEED: 120\l"
	.string "TOTAL: 700\p"
	.string "The legend of METEOR FALLS. Despite\n"
	.string "the frequency at which others mistaken\l"
	.string "it as a LEGENDARY, this is still a mortal\l"
	.string "POKÉMON, for all its impressive power.\l"
	.string "It bears all the greatest qualities of a\l"
	.string "DRAGON: incredible SPEED and ATTACK\l"
	.string "with an impressive array of\l"
	.string "high-powered moves. It has even\l"
	.string "regained its sturdy DEFENSE as a\l"
	.string "SHELGON, and even its weakness in\l"
	.string "SPECIAL DEFENSE is mitigated.$"



RocketHideoutJohtoP1Documento_128::
lock        
showmonpic SPECIES_METAGROSS_MEGA, 10, 3 
playmoncry SPECIES_METAGROSS, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_128, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_128:
.string "MEGA METAGROSS:\p"
	.string "HP: 80\n"
	.string "ATTACK: 145\l"
	.string "DEFENSE: 150\l"
	.string "SPECIAL ATTACK: 105\l"
	.string "SPECIAL DEFENSE: 110\l"
	.string "SPEED: 110\l"
	.string "TOTAL: 700\p"
	.string "DEVON CO.'s flagship experiment\n"
	.string "silently supersedes the original MEWTWO\l"
	.string "in power. An incredibly efficient\l"
	.string "warmachine capable of total\l"
	.string "annihilation without notable weak\l"
	.string "points. Even its once abysmal SPEED\l"
	.string "stands at 110 now. However, its frame is\l"
	.string "far less capable of sustaining itself\l"
	.string "at a rather comparatively lagging 80 HP.$"



RocketHideoutJohtoP1Documento_129::
lock        
showmonpic SPECIES_LUCARIO_MEGA, 10, 3 
playmoncry SPECIES_LUCARIO, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_129, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_129:
.string "MEGA LUCARIO:\p"
	.string "HP: 70\n"
	.string "ATTACK: 145\l"
	.string "DEFENSE: 88\l"
	.string "SPECIAL ATTACK: 140\l"
	.string "SPECIAL DEFENSE: 70\l"
	.string "SPEED: 112\l"
	.string "TOTAL: 625\p"
	.string "STAB CLOSE COMBAT + ADAPTABILITY.\n"
	.string "STAB METEOR MASH + ADAPTABILITY.\l"
	.string "Priority BULLET PUNCH and\l"
	.string "STAB-enhanced VACUUM WAVE further\l"
	.string "bolstered by ADAPTABILITY… Its\l"
	.string "middling DEFENSEs belie the unmatched\l"
	.string "firepower of this POKÉMON and its\l"
	.string "versatile moveset. In addition to\l"
	.string "enhancing itself, it can strike at an\l"
	.string "array of foes with moves like STONE\l"
	.string "EDGE and BLAZE KICK. Only something\l"
	.string "like INFERNAPE could match its\l"
	.string "movepool.$"



RocketHideoutJohtoP1Documento_130::
lock        
showmonpic SPECIES_MILOTIC_MEGA, 10, 3 
playmoncry SPECIES_MILOTIC, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_130, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_130:
.string "MEGA MILOTIC:\p"
	.string "HP: 105\n"
	.string "ATTACK: 65\l"
	.string "DEFENSE: 99\l"
	.string "SPECIAL ATTACK: 135\l"
	.string "SPECIAL DEFENSE: 185\l"
	.string "SPEED: 81\l"
	.string "TOTAL: 670\p"
	.string "Its mysterious origins make experts\n"
	.string "hesitant to classify it as the third\l"
	.string "PSEUDO-LEGENDARY of HOENN. MEGA\l"
	.string "MILOTIC boasts a staggering 185\l"
	.string "SPECIAL DEFENSE while rising to\l"
	.string "ALAKAZAM's striking power. Even its\l"
	.string "DEFENSE is impressive. However, its 81\l"
	.string "SPEED leaves something to be desired.$"



RocketHideoutJohtoP1Documento_131::
lock        
showmonpic SPECIES_NOIVERN_MEGA, 10, 3 
playmoncry SPECIES_NOIVERN, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_131, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_131:
.string "MEGA NOIVERN:\p"
	.string "HP: 85\n"
	.string "ATTACK: 80\l"
	.string "DEFENSE: 100\l"
	.string "SPECIAL ATTACK: 127\l"
	.string "SPECIAL DEFENSE: 90\l"
	.string "SPEED: 153\l"
	.string "TOTAL: 635\p"
	.string "The fastest known DRAGON hailing from\n"
	.string "the distant KALOS. Its NO GUARD and 127\l"
	.string "SPECIAL ATTACK eviscerate its foes\l"
	.string "with HURRICANE and FOCUS BLAST. It's\l"
	.string "said to be a distant relative of CROBAT.$"



RocketHideoutJohtoP1Documento_132::
lock        
showmonpic SPECIES_FLYGON_MEGA, 10, 3 
playmoncry SPECIES_FLYGON, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_132, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_132:
.string "MEGA FLYGON:\p"
	.string "HP: 80\n"
	.string "ATTACK: 90\l"
	.string "DEFENSE: 100\l"
	.string "SPECIAL ATTACK: 140\l"
	.string "SPECIAL DEFENSE: 100\l"
	.string "SPEED: 140\l"
	.string "TOTAL: 650\p"
	.string "It trades in its GROUND TYPE for BUG\n"
	.string "and sacrifices 10 ATTACK to offset its\l"
	.string "staggering 140 SPECIAL ATTACK. A\l"
	.string "unique combination of SPEED and\l"
	.string "SPECIAL ATTACK. Its wide array of\l"
	.string "moves and its TINTED LENS make it\l"
	.string "capable of taking down anyone.$"



RocketHideoutJohtoP1Documento_133::
lock        
showmonpic SPECIES_STARMIE_MEGA, 10, 3 
playmoncry SPECIES_STARMIE, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_133, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_133:
.string "MEGA STARMIE:\p"
	.string "HP: 65\n"
	.string "ATTACK: 75\l"
	.string "DEFENSE: 100\l"
	.string "SPECIAL ATTACK: 135\l"
	.string "SPECIAL DEFENSE: 100\l"
	.string "SPEED: 145\l"
	.string "TOTAL: 620\p"
	.string "Its WATER hardened into ICE to\n"
	.string "effectively match its PSYCHIC prowess\l"
	.string "and bolster its agility, potency, and\l"
	.string "even stamina. Its SHEER FORCE\l"
	.string "complements its array of moves to\l"
	.string "devastate its foes.$"


RocketHideoutJohtoP1Documento_134::
msgbox RocketHideoutJohtoP1Documento_Text_134, MSGBOX_SIGN   
end

RocketHideoutJohtoP1Documento_Text_134:
	.string "TEAM ROCKET's grace is the reason for\n"
	.string "the existence of all these POKÉMON!$"



RocketHideoutJohtoP1_EventScript_ReceiveKlink::
    lock
    faceplayer
	checkmoncatch SPECIES_KLINK
	goto_if_eq VAR_RESULT, FALSE, RocketHideoutJohtoP1_EventScript_TakeKlink 
	msgbox RocketHideoutJohtoP1_Text_33, MSGBOX_DEFAULT
	release
	end



RocketHideoutJohtoP1_EventScript_TakeKlink::
    msgbox RocketHideoutJohtoP1_Text_TakeKlink MSGBOX_DEFAULT
	msgbox RocketHideoutJohtoP1_Text_TakeKlink2 MSGBOX_DEFAULT
	msgbox RocketHideoutJohtoP1_Text_TakeKlink3 MSGBOX_DEFAULT
    playfanfare MUS_OBTAIN_TMHM
	msgbox RocketHideoutJohtoP1_Text_MensajeKlink, MSGBOX_DEFAULT
	givemon SPECIES_KLINK, 10, ITEM_STEEL_GEM
	waitfanfare  
	release
	end 



RocketHideoutJohtoP1_Text_TakeKlink:
	.string "For a long time, MAGNEMITE and MAGNETON\n"
	.string "were the favorite POKÉMON of\l"
	.string "scientists like us.$"

RocketHideoutJohtoP1_Text_TakeKlink2:
	.string "But that was when we knew only the\n"
	.string "POKÉMON of KANTO. Now we have many\l"
	.string "more options to build our teams.$"

RocketHideoutJohtoP1_Text_TakeKlink3:
	.string "One of our companions who ventured to\n"
	.string "UNOVA returned with an evolutionary\l"
	.string "line strikingly similar to that of\l"
	.string "MAGNEMITE. Here, take a look at this\l"
	.string "specimen.$"

RocketHideoutJohtoP1_Text_MensajeKlink:
.string "YOU OBTAINED A KLINK AT LV.10!$"

RocketHideoutJohtoP1_Text_33:
	.string "Unlike MAGNEMITE, KLINK is a pure STEEL\n"
	.string "TYPE, faster, and focused on PHYSICAL\l"
	.string "ATTACK. Although MAGNEZONE is slightly\l"
	.string "better defensively.$"

RocketHideoutJohtoP1_Encuentro_Andra::
lock
faceplayer
playse SE_PIN
applymovement 16, RocketHideoutJohtoP1_Encuentro_Andra_Move_1
waitmovement 0x0
msgbox RocketHideoutJohtoP1_Encuentro_Andra_Texto_1 MSGBOX_AUTOCLOSE
applymovement 16, RocketHideoutJohtoP1_Encuentro_Andra_Move_2
waitmovement 0x0
msgbox RocketHideoutJohtoP1_Encuentro_Andra_Texto_2 MSGBOX_AUTOCLOSE
delay 20
msgbox RocketHideoutJohtoP1_Encuentro_Andra_Texto_3 MSGBOX_AUTOCLOSE
setflag FLAG_HIDE_PETALBURG_GYM_WALLYS_DAD
fadescreen 1
delay 20
removeobject 16
fadescreen 0
release
end

RocketHideoutJohtoP1_Encuentro_Andra_Texto_1:
	.string "ANDRA: Didja see all this, {PLAYER}?\n"
	.string "We're making our own MEGA STONEs! Now\l"
	.string "we've got everything a TRAINER could\l"
	.string "need maximize their POKÉMON to its\l"
	.string "limits-more than anyone could imagine.$"

RocketHideoutJohtoP1_Encuentro_Andra_Texto_2:
	.string "You know what? I'm gonna hop around\n"
	.string "the eastern ROUTEs of JOHTO, right by\l"
	.string "KANTO. They said in the meeting we'll be\l"
	.string "getting access soon. If I got it right,\l"
	.string "that's where they stuffed RED. I'm\l"
	.string "kinda curious to see what'd happen if\l"
	.string "we paid him a visit…$"

RocketHideoutJohtoP1_Encuentro_Andra_Texto_3:
	.string "Well, I won't keep you any longer. Just\n"
	.string "head further up; we've got a surprise\l"
	.string "for your performance and loyalty to\l"
	.string "TEAM ROCKET.$"


RocketHideoutJohtoP1_Encuentro_Andra_Move_1:
emote_exclamation_mark
face_player
step_end

RocketHideoutJohtoP1_Encuentro_Andra_Move_2:
walk_in_place_up
face_player
step_end

RocketHideoutJohtoP1_Encuentro_Cientifico::
lock
applymovement OBJ_EVENT_ID_PLAYER, RocketHideoutJohtoP1_Encuentro_Cientifico_Move_1
applymovement 4, RocketHideoutJohtoP1_Encuentro_Cientifico_Move_2
waitmovement 0x0
msgbox RocketHideoutJohtoP1_Encuentro_Cientifico_Texto_1
applymovement 4, RocketHideoutJohtoP1_Encuentro_Cientifico_Move_3
waitmovement 0x0
msgbox RocketHideoutJohtoP1_Encuentro_Cientifico_Texto_2
playfanfare MUS_RG_OBTAIN_KEY_ITEM
additem ITEM_BASEMENT_KEY
msgbox Goldenrod_RadioTower_P4_Encuentro_Andra_Texto_10.2 MSGBOX_DEFAULT
waitfanfare
applymovement 4, RocketHideoutJohtoP1_Encuentro_Cientifico_Move_4
waitmovement 0x0
setvar VAR_UNUSED_0x40F7, 154
release
end

Goldenrod_RadioTower_P4_Encuentro_Andra_Texto_10.2:
.string "You obtained an OFFICE CARD\n"
	.string "from the SCIENTIST!$"

RocketHideoutJohtoP1_Encuentro_Cientifico_Texto_1:
.string "CHIEF ADMIN. {PLAYER},\n"
	.string " we were waiting for you, sir.$"

RocketHideoutJohtoP1_Encuentro_Cientifico_Texto_2:
	.string "As the LEADER of our branch in JOHTO,\n"
	.string "it's only fitting for you to have a\l"
	.string "suitable workplace. With this, you'll be\l"
	.string "able to access the private office we've\l"
	.string "prepared for you.$"

RocketHideoutJohtoP1_Encuentro_Cientifico_Move_1:
walk_in_place_up
step_end

RocketHideoutJohtoP1_Encuentro_Cientifico_Move_2:
walk_in_place_down
step_end

RocketHideoutJohtoP1_Encuentro_Cientifico_Move_3:
walk_left
walk_left
walk_left
walk_left
walk_down
step_end

RocketHideoutJohtoP1_Encuentro_Cientifico_Move_4:
walk_right
walk_right
walk_right
walk_right
walk_up
step_end

Llave_Despacho_Warp::
msgbox Llave_Despacho_Warp_Text_YesNo, MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq RocketHideout_4F_Warp_No
delay 40
playse SE_CARD
delay 40
playse SE_CLICK
delay 40
playse SE_UNLOCK
setmetatile 20, 4, 0x335, FALSE
setmetatile 20, 3, 0x335, FALSE
setmetatile 21, 4, 0x334, FALSE
setmetatile 21, 3, 0x334, FALSE
setmetatile 22, 4, 0x334, FALSE
setmetatile 22, 3, 0x334, FALSE
special DrawWholeMapView
delay 60
release
end

Llave_Despacho_Warp_Text_YesNo:
	.string "Would you like to come into your office?$"

Llave_Despacho_2_Warp::
msgbox Llave_Despacho_Warp_Text_2_YesNo, MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq RocketHideout_4F_Warp_No
delay 40
playse SE_CARD
delay 40
playse SE_CLICK
delay 40
playse SE_UNLOCK
setmetatile 20, 4, 0x335, FALSE
setmetatile 20, 3, 0x335, FALSE
setmetatile 21, 4, 0x334, FALSE
setmetatile 21, 3, 0x334, FALSE
setmetatile 22, 4, 0x334, FALSE
setmetatile 22, 3, 0x334, FALSE
special DrawWholeMapView
delay 60
release
end

Llave_Despacho_Warp_Text_2_YesNo:
	.string "Would you like to left your office?$"

RocketHideoutJohtoP1_LanzaMugre::
lock     
faceplayer  
goto_if_set FLAG_NUEVA_858, RocketHideoutJohtoP1_LanzaMugre_Despues
msgbox RocketHideoutJohtoP1_LanzaMugre_Texto_1, MSGBOX_NPC
msgbox RocketHideoutJohtoP1_LanzaMugre_Texto_1.2, MSGBOX_NPC
playfanfare MUS_OBTAIN_TMHM
additem ITEM_TM114
msgbox RocketHideoutJohtoP1_LanzaMugre_Texto_1.1 MSGBOX_DEFAULT
waitfanfare
setflag FLAG_NUEVA_858
release     
end

RocketHideoutJohtoP1_LanzaMugre_Despues::
msgbox RocketHideoutJohtoP1_LanzaMugre_Texto_2, MSGBOX_NPC
release
end

RocketHideoutJohtoP1_LanzaMugre_Texto_1.2:
	.string "GUNK SHOT is the solution to that; this\n"
	.string "move is capable of corrupting\l"
	.string "everything good and pure in this world.\l"
	.string "Take it.$"

RocketHideoutJohtoP1_LanzaMugre_Texto_1:
	.string "It's so frustrating that CROSS POISON\n"
	.string "is the strongest PHYSICAL POISON TYPE\l"
	.string "move, isn't it?$"

RocketHideoutJohtoP1_LanzaMugre_Texto_1.1:
.string "{PLAYER} obtained TM114 GUNK SHOT\n"
	.string "from the scientist!!$"

RocketHideoutJohtoP1_LanzaMugre_Texto_2:
	.string "Apart from its outstanding power, GUNK\n"
	.string "SHOT doesn't require physical contact\l"
	.string "with the opponent. The only downside is\l"
	.string "its accuracy. Can you imagine being able\l"
	.string "to use it without missing?$"

