RocketHideout_JohtoP1_MapScripts::
	.byte 0

RocketHideoutP1_1::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_1, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_1:
.string "La ausencia generalizada de estrés\n"
.string "salpicada de breves momentos de\l"
.string "estrés extremo es infinitamente\l"
.string "mejor que el hecho de vivir con\l"
.string "algo de estrés todo el tiempo.$"



RocketHideoutP1_2::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_2, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_2:
.string "Con nuestra tecnología hemos\n"
.string "podido replicar varias de las\l"
.string "MEGAPIEDRAS que muy rara vez\l"
.string "pueden encontrarse en la\l"
.string "naturaleza, incluso hemos podido\l"
.string "crear algunas nuevas para POKÉMON\l"
.string "con el potencial de la\l"
.string "MEGAEVOLUCIÓN, como FLYGON o\l"
.string "MILOTIC.$"



RocketHideoutP1_3::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_3, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_3:
.string "Aquí estamos convirtiendo la\n"
.string "excelencia y la perfección en la\l"
.string "norma, ¿no encuentras eso\l"
.string "desmotivante?\l"
.string "Si todos son súper… ya nadie lo\l"
.string "será, y nuestros logros, por más\l"
.string "buenos que sean, no dejarán de ser\l"
.string "unos más del montón.$"



RocketHideoutP1_4::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_4, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_4:
.string "¿Qué se siente al ser el dueño de\n"
.string "todo esto?$"



RocketHideoutP1_5::
end



RocketHideoutP1_6::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_6, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_6:
.string "BUTTERFREE es el único POKÉMON\n"
.string "conocido que cuenta con una\l"
.string "MEGAEVOLUCIÓN y a la vez una forma\l"
.string "FUERTE VÍNCULO, que, gracias a ti,\l"
.string "pudimos estudiar después de tu\l"
.string "combate con CÉSAR. Con ello\l"
.string "pudimos comparar las diferencias\l"
.string "entre una MEGA y un FUERTE VÍNCULO\l"
.string "dentro de una especie.\l"
.string "La conclusión era la esperada: el\l"
.string "FUERTE VÍNCULO produce una mejora\l"
.string "del rendimiento aún más drástica\l"
.string "que la MEGAEVOLUCIÓN. Entre sus\l"
.string "+110 de BASE y solo 5 en ATAQUE\l"
.string "FÍSICO, el BUTTERFREE de CÉSAR\l"
.string "supera en 20 puntos de BASE a la\l"
.string "MEGA de BUTTERFREE. Es mucho más\l"
.string "resistente y de similar capacidad\l"
.string "ofensiva, aunque la forma MEGA\l"
.string "logra ser algo más rápida.$"



RocketHideoutP1_7::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_7, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_7:
.string "Nos costó horrores crear\n"
.string "MEGAPIEDRAS a la carta, pero\l"
.string "finalmente pudimos hacerlo con\l"
.string "FLYGON y MILOTIC. Es un gran paso\l"
.string "hacia, quizás, MEGAPIEDRAS aún más\l"
.string "potentes.$"



RocketHideoutP1_8::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_8, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_8:
.string "A la Madre Naturaleza no le gusta\n"
.string "la especialización excesiva, pues\l"
.string "esta limita la evolución y vuelve\l"
.string "más vulnerables a los POKÉMON. Por\l"
.string "fortuna, gracias a la tecnología y\l"
.string "la ciencia, podremos saltarnos este\l"
.string "principio básico.$"



RocketHideoutP1_9::
end



RocketHideoutP1_10::
end



RocketHideoutP1_11::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_11, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_11:
.string "A muchos les parecería un\n"
.string "despropósito los números de poder\l"
.string "que aquí estamos manejando.\l"
.string "¡Un NO LEGENDARIO con 700 STATS\l"
.string "BASE, quién lo diría!$"



RocketHideoutP1_12::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_12, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_12:
.string "Lo que hay en esta sala es un\n"
.string "imposible para el 99% de la\l"
.string "población común, dudo que\l"
.string "comprendan siquiera el poder que\l"
.string "hay escrito en estos documentos,\l"
.string "para ellos el mejor NO LEGENDARIO\l"
.string "sigue y seguirá siendo DRAGONITE.$"



RocketHideoutP1_13::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_13, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_13:
.string "¡Imagínate tener un MEGA-HOUNDOOM!\n"
.string "¡Todos se arrodillarían ante mí\l"
.string "nada más sacarlo de la POKÉ BALL!$"



RocketHideoutP1_14::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_14, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_14:
.string "GIOVANNI siempre se negó a ser un\n"
.string "muñeco movido por los hilos de\l"
.string "LANCE, por eso hoy el TEAM ROCKET\l"
.string "está donde está.$"



RocketHideoutP1_15::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_15, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_15:
.string "De vez en cuando, dí la verdad para\n"
.string "que te crean cuando mientas.\l"
.string "¡TEAM ROCKET RULES!$"



RocketHideoutP1_16::
end



RocketHideoutP1_17::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_17, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_17:
.string "En general, no nos basta con tener\n"
.string "éxito, ¡los demás deben fracasar!$"



RocketHideoutP1_18::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_18, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_18:
.string "¿Crees que los POKÉMON perderán su\n"
.string "verdadera esencia si les\l"
.string "modificamos los IVs?$"



RocketHideoutP1_19::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_19, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_19:
.string "JOHTO cuenta con más de un\n"
.string "ENTRENADOR que podría haber hecho\l"
.string "morder el polvo al dictador LANCE,\l"
.string "el problema es que están muy bien\l"
.string "escondidos.$"



RocketHideoutP1_20::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_20, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_20:
.string "Los IVs de cualquier POKÉMON ya no\n"
.string "son ningún misterio para nosotros,\l"
.string "podrás ponerlos todos en 31\l"
.string "gracias al sistema que hemos\l"
.string "creado.$"



RocketHideoutP1_21::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_21, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_21:
.string "Los POKÉMON de la ADMIN.JEFA ANDRA\n"
.string "son terríblemente fuertes, es como\l"
.string "si el hecho de saber que tienen un\l"
.string "límite menor que el de un\l"
.string "LEGENDARIO hubiera provocado en\l"
.string "ellos el efecto contrario a,\l"
.string "efectivamente, verse limitados por\l"
.string "eso.$"



RocketHideoutP1_22::
end



RocketHideoutP1_23::
end



RocketHideoutP1_24::
end



RocketHideoutP1_25::
end



RocketHideoutP1_26::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_26, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_26:
.string "Decir que existe un límite\n"
.string "superior pero no sé a qué altura\l"
.string "se encuentra, y decir que no\l"
.string "existe límite alguno tienen en la\l"
.string "práctica las mismas consecuencias.\l"
.string "Ahí está la trampa de la conocida\l"
.string "frase: no hay límite.$"



RocketHideoutP1_27::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_27, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_27:
.string "Este es el lugar en el que las\n"
.string "variables de la naturaleza se han\l"
.string "convertido en un libro abierto\l"
.string "para nosotros.$"



RocketHideoutP1_28::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_28, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_28:
.string "En las tinieblas la imaginación\n"
.string "trabaja más activamente que en\l"
.string "plena luz.$"



RocketHideoutP1_29::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_29, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_29:
.string "La aleatoriedad no siempre es\n"
.string "mala, puede ser mucho más\l"
.string "igualitaria que, incluso, la\l"
.string "inteligencia.\l"
.string "Si a las personas se las\l"
.string "recompensara estrictamente por\l"
.string "según sus habilidades, las cosas\l"
.string "serían aún más injustas ya que no\l"
.string "escogemos nuestras habilidades.\l"
.string "El azar produce el efecto benéfico\l"
.string "de volver a barajar las cartas de\l"
.string "la sociedad, para poder ganar al\l"
.string "afortunado de siempre.$"



RocketHideoutP1_30::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_30, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_30:
.string "Nuestra psicología conspira contra\n"
.string "nosotros mismos: a las personas\l"
.string "nos gusta ir hacia un destino\l"
.string "preciso antes que enfrentarnos a\l"
.string "cierto grado de incertidumbre,\l"
.string "aunque este sea beneficioso.$"



RocketHideoutP1_31::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_31, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_31:
.string "En la práctica, no existe el\n"
.string "largo plazo, lo que importa es\l"
.string "lo que sucede antes de ese largo\l"
.string "plazo.\l"
.string "El problema de usar la noción de\l"
.string "largo plazo, es que tiende a\l"
.string "volvernos ciegos a lo que ocurre\l"
.string "antes del largo plazo.$"



RocketHideoutP1_32::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_32, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_32:
.string "Las librerías están repletas de\n"
.string "libros sobre cómo alguien logró\l"
.string "tener éxito, casi no hay ninguno\l"
.string "con títulos como -Lo que aprendí\l"
.string "al arruinarme-. Tenemos\l"
.string "preferencia por hacer algo antes\l"
.string "que no hacer nada, incluso en\l"
.string "casos en los que hacer algo\l"
.string "resulta perjudicial.$"



RocketHideoutP1_33::
end



RocketHideoutP1_34::
lock     
faceplayer     
msgbox RocketHideoutP1_Text_34, MSGBOX_DEFAULT
release     
end

RocketHideoutP1_Text_34:
.string "GIOVANNI se reveló contra su\n"
.string "propio destino, ese que decía que\l"
.string "perdería siempre contra el niño de\l"
.string "10 años de turno, y lo mejor es\l"
.string "que todos esos ilusos allá afuera\l"
.string "creen que es verdad.$"



RocketHideoutJohtoP1Documento_100::
lock        
msgbox RocketHideoutJohtoP1Documento_Text_100, MSGBOX_DEFAULT
msgbox RocketHideoutJohtoP1Documento_Text_101, MSGBOX_DEFAULT
release     
end

RocketHideoutJohtoP1Documento_Text_100:
.string "TÉCNICAS EMPLEADAS POR OAK:\n"
	.string "...Pero el motivo principal por\l"
	.string "el que accedimos a respaldar a\l"
	.string "LANCE fue, básicamente, el\l"
	.string "control de la información y el\l"
	.string "prestigio que la LIGA POKÉMON\l"
	.string "adquiriría al ser ella la que\l"
	.string "terminase con una guerra que iba\l"
	.string "camino de asolar la región.\l"
	.string "Una cosa lleva a la otra, y la\l"
	.string "nueva confianza ganada al pueblo\l"
	.string "nos permitió modificar todo tipo\l"
	.string "de datos, desde bibliotecas hasta\l"
	.string "carteles, para eliminar todo lo\l"
	.string "proveniente de fuera y limitar el\l"
	.string "pensamiento.$"


RocketHideoutJohtoP1Documento_Text_101:
.string "Esto hace que sea cada vez más\n"
	.string "difícil de desenmascarar este\l"
	.string "entramado, por el hecho de que no\l"
	.string "existirán datos sobre los que\l"
	.string "respaldarse. No podemos evitar que\l"
	.string "un ENTRENADOR use a un CYNDAQUIL o\l"
	.string "un MARILL en territorio de KANTO,\l"
	.string "pero sí podemos hacer que sea\l"
	.string "imposible de demostrar que ese\l"
	.string "POKÉMON pertenezca a otra región.\l"
	.string "Sin POKÉDEX ni recopilación\l"
	.string "oficial de los POKÉMON de KANTO,\l"
	.string "se sobreentenderá que es uno más\l"
	.string "de los 151 de KANTO, y nadie se\l"
	.string "parará a contarlos uno por uno\l"
	.string "para comprobar que tal número es\l"
	.string "el total existente.$"



RocketHideoutJohtoP1Documento_102::
lock       
msgbox RocketHideoutJohtoP1Documento_Text_102, MSGBOX_DEFAULT
release     
end

RocketHideoutJohtoP1Documento_Text_102:
.string "DECISIONES ÓPTIMAS DE INVERSIÓN Y\n"
	.string "FINANCIACIÓN EN LA EMPRESA$"



RocketHideoutJohtoP1Documento_103::
lock        
showmonpic SPECIES_BUTTERFREE_MEGA, 10, 3 
playmoncry SPECIES_BUTTERFREE, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_103, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_103:
.string "BUTTERFREE-MEGA:\p"
	.string "PS: 60\n"
	.string "ATAQUE: 15\l"
	.string "DEFENSA: 50\l"
	.string "ATAQUE ESPECIAL: 140\l"
	.string "DEFENSA ESPECIAL: 108\l"
	.string "VELOCIDAD: 122\l"
	.string "TOTAL: 495\p"
	.string "La contraparte por el lado\n"
	.string "especial de BEEDRILL-MEGA. Algo\l"
	.string "menos potente, pero superior\l"
	.string "defensivamente. Igualmente con\l"
	.string "ADAPTABLE por HABILIDAD y\l"
	.string "movimientos de mayor potencia\l"
	.string "como PSÍQUICO y ZUMBIDO.$"



RocketHideoutJohtoP1Documento_104::
lock        
showmonpic SPECIES_VENUSAUR_MEGA, 10, 3 
playmoncry SPECIES_VENUSAUR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_104, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_104:
.string "VENUSAUR-MEGA:\p"
	.string "PS: 90\n"
	.string "ATAQUE: 100\l"
	.string "DEFENSA: 123\l"
	.string "ATAQUE ESPECIAL: 123\l"
	.string "DEFENSA ESPECIAL: 132\l"
	.string "VELOCIDAD: 80\l"
	.string "TOTAL: 648\p"
	.string "Uno de los mayores tanques que\n"
	.string "existen, capaz de pasar de 120 de\l"
	.string "base en 3 STATS diferentes.\l"
	.string "Gracias a su habilidad SEBO,\l"
	.string "resistirá de forma neutral los\l"
	.string "tipos FUEGO y HIELO, siendo débil\l"
	.string "únicamente al VOLADOR y PSÍQUICO.$"



RocketHideoutJohtoP1Documento_105::
lock        
showmonpic SPECIES_CHARIZARD_MEGA_X, 10, 3 
playmoncry SPECIES_CHARIZARD, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_105, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_105:
.string "CHARIZARD-X:\p"
	.string "PS: 78\n"
	.string "ATAQUE: 135\l"
	.string "DEFENSA: 111\l"
	.string "ATAQUE ESPECIAL: 130\l"
	.string "DEFENSA ESPECIAL: 95\l"
	.string "VELOCIDAD: 100\l"
	.string "TOTAL: 649\p"
	.string "Su existencia ha demostrado que,\n"
	.string "efectivamente, el tipo DRAGÓN\l"
	.string "corría por las venas de la línea\l"
	.string "evolutiva de CHARIZARD. Esta forma\l"
	.string "ve aumentada enormemente su\l"
	.string "DEFENSA y ATAQUE físicos gracias\l"
	.string "al endurecimiento de su piel,\l"
	.string "pegando más duro que cualquier\l"
	.string "otro DRAGÓN PSEUDOLEGENDARIO y\l"
	.string "siendo capaz de mantener su\l"
	.string "notable VELOCIDAD de 100 de BASE.\l"
	.string "Su combinación FUEGO-DRAGÓN pegará\l"
	.string "a todo neutralmente.$"



RocketHideoutJohtoP1Documento_106::
lock        
showmonpic SPECIES_CHARIZARD_MEGA_Y, 10, 3 
playmoncry SPECIES_CHARIZARD, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_106, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_106:
.string "CHARIZARD-Y:\p"
	.string "PS: 78\n"
	.string "ATAQUE: 104\l"
	.string "DEFENSA: 83\l"
	.string "ATAQUE ESPECIAL: 159\l"
	.string "DEFENSA ESPECIAL: 115\l"
	.string "VELOCIDAD: 110\l"
	.string "TOTAL: 649\p"
	.string "El mejor ejemplo del poder\n"
	.string "obtenido mediante la\l"
	.string "MEGAEVOLUCIÓN, puesto que el poder\l"
	.string "de su SEQUÍA rivaliza con el poder\l"
	.string "de LLOVIZNA del propio KYOGRE,\l"
	.string "teniendo CHARIZARD-Y incluso mayor\l"
	.string "ATAQUE ESPECIAL (159) que la\l"
	.string "bestia de HOENN. Sus ataques tipo\l"
	.string "FUEGO harán estragos como ningún\l"
	.string "otro, y con RAYO SOLAR bajo su\l"
	.string "SEQUÍA destruirá a todo tipo AGUA\l"
	.string "que se le cruce. Su debilidad x4\l"
	.string "al ROCA y baja DEFENSA convierten\l"
	.string "a AERODACTYL en su mayor\l"
	.string "debilidad.$"



RocketHideoutJohtoP1Documento_107::
lock        
showmonpic SPECIES_BLASTOISE_MEGA, 10, 3 
playmoncry SPECIES_BLASTOISE, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_107, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_107:
.string "BLASTOISE-MEGA:\p"
	.string "PS: 99\n"
	.string "ATAQUE: 103\l"
	.string "DEFENSA: 120\l"
	.string "ATAQUE ESPECIAL: 135\l"
	.string "DEFENSA ESPECIAL: 115\l"
	.string "VELOCIDAD: 78\l"
	.string "TOTAL: 650\p"
	.string "La enorme capacidad defensiva de\n"
	.string "BLASTOISE concentrada ahora en un\l"
	.string "POKÉMON con 135 de BASE en ATAQUE\l"
	.string "ESPECIAL. Gracias a su enorme\l"
	.string "cañón, movimientos como HIDROPULSO\l"
	.string "(75 pot.), PULSO UMBRÍO o ESFERA\l"
	.string "AURAL tendrán un 50% más de\l"
	.string "potencia. Un muro que ahora, además,\l"
	.string "acribillará al rival a cañonazos.$"



RocketHideoutJohtoP1Documento_108::
lock        
showmonpic SPECIES_BEEDRILL_MEGA, 10, 3 
playmoncry SPECIES_BEEDRILL, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_108, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_108:
.string "BEEDRILL-MEGA:\p"
	.string "PS: 65\n"
	.string "ATAQUE: 150\l"
	.string "DEFENSA: 40\l"
	.string "ATAQUE ESPECIAL: 15\l"
	.string "DEFENSA ESPECIAL: 80\l"
	.string "VELOCIDAD: 145\l"
	.string "TOTAL: 495\p"
	.string "Prueba de cómo las adaptaciones\n"
	.string "que produce la MEGAEVOLUCIÓN\l"
	.string "pueden cambiar radicalmente a un\l"
	.string "POKÉMON mediocre como BEEDRILL.\l"
	.string "Con solo 495 de BASE, es el\l"
	.string "POKÉMON conocido que reparte más\l"
	.string "eficientemente sus STATS, siendo\l"
	.string "de papel por el lado FÍSICO, pero\l"
	.string "contando a cambio con una ofensiva\l"
	.string "extrema. Un POKÉMON que caerá\l"
	.string "facilmente si es golpeado, pero\l"
	.string "que puede llevarse a muchos por\l"
	.string "delante antes de que eso ocurra.$"



RocketHideoutJohtoP1Documento_109::
lock        
showmonpic SPECIES_PIDGEOT_MEGA, 10, 3 
playmoncry SPECIES_PIDGEOT, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_109, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_109:
.string "PIDGEOT-MEGA:\p"
	.string "PS: 83\n"
	.string "ATAQUE: 80\l"
	.string "DEFENSA: 80\l"
	.string "ATAQUE ESPECIAL: 135\l"
	.string "DEFENSA ESPECIAL: 80\l"
	.string "VELOCIDAD: 121\l"
	.string "TOTAL: 579\p"
	.string "Cambio radical respecto a PIDGEOT,\n"
	.string "ganando su MEGA un enorme ATAQUE\l"
	.string "ESPECIAL con el que hacer uso de\l"
	.string "un VENDAVAL y ONDA ÍGNEA que jamás\l"
	.string "fallarán por su habilidad.\l"
	.string "Igualmente, con una muy notable\l"
	.string "VELOCIDAD, se queda a un solo\l"
	.string "punto de igualar los 580 de BASE\l"
	.string "de las AVES LEGENDARIAS de KANTO,\l"
	.string "aunque reparte sus STATS de mejor\l"
	.string "forma que estas.$"



RocketHideoutJohtoP1Documento_110::
lock        
showmonpic SPECIES_ALAKAZAM_MEGA, 10, 3 
playmoncry SPECIES_ALAKAZAM, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_110, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_110:
.string "ALAKAZAM-MEGA:\p"
	.string "PS: 55\n"
	.string "ATAQUE: 50\l"
	.string "DEFENSA: 65\l"
	.string "ATAQUE ESPECIAL: 175\l"
	.string "DEFENSA ESPECIAL: 105\l"
	.string "VELOCIDAD: 150\l"
	.string "TOTAL: 600\p"
	.string "Se creía fisiológicamente\n"
	.string "imposible que un POKÉMON no\l"
	.string "LEGENDARIO pudiera reunir tal\l"
	.string "combinación de ATAQUE ESPECIAL\l"
	.string "(175) y VELOCIDAD (150). Dejando\l"
	.string "atrás al MEWTWO original, consigue\l"
	.string "incluso contar con una buena\l"
	.string "DEFENSA ESPECIAL y mejorar algo\l"
	.string "su nefasta DEFENSA como ALAKAZAM,\l"
	.string "siendo sorprendentemente\l"
	.string "resistente si tenemos en cuenta su\l"
	.string "ofensiva.$"



RocketHideoutJohtoP1Documento_111::
lock        
showmonpic SPECIES_SLOWBRO_MEGA, 10, 3 
playmoncry SPECIES_SLOWBRO, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_111, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_111:
.string "SLOWBRO-MEGA:\p"
	.string "PS: 95\n"
	.string "ATAQUE: 75\l"
	.string "DEFENSA: 180\l"
	.string "ATAQUE ESPECIAL: 130\l"
	.string "DEFENSA ESPECIAL: 80\l"
	.string "VELOCIDAD: 30\l"
	.string "TOTAL: 590\p"
	.string "Misma DEFENSA FÍSICA (180) que\n"
	.string "CLOYSTER, con 45 puntos más de base\l"
	.string "en PS y sin contar con una pésima\l"
	.string "DEFENSA ESPECIAL como precio a\l"
	.string "pagar por tal DEFENSA. Resume la\l"
	.string "forma en que la MEGAEVOLUCIÓN\l"
	.string "puede saltarse algunas leyes\l"
	.string "básicas de equilibrio entre STATS\l"
	.string "BASE.\l"
	.string "Para rematar, 130 de BASE en\l"
	.string "ATAQUE ESPECIAL, una locura\l"
	.string "teniendo en cuenta lo dicho.$"



RocketHideoutJohtoP1Documento_112::
lock        
showmonpic SPECIES_GENGAR_MEGA, 10, 3 
playmoncry SPECIES_GENGAR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_112, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_112:
.string "GENGAR-MEGA:\p"
	.string "PS: 70\n"
	.string "ATAQUE: 75\l"
	.string "DEFENSA: 90\l"
	.string "ATAQUE ESPECIAL: 170\l"
	.string "DEFENSA ESPECIAL: 117\l"
	.string "VELOCIDAD: 130\l"
	.string "TOTAL: 652\p"
	.string "Temible. Esa sería la palabra para\n"
	.string "definir a este POKÉMON. Con solo\l"
	.string "una mediana capacidad defensiva\l"
	.string "por el lado físico como única\l"
	.string "debilidad, ATAQUE ESPECIAL por las\l"
	.string "nubes, misma VELOCIDAD que\l"
	.string "AERODACTYL, y, por si fuera poco,\l"
	.string "una muy notable DEFENSA ESPECIAL\l"
	.string "también.\l"
	.string "Su BASE total (652) lo convierte\l"
	.string "en la MEGA no PSEUDOLEGENDARIA de\l"
	.string "mayor poder global conocida, a\l"
	.string "solo 28 puntos de LEGENDARIOS\l"
	.string "pesados como LUGIA y HO-OH.$"



RocketHideoutJohtoP1Documento_113::
lock        
showmonpic SPECIES_KANGASKHAN_MEGA, 10, 3 
playmoncry SPECIES_KANGASKHAN, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_113, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_113:
.string "KANGASKHAN-MEGA:\p"
	.string "PS: 105\n"
	.string "ATAQUE: 125\l"
	.string "DEFENSA: 100\l"
	.string "ATAQUE ESPECIAL: 60\l"
	.string "DEFENSA ESPECIAL: 100\l"
	.string "VELOCIDAD: 100\l"
	.string "TOTAL: 590\p"
	.string "El poder que une los lazos\n"
	.string "familiares concentrado en un\l"
	.string "POKÉMON, el despojarse de su cría\l"
	.string "permite a KANGASKHAN luchar con\l"
	.string "plenas facultades, por si un\l"
	.string "POKÉMON de este poder (590 de BASE\l"
	.string "con solo 60 en un AT.ESPECIAL que\l"
	.string "no usará), no fuera suficiente, su\l"
	.string "cría le ayudará golpeando también\l"
	.string "al rival en cada turno.$"



RocketHideoutJohtoP1Documento_114::
lock        
showmonpic SPECIES_PINSIR_MEGA, 10, 3 
playmoncry SPECIES_PINSIR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_114, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_114:
.string "PINSIR-MEGA:\p"
	.string "PS: 65\n"
	.string "ATAQUE: 155\l"
	.string "DEFENSA: 120\l"
	.string "ATAQUE ESPECIAL: 55\l"
	.string "DEFENSA ESPECIAL: 90\l"
	.string "VELOCIDAD: 115\l"
	.string "TOTAL: 600\p"
	.string "Una bestia ofensiva, con muchas\n"
	.string "debilidades debido a su tipo dual\l"
	.string "BICHO-VOLADOR, pero que gracias a\l"
	.string "su habilidad PIEL CELESTE golpeará\l"
	.string "con una violencia única haciendo\l"
	.string "uso de RETROCESO y DOBLE-FILO, los\l"
	.string "cuales se volverán tipo VOLADOR,\l"
	.string "recibiendo STAB y ganando además\l"
	.string "otro 20% de potencia.\l"
	.string "Es visto como una leyenda por los\l"
	.string "CAZABICHOS de KANTO y JOHTO.$"



RocketHideoutJohtoP1Documento_115::
lock        
showmonpic SPECIES_GYARADOS_MEGA, 10, 3 
playmoncry SPECIES_GYARADOS, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_115, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_115:
.string "GYARADOS-MEGA:\p"
	.string "PS: 95\n"
	.string "ATAQUE: 155\l"
	.string "DEFENSA: 109\l"
	.string "ATAQUE ESPECIAL: 70\l"
	.string "DEFENSA ESPECIAL: 130\l"
	.string "VELOCIDAD: 81\l"
	.string "TOTAL: 640\p"
	.string "El TRITURAR de este POKÉMON\n"
	.string "destroza todo lo que alcance.\l"
	.string "Entre sus 155 en ATAQUE,\l"
	.string "conversión al TIPO SINIESTRO y\l"
	.string "habilidad MANDÍBULA FUERTE, ningún\l"
	.string "POKÉMON está a salvo de su\l"
	.string "mordedura, la más potente\l"
	.string "conocida.$"



RocketHideoutJohtoP1Documento_116::
lock        
showmonpic SPECIES_AMPHAROS_MEGA, 10, 3 
playmoncry SPECIES_AMPHAROS, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_116, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_116:
.string "AMPHAROS-MEGA:\p"
	.string "PS: 90\n"
	.string "ATAQUE: 95\l"
	.string "DEFENSA: 105\l"
	.string "ATAQUE ESPECIAL: 165\l"
	.string "DEFENSA ESPECIAL: 110\l"
	.string "VELOCIDAD: 45\l"
	.string "TOTAL: 610\p"
	.string "Gracias a su HABILIDAD, ADAPTABLE\n"
	.string "y sus 165 de BASE en ATAQUE\l"
	.string "ESPECIAL, el RAYO y PULSO DRAGÓN\l"
	.string "de este POKÉMON hará estragos. Aún\l"
	.string "con su pésima VELOCIDAD, gracias a\l"
	.string "sus buenas defensas y acceso a\l"
	.string "AGILIDAD, puede sacarle un gran\l"
	.string "provecho a su extraordinaria\l"
	.string "pegada.$"



RocketHideoutJohtoP1Documento_117::
lock        
showmonpic SPECIES_STEELIX_MEGA, 10, 3 
playmoncry SPECIES_STEELIX, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_117, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_117:
.string "STEELIX-MEGA:\p"
	.string "PS: 75\n"
	.string "ATAQUE: 125\l"
	.string "DEFENSA: 230\l"
	.string "ATAQUE ESPECIAL: 55\l"
	.string "DEFENSA ESPECIAL: 95\l"
	.string "VELOCIDAD: 30\l"
	.string "TOTAL: 610\p"
	.string "El mayor muro físico que existe,\n"
	.string "una DEFENSA a prueba de bombas, y\l"
	.string "un ATAQUE de 125 que le permite\l"
	.string "golpear duro con TERREMOTO y\l"
	.string "CABEZAHIERRO. Podríamos decir que\l"
	.string "tiene incluso un decente aguante\l"
	.string "especial, algo rarísimo en un TIPO\l"
	.string "TIERRA, elevando en 30 la DEFENSA\l"
	.string "ESPECIAL que STEELIX tiene, y\l"
	.string "quedándose en 95 de BASE.$"



RocketHideoutJohtoP1Documento_118::
lock        
showmonpic SPECIES_SCIZOR_MEGA, 10, 3 
playmoncry SPECIES_SCIZOR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_118, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_118:
.string "SCIZOR-MEGA:\p"
	.string "PS: 80\n"
	.string "ATAQUE: 155\l"
	.string "DEFENSA: 145\l"
	.string "ATAQUE ESPECIAL: 65\l"
	.string "DEFENSA ESPECIAL: 100\l"
	.string "VELOCIDAD: 85\l"
	.string "TOTAL: 630\p"
	.string "Por jerarquía y números, el TIPO\n"
	.string "BICHO de mayor poder global de\l"
	.string "todo KANTO y JOHTO. Sin un TIPO\l"
	.string "FUEGO de por medio, tumbar a este\l"
	.string "POKÉMON es complicadísimo. Con un\l"
	.string "aguante y pegada por el lado\l"
	.string "FÍSICO a la altura de GROUDON,\l"
	.string "buena DEFENSA ESPECIAL y potente\l"
	.string "prioridad con PUÑO BALA. De lo más\l"
	.string "completo y letal que existe.$"



RocketHideoutJohtoP1Documento_119::
lock        
showmonpic SPECIES_HERACROSS_MEGA, 10, 3 
playmoncry SPECIES_HERACROSS, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_119, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_119:
.string "HERACROSS-MEGA:\p"
	.string "PS: 80\n"
	.string "ATAQUE: 185\l"
	.string "DEFENSA: 115\l"
	.string "ATAQUE ESPECIAL: 40\l"
	.string "DEFENSA ESPECIAL: 105\l"
	.string "VELOCIDAD: 75\l"
	.string "TOTAL: 600\p"
	.string "El POKÉMON de mayor ATAQUE FÍSICO\n"
	.string "registrado hasta la fecha, con 185\l"
	.string "de BASE. Puede llegar a superar\l"
	.string "los 510 al nivel 100 en esta\l"
	.string "estadística. A pesar de su pequeña\l"
	.string "bajada en VELOCIDAD debido al\l"
	.string "engordamiento de su exoesqueleto,\l"
	.string "y su fatal debilidad x4 al TIPO\l"
	.string "VOLADOR, su HABILIDAD ENCADENADO\l"
	.string "le permitirá golpear durísimo con\l"
	.string "PIN MISIL, PEDRADA y RECURRENTE,\l"
	.string "tumbando de un golpe a muchísimos\l"
	.string "POKÉMON si alcanza a atacar.$"



RocketHideoutJohtoP1Documento_120::
lock        
showmonpic SPECIES_HOUNDOOM_MEGA, 10, 3 
playmoncry SPECIES_HOUNDOOM, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_120, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_120:
.string "HOUNDOOM-MEGA:\p"
	.string "PS: 85\n"
	.string "ATAQUE: 80\l"
	.string "DEFENSA: 90\l"
	.string "ATAQUE ESPECIAL: 145\l"
	.string "DEFENSA ESPECIAL: 95\l"
	.string "VELOCIDAD: 115\l"
	.string "TOTAL: 610\p"
	.string "Gracias a POTENCIA BRUTA, elevará\n"
	.string "en un 30% la potencia de\l"
	.string "movimientos como PULSO UMBRÍO,\l"
	.string "LANZALLAMAS o BOMBA LODO,\l"
	.string "aumentando mucho el valor de esos\l"
	.string "ya elevadísimos 145 en ATAQUE\l"
	.string "ESPECIAL.\l"
	.string "Con 90 de BASE en DEFENSA, arregla\l"
	.string "la que fue su mayor debilidad como\l"
	.string "HOUNDOOM.$"



RocketHideoutJohtoP1Documento_121::
lock        
showmonpic SPECIES_TYRANITAR_MEGA, 10, 3 
playmoncry SPECIES_TYRANITAR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_121, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_121:
.string "TYRANITAR-MEGA:\p"
	.string "PS: 100\n"
	.string "ATAQUE: 164\l"
	.string "DEFENSA: 150\l"
	.string "ATAQUE ESPECIAL: 95\l"
	.string "DEFENSA ESPECIAL: 120\l"
	.string "VELOCIDAD: 71\l"
	.string "TOTAL: 700\p"
	.string "Un titán con la capacidad de\n"
	.string "modificar el paisaje a su antojo.\l"
	.string "Entre ROCA SÓLIDA para frenar\l"
	.string "movimientos superefectivos y la\l"
	.string "pérdida del tipo SINIESTRO a\l"
	.string "cambio de ganar el DRAGÓN como un\l"
	.string "medio para eliminar muchas de sus\l"
	.string "debilidades, este POKÉMON es el\l"
	.string "tirano de JOHTO, ante el que,\l"
	.string "según cuenta la leyenda, solo un\l"
	.string "POKÉMON venido de las\l"
	.string "profundidades de la GUARIDA DRAGÓN\l"
	.string "puede rebasar en números globales.$"



RocketHideoutJohtoP1Documento_122::
lock        
showmonpic SPECIES_GARDEVOIR_MEGA, 10, 3 
playmoncry SPECIES_GARDEVOIR, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_122, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_122:
.string "GARDEVOIR-MEGA:\p"
	.string "PS: 68\n"
	.string "ATAQUE: 65\l"
	.string "DEFENSA: 85\l"
	.string "ATAQUE ESPECIAL: 165\l"
	.string "DEFENSA ESPECIAL: 135\l"
	.string "VELOCIDAD: 100\l"
	.string "TOTAL: 618\p"
	.string "Inmune a dragones y resistente al\n"
	.string "TIPO SINIESTRO, su VOZARRÓN\l"
	.string "golpeará durísimo gracias a su\l"
	.string "HABILIDAD, PIEL FEÉRICA, al tiempo\l"
	.string "que cuenta con buena VELOCIDAD y\l"
	.string "DEFENSA ESPECIAL sobresaliente.\l"
	.string "Cuenta con gran variedad de\l"
	.string "golpes, como RAYO y LLAMA\l"
	.string "EMBRUJADA, que su contraparte de\l"
	.string "KANTO, ALAKAZAM-MEGA, no puede\l"
	.string "aprender.$"



RocketHideoutJohtoP1Documento_123::
lock        
showmonpic SPECIES_GALLADE_MEGA, 10, 3 
playmoncry SPECIES_GALLADE, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_123, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_123:
.string "GALLADE-MEGA:\p"
	.string "PS: 68\n"
	.string "ATAQUE: 165\l"
	.string "DEFENSA: 95\l"
	.string "ATAQUE ESPECIAL: 65\l"
	.string "DEFENSA ESPECIAL: 115\l"
	.string "VELOCIDAD: 110\l"
	.string "TOTAL: 618\p"
	.string "La contraparte del TIPO LUCHA de\n"
	.string "GARDEVOIR. Gracias a su HABILIDAD\l"
	.string "ADAPTABLE compensa la baja\l"
	.string "potencia general de sus\l"
	.string "movimientos FÍSICOS, permitiéndole\l"
	.string "hacer uso de un PUÑO DRENAJE que,\l"
	.string "aparte de hacer estragos, le\l"
	.string "recuperará una ingente cantidad de\l"
	.string "vida. Sus bajos PS y buenas\l"
	.string "defensas contribuyen a agravar\l"
	.string "este efecto.$"



RocketHideoutJohtoP1Documento_124::
lock        
showmonpic SPECIES_AGGRON_MEGA, 10, 3 
playmoncry SPECIES_AGGRON, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_124, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_124:
.string "AGGRON-MEGA:\p"
	.string "PS: 70\n"
	.string "ATAQUE: 140\l"
	.string "DEFENSA: 230\l"
	.string "ATAQUE ESPECIAL: 60\l"
	.string "DEFENSA ESPECIAL: 80\l"
	.string "VELOCIDAD: 50\l"
	.string "TOTAL: 630\p"
	.string "Ligeramente inferior a\n"
	.string "STEELIX-MEGA defensivamente\l"
	.string "hablando, pero con un mayor ATAQUE\l"
	.string "FÍSICO que no podrá beneficiarse\l"
	.string "de golpear con TERREMOTO por STAB.\l"
	.string "Aún así, la pureza de su TIPO\l"
	.string "ACERO le libra de ser débil al\l"
	.string "AGUA, otorgándole también multitud\l"
	.string "de resistencias respecto a\l"
	.string "STEELIX-MEGA, como al PLANTA o al\l"
	.string "HIELO.$"



RocketHideoutJohtoP1Documento_125::
lock        
showmonpic SPECIES_ABSOL_MEGA, 10, 3 
playmoncry SPECIES_ABSOL, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_125, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_125:
.string "ABSOL-MEGA:\p"
	.string "PS: 65\n"
	.string "ATAQUE: 150\l"
	.string "DEFENSA: 100\l"
	.string "ATAQUE ESPECIAL: 115\l"
	.string "DEFENSA ESPECIAL: 100\l"
	.string "VELOCIDAD: 115\l"
	.string "TOTAL: 645\p"
	.string "Devolverá cualquier movimiento de\n"
	.string "estado que traten de usar contra\l"
	.string "él gracias a su HABILIDAD\l"
	.string "ESPEJOMÁGICO.\l"
	.string "A pesar de no contar con una\l"
	.string "HABILIDAD que aumente su pegada,\l"
	.string "sus 150 de BASE en ATAQUE hablan\l"
	.string "por sí solos, lo que unido a sus\l"
	.string "115 en VELOCIDAD le permitirán ser\l"
	.string "un POKÉMON peligroso que mantiene\l"
	.string "alejados los cambios de estado.$"



RocketHideoutJohtoP1Documento_126::
lock        
showmonpic SPECIES_MEDICHAM_MEGA, 10, 3 
playmoncry SPECIES_MEDICHAM, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_126, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_126:
.string "MEDICHAM-MEGA:\p"
	.string "PS: 60\n"
	.string "ATAQUE: 100\l"
	.string "DEFENSA: 85\l"
	.string "ATAQUE ESPECIAL: 80\l"
	.string "DEFENSA ESPECIAL: 85\l"
	.string "VELOCIDAD: 100\l"
	.string "TOTAL: 510\p"
	.string "Puede, en la práctica, alcanzar los\n"
	.string "245 de BASE en ATAQUE FÍSICO\l"
	.string "gracias a su HABILIDAD ENERGÍA\l"
	.string "PURA, que directamente multiplica\l"
	.string "x2 esta estadística.\l"
	.string "Fuera de esta absoluta anomalía\l"
	.string "que dispara su poder, un POKÉMON\l"
	.string "bastante normal, con números más\l"
	.string "propios de un POKÉMON con STATS\l"
	.string "decentes que de una\l"
	.string "MEGAEVOLUCIÓN.$"



RocketHideoutJohtoP1Documento_127::
lock        
showmonpic SPECIES_SALAMENCE_MEGA, 10, 3 
playmoncry SPECIES_SALAMENCE, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_127, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_127:
.string "SALAMENCE-MEGA:\p"
	.string "PS: 95\n"
	.string "ATAQUE: 145\l"
	.string "DEFENSA: 130\l"
	.string "ATAQUE ESPECIAL: 120\l"
	.string "DEFENSA ESPECIAL: 90\l"
	.string "VELOCIDAD: 120\l"
	.string "TOTAL: 700\p"
	.string "La leyenda de CASCADA METEORO.\n"
	.string "Dado su poder, muchos lo confunden\l"
	.string "con un POKÉMON LEGENDARIO, pero,\l"
	.string "aunque parezca sorprendente, un\l"
	.string "POKÉMON mortal ha podido alcanzar\l"
	.string "cotas tan elevadas, teniendo\l"
	.string "prácticamente todo lo que se le\l"
	.string "puede pedir a un DRAGÓN. Muy\l"
	.string "rápido, ATAQUE FÍSICO potente,\l"
	.string "movimientos de gran potencia,\l"
	.string "variedad tanto por lado físico y\l"
	.string "especial, incluso una enorme\l"
	.string "DEFENSA heredada de su etapa como\l"
	.string "SHELGON. Un sobresaliente en todo\l"
	.string "exceptuando su DEFENSA ESPECIAL,\l"
	.string "que sigue siendo buena.$"



RocketHideoutJohtoP1Documento_128::
lock        
showmonpic SPECIES_METAGROSS_MEGA, 10, 3 
playmoncry SPECIES_METAGROSS, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_128, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_128:
.string "METAGROSS-MEGA:\p"
	.string "PS: 80\n"
	.string "ATAQUE: 145\l"
	.string "DEFENSA: 150\l"
	.string "ATAQUE ESPECIAL: 105\l"
	.string "DEFENSA ESPECIAL: 110\l"
	.string "VELOCIDAD: 110\l"
	.string "TOTAL: 700\p"
	.string "El experimento estrella de DEVON\n"
	.string "C.O, que sin hacer mucho ruido ha\l"
	.string "sobrepasado el poder del MEWTWO\l"
	.string "original, siendo lo más parecido a\l"
	.string "un cyborg ultraoptimizado que\l"
	.string "arrasará con todo a su paso,\l"
	.string "carente de puntos débiles.\l"
	.string "Logró solucionar su baja VELOCIDAD\l"
	.string "como METAGROSS, ascendiendo a 110.\l"
	.string "Su único fallo radica en su propia\l"
	.string "estructura, incapaz de soportar\l"
	.string "más de 80 de BASE en SALUD, cifra\l"
	.string "algo corta para estos niveles.$"



RocketHideoutJohtoP1Documento_129::
lock        
showmonpic SPECIES_LUCARIO_MEGA, 10, 3 
playmoncry SPECIES_LUCARIO, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_129, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_129:
.string "LUCARIO-MEGA:\p"
	.string "PS: 70\n"
	.string "ATAQUE: 145\l"
	.string "DEFENSA: 88\l"
	.string "ATAQUE ESPECIAL: 140\l"
	.string "DEFENSA ESPECIAL: 70\l"
	.string "VELOCIDAD: 112\l"
	.string "TOTAL: 625\p"
	.string "A BOCAJARO por STAB + ADAPTABLE.\n"
	.string "PUÑO METEORO por STAB + ADAPTABLE.\l"
	.string "Prioridad con PUÑO BALA y ONDA\l"
	.string "VACÍO también por STAB y\l"
	.string "ADAPTABLE...\l"
	.string "A pesar de sus mejorables\l"
	.string "defensas, la variedad y poder\l"
	.string "ofensivo de este POKÉMON no tienen\l"
	.string "rival. Con todo tipo de boosteos y\l"
	.string "coberturas con ROCA AFILADA y\l"
	.string "PATADA ÍGNEA, solo INFERNAPE se le\l"
	.string "asemeja en movepool.$"



RocketHideoutJohtoP1Documento_130::
lock        
showmonpic SPECIES_MILOTIC_MEGA, 10, 3 
playmoncry SPECIES_MILOTIC, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_130, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_130:
.string "MILOTIC-MEGA:\p"
	.string "PS: 105\n"
	.string "ATAQUE: 65\l"
	.string "DEFENSA: 99\l"
	.string "ATAQUE ESPECIAL: 135\l"
	.string "DEFENSA ESPECIAL: 185\l"
	.string "VELOCIDAD: 81\l"
	.string "TOTAL: 670\p"
	.string "Los expertos dudan en si\n"
	.string "catalogarlo como el tercer\l"
	.string "PSEUDOLEGENDARIO de HOENN, dado\l"
	.string "que su origen aún es un misterio.\l"
	.string "MILOTIC-MEGA dispara su DEFENSA\l"
	.string "ESPECIAL hasta los 185 de BASE\l"
	.string "mientras mantiene la pegada de un\l"
	.string "ALAKAZAM. Bueno también aguantando\l"
	.string "golpes físicos. Su única pega es\l"
	.string "una VELOCIDAD de 81 puntos.$"



RocketHideoutJohtoP1Documento_131::
lock        
showmonpic SPECIES_NOIVERN_MEGA, 10, 3 
playmoncry SPECIES_NOIVERN, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_131, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_131:
.string "NOIVERN-MEGA:\p"
	.string "PS: 85\n"
	.string "ATAQUE: 80\l"
	.string "DEFENSA: 100\l"
	.string "ATAQUE ESPECIAL: 127\l"
	.string "DEFENSA ESPECIAL: 90\l"
	.string "VELOCIDAD: 153\l"
	.string "TOTAL: 635\p"
	.string "De la lejana KALOS, el DRAGÓN más\n"
	.string "rápido conocido, que entre\l"
	.string "INDEFENSO y sus 127 en ATAQUE\l"
	.string "ESPECIAL podrá seguir pegando muy\l"
	.string "duro con VENDAVAL u ONDA CERTERA.\l"
	.string "Se cree que pertenece a la misma\l"
	.string "rama familiar de CROBAT.$"



RocketHideoutJohtoP1Documento_132::
lock        
showmonpic SPECIES_FLYGON_MEGA, 10, 3 
playmoncry SPECIES_FLYGON, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_132, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_132:
.string "FLYGON-MEGA:\p"
	.string "PS: 80\n"
	.string "ATAQUE: 90\l"
	.string "DEFENSA: 100\l"
	.string "ATAQUE ESPECIAL: 140\l"
	.string "DEFENSA ESPECIAL: 100\l"
	.string "VELOCIDAD: 140\l"
	.string "TOTAL: 650\p"
	.string "Al cambiar su TIPO TIERRA por el\n"
	.string "BICHO, vio disminuido en 10 puntos\l"
	.string "su ATAQUE, y a cambio, elevó hasta\l"
	.string "los 140 de BASE su ATAQUE\l"
	.string "ESPECIAL, contando con un ratio\l"
	.string "VELOCIDAD-AT.ESP único.\l"
	.string "Su gran variedad de movimientos y\l"
	.string "HABILIDAD CROMOLENTE, le hacen\l"
	.string "capaz de tumbar a cualquiera.$"



RocketHideoutJohtoP1Documento_133::
lock        
showmonpic SPECIES_STARMIE_MEGA, 10, 3 
playmoncry SPECIES_STARMIE, CRY_MODE_ENCOUNTER
msgbox RocketHideoutJohtoP1Documento_Text_133, MSGBOX_DEFAULT
hidemonpic
release     
end

RocketHideoutJohtoP1Documento_Text_133:
.string "STARMIE-MEGA:\p"
	.string "PS: 65\n"
	.string "ATAQUE: 75\l"
	.string "DEFENSA: 100\l"
	.string "ATAQUE ESPECIAL: 135\l"
	.string "DEFENSA ESPECIAL: 100\l"
	.string "VELOCIDAD: 145\l"
	.string "TOTAL: 620\p"
	.string "Su conversión al TIPO HIELO le\n"
	.string "permitió canalizar mucho mejor sus\l"
	.string "poderes psíquicos, ganando\l"
	.string "potencia, agilidad y aguante\l"
	.string "también.\l"
	.string "Gracias a su HABILIDAD, POTENCIA\l"
	.string "BRUTA, será aún más letal con toda\l"
	.string "la variedad de movimientos que se\l"
	.string "verán beneficiados.$"
