SafariZone_House4_MapScripts::
	.byte 0

SafariZoneHouse4_1::
lock     
faceplayer     
msgbox SafariZone_House41_Text_1, MSGBOX_DEFAULT
release     
end

SafariZone_House41_Text_1:
.string "Utilizar CEBO te permitirá atrapar\n"
.string "más fácilmente a los POKéMON.$"



SafariZoneHouse4_2::
lock     
faceplayer     
msgbox SafariZone_House41_Text_2, MSGBOX_DEFAULT
release     
end

SafariZone_House41_Text_2:
.string "Tirar PIEDRAS a los POKéMON\n"
.string "podría hacerles huir, pero hará\l"
.string "que sean más fáciles de atrapar.$"



SafariZoneHouse4_3::
lock     
faceplayer     
msgbox SafariZone_House41_Text_3, MSGBOX_DEFAULT
release     
end

SafariZone_House41_Text_3:
.string "Caminé mucho, pero no he visto\n"
.string "a los POKéMON que quería.$"
