Cianwood_PkmnCenter_MapScripts::
	.byte 0

CianwoodPkmnCenter1::
end



CianwoodPkmnCenter2::
lock     
faceplayer     
msgbox Cianwood_PkmnCenter_Text_2, MSGBOX_DEFAULT
release     
end

Cianwood_PkmnCenter_Text_2:
.string "La vida del marinero es dura, pero\n"
.string "también lo es para sus mujeres, no\l"
.string "dejamos de otear el horizonte cada\l"
.string "mañana, esperando el regreso de\l"
.string "nuestros maridos.$"



CianwoodPkmnCenter3::
lock     
faceplayer     
msgbox Cianwood_PkmnCenter_Text_3, MSGBOX_DEFAULT
release     
end

Cianwood_PkmnCenter_Text_3:
.string "Los TIPO LUCHA de ANÍBAL son\n"
.string "terriblemente fuertes, ¿puedes\l"
.string "creerte que un MACHAMP a altísimo\l"
.string "nivel es su POKÉMON más débil?$"



CianwoodPkmnCenter4::
lock     
faceplayer     
msgbox Cianwood_PkmnCenter_Text_4, MSGBOX_DEFAULT
release     
end

Cianwood_PkmnCenter_Text_4:
.string "ISLAS REMOLINO siempre fueron un\n"
.string "misterio, dicen que todo cambió en\l"
.string "ellas el día del incendio de TORRE\l"
.string "LATÓN.$"
