SouthRoute45_MapScripts::
	.byte 0

SouthRoute45-1::
end



SouthRoute45-2::
end



SouthRoute45-3::
end



SouthRoute45-4::
end



SouthRoute45-5::
end



SouthRoute45-6::
end



SouthRoute45-7::
end



SouthRoute45-8::
end



SouthRoute45-9::
lock     
faceplayer     
msgbox Text_9, MSGBOX_DEFAULT
release     
end

Text_9:
.string "Mi misión es asegurarme que nadie\n"
.string "pasa de este punto por casualidad,\l"
.string "en caso de presentarse algún\l"
.string "montañero despistado, ¡el RUGIDO\l"
.string "de mi GRANBULL acabará de un\l"
.string "plumazo con esa casualidad y le\l"
.string "hará torcer para el otro lado!$"



SouthRoute45-10::
lock     
faceplayer     
msgbox Text_10, MSGBOX_DEFAULT
release     
end

Text_10:
.string "¿Todo bien, sir?\n"
.string "¡Le deseamos suerte en su andadura\l"
.string "por JOHTO!$"



SouthRoute45-11::
lock     
faceplayer     
msgbox Text_11, MSGBOX_DEFAULT
release     
end

Text_11:
.string "¡A su servicio para todo lo que\n"
.string "necesite, ADMIN.JEFE [player]!$"



SouthRoute45-12::
lock     
faceplayer     
msgbox Text_12, MSGBOX_DEFAULT
release     
end

Text_12:
.string "Al norte de aquí se encuentra\n"
.string "CIUDAD ENDRINO, famosa por su gran\l"
.string "devoción hacia el TIPO DRAGÓN, sin\l"
.string "embargo, es imposible llegar a la\l"
.string "ciudad desde aquí, la única forma\l"
.string "de llegar es pasando por la\l"
.string "RUTA HELADA.$"



SouthRoute45-13::
lock     
faceplayer     
msgbox Text_13, MSGBOX_DEFAULT
release     
end

Text_13:
.string "Es imposible que descubran la\n"
.string "base, las montañas de los\l"
.string "alrededores la tapan\l"
.string "completamente.\l"
.string "¡Solo TORRE CAMPANA tiene la\l"
.string "altura como para sobresalir por\l"
.string "encima de ellas!$"



SouthRoute45-14::
lock     
faceplayer     
msgbox Text_14, MSGBOX_DEFAULT
release     
end

Text_14:
.string "Estamos al sur de RUTA 45, tan al\n"
.string "sur que esta zona no está\l"
.string "registrada por los mapas\l"
.string "convencionales, pero no lo\l"
.string "suficiente como para considerarse\l"
.string "parte del norte de RUTA 29, entre\l"
.string "PUEBLO PRIMAVERA y CIUDAD CEREZO.$"



SouthRoute45-15::
end



SouthRoute45-16::
end
