CeladonCity_Shop_6F_MapScripts::
	.byte 0

CeladonShop6F-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Mi hermano dice que no hable con\n"
.string "gente del TEAM ROCKET.$"



CeladonShop6F-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Mi hermana es ENTRENADORA,\n"
.string "¡de verdad!\p"
.string "¡Pero es tan infantil que me vuelve\n"
.string "loco!$"
