RuinValley_MapScripts::
	.byte 0

RuinValley1::
end


RuinValley2::
end


RuinValley3::
end


RuinValley4::
end


RuinValley5::
end


RuinValley6::
end


RuinValley7::
end


RuinValley8::
end


RuinValley9::
end


RuinValley10::
end


RuinValley11::
end


RuinValley12::
end


RuinValley13::
end


RuinValley14::
end


RuinValley15::
end


RuinValley16::
end


RuinValley17::
end


RuinValley18::
end



RuinValley_EventScript_Montanero::
	trainerbattle_single TRAINER_NICHOLAS, RuinValley_Text_MontaneroIntro, RuinValley_Text_MontaneroDefeated
	msgbox RuinValley_Text_MontaneroPostBattle, MSGBOX_AUTOCLOSE
	end



RuinValley_EventScript_Montanero2::
	trainerbattle_single TRAINER_BRENDAN_ROUTE_119_TREECKO, RuinValley_Text_Montanero2Intro, RuinValley_Text_Montanero2Defeated
	msgbox RuinValley_Text_Montanero2PostBattle, MSGBOX_AUTOCLOSE
	end



RuinValley_EventScript_Montanero3::
	trainerbattle_single TRAINER_KATHLEEN, RuinValley_Text_Montanero3Intro, RuinValley_Text_Montanero3Defeated
	msgbox RuinValley_Text_Montanero3PostBattle, MSGBOX_AUTOCLOSE
	end



RuinValley_EventScript_Montanero4::
	trainerbattle_single TRAINER_CLIFFORD, RuinValley_Text_Montanero4Intro, RuinValley_Text_Montanero4Defeated
	msgbox RuinValley_Text_Montanero4PostBattle, MSGBOX_AUTOCLOSE
	end



RuinValley_EventScript_Necio::
	trainerbattle_single TRAINER_GRUNT_SPACE_CENTER_3, RuinValley_Text_NecioIntro, RuinValley_Text_NecioDefeated
	msgbox RuinValley_Text_NecioPostBattle, MSGBOX_AUTOCLOSE
	end
