RuinsOfAlph_House_MapScripts::
	.byte 0

RuinsOfAlphHouse1::
lock     
faceplayer     
msgbox RuinsOfAlph_House1_Text_1, MSGBOX_DEFAULT
release     
end

RuinsOfAlph_House1_Text_1:
.string "Creo que todos esos NATU y XATU\n"
.string "que viven por las RUINAS son una\l"
.string "de las claves para resolver su\l"
.string "misterio.$"



RuinsOfAlphHouse2::
lock     
faceplayer     
msgbox RuinsOfAlph_House1_Text_2, MSGBOX_DEFAULT
release     
end

RuinsOfAlph_House1_Text_2:
.string "No me gustan nada esos individuos\n"
.string "de negro que vinieron poco después\l"
.string "del terremoto.\l"
.string "…\l"
.string "…\l"
.string "¿Qué?\l"
.string "¿¡Tú eres su superior?!$"



RuinsOfAlphHouse3::
lock     
faceplayer     
msgbox RuinsOfAlph_House1_Text_3, MSGBOX_DEFAULT
release     
end

RuinsOfAlph_House1_Text_3:
.string "Las RUINAS datan de hace unos 1500\n"
.string "años.\l"
.string "Pero ignoramos por qué o por quién\l"
.string "fueron construidas.$"
