OreburghCity_MapScripts::
	.byte 0

Pirita_Cartel::
lock
msgbox Pirita_Cartel_Texto_1, MSGBOX_SIGN
release
end

Pirita_Cartel_Texto_1:
	.string "CIUDAD PIRITA\n"
	.string "Ciudad de la energía$"



Pirita_Gimnasio::
lock
msgbox Pirita_Gimnasio_Texto_1, MSGBOX_SIGN
release
end

Pirita_Gimnasio_Texto_1:
	.string "GIMNASIO POKÉMON de CIUDAD PIRITA\n"
	.string "LÍDER: ROCO\l"
	.string "¡La Roca para mis amigos!$"


Pirita_Museo::
lock
msgbox Pirita_Museo_Texto_1, MSGBOX_SIGN
release
end

Pirita_Museo_Texto_1:
	.string "MUSEO MINERO de CIUDAD PIRITA\n"
	.string "La aventura de la minería$"


Pirita_Primer_NPC::
lock     
faceplayer     
msgbox Pirita_Primer_NPC_Texto_1, MSGBOX_NPC
release     
end

Pirita_Primer_NPC_Texto_1:
.string "Es una suerte que podamos enseñar una\n"
.string "MT todas las veces que queramos.\p"
.string "¿Te imaginas el problema para decidir,\n"
.string "si solo se pudieran usar una vez?$"



Pirita_Segundo_NPC::
lock     
faceplayer     
msgbox Pirita_Segundo_NPC_Texto_1, MSGBOX_NPC
release     
end

Pirita_Segundo_NPC_Texto_1:
.string "El LÍDER del GIMNASIO es joven, pero es\n"
.string "el encargado de la seguridad de la mina.\p"
.string "¡Es un experto en muchos campos!$"



Pirita_Tercer_NPC::
lock     
faceplayer     
msgbox Pirita_Tercer_NPC_Texto_1, MSGBOX_NPC
release     
end

Pirita_Tercer_NPC_Texto_1:
.string "Cuando me paseo con mis deportivas,\n"
.string "¡soy el centro de todas las miradas!\p"
.string "O eso me parece a mí.\n"
.string "Siempre hay alguien mirándome.$"



Pirita_Cuarto_NPC::
lock     
faceplayer     
msgbox Pirita_Cuarto_NPC_Texto_1, MSGBOX_NPC
release     
end

Pirita_Cuarto_NPC_Texto_1:
.string "¿Has visto las chimeneas?\n"
.string "Expulsan el vapor de abajo.$"


Pirita_Quinto_NPC::
lock     
faceplayer     
msgbox Pirita_Quinto_NPC_Texto_1, MSGBOX_NPC
release     
end

Pirita_Quinto_NPC_Texto_1:
.string "Cápsulas del tiempo naturales\n"
.string "enterradas hace muchísimos años…\p"
.string "Eso son los FÓSILES.$"


Pirita_Sexto_NPC::
lock     
faceplayer     
msgbox Pirita_Sexto_NPC_Texto_1, MSGBOX_NPC
release     
end

Pirita_Sexto_NPC_Texto_1:
.string "Más adelante hay una gran montaña\n"
.string "que se yergue sobre toda la zona.\p"
.string "Divide SINNOH en dos partes.$"
