VermilionCity_MapScripts::
	.byte 0

VermilionCity1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "¡Toda esta contaminación que\n"
.string "últimamente se aprecia por la\l"
.string "región debe ser culpa vuestra!\l"
.string "¡Vuestros GRIMER y KOFFING acaban\l"
.string "con el medio ambiente!$"


VermilionCity2::
end


VermilionCity3::
end


VermilionCity4::
end


VermilionCity5::
end


VermilionCity6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "A vosotros los ROCKET pronto se\n"
.string "os va a acabar el privilegio de\l"
.string "poder usar nuestro transporte\l"
.string "marítimo. He oído que el COMITÉ DE\l"
.string "LA LIGA aprobará pronto una ley\l"
.string "que prohíba el transporte de\l"
.string "ROCKET en el trayecto CARMÍN-ISLA\l"
.string "INTA y viceversa.$"


VermilionCity7::
end


VermilionCity8::
end


VermilionCity9::
end


VermilionCity10::
end


VermilionCity11::
end
