MahoganyTown_PkmnCenter_MapScripts::
	.byte 0

MahoganyTownPkmnCenter1::
end



MahoganyTownPkmnCenter2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Mucha gente nueva está llegando\n"
.string "aquí últimamente, me sorprende que\l"
.string "FREDO no haya dicho nada.$"



MahoganyTownPkmnCenter3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "En mi juventud, rodeaba a nado todo\n"
.string "el LAGO DE LA FURIA. ¡Ahora lo\l"
.string "rodeo caminando!$"



MahoganyTownPkmnCenter4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "¿Has estado en el LAGO DE LA\n"
.string "FURIA?\l"
.string "Parece que su profundidad total es\l"
.string "aún un misterio, ¿podría haber\l"
.string "alguna nueva especie ahí abajo?$"
