CeladonCity_Gym_MapScripts::
	.byte 0

CeladonCityGym1::
end



CeladonCityGym2::
end



CeladonCityGym3::
end



CeladonCityGym4::
end



CeladonCityGym5::
end



CeladonCityGym6::
end



CeladonCityGym7::
end



CeladonCityGym10::
end



CeladonCityGym_EventScript_Chica::
	trainerbattle_single TRAINER_JESSICA_3, CeladonCityGym_Text_ChicaIntro, CeladonCityGym_Text_ChicaDefeated
	msgbox CeladonCityGym_Text_ChicaPostBattle, MSGBOX_AUTOCLOSE
	end



CeladonCityGym_EventScript_Chica2::
	trainerbattle_single TRAINER_BRAWLY_1, CeladonCityGym_Text_Chica2Intro, CeladonCityGym_Text_Chica2Defeated
	msgbox CeladonCityGym_Text_Chica2PostBattle, MSGBOX_AUTOCLOSE
	end



CeladonCityGym_EventScript_Chica3::
	trainerbattle_single TRAINER_WATTSON_1, CeladonCityGym_Text_Chica3Intro, CeladonCityGym_Text_Chica3Defeated
	msgbox CeladonCityGym_Text_Chica3PostBattle, MSGBOX_AUTOCLOSE
	end



CeladonCityGym_EventScript_Chica4::
	trainerbattle_single TRAINER_NOLEN, CeladonCityGym_Text_Chica4Intro, CeladonCityGym_Text_Chica4Defeated
	msgbox CeladonCityGym_Text_Chica4PostBattle, MSGBOX_AUTOCLOSE
	end



CeladonCityGym_EventScript_Chica5::
	trainerbattle_single TRAINER_FLANNERY_1, CeladonCityGym_Text_Chica5Intro, CeladonCityGym_Text_Chica5Defeated
	msgbox CeladonCityGym_Text_Chica5PostBattle, MSGBOX_AUTOCLOSE
	end



CeladonCityGym_EventScript_Chica6::
	trainerbattle_single TRAINER_JESSICA_4, CeladonCityGym_Text_Chica6Intro, CeladonCityGym_Text_Chica6Defeated
	msgbox CeladonCityGym_Text_Chica6PostBattle, MSGBOX_AUTOCLOSE
	end



CeladonCityGym_EventScript_Chica7::
	trainerbattle_single TRAINER_PRESLEY, CeladonCityGym_Text_Chica7Intro, CeladonCityGym_Text_Chica7Defeated
	msgbox CeladonCityGym_Text_Chica7PostBattle, MSGBOX_AUTOCLOSE
	end
