Ecruteak_TinTowerP1_MapScripts::
	.byte 0

TinTowerP1_1::
lock     
faceplayer     
msgbox Ecruteak_TinTowerp1_Text_1, MSGBOX_DEFAULT
release     
end

Ecruteak_TinTowerp1_Text_1:
	.string "Whoever chases the truth has the risk\n"
	.string "to find it.$"



TinTowerP1_2::
lock     
faceplayer     
msgbox Ecruteak_TinTowerp1_Text_2, MSGBOX_DEFAULT
release     
end

Ecruteak_TinTowerp1_Text_2:
	.string "Don't fight for the power, do it for the\n"
	.string "virtue.$"



TinTowerP1_3::
lock     
faceplayer     
msgbox Ecruteak_TinTowerp1_Text_3, MSGBOX_DEFAULT
release     
end

Ecruteak_TinTowerp1_Text_3:
	.string "A fool never recovers from success.$"



TinTowerP1_4::
lock     
faceplayer     
msgbox Ecruteak_TinTowerp1_Text_4, MSGBOX_DEFAULT
release     
end

Ecruteak_TinTowerp1_Text_4:
	.string "BELL TOWER was built in honor of HO-OH,\n"
	.string "just as BURNED TOWER, formerly known as\l"
	.string "BRASS TOWER, was built in honor of\l"
	.string "LUGIA. Those who came to know the\l"
	.string "ultimate connection between the two\l"
	.string "towers are no longer among us.$"



TinTowerP1_5::
lock     
faceplayer     
msgbox Ecruteak_TinTowerp1_Text_5, MSGBOX_DEFAULT
release     
end

Ecruteak_TinTowerp1_Text_5:
	.string "Experience is something you don't get\n"
	.string "until just after you need it.$"
