BaseRocketHoenn_MapScripts::
map_script MAP_SCRIPT_ON_FRAME_TABLE, BaseRocketHoenn_OnFrame
	.byte 0

BaseRocketHoenn_OnFrame:
map_script_2 VAR_UNUSED_0x40F7, 184, BaseRocketHoenn_Escena_Lavanda
	.2byte 0


BaseRocketHoenn_Escena_Lavanda::
setvar VAR_UNUSED_0x40F7, 185
warpsilent MAP_LAVENDER_TOWN, 18, 0
release
end



BaseRocketHoenn_1::
end

BaseRocketHoenn_2::
end

BaseRocketHoenn_3::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_3, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_3:
.string "Dejar que otros ganen las batallas\n"
.string "pequeñas es una manipulación muy\l"
.string "poderosa.$"



BaseRocketHoenn_4::
end

BaseRocketHoenn_5::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_5, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_5:
.string "Hay algunos POKÉMON de HOENN que molan\n"
.string "mucho. ¡MIGHTYENA y SHARPEDO son mis\l"
.string "favoritos!$"




BaseRocketHoenn_6::
end

BaseRocketHoenn_7::
end

BaseRocketHoenn_8::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_8, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_8:
.string "A nuestra ADMIN.JEFA le gusta más salir\n"
.string "a explorar que estar sentada en su\l"
.string "despacho. Los POKÉMON que tiene\l"
.string "reflejan sus innumerables viajes.$"




BaseRocketHoenn_9::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_9, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_9:
.string "Uno sabe que ha avanzado realmente en\n"
.string "una teoría cuando ya no puede explicar\l"
.string "por qué durante tanto tiempo no fue\l"
.string "capaz de ver lo obvio.$"




BaseRocketHoenn_10::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_10, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_10:
.string "Esta región está llena de POKÉMON raros\n"
.string "y exóticos. Cuando salí al desierto me\l"
.string "atacó un POKÉMON que parecía una\l"
.string "libélula, pero los CIENTÍFICOS de aquí\l"
.string "me han dicho que no es TIPO BICHO.$"

BaseRocketHoenn_11::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_11, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_11:
.string "¿Has oído hablar de los movimientos Z?\n"
.string "Un colega en la sucursal de KANTO me\l"
.string "filtró que en la nueva TORRE RADIO\l"
.string "podrá comprarse un objeto que activa\l"
.string "ese poder.$"




BaseRocketHoenn_12::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_12, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_12:
.string "El hecho de crear prototipos superiores\n"
.string "a PORYGON3 supondrá un duro golpe al\l"
.string "ego de BILL. Aunque no es fácil superar\l"
.string "la ofensiva de ese monstruo.$"



BaseRocketHoenn_13::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_13, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_13:
.string "Muchos creen que GIOVANNI debió ser\n"
.string "más duro con LANCE, después de todo el\l"
.string "daño que causó. Yo creo que el\l"
.string "verdadero castigo de LANCE aún no lo\l"
.string "hemos visto.$"


BaseRocketHoenn_14::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_14, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_14:
.string "Con frecuencia, no hacer nada es el\n"
.string "mayor riesgo.$"




BaseRocketHoenn_15::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_15, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_15:
.string "Hemos invertido millones en explorar\n"
.string "cada rincón de las regiones conocidas,\l"
.string "ahora nuestra red de información es la\l"
.string "más completa del mundo.$"





BaseRocketHoenn_16::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_16, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_16:
.string "Efectivamente, TESELIA es la región\n"
.string "que vio nacer al DRAGÓN ORIGINAL. Este\l"
.string "se dividió en 3 POKÉMON, de un poder\l"
.string "similar a MEWTWO, ¿cómo hiciste para\l"
.string "derrotar a semejante bestia?$"





BaseRocketHoenn_17::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_17, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_17:
.string "VOLCARONA es increíble, los dioses del\n"
.string "MUNDO POKÉMON debieron concederle la\l"
.string "jerarquía de un PSEUDOLEGENDARIO, ¿o\l"
.string "crees que eso no lo deciden los dioses,\l"
.string "sino la voluntad de los mortales?$"




BaseRocketHoenn_18::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_18, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_18:
.string "Muchos confunden AERODACTYL MEGA con\n"
.string "AERODACTYL PRIMIGENIO. El primero fue\l"
.string "creado por el C.MIGUEL, gracias a\l"
.string "formar la MEGAPIEDRA específica. El\l"
.string "segundo fue obra de OAK y BLAINE, su\l"
.string "reparto de STATS varía ligeramente,\l"
.string "pero AERODACTYL PRIMIGENIO es\l"
.string "superior, ya que puede usar un objeto\l"
.string "equipable.$"




BaseRocketHoenn_19::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_19, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_19:
.string "¿Has visto los mares de HOENN? Son el\n"
.string "50% de la región, existe un equilibrio\l"
.string "perfecto entre agua y tierra aquí,\l"
.string "nadie debería tratar de romperlo.$"




BaseRocketHoenn_20::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_20, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_20:
.string "No hay sufrimiento mayor que\n"
.string "levantarse por la mañana siendo\l"
.string "consciente de que eres tan solo un\l"
.string "dígito, un pasivo, un peón, un esclavo,\l"
.string "un ser inerte y clónico sometido a una\l"
.string "servidumbre incesante.$"

BaseRocketHoenn_21::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_21, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_21:
.string "Ese SEVIPER se parece mucho a nuestro\n"
.string "ARBOK, creo que es incluso mejor. ¡Un\l"
.string "CIENTÍFICO me dijo que puede aprender\l"
.string "LANZALLAMAS para defenderse del TIPO\l"
.string "ACERO!$"




BaseRocketHoenn_22::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_22, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_22:
.string "SINOHH es la región con mayor número de\n"
.string "LEGENDARIOS. Que sea el epicentro del\l"
.string "llamado “DIOS POKÉMON” tiene mucho\l"
.string "que ver.$"




BaseRocketHoenn_23::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_23, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_23:
.string "Sé que CAMERUPT no es TIPO VENENO, aún\n"
.string "así, tiene ese algo que le hace el\l"
.string "compañero ideal para un miembro del\l"
.string "TEAM ROCKET. ¡Igual que SHARPEDO!$"




BaseRocketHoenn_24::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_24, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_24:
.string "Me gusta ZANGOOSE, es más lento que\n"
.string "PERSIAN, ¡pero su CUCHILLADA es letal!$"




BaseRocketHoenn_25::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_25, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_25:
.string "¡No hay nada como un MUK! ¡Ese SWALOT\n"
.string "de HOENN no es más que una copia\l"
.string "barata!$"




BaseRocketHoenn_26::
end

BaseRocketHoenn_27::
end

BaseRocketHoenn_28::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_28, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_28:
.string "Ese ARCHEOPS tiene mucho potencial,\n"
.string "¿no crees? ¡Qué desperdicio de\l"
.string "HABILIDAD!$"




BaseRocketHoenn_29::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_29, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_29:
.string "La seguridad de esta BASE es muy\n"
.string "estricta, para llegar al S2 necesitas\l"
.string "una tarjeta, individualizada para cada\l"
.string "miembro.$"




BaseRocketHoenn_30::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_30, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_30:
.string "Más al sur está CIUDAD MALVALONA, dicen\n"
.string "que tiene un CASINO como el nuestro.$"




BaseRocketHoenn_31::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_31, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_31:
.string "KALOS es la región con menos POKÉMON\n"
.string "singulares, aunque la tecnología de las\l"
.string "MEGAPIEDRAS se desarrolló por primera\l"
.string "vez allí.$"




BaseRocketHoenn_32::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_32, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_32:
.string "ELM está obsesionado con las ONDAS DE\n"
.string "RADIO y la EVOLUCIÓN POKÉMON. Creo que\l"
.string "no le importaría dejar aberraciones\l"
.string "por el camino, si con ello logra sus\l"
.string "objetivos.$"




BaseRocketHoenn_33::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_33, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_33:
.string "Me encantaría ser trasladado a la\n"
.string "nueva TORRE RADIO, en LAVANDA, y\l"
.string "trabajar en el P6 o P7, ¡las vistas que\l"
.string "debe haber allí!$"




BaseRocketHoenn_34::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_34, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_34:
.string "El otro día bajé al DESIERTO y un\n"
.string "enorme cactus me atacó. Desde\l"
.string "entonces, se ha vuelto mi POKÉMON\l"
.string "favorito.$"




BaseRocketHoenn_35::
lock     
faceplayer     
msgbox BaseRocketHoenn_Text_35, MSGBOX_DEFAULT
release     
end

BaseRocketHoenn_Text_35:
.string "Lo que más nos impide avanzar es lo\n"
.string "pronto que nos sentimos contentos con\l"
.string "nosotros mismos.$"



BaseRocketHoennDocumento_100::
lock        
showmonpic SPECIES_UXIE, 10, 3 
playmoncry SPECIES_UXIE, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_100, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_100:
.string "NÚMERO 14: UXIE\p"
	.string "PS: 75\n"
	.string "ATAQUE: 75\l"
	.string "DEFENSA: 130\l"
	.string "ATAQUE ESPECIAL: 75\l"
	.string "DEFENSA ESPECIAL: 130\l"
	.string "VELOCIDAD: 95\l"
	.string "TOTAL: 580\p"
	.string "LEGENDARIOS de SINOHH. Representa la\n"
	.string "sabiduría. Cuenta con unos atributos\l"
	.string "defensivos extrardinarios, hasta el\l"
	.string "punto de superar tanto en DEFENSA\l"
	.string "como en DEFENSA ESPECIAL al propio\l"
	.string "DIOS POKEMON, contando con 130 STATS\l"
	.string "BASE en ambas. Aún con buena\l"
	.string "VELOCIDAD, su capacidad ofensiva es\l"
	.string "mediocre para un LEGENDARIO.$"



BaseRocketHoennDocumento_101::
lock        
showmonpic SPECIES_AZELF, 10, 3 
playmoncry SPECIES_AZELF, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_101, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_101:
.string "NÚMERO 13: AZELF\p"
	.string "PS: 75\n"
	.string "ATAQUE: 125\l"
	.string "DEFENSA: 70\l"
	.string "ATAQUE ESPECIAL: 125\l"
	.string "DEFENSA ESPECIAL: 70\l"
	.string "VELOCIDAD: 115\l"
	.string "TOTAL: 580\p"
	.string "Uno de los 3 ELFOS LEGENDARIOS de\n"
	.string "SINOHH. Representa la voluntad. Con\l"
	.string "diferencia el de mayor cappacidad\l"
	.string "ofensiva de los 3 ELFOS, aún a costa de\l"
	.string "ser el más frágil, su gran variedad de\l"
	.string "movimientos tanto físicos como\l"
	.string "especiales lo convierten en un peligro,\l"
	.string "pudiendo incluso usar combos como el\l"
	.string "de MOFA+TRAMPA ROCAS+EXPLOSIÓN y 115\l"
	.string "de STATS BASE en VELOCIDAD como\l"
	.string "respaldo.$"



BaseRocketHoennDocumento_102::
lock        
showmonpic SPECIES_MESPRIT, 10, 3 
playmoncry SPECIES_MESPRIT, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_102, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_102:
.string "NÚMERO 12: MESPRIT\p"
	.string "PS: 80\n"
	.string "ATAQUE: 105\l"
	.string "DEFENSA: 105\l"
	.string "ATAQUE ESPECIAL: 105\l"
	.string "DEFENSA ESPECIAL: 105\l"
	.string "VELOCIDAD: 80\l"
	.string "TOTAL: 580\p"
	.string "Uno de los 3 ELFOS LEGENDARIOS de\n"
	.string "SINOHH. Representa las emociones. Es\l"
	.string "el más equilibrado de los 3, hasta el\l"
	.string "punto de superar los 100 STATS BASE en\l"
	.string "4 estadísticas diferentes, algo casi\l"
	.string "inédito en un LEGENDARIO MENOR. Para\l"
	.string "muchos este reparto le supone un\l"
	.string "lastre, puesto que no llega a\l"
	.string "especializarse por completo en una\l"
	.string "sola faceta como sus dos hermanos,\l"
	.string "quedando en tierra de nadie.$"



BaseRocketHoennDocumento_103::
lock        
showmonpic SPECIES_GARCHOMP, 10, 3 
playmoncry SPECIES_GARCHOMP, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_103, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_103:
.string "NÚMERO 11: GARCHOMP\p"
	.string "PS: 108\n"
	.string "ATAQUE: 130\l"
	.string "DEFENSA: 95\l"
	.string "ATAQUE ESPECIAL: 80\l"
	.string "DEFENSA ESPECIAL: 85\l"
	.string "VELOCIDAD: 102\l"
	.string "TOTAL: 580\p"
.string "Para muchos, el PSEUDOLEGENDARIO\n"
	.string "número 1. Lo tiene todo para ser un\l"
	.string "POKÉMON dominante: VELOCIDAD\l"
	.string "superior a 100, ATAQUE FÍSICO\l"
	.string "desbordante, buena combinación de\l"
	.string "tipos, golpeando duro por STAB en\l"
	.string "ambos casos, ATAQUE ESPECIAL de solo\l"
	.string "80 puntos para repartir de la forma más\l"
	.string "eficiente sus 600 STATS BASE de\l"
	.string "total... Algunos incluso creen que está\l"
	.string "en disposición de competir con\l"
	.string "LEGENDARIOS MAYORES.$"



BaseRocketHoennDocumento_104::
lock        
showmonpic SPECIES_SHAYMIN, 10, 3 
playmoncry SPECIES_SHAYMIN, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_104, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_104:
.string "NÚMERO 10: SHAYMIN\p"
	.string "PS: 100\n"
	.string "ATAQUE: 100\l"
	.string "DEFENSA: 100\l"
	.string "ATAQUE ESPECIAL: 100\l"
	.string "DEFENSA ESPECIAL: 100\l"
	.string "VELOCIDAD: 100\l"
	.string "TOTAL: 600\p"
.string "Se cree que está en total simbiosis con\n"
	.string "la fauna y flora de SINOHH, de ahí su\l"
	.string "característico FOGONAZO. Su FORMA\l"
	.string "CIELO es la más interesante\l"
	.string "competitivamente hablando. Gracias a\l"
	.string "su HABILIDAD DICHA podrá hacer uso de\l"
	.string "TAJO AÉREO con un 60% de opciones de\l"
	.string "retroceso, a la vez que un FOGONAZO de\l"
	.string "120 de potencia, bajando en un 80% de\l"
	.string "los casos en 2 niveles la DEF.ESPECIAL\l"
	.string "rival. Esto, para un POKÉMON con 127\l"
	.string "puntos en VELOCIDAD y 120 en ATAQUE\l"
	.string "ESPECIAL, supone una tremenda ventaja\l"
	.string "ante todos los POKÉMON de menor\l"
	.string "VELOCIDAD, es decir, la inmensa\l"
	.string "mayoría.$"



BaseRocketHoennDocumento_105::
lock        
showmonpic SPECIES_MANAPHY, 10, 3 
playmoncry SPECIES_MANAPHY, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_105, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_105:
.string "NÚMERO 9: MANAPHY\p"
	.string "PS: 100\n"
	.string "ATAQUE: 100\l"
	.string "DEFENSA: 100\l"
	.string "ATAQUE ESPECIAL: 100\l"
	.string "DEFENSA ESPECIAL: 100\l"
	.string "VELOCIDAD: 100\l"
	.string "TOTAL: 600\p"
	.string "Nacido en las profundidades del mar, se\n"
	.string "vio obligado a generar luz de entre la\l"
	.string "oscuridad más absoluta. Gracias a ello,\l"
	.string "su movimiento característico RÁFAGA\l"
	.string "produce el incremento de ATAQUE\l"
	.string "ESPECIAL más radical conocido, motivo\l"
	.string "por el cual es un terrible sweeper a\l"
	.string "pesar de no contar con una gran\l"
	.string "capacidad ofensiva de base.$"



BaseRocketHoennDocumento_106::
lock        
showmonpic SPECIES_HEATRAN, 10, 3 
playmoncry SPECIES_HEATRAN, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_106, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_106:
.string "NÚMERO 8: HEATRAN\p"
	.string "PS: 91\n"
	.string "ATAQUE: 90\l"
	.string "DEFENSA: 106\l"
	.string "ATAQUE ESPECIAL: 130\l"
	.string "DEFENSA ESPECIAL: 106\l"
	.string "VELOCIDAD: 77\l"
	.string "TOTAL: 600\p"
	.string "Estudios apuntan a que puede soportar\n"
	.string "temperaturas de varios millones de\l"
	.string "grados. Combina un potente ATAQUE\l"
	.string "ESPECIAL de 130 puntos con una\l"
	.string "interesante capacidad defensiva, más\l"
	.string "por su extraordinario FUEGO/ACERO que\l"
	.string "por sus notables números defensivos.$"



BaseRocketHoennDocumento_107::
lock        
showmonpic SPECIES_CRESSELIA, 10, 3 
playmoncry SPECIES_CRESSELIA, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_107, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_107:
.string "NÚMERO 7: CRESSELIA\p"
	.string "PS: 120\n"
	.string "ATAQUE: 70\l"
	.string "DEFENSA: 120\l"
	.string "ATAQUE ESPECIAL: 75\l"
	.string "DEFENSA ESPECIAL: 130\l"
	.string "VELOCIDAD: 85\l"
	.string "TOTAL: 600\p"
	.string "El POKÉMON LUNAR. Uno de los mayores\n"
	.string "tanques en cuanto números puros que\l"
	.string "existen. Rivaliza con el propio LUGIA\l"
	.string "en este apartado, aunque, como\l"
	.string "consecuencia, su capacidad de hacer\l"
	.string "daño directo se ve muy mermada. El\l"
	.string "precio a pagar por sostener numeros\l"
	.string "notables para un LEGENDARIO mayor en\l"
	.string "PS, DEFENSA y DEFENSA ESPECIAL.$"



BaseRocketHoennDocumento_108::
lock        
showmonpic SPECIES_DARKRAI, 10, 3 
playmoncry SPECIES_DARKRAI, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_108, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_108:
.string "NÚMERO 6: DARKRAI\p"
	.string "PS: 90\n"
	.string "ATAQUE: 70\l"
	.string "DEFENSA: 90\l"
	.string "ATAQUE ESPECIAL: 135\l"
	.string "DEFENSA ESPECIAL: 90\l"
	.string "VELOCIDAD: 125\l"
	.string "TOTAL: 600\p"
	.string "Guardián de las sombras, su misteriosa\n"
	.string "naturaleza inspira terror en sus\l"
	.string "enemigos. Una VELOCIDAD de 125 puntos,\l"
	.string "unida a su ATAQUE ESPECIAL de 135,\l"
	.string "gran variedad de movimientos\l"
	.string "especiales y su característica BRECHA\l"
	.string "NEGRA, justifican el temor que infunde.\l"
	.string "Para todo lo dicho, un triple 90 en PS,\l"
	.string "DEFENSA y DEFENSA ESPECIAL son\l"
	.string "números más que notables para un\l"
	.string "LEGENDARIO de 600 STATS BASE.$"



BaseRocketHoennDocumento_109::
lock        
showmonpic SPECIES_REGIGIGAS, 10, 3 
playmoncry SPECIES_REGIGIGAS, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_109, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_109:
.string "NÚMERO 5: REGIGIGAS\p"
	.string "PS: 110\n"
	.string "ATAQUE: 160\l"
	.string "DEFENSA: 110\l"
	.string "ATAQUE ESPECIAL: 80\l"
	.string "DEFENSA ESPECIAL: 110\l"
	.string "VELOCIDAD: 100\l"
	.string "TOTAL: 670\p"
	.string "Algunos afirman que su verdadera forma,\n"
	.string "aquella que arrastraba continentes\l"
	.string "con cuerdas, se encuentra aún dormida.\l"
	.string "Estimaciones apuntan a que en todo su\l"
	.string "esplendor su ATAQUE FÍSICO rebasaría\l"
	.string "los 200 puntos de STATS BASE. En su\l"
	.string "forma actual, su HABILIDAD lo arrastra\l"
	.string "hacia la mediocridad, desperdiciando un\l"
	.string "potencial natural único.$"



BaseRocketHoennDocumento_110::
lock        
showmonpic SPECIES_PALKIA, 10, 3 
playmoncry SPECIES_PALKIA, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_110, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_110:
.string "NÚMERO 4: PALKIA\p"
	.string "PS: 90\n"
	.string "ATAQUE: 120\l"
	.string "DEFENSA: 100\l"
	.string "ATAQUE ESPECIAL: 150\l"
	.string "DEFENSA ESPECIAL: 120\l"
	.string "VELOCIDAD: 100\l"
	.string "TOTAL: 680\p"
	.string "Una de las 3 deidades de SINOHH. Señor\n"
	.string "del espacio, puede controlarlo a su\l"
	.string "merced e incluso destruirlo gracias a\l"
	.string "su CORTE VACÍO. Al igual que su gran\l"
	.string "rival, DIALGA, el número dorado de 150\l"
	.string "puntos se halla en su ATAQUE ESPECIAL.\l"
	.string "Su TIPO AGUA y VELOCIDAD de 100\l"
	.string "puntos le permiten atacar rápido, duro\l"
	.string "y variado.$"



BaseRocketHoennDocumento_111::
lock        
showmonpic SPECIES_DIALGA, 10, 3 
playmoncry SPECIES_DIALGA, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_111, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_111:
.string "NÚMERO 3: DIALGA\p"
	.string "PS: 100\n"
	.string "ATAQUE: 120\l"
	.string "DEFENSA: 120\l"
	.string "ATAQUE ESPECIAL: 150\l"
	.string "DEFENSA ESPECIAL: 100\l"
	.string "VELOCIDAD: 90\l"
	.string "TOTAL: 680\p"
	.string "Una de las 3 deidades de SINOHH. Señor\n"
	.string "del tiempo, puede alterarlo a su antojo\l"
	.string "gracias a su DISTORSIÓN, el movimiento\l"
	.string "TIPO DRAGÓN más poderoso conocido. Al\l"
	.string "igual que su gran rival, PALKIA, el\l"
	.string "número dorado de 150 puntos se halla\l"
	.string "en su ATAQUE ESPECIAL. Su TIPO ACERO y\l"
	.string "buenos atributos defensivos le hacen\l"
	.string "un sólido oponente que es capaz de\l"
	.string "pegar durísimo.$"



BaseRocketHoennDocumento_112::
lock        
showmonpic SPECIES_GIRATINA, 10, 3 
playmoncry SPECIES_GIRATINA, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_112, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_112:
.string "NÚMERO 2: GIRATINA\p"
	.string "PS: 150\n"
	.string "ATAQUE: 100\l"
	.string "DEFENSA: 120\l"
	.string "ATAQUE ESPECIAL: 100\l"
	.string "DEFENSA ESPECIAL: 120\l"
	.string "VELOCIDAD: 90\l"
	.string "TOTAL: 680\p"
	.string "Una de las 3 deidades de SINOHH. Señor\n"
	.string "del MUNDO DISTORSIÓN, cambia su\l"
	.string "fisionomía hacia una más ofensiva al\l"
	.string "pisar nuestro mundo. El número dorado\l"
	.string "de 150 puntos va para su SALUD, lo que,\l"
	.string "junto con 120 STATS BASE en ambas\l"
	.string "defensas, hacen de este POKÉMON uno\l"
	.string "de los 3 mayores muros en cuanto STATS\l"
	.string "BASE se refiere. Su GOLPE UMBRÍO es el\l"
	.string "movimiento más inescapable que existe.$"



BaseRocketHoennDocumento_113::
lock        
showmonpic SPECIES_ARCEUS, 10, 3 
playmoncry SPECIES_ARCEUS, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_113, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_113:
.string "NÚMERO 1: ARCEUS\p"
	.string "PS: 120\n"
	.string "ATAQUE: 120\l"
	.string "DEFENSA: 120\l"
	.string "ATAQUE ESPECIAL: 120\l"
	.string "DEFENSA ESPECIAL: 120\l"
	.string "VELOCIDAD: 120\l"
	.string "TOTAL: 720\p"
	.string "El DIOS POKÉMON, sobre el papel, de\n"
	.string "nuestro universo. En su forma actual\l"
	.string "mantiene una constante de 120 puntos\l"
	.string "en sus 6 STATS. Ahora sabemos, gracias\l"
	.string "al ADMIN.JEFE {PLAYER}, que en su FORMA\l"
	.string "PRIMIGENIA logra el número dorado de\l"
	.string "150 de BASE en cada uno de sus 6 STATS,\l"
	.string "de ahí que esta cifra se considere la\l"
	.string "constante de los dioses.$"



BaseRocketHoennDocumento_114::
lock        
showmonpic SPECIES_VOLCARONA, 10, 3 
playmoncry SPECIES_VOLCARONA, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_114, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_114:
.string "NÚMERO 17: VOLCARONA\p"
	.string "PS: 85\n"
	.string "ATAQUE: 60\l"
	.string "DEFENSA: 65\l"
	.string "ATAQUE ESPECIAL: 135\l"
	.string "DEFENSA ESPECIAL: 105\l"
	.string "VELOCIDAD: 100\l"
	.string "TOTAL: 550\p"
	.string "La gran polilla de TESELIA. Lanza sus\n"
	.string "movimientos TIPO FUEGO con tanta\l"
	.string "fuerza y vigor que parecen provenir del\l"
	.string "sol. Era adorado en culturas antiguas,\l"
	.string "muchas leyendas giran en torno a su\l"
	.string "historia, algunos creen que no era más\l"
	.string "que un POKÉMON mortal, que llegó a\l"
	.string "entrar en territorio divino gracias a\l"
	.string "su voluntad.$"



BaseRocketHoennDocumento_115::
lock        
showmonpic SPECIES_DARMANITAN_ZEN_MODE, 10, 3 
playmoncry SPECIES_DARMANITAN_ZEN_MODE, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_115, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_115:
.string "NÚMERO 16: DARMANITAN-ZEN:\p"
	.string "PS: 105\n"
	.string "ATAQUE: 30\l"
	.string "DEFENSA: 105\l"
	.string "ATAQUE ESPECIAL: 160\l"
	.string "DEFENSA ESPECIAL: 105\l"
	.string "VELOCIDAD: 55\l"
	.string "TOTAL: 560\p"
	.string "Solo se conocen decenas de\n"
	.string "ejemplares en todo el mundo, se\l"
	.string "cree que provenientes de un\l"
	.string "DARMANITAN que fue capaz de\l"
	.string "alcanzar el estado de iluminación,\l"
	.string "canalizando con ello todo su vigor\l"
	.string "físico hacia su mente, tal fue la\l"
	.string "sabiduría acumulada en el proceso\l"
	.string "que su ATAQUE FÍSICO quedó\l"
	.string "completamente inutilizado, ganando\l"
	.string "en el proceso un ATAQUE ESPECIAL\l"
	.string "aún mayor que su otrora FÍSICO\l"
	.string "como DARMANITAN NORMAL, unos 160\l"
	.string "de BASE que siquiera MEWTWO pudo\l"
	.string "igualar.$"



BaseRocketHoennDocumento_116::
lock        
showmonpic SPECIES_ARCHEOPS, 10, 3 
playmoncry SPECIES_ARCHEOPS, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_116, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_116:
.string "NÚMERO 15: ARCHEOPS:\p"
	.string "PS: 75\n"
	.string "ATAQUE: 140\l"
	.string "DEFENSA: 65\l"
	.string "ATAQUE ESPECIAL: 112\l"
	.string "DEFENSA ESPECIAL: 65\l"
	.string "VELOCIDAD: 110\l"
	.string "TOTAL: 567\p"
	.string "A pesar de sus extraordinarias\n"
	.string "capacidades ofensivas, impresionando\l"
	.string "a los científicos de KANTO - los cuales\l"
	.string "lo consideraban un AERODACTYL\l"
	.string "mejorado - , echa por tierra su letal\l"
	.string "140/110 en ATAQUE/VELOCIDAD, debido a\l"
	.string "su HABILIDAD FLAQUEZA. A pesar de ello,\l"
	.string "investigaciones recientes apuntan a\l"
	.string "que su FORMA PRIMIGENIA, en estado\l"
	.string "salvaje, carecía de una HABILIDAD\l"
	.string "limitante.$"



BaseRocketHoennDocumento_117::
lock        
showmonpic SPECIES_VIRIZION, 10, 3 
playmoncry SPECIES_VIRIZION, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_117, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_117:
.string "NÚMERO 14: VIRIZION:\p"
	.string "PS: 91\n"
	.string "ATAQUE: 90\l"
	.string "DEFENSA: 72\l"
	.string "ATAQUE ESPECIAL: 90\l"
	.string "DEFENSA ESPECIAL: 129\l"
	.string "VELOCIDAD: 108\l"
	.string "TOTAL: 580\p"
	.string "Gran muralla especial, el más vulnerable\n"
	.string "de los ESPADACHINES MÍSTICOS en\l"
	.string "cuanto resistencias y debilidades. Aún\l"
	.string "así, aprovecha muy bien el LIZASTAL Z,\l"
	.string "para, en el que es su set estrella,\l"
	.string "golpear con un A BOCAJARRO de 190 de\l"
	.string "potencia, con opciones de boostearse\l"
	.string "con DANZA ESPADA, golpear por STAB con\l"
	.string "HOJA AGUDA, y con ROCA AFILADA como\l"
	.string "excelente cobertura.$"



BaseRocketHoennDocumento_118::
lock        
showmonpic SPECIES_COBALION, 10, 3 
playmoncry SPECIES_COBALION, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_118, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_118:
.string "NÚMERO 13: COBALION:\p"
	.string "PS: 91\n"
	.string "ATAQUE: 90\l"
	.string "DEFENSA: 129\l"
	.string "ATAQUE ESPECIAL: 72\l"
	.string "DEFENSA ESPECIAL: 90\l"
	.string "VELOCIDAD: 108\l"
	.string "TOTAL: 580\p"
	.string "Gran muralla física, su combinación\n"
	.string "ACERO/LUCHA le otorga 8 resistencias y\l"
	.string "1 inmunidad al VENENO. A pesar de su\l"
	.string "insuficiente ATAQUE de 90 puntos,\l"
	.string "puede hacer mucho daño gracias a su\l"
	.string "facilidad para boostearse con DANZA\l"
	.string "ESPADA, y, junto a 108 puntos en\l"
	.string "VELOCIDAD, tumbar a muchos de un golpe\l"
	.string "con A BOCAJARRO y CABEZAHIERRO por\l"
	.string "STAB.$"



BaseRocketHoennDocumento_119::
lock        
showmonpic SPECIES_TERRAKION, 10, 3 
playmoncry SPECIES_TERRAKION, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_119, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_119:
.string "NÚMERO 12: TERRAKION:\p"
	.string "PS: 91\n"
	.string "ATAQUE: 129\l"
	.string "DEFENSA: 90\l"
	.string "ATAQUE ESPECIAL: 72\l"
	.string "DEFENSA ESPECIAL: 90\l"
	.string "VELOCIDAD: 108\l"
	.string "TOTAL: 580\p"
	.string "Algo infravalorado para el excelente\n"
	.string "reparto de STATS con el que cuenta,\l"
	.string "con solo 72 puntos en ATAQUE ESPECIAL,\l"
	.string "para un total de 580, lo convierten\l"
	.string "casi en el LEGENDARIO MENOR de reparto\l"
	.string "más eficiente en sus STATS. Como\l"
	.string "consecuencia, una extraordinaria\l"
	.string "combinación de 129/108 en\l"
	.string "ATAQUE/VELOCIDAD, con movimientos\l"
	.string "como AVALANCHA, ROCA AFILADA o A\l"
	.string "BOCAJARRO por STAB, y notables\l"
	.string "defensas. GIOVANNI lamentó que no\l"
	.string "fuera TIPO TIERRA en lugar de ROCA,\l"
	.string "ciertamente un TERREMOTO por STAB en\l"
	.string "este POKÉMON hubiera sido demasiado.$"



BaseRocketHoennDocumento_120::
lock        
showmonpic SPECIES_KELDEO, 10, 3 
playmoncry SPECIES_KELDEO, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_120, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_120:
.string "NÚMERO 11: KELDEO:\p"
	.string "PS: 91\n"
	.string "ATAQUE: 72\l"
	.string "DEFENSA: 90\l"
	.string "ATAQUE ESPECIAL: 129\l"
	.string "DEFENSA ESPECIAL: 90\l"
	.string "VELOCIDAD: 108\l"
	.string "TOTAL: 580\p"
	.string "El cuarto de los ESPADACHINES\n"
	.string "MÍSTICOS, junto con TERRAKION el de\l"
	.string "mejor reparto de STATS, y para algunos\l"
	.string "el mejor competitivamente. Su\l"
	.string "combinación AGUA/LUCHA le otorga muy\l"
	.string "buenas coberturas por STAB, con un\l"
	.string "excelente 129/108 en\l"
	.string "AT.ESPECIAL/VELOCIDAD, objetos como\l"
	.string "la VIDASFERA o GAFAS ELEGIDAS\l"
	.string "desbordarán muchos equipos. PAZ\l"
	.string "MENTAL puede sorprender mucho, debido\l"
	.string "a la ofensiva inminente que puede\l"
	.string "esperarse de este POKÉMON.$"



BaseRocketHoennDocumento_121::
lock        
showmonpic SPECIES_TORNADUS, 10, 3 
playmoncry SPECIES_TORNADUS, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_121, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_121:
.string "NÚMERO 10: TORNADUS:\p"
	.string "PS: 79\n"
	.string "ATAQUE: 115\l"
	.string "DEFENSA: 70\l"
	.string "ATAQUE ESPECIAL: 125\l"
	.string "DEFENSA ESPECIAL: 80\l"
	.string "VELOCIDAD: 111\l"
	.string "TOTAL: 580\p"
	.string "Forma parte del TRÍO DE LAS NUBES de\n"
	.string "TESELIA. Comparte ratio ATAQUE\l"
	.string "ESPECIAL/VELOCIDAD (125/111) con\l"
	.string "THUNDURUS, permitiéndole golpear muy\l"
	.string "duro con su VENDAVAL por STAB. Su\l"
	.string "forma TÓTEM es aún más rápida (121) y\l"
	.string "defensiva, a costa de perder pegada\l"
	.string "(100-110 en ATAQUE/ATAQUE ESPECIAL\l"
	.string "frente a 115-125).$"



BaseRocketHoennDocumento_122::
lock        
showmonpic SPECIES_THUNDURUS, 10, 3 
playmoncry SPECIES_THUNDURUS, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_122, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_122:
.string "NÚMERO 9: THUNDURUS:\p"
	.string "PS: 79\n"
	.string "ATAQUE: 115\l"
	.string "DEFENSA: 70\l"
	.string "ATAQUE ESPECIAL: 125\l"
	.string "DEFENSA ESPECIAL: 80\l"
	.string "VELOCIDAD: 111\l"
	.string "TOTAL: 580\p"
	.string "Forma parte del TRÍO DE LAS NUBES de\n"
	.string "TESELIA. Su HABILIDAD BROMISTA, junto\l"
	.string "con un excelente ratio entre ATAQUE\l"
	.string "ESPECIAL/VELOCIDAD (125/111), le\l"
	.string "convierten en un POKÉMON muy peligroso\l"
	.string "e impredecible. Su forma TÓTEM gana aún\l"
	.string "más poder en ATAQUE ESPECIAL (145), a\l"
	.string "costa de la VELOCIDAD (101), siendo\l"
	.string "también inmune a ataques del TIPO\l"
	.string "ELÉCTRICO.$"



BaseRocketHoennDocumento_123::
lock        
showmonpic SPECIES_HYDREIGON, 10, 3 
playmoncry SPECIES_HYDREIGON, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_123, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_123:
.string "NÚMERO 8: HYDREIGON:\p"
	.string "PS: 92\n"
	.string "ATAQUE: 105\l"
	.string "DEFENSA: 90\l"
	.string "ATAQUE ESPECIAL: 125\l"
	.string "DEFENSA ESPECIAL: 90\l"
	.string "VELOCIDAD: 98\l"
	.string "TOTAL: 600\p"
	.string "El único PSEUDOLEGENDARIO que base su\n"
	.string "ofensiva en el ATAQUE ESPECIAL,\l"
	.string "contando con un arsenal más que\l"
	.string "temible de esta clase de movimientos.\l"
	.string "Se caracteriza por no dar respiro a sus\l"
	.string "oponentes, haciendo uso de su gran\l"
	.string "variedad y notable potencia por lados\l"
	.string "FÍSICO/ESPECIAL, siendo la VIDASFERA\l"
	.string "su mejor aliada. Para muchos, perdió el\l"
	.string "pulso con GARCHOMP por el título de\l"
	.string "mejor PSEUDOLENDARIO en el momento en\l"
	.string "que no pudo pasar de 100 de BASE en\l"
	.string "VELOCIDAD.$"



BaseRocketHoennDocumento_124::
lock        
showmonpic SPECIES_MELOETTA, 10, 3 
playmoncry SPECIES_MELOETTA, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_124, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_124:
.string "NÚMERO 7: MELOETTA:\p"
	.string "PS: 100\n"
	.string "ATAQUE: 77\l"
	.string "DEFENSA: 77\l"
	.string "ATAQUE ESPECIAL: 128\l"
	.string "DEFENSA ESPECIAL: 128\l"
	.string "VELOCIDAD: 90\l"
	.string "TOTAL: 600\p"
	.string "Peculiar POKÉMON, con el estatus de un\n"
	.string "LEGENDARIO, capaz de invertir sus\l"
	.string "valores (128) de ATAQUE\l"
	.string "ESPECIAL/DEFENSA ESPECIAL con los de\l"
	.string "ATAQUE/VELOCIDAD, además de su TIPO\l"
	.string "PSÍQUICO con el LUCHA, todo ello en\l"
	.string "plena batalla gracias a su\l"
	.string "característico CANTO ARCAICO. Su\l"
	.string "reparto de stats es uno de los más\l"
	.string "eficientes en POKÉMON no intervenidos,\l"
	.string "con solo 77 en ATAQUE FÍSICO para un\l"
	.string "total de 600.$"



BaseRocketHoennDocumento_125::
lock        
showmonpic SPECIES_VICTINI, 10, 3 
playmoncry SPECIES_VICTINI, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_125, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_125:
.string "NÚMERO 6: VICTINI:\p"
	.string "PS: 100\n"
	.string "ATAQUE: 125\l"
	.string "DEFENSA: 100\l"
	.string "ATAQUE ESPECIAL: 50\l"
	.string "DEFENSA ESPECIAL: 100\l"
	.string "VELOCIDAD: 125\l"
	.string "TOTAL: 600\p"
	.string "El POKÉMON VICTORIA, dueño de uno de\n"
	.string "los MOVEPOOL más privilegiados, puesto\l"
	.string "que tiene acceso tanto al FUEGO AZUL\l"
	.string "como al ATAQUE FULGOR de las leyendas\l"
	.string "de TESELIA. Además, su característica\l"
	.string "V DE FUEGO, con unos locos 180 de\l"
	.string "potencia, semejante ataque es una\l"
	.string "rareza entre POKÉMON de esta\l"
	.string "jerarquía, más aún teniendo en cuenta\l"
	.string "la escasa sanción de bajar únicamente\l"
	.string "VELOCIDAD y defensas. Gracias a su\l"
	.string "HABILIDAD, TINOVICTORIA, V DE FUEGO\l"
	.string "acertará siempre, mientras que ATAQUE\l"
	.string "FULGOR Y FUEGO AZUL tendrán un 93,5%\l"
	.string "de precisión.$"



BaseRocketHoennDocumento_126::
lock        
showmonpic SPECIES_GENESECT, 10, 3 
playmoncry SPECIES_GENESECT, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_126, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_126:
.string "NÚMERO 5: GENESECT:\p"
    .string "PS: 71\n"
	.string "ATAQUE: 120\l"
	.string "DEFENSA: 95\l"
	.string "ATAQUE ESPECIAL: 120\l"
	.string "DEFENSA ESPECIAL: 95\l"
	.string "VELOCIDAD: 99\l"
	.string "TOTAL: 600\p"
	.string "POKÉMON modificado a partir del\n"
	.string "depredador del tipo BICHO más\l"
	.string "letal de TESELIA hace 300 millones\l"
	.string "de años, del cual desconocemos sus\l"
	.string "STATS BASE, pero lo estimamos en\l"
	.string "520-540, con un ATAQUE ESPECIAL\l"
	.string "realmente bajo de entre 40 y 60\l"
	.string "puntos, consistiendo su principal\l"
	.string "mejora entre el GENESECT original\l"
	.string "y el modificado en ese incremento\l"
	.string "de 60-80 en ATAQUE ESPECIAL que lo\l"
	.string "colocaría en 600 de BASE.\l"
	.string "Queda por estudiar un posible\l"
	.string "parentesco con KABUTOPS.$"



BaseRocketHoennDocumento_127::
lock        
showmonpic SPECIES_LANDORUS, 10, 3 
playmoncry SPECIES_LANDORUS, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_127, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_127:
.string "NÚMERO 4: LANDORUS:\p"
    .string "PS: 89\n"
	.string "ATAQUE: 125\l"
	.string "DEFENSA: 90\l"
	.string "ATAQUE ESPECIAL: 115\l"
	.string "DEFENSA ESPECIAL: 80\l"
	.string "VELOCIDAD: 101\l"
	.string "TOTAL: 600\p"
	.string "El genio y dios de las cosechas de\n"
	.string "TESELIA, tanto su FORMA NORMAL como\l"
	.string "TÓTEM tienen grandes aplicaciones\l"
	.string "competitivas.$"



BaseRocketHoennDocumento_128::
lock        
showmonpic SPECIES_KYUREM, 10, 3 
playmoncry SPECIES_KYUREM, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_128, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_128:
.string "NÚMERO 3: KYUREM:\p"
    .string "PS: 125\n"
	.string "ATAQUE: 130\l"
	.string "DEFENSA: 90\l"
	.string "ATAQUE ESPECIAL: 130\l"
	.string "DEFENSA ESPECIAL: 90\l"
	.string "VELOCIDAD: 95\l"
	.string "TOTAL: 660\p"
	.string "El POKÉMON CERO, la cáscara vacía que\n"
	.string "quedó después de la división del\l"
	.string "DRAGÓN ORIGINAL en RESHIRAM y ZEKROM.\l"
	.string "Que supere los 120 puntos, el techo\l"
	.string "impuesto por ARCEUS, en 3 de los 6\l"
	.string "stats, siendo en salud y ambos\l"
	.string "ataques, es prueba de que estamos\l"
	.string "ante un POKÉMON muy poco\l"
	.string "convencional. Su mejorable VELOCIDAD y\l"
	.string "un TIPO HIELO con grandes debilidades\l"
	.string "le privan, a pesar de contar con\l"
	.string "números de LEGENDARIO MAYOR, de ser\l"
	.string "mucho más peligroso.$"



BaseRocketHoennDocumento_129::
lock        
showmonpic SPECIES_ZEKROM, 10, 3 
playmoncry SPECIES_ZEKROM, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_129, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_129:
.string "NÚMERO 2: ZEKROM:\p"
    .string "PS: 100\n"
	.string "ATAQUE: 150\l"
	.string "DEFENSA: 120\l"
	.string "ATAQUE ESPECIAL: 120\l"
	.string "DEFENSA ESPECIAL: 100\l"
	.string "VELOCIDAD: 90\l"
	.string "TOTAL: 680\p"
	.string "El POKÉMON YING, la parte pura que se\n"
	.string "separó del DRAGÓN ORIGINAL. La\l"
	.string "violencia con la que suelta descargas\l"
	.string "es única, ATAQUE FULGOR fue escogido\l"
	.string "por unanimidad como el mejor\l"
	.string "movimiento TIPO ELÉCTRICO que existe,\l"
	.string "con 10 puntos más de potencia que\l"
	.string "PLACAJE ELÉCTRICO, 85% de precisión, y\l"
	.string "no solo no es sancionado con daño de\l"
	.string "retroceso, sino que incluso paralizará\l"
	.string "al rival en un 30% de los casos.$"



BaseRocketHoennDocumento_130::
lock        
showmonpic SPECIES_RESHIRAM, 10, 3
playmoncry SPECIES_RESHIRAM, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_130, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_130:
.string "NÚMERO 1: RESHIRAM:\p"
    .string "PS: 100\n"
	.string "ATAQUE: 120\l"
	.string "DEFENSA: 100\l"
	.string "ATAQUE ESPECIAL: 150\l"
	.string "DEFENSA ESPECIAL: 120\l"
	.string "VELOCIDAD: 90\l"
	.string "TOTAL: 680\p"
	.string "El POKÉMON YANG, la parte veraz que se\n"
	.string "separó del DRAGÓN ORIGINAL. La\l"
	.string "intensidad de sus llamas no conocen\l"
	.string "igual, FUEGO AZUL es considerado por\l"
	.string "nuestros científicos uno de los 3\l"
	.string "mejores movimientos TIPO FUEGO que\l"
	.string "existen, siendo un 17% más potente que\l"
	.string "LLAMARADA, de similar precisión, y\l"
	.string "quemando en un 30% de los casos. Si a\l"
	.string "esto le sumamos 150 puntos en ATAQUE\l"
	.string "ESPECIAL, junto con COMETA DRACO hará\l"
	.string "un daño insano a cualquier POKÉMON.$"



BaseRocketHoennDocumento_131::
lock        
showmonpic SPECIES_FLORGES, 10, 3
playmoncry SPECIES_FLORGES, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_131, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_131:
.string "NÚMERO 8: FLORGES:\p"
    .string "PS: 78\n"
	.string "ATAQUE: 65\l"
	.string "DEFENSA: 68\l"
	.string "ATAQUE ESPECIAL: 112\l"
	.string "DEFENSA ESPECIAL: 154\l"
	.string "VELOCIDAD: 75\l"
	.string "TOTAL: 552\p"
	.string "Uno de los NO LEGENDARIOS ni PSEUDO\n"
	.string "con mejores stats, para un total de 552\l"
	.string "STATS BASE, logra empatar los 154\l"
	.string "puntos en DEFENSA ESPECIAL de LUGIA y\l"
	.string "HO-OH, además de 112 en ATAQUE\l"
	.string "ESPECIAL. Reforzando así su faceta\l"
	.string "como POKÉMON HADA por excelencia, ya\l"
	.string "que destacan por su gran DEFENSA\l"
	.string "ESPECIAL. Una habilidad a la altura de\l"
	.string "sus números de poder le hubieran dado\l"
	.string "un enorme salto de calidad.$"



BaseRocketHoennDocumento_132::
lock        
showmonpic SPECIES_GOODRA, 10, 3
playmoncry SPECIES_GOODRA, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_132, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_132:
.string "NÚMERO 7: GOODRA:\p"
    .string "PS: 90\n"
	.string "ATAQUE: 100\l"
	.string "DEFENSA: 70\l"
	.string "ATAQUE ESPECIAL: 110\l"
	.string "DEFENSA ESPECIAL: 150\l"
	.string "VELOCIDAD: 80\l"
	.string "TOTAL: 600\p"
	.string "Tal vez el PSEUDOLEGENDARIO con menos\n"
	.string "utilidad competitiva, aunque de\l"
	.string "cualidades interesantes. Sus 150 en\l"
	.string "DEFENSA ESPECIAL son el STAT más\l"
	.string "elevado alcanzado por un PSEUDO,\l"
	.string "combinado con 110 en ATAQUE ESPECIAL\l"
	.string "y gran variedad de movimientos, le\l"
	.string "vuelven un POKÉMON top en cuando\l"
	.string "combate cuerpo a cuerpo por el lado\l"
	.string "especial. Su fragilidad por el lado\l"
	.string "físico y mejorable VELOCIDAD lo\l"
	.string "vuelven demasiado vulnerable.$"



BaseRocketHoennDocumento_133::
lock        
showmonpic SPECIES_DIANCIE, 10, 3
playmoncry SPECIES_DIANCIE, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_133, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_133:
.string "NÚMERO 6: DIANCIE:\p"
    .string "PS: 50\n"
	.string "ATAQUE: 100\l"
	.string "DEFENSA: 150\l"
	.string "ATAQUE ESPECIAL: 100\l"
	.string "DEFENSA ESPECIAL: 150\l"
	.string "VELOCIDAD: 50\l"
	.string "TOTAL: 600\p"
	.string "Al igual que REGISTEEL, fue bendecido\n"
	.string "con el número dorado, 150, en ambas\l"
	.string "defensas, aunque con menos PS y más\l"
	.string "debilidades que el REGI de ACERO. Aún\l"
	.string "así, conserva una interesante\l"
	.string "capacidad ofensiva, con su\l"
	.string "característico TORMENTA DE\l"
	.string "DIAMANTES, y acceso a\l"
	.string "CARANTOÑA/FUERZA LUNAR, también por\l"
	.string "STAB. Su baja VELOCIDAD (50) le\l"
	.string "convierte en un buen usuario de\l"
	.string "ESPACIO RARO, movimiento al cual tiene\l"
	.string "acceso.$"



BaseRocketHoennDocumento_134::
lock        
showmonpic SPECIES_HOOPA, 10, 3
playmoncry SPECIES_HOOPA, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_134, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_134:
.string "NÚMERO 5: HOOPA:\p"
    .string "PS: 80\n"
	.string "ATAQUE: 110\l"
	.string "DEFENSA: 60\l"
	.string "ATAQUE ESPECIAL: 150\l"
	.string "DEFENSA ESPECIAL: 130\l"
	.string "VELOCIDAD: 70\l"
	.string "TOTAL: 600\p"
	.string "Crea portales dimensionales, pudiendo\n"
	.string "viajar a través de ellos. Destaca por\l"
	.string "su AT.ESPECIAL anormalmente alto (150)\l"
	.string "para su apariencia, también por su\l"
	.string "DEF.ESPECIAL (130). Una baja VELOCIDAD\l"
	.string "y debilidad x4 a FANTASMA y SINIESTRO\l"
	.string "le lastran demasiado.$"



BaseRocketHoennDocumento_135::
lock        
showmonpic SPECIES_VOLCANION, 10, 3
playmoncry SPECIES_VOLCANION, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_135, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_135:
.string "NÚMERO 4: VOLCANION:\p"
    .string "PS: 80\n"
	.string "ATAQUE: 110\l"
	.string "DEFENSA: 120\l"
	.string "ATAQUE ESPECIAL: 130\l"
	.string "DEFENSA ESPECIAL: 90\l"
	.string "VELOCIDAD: 70\l"
	.string "TOTAL: 600\p"
    .string "De un más que interesante FUEGO/AGUA,\n"
	.string "siendo inmune a este último gracias a\l"
	.string "ABSORBER AGUA, y resistiendo x4 al\l"
	.string "propio fuego, un inútil ATAQUE de 110 y\l"
	.string "una muy mejorable VELOCIDAD de 70 son\l"
	.string "su mayor lastre, a pesar de sus buenos\l"
	.string "STATS. Su CHORRO DE VAPOR es uno de los\l"
	.string "mejores movimientos TIPO AGUA, de 110\l"
	.string "de potencia y 95% de precisión, quemará\l"
	.string "al rival en un 30% de los casos, ideal\l"
	.string "para, apoyado en 130 puntos de\l"
	.string "AT.ESPECIAL, abrir huecos en el equipo\l"
	.string "rival.$"



BaseRocketHoennDocumento_136::
lock        
showmonpic SPECIES_XERNEAS, 10, 3
playmoncry SPECIES_XERNEAS, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_136, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_136:
.string "NÚMERO 3: XERNEAS:\p"
    .string "PS: 126\n"
	.string "ATAQUE: 131\l"
	.string "DEFENSA: 95\l"
	.string "ATAQUE ESPECIAL: 131\l"
	.string "DEFENSA ESPECIAL: 98\l"
	.string "VELOCIDAD: 99\l"
	.string "TOTAL: 680\p"
	.string "El POKÉMON X, dueño de uno de los\n"
	.string "mejores movimientos de boosteo que\l"
	.string "existen: GEOCONTROL, pudiéndose\l"
	.string "activar en un solo turno con HIERBA\l"
	.string "ÚNICA, elevará en 2 niveles su\l"
	.string "AT.ESPECIAL, DEF.ESP y VELOCIDAD. Con\l"
	.string "un FUERZA LUNAR incrementado en un\l"
	.string "33% su potencia, y coberturas como\l"
	.string "RAYO, ONDA CERTERA, PSÍQUICO y HIERBA\l"
	.string "LAZO, estará en disposición de tumbar a\l"
	.string "todo lo que golpee neutral de un solo\l"
	.string "golpe.$"



BaseRocketHoennDocumento_137::
lock        
showmonpic SPECIES_YVELTAL, 10, 3
playmoncry SPECIES_YVELTAL, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_137, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_137:
.string "NÚMERO 2: YVELTAL:\p"
    .string "PS: 126\n"
	.string "ATAQUE: 131\l"
	.string "DEFENSA: 95\l"
	.string "ATAQUE ESPECIAL: 131\l"
	.string "DEFENSA ESPECIAL: 98\l"
	.string "VELOCIDAD: 99\l"
	.string "TOTAL: 680\p"
	.string "El POKÉMON Y, su PULSO UMBRÍO\n"
	.string "incrementado en un 33% (por AURA\l"
	.string "OSCURA) es una pesadilla. Pero su ALA\l"
	.string "MORTÍFERA es aún más interesante,\l"
	.string "recuperando el 75% del daño infligido,\l"
	.string "para un movimiento de STAB, 80 de\l"
	.string "potencia y bajo un AT.ESPECIAL de 131,\l"
	.string "supone para muchos el equilibrio\l"
	.string "perfecto entre ATAQUE/DEFENSA, pues\l"
	.string "con VIDASFERA o GAFAS ELEGIDAS\l"
	.string "restara y recuperará cantidades\l"
	.string "ingentes de vida, dando la sensación de\l"
	.string "ser invencible ante todo lo que golpee\l"
	.string "neutral. El CHALECO ASALTO igualmente\l"
	.string "explota mucho este movimiento.$"



BaseRocketHoennDocumento_138::
lock        
showmonpic SPECIES_ZYGARDE_COMPLETE, 10, 3
playmoncry SPECIES_ZYGARDE, CRY_MODE_ENCOUNTER
msgbox BaseRocketHoennDocumento_Text_138, MSGBOX_DEFAULT
hidemonpic
release     
end

BaseRocketHoennDocumento_Text_138:
.string "NÚMERO 1: ZYGARDE PERFECTO:\p"
    .string "PS: 216\n"
	.string "ATAQUE: 100\l"
	.string "DEFENSA: 121\l"
	.string "ATAQUE ESPECIAL: 91\l"
	.string "DEFENSA ESPECIAL: 98\l"
	.string "VELOCIDAD: 95\l"
	.string "TOTAL: 708\p"
	.string "Tal vez el mayor muro físico que existe,\n"
	.string "las posibildiades competitivas de este\l"
	.string "POKÉMON son infinitas. MIL FLECHAS es\l"
	.string "el movimiento más inescapable que\l"
	.string "existe, golpeando a todo y cubriendo la\l"
	.string "mayoría de tipos. Esto le permite\l"
	.string "invertir el resto de movimientos en\l"
	.string "boosteos, stall y recuperación. Sin\l"
	.string "perder pegada, da como resultado uno\l"
	.string "de los POKÉMON más incómodos de\l"
	.string "enfrentar.$"



BaseRocketHoenn_EventScript_ReceiveTynamo::
    lock
    faceplayer
	checkmoncatch SPECIES_TYNAMO
	goto_if_eq VAR_RESULT, FALSE, BaseRocketHoenn_EventScript_TakeTynamo 
	msgbox BaseRocketHoenn_Text_27, MSGBOX_DEFAULT
	release
	end



BaseRocketHoenn_EventScript_TakeTynamo::
    msgbox BaseRocketHoenn_Text_TakeTynamo MSGBOX_DEFAULT
    playfanfare MUS_OBTAIN_TMHM
	msgbox BaseRocketHoenn_Text_MensajeTynamo, MSGBOX_DEFAULT
	givemon SPECIES_TYNAMO, 25, ITEM_CELL_BATTERY
	waitfanfare  
	release
	end 



BaseRocketHoenn_Text_TakeTynamo:
   .string "¿Me creerías si te dijera que existe un\n"
	.string "POKÉMON sin debilidades? ¿No? ¡Toma!$"



BaseRocketHoenn_Text_MensajeTynamo:
.string "¡OBTUVISTE UN TYNAMO AL NV.25!$"


BaseRocketHoenn_Text_27:
    .string "La línea evolutiva de TYNAMO es del\n"
	.string "TIPO ELÉCTRICO puro, y solapa su única\l"
	.string "debilidad al TIERRA gracias a\l"
	.string "LEVITACIÓN. ¿No es increíble?$"

BaseRocketHoenn_Encuentro_Oak_Der::
lock
applymovement 37, BaseRocketHoenn_Encuentro_Oak_Move_2
applymovement OBJ_EVENT_ID_PLAYER, BaseRocketHoenn_Encuentro_Oak_Move_1
waitmovement 0x0
goto BaseRocketHoenn_Encuentro_Oak

BaseRocketHoenn_Encuentro_Oak_Izq::
lock
applymovement 37, BaseRocketHoenn_Encuentro_Oak_Move_2
applymovement OBJ_EVENT_ID_PLAYER, BaseRocketHoenn_Encuentro_Oak_Move_1.1
waitmovement 0x0
goto BaseRocketHoenn_Encuentro_Oak


BaseRocketHoenn_Encuentro_Oak::
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_1 MSGBOX_AUTOCLOSE
clearflag FLAG_RECEIVED_SHOAL_SALT_3
addobject 36
applymovement 37, BaseRocketHoenn_Encuentro_Oak_Move_1
applymovement OBJ_EVENT_ID_PLAYER, BaseRocketHoenn_Encuentro_Oak_Move_1
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_4
waitmovement 0x0
playse SE_PIN
applymovement 37, BaseRocketHoenn_Encuentro_Oak_Move_3
applymovement OBJ_EVENT_ID_PLAYER, BaseRocketHoenn_Encuentro_Oak_Move_3
special SpawnCameraObject
applymovement OBJ_EVENT_ID_CAMERA, BaseRocketHoenn_Encuentro_Oak_10
waitmovement 0x0
special RemoveCameraObject
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_2 MSGBOX_AUTOCLOSE
delay 20
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_3 MSGBOX_AUTOCLOSE
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_4 MSGBOX_AUTOCLOSE
applymovement 37, BaseRocketHoenn_Encuentro_Oak_Move_5
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_5 MSGBOX_AUTOCLOSE
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_6
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_6 MSGBOX_AUTOCLOSE
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_7 MSGBOX_AUTOCLOSE
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_7
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_8 MSGBOX_AUTOCLOSE
delay 15
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_9 MSGBOX_AUTOCLOSE
delay 15
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_8
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_10 MSGBOX_AUTOCLOSE
delay 10
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_11 MSGBOX_AUTOCLOSE
delay 10
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_12 MSGBOX_AUTOCLOSE
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_13 MSGBOX_AUTOCLOSE
special SpawnCameraObject
applymovement 37, BaseRocketHoenn_Encuentro_Oak_Move_7
applymovement OBJ_EVENT_ID_PLAYER, BaseRocketHoenn_Encuentro_Oak_Move_7
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_9
applymovement OBJ_EVENT_ID_CAMERA, BaseRocketHoenn_Encuentro_Oak_11
waitmovement 0x0
special RemoveCameraObject
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_14 MSGBOX_AUTOCLOSE
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_2
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_15 MSGBOX_AUTOCLOSE
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_12
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_16 MSGBOX_AUTOCLOSE
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_17 MSGBOX_AUTOCLOSE
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_2
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_18 MSGBOX_AUTOCLOSE
delay 15
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_19 MSGBOX_AUTOCLOSE
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_12
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_20 MSGBOX_AUTOCLOSE
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_2
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_21 MSGBOX_AUTOCLOSE
applymovement 36, BaseRocketHoenn_Encuentro_Oak_Move_13
waitmovement 0x0
setflag FLAG_RECEIVED_SHOAL_SALT_3
removeobject 36
applymovement 37, BaseRocketHoenn_Encuentro_Oak_Move_2
applymovement OBJ_EVENT_ID_PLAYER, BaseRocketHoenn_Encuentro_Oak_Move_14
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_22 MSGBOX_AUTOCLOSE
applymovement 37, BaseRocketHoenn_Encuentro_Oak_Move_15
waitmovement 0x0
msgbox BaseRocketHoenn_Encuentro_Oak_Texto_23 MSGBOX_AUTOCLOSE
playfanfare MUS_RG_OBTAIN_KEY_ITEM
waitfanfare
setflag FLAG_HIDE_SLATEPORT_CITY_TEAM_AQUA
fadescreen 1
delay 20
removeobject 37
fadescreen 0
setvar VAR_UNUSED_0x40F7, 187
release
end

BaseRocketHoenn_Encuentro_Oak_Move_15:
walk_in_place_up
step_end

BaseRocketHoenn_Encuentro_Oak_Move_14:
face_down
step_end

BaseRocketHoenn_Encuentro_Oak_Move_13:
walk_up
walk_up
walk_up
walk_up
walk_up
walk_up
step_end

BaseRocketHoenn_Encuentro_Oak_Move_12:
face_right
step_end

BaseRocketHoenn_Encuentro_Oak_11:
walk_up
walk_up
walk_up
step_end

BaseRocketHoenn_Encuentro_Oak_10:
walk_down
walk_down
walk_down
step_end

BaseRocketHoenn_Encuentro_Oak_Move_9:
walk_slow_up
face_right
step_end

BaseRocketHoenn_Encuentro_Oak_Move_8:
walk_slow_left
step_end

BaseRocketHoenn_Encuentro_Oak_Move_7:
face_left
step_end

BaseRocketHoenn_Encuentro_Oak_Move_6:
walk_up
step_end

BaseRocketHoenn_Encuentro_Oak_Move_5:
walk_in_place_down
step_end

BaseRocketHoenn_Encuentro_Oak_Move_4:
walk_left
walk_up
walk_up
step_end

BaseRocketHoenn_Encuentro_Oak_Move_3:
emote_exclamation_mark
step_end

BaseRocketHoenn_Encuentro_Oak_Move_2:
face_up
step_end

BaseRocketHoenn_Encuentro_Oak_Move_1.1:
walk_down
walk_right
walk_down
step_end

BaseRocketHoenn_Encuentro_Oak_Move_1:
walk_down
walk_down
step_end

BaseRocketHoenn_Encuentro_Oak_Texto_1:
.string "ANDRA: Ya estás. ¡Sígueme!$"

BaseRocketHoenn_Encuentro_Oak_Texto_2:
.string "OAK: Vaya, vaya. He aquí yo de nuevo,\n"
	.string "frente a la nueva generación, y dos\l"
	.string "jóvenes competentes con ganas de más\l"
	.string "como máximos exponentes de ella.$"

BaseRocketHoenn_Encuentro_Oak_Texto_3:
.string "ANDRA: Tú… ¿Qué haces aquí?$"

BaseRocketHoenn_Encuentro_Oak_Texto_4:
.string "OAK: No deberías dirigirte hacia mí con\n"
	.string "ese desprecio, joven ADMIN. Ahora\l"
	.string "trabajamos juntos, y mi compromiso con\l"
	.string "el futuro es total, ¿lo es el tuyo?$"

BaseRocketHoenn_Encuentro_Oak_Texto_5:
.string "ANDRA: ¡Claro!$"

BaseRocketHoenn_Encuentro_Oak_Texto_6:
.string "OAK: Creí que despreciabas a los\n"
	.string "LEGENDARIOS por el mero hecho de serlo\l"
	.string "de nacimiento. ¿No crees que el\l"
	.string "propósito último de todas estas bases\l"
	.string "y reuniones es precisamente la\l"
	.string "construcción de algo mucho más\l"
	.string "despreciable?$"

BaseRocketHoenn_Encuentro_Oak_Texto_7:
.string "ANDRA: Ni por asomo, ¡serán fruto de\n"
	.string "nuestro esfuerzo y voluntad!$"

BaseRocketHoenn_Encuentro_Oak_Texto_8:
.string "OAK: La tuya. Los POKÉMON surgidos no\n"
	.string "tendrán nada que ver, igual que un\l"
	.string "LEGENDARIO. No, igual no, su privilegio\l"
	.string "de nacimiento será mucho mayor.$"

BaseRocketHoenn_Encuentro_Oak_Texto_9:
.string "ANDRA: …$"

BaseRocketHoenn_Encuentro_Oak_Texto_10:
.string "OAK: Ahh… La voluntad… ¡Qué fácil de\n"
	.string "torcer ante los estímulos y\l"
	.string "contratiempos adecuados!$"

BaseRocketHoenn_Encuentro_Oak_Texto_11:
.string "ANDRA: No nos has respondido, ¿qué\n"
	.string "haces en mi BASE, OAK? No se me ha\l"
	.string "informado de tu presencia aquí.$"

BaseRocketHoenn_Encuentro_Oak_Texto_12:
.string "OAK: Recibí una llamada de GIOVANNI, y\n"
	.string "me informó sobre el posible choque que\l"
	.string "habéis tenido con DEVON, algo que\l"
	.string "parece acabáis de confirmarle. He\l"
	.string "venido a avisaros.$"

BaseRocketHoenn_Encuentro_Oak_Texto_13:
.string "ANDRA: ¿Avisarnos?$"

BaseRocketHoenn_Encuentro_Oak_Texto_14:
.string "OAK: Cuando aquí en KANTO apenas\n"
	.string "habíamos logrado crear la primera\l"
	.string "versión de PORYGON, DEVON ya simuló el\l"
	.string "poder de un PSEUDOLEGENDARIO, creando\l"
	.string "a METAGROSS.$"

BaseRocketHoenn_Encuentro_Oak_Texto_15:
.string "De eso hace ya varios años, quién sabe a\n"
	.string "día de hoy los medios de los que\l"
	.string "disponen.$"

BaseRocketHoenn_Encuentro_Oak_Texto_16:
.string "Por fortuna no saben nada de MEWTWO,\n"
	.string "pero BLAINE y yo colaboramos con ellos\l"
	.string "en el pasado, y están al tanto de todos\l"
	.string "nuestros avances respecto a DEOXYS.$"

BaseRocketHoenn_Encuentro_Oak_Texto_17:
.string "ANDRA: {PLAYER} ya los derrotó, ha\n"
	.string "derrotado a las mayores fuerzas del\l"
	.string "MUNDO POKÉMON; nada de lo que puedan\l"
	.string "crear superará eso.$"

BaseRocketHoenn_Encuentro_Oak_Texto_18:
.string "OAK: Tal vez, pero no es necesario crear\n"
	.string "algo con mayor poder bruto, algo más\l"
	.string "eficiente y optimizado para las leyes\l"
	.string "que rigen nuestros combates podría\l"
	.string "ser suficiente para haceros caer.$"

BaseRocketHoenn_Encuentro_Oak_Texto_19:
.string "ANDRA: ¿Qué quieres decir?$"

BaseRocketHoenn_Encuentro_Oak_Texto_20:
.string "OAK: Que andéis con cuidado, no sabemos\n"
	.string "qué buscan, ni qué poder, ni qué\l"
	.string "intenciones tienen.$"

BaseRocketHoenn_Encuentro_Oak_Texto_21:
.string "Como vosotros, quiero ver a la\n"
	.string "KANTO-JOHTO de los 251 originales\l"
	.string "triunfar. Espero que lo tengáis en\l"
	.string "cuenta y acudamos a la II GRAN REUNIÓN\l"
	.string "de TRIGAL como aliados de verdad.$"

BaseRocketHoenn_Encuentro_Oak_Texto_22:
.string "ANDRA: Este OAK… nos trata como si aún\n"
	.string "fuéramos reclutas recogiendo FÓSILES\l"
	.string "en el MT.MOON. Deberíamos callarle la\l"
	.string "boca de nuevo en un combate.$"

BaseRocketHoenn_Encuentro_Oak_Texto_23:
.string "En fin, te espero en el S2, toma la\n"
	.string "TARJETA MAGNÉTICA que da acceso a él.$"

BaseRocketHoenn_Salida_Base::
compare VAR_UNUSED_0x40F7, 187
goto_if_gt LavenderTown_Barrera_Mision_Kangaskhan_2
applymovement OBJ_EVENT_ID_PLAYER, BaseRocketHoenn_Salida_Base_Move_1
waitmovement 0x0
msgbox BaseRocketHoenn_Salida_Base_Texto_1 MSGBOX_AUTOCLOSE
applymovement OBJ_EVENT_ID_PLAYER, BaseRocketHoenn_Salida_Base_Move_2
waitmovement 0x0
release
end

BaseRocketHoenn_Salida_Base_Texto_1:
.string "(Esta es la salida, debería ver antes\n"
.string "la BASE con ANDRA, tal y como\l"
	.string "acordamos).$"

BaseRocketHoenn_Salida_Base_Move_1:
walk_in_place_down
step_end

BaseRocketHoenn_Salida_Base_Move_2:
walk_slow_left
step_end

Llave_Despacho_Hoenn_2_Warp::
msgbox Llave_Despacho_Hoenn_2_Warp_YesNo, MSGBOX_AUTOCLOSE
playse SE_CLICK
delay 40
playse SE_UNLOCK
setmetatile 18, 21, 0x335, FALSE
setmetatile 18, 22, 0x335, FALSE
setmetatile 19, 22, 0x334, FALSE
setmetatile 19, 21, 0x334, FALSE
special DrawWholeMapView
delay 60
release
end

Llave_Despacho_Hoenn_2_Warp_YesNo:
.string "Usaste la LL.MAGNÉTICA$"


BaseRocketHoenn_Tienda_Pokemon::
lock
faceplayer
msgbox Text_CompraPokemon MSGBOX_AUTOCLOSE
waitmessage
multichoice 22, 0, MULTI_VENTA_BASE_HOENN, 0
switch VAR_RESULT
case 0, EventScript_Rockruff
case 1, EventScript_Drilbur
case 2, EventScript_Timburr
case 3, EventScript_Frosmoth
case 4, EventScript_Bouffalant
case 5, EventScript_Oshawott
case 6, EventScript_Chimchar
case 7, EventScript_Jangmo 
release
end

EventScript_Jangmo::
lock
showmoneybox 0, 0
msgbox EventScript_Jangmo_Texto_1 MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq EventScript_Compra_No
checkmoney 168000
goto_if_eq VAR_RESULT, FALSE, Tienda_Pokemon_No_Money
delay 15
playse SE_SHOP
removemoney 168000 0
waitse
updatemoneybox
delay 20
hidemoneybox
delay 20
givemon SPECIES_JANGMO_O, 32, ITEM_NONE
release
end

EventScript_Chimchar::
lock
showmoneybox 0, 0
msgbox EventScript_Chimchar_Texto_1 MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq EventScript_Compra_No
checkmoney 82000
goto_if_eq VAR_RESULT, FALSE, Tienda_Pokemon_No_Money
delay 15
playse SE_SHOP
removemoney 82000 0
waitse
updatemoneybox
delay 20
hidemoneybox
delay 20
givemon SPECIES_CHIMCHAR, 12, ITEM_NONE
release
end

EventScript_Oshawott::
lock
showmoneybox 0, 0
msgbox EventScript_Oshawott_Texto_1 MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq EventScript_Compra_No
checkmoney 68000
goto_if_eq VAR_RESULT, FALSE, Tienda_Pokemon_No_Money
delay 15
playse SE_SHOP
removemoney 68000 0
waitse
updatemoneybox
delay 20
hidemoneybox
delay 20
givemon SPECIES_OSHAWOTT, 16, ITEM_NONE
release
end

EventScript_Bouffalant::
lock
showmoneybox 0, 0
msgbox EventScript_Bouffalant_Texto_1 MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq EventScript_Compra_No
checkmoney 60000
goto_if_eq VAR_RESULT, FALSE, Tienda_Pokemon_No_Money
delay 15
playse SE_SHOP
removemoney 60000 0
waitse
updatemoneybox
delay 20
hidemoneybox
delay 20
givemon SPECIES_BOUFFALANT, 60, ITEM_NONE
release
end


EventScript_Frosmoth::
lock
showmoneybox 0, 0
msgbox EventScript_Frosmoth_Texto_1 MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq EventScript_Compra_No
checkmoney 48000
goto_if_eq VAR_RESULT, FALSE, Tienda_Pokemon_No_Money
delay 15
playse SE_SHOP
removemoney 48000 0
waitse
updatemoneybox
delay 20
hidemoneybox
delay 20
givemon SPECIES_FROSMOTH, 55, ITEM_NONE
release
end

EventScript_Timburr::
lock
showmoneybox 0, 0
msgbox EventScript_Timburr_Texto_1 MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq EventScript_Compra_No
checkmoney 30000
goto_if_eq VAR_RESULT, FALSE, Tienda_Pokemon_No_Money
delay 15
playse SE_SHOP
removemoney 30000 0
waitse
updatemoneybox
delay 20
hidemoneybox
delay 20
givemon SPECIES_TIMBURR, 24, ITEM_NONE
release
end

EventScript_Drilbur::
lock
showmoneybox 0, 0
msgbox EventScript_Drilbur_Texto_1 MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq EventScript_Compra_No
checkmoney 22500
goto_if_eq VAR_RESULT, FALSE, Tienda_Pokemon_No_Money
delay 15
playse SE_SHOP
removemoney 22500 0
waitse
updatemoneybox
delay 20
hidemoneybox
delay 20
givemon SPECIES_DRILBUR, 25, ITEM_NONE
release
end

EventScript_Rockruff::
lock
showmoneybox 0, 0
msgbox EventScript_Rockruff_Texto_1 MSGBOX_YESNO
compare VAR_RESULT, 0
goto_if_eq EventScript_Compra_No
checkmoney 15000
goto_if_eq VAR_RESULT, FALSE, Tienda_Pokemon_No_Money
delay 15
playse SE_SHOP
removemoney 15000 0
waitse
updatemoneybox
delay 20
hidemoneybox
delay 20
givemon SPECIES_ROCKRUFF, 15, ITEM_NONE
release
end

EventScript_Jangmo_Texto_1:
.string "¿Seguro que quiere a JANGMO-O?\n"
	.string "Costará 168000 POKÉS.$"

EventScript_Poplio_Texto_1:
.string "¿Seguro que quiere a POPLIO?\n"
	.string "Costará 76000 POKÉS.$"

EventScript_Chimchar_Texto_1:
.string "¿Seguro que quiere a CHIMCHAR?\n"
	.string "Costará 82000 POKÉS.$"

EventScript_Oshawott_Texto_1:
.string "¿Seguro que quiere a OSHAWOTT?\n"
	.string "Costará 68000 POKÉS.$"

EventScript_Bouffalant_Texto_1:
.string "¿Seguro que quiere a BOUFFALANT?\n"
	.string "Costará 60000 POKÉS.$"

EventScript_Frosmoth_Texto_1:
.string "¿Seguro que quiere a FROSMOTH?\n"
	.string "Costará 48000 POKÉS.$"

EventScript_Timburr_Texto_1:
.string "¿Seguro que quiere a TIMBURR?\n"
	.string "Costará 30000 POKÉS.$"

EventScript_Drilbur_Texto_1:
.string "¿Seguro que quiere a DRILBUR?\n"
	.string "Costará 22500 POKÉS.$"

EventScript_Rockruff_Texto_1:
.string "¿Seguro que quiere a ROCKRUFF?\n"
	.string "Costará 15000 POKÉS.$"

BaseRocketHoenn_Potencial_Sinohh::
lock
msgbox BaseRocketHoenn_Potencial_Sinohh_Texto, MSGBOX_SIGN   
end

BaseRocketHoenn_Potencial_Sinohh_Texto:
	.string "ZONA DE INVESTIGACIÓN DE LOS\n"
	.string "POKÉMON MAS PODEROSOS DE CADA\l"
	.string "REGIÓN:\p"
	.string "SINNOH$"

BaseRocketHoenn_Potencial_Teselia::
lock
msgbox BaseRocketHoenn_Potencial_Teselia_Texto, MSGBOX_SIGN   
end

BaseRocketHoenn_Potencial_Teselia_Texto:
	.string "ZONA DE INVESTIGACIÓN DE LOS\n"
	.string "POKÉMON MAS PODEROSOS DE CADA\l"
	.string "REGIÓN:\p"
	.string "TESELIA$"

BaseRocketHoenn_Potencial_Kalos::
lock
msgbox BaseRocketHoenn_Potencial_Kalos_Texto, MSGBOX_SIGN   
end

BaseRocketHoenn_Potencial_Kalos_Texto:
	.string "ZONA DE INVESTIGACIÓN DE LOS\n"
	.string "POKÉMON MAS PODEROSOS DE CADA\l"
	.string "REGIÓN:\p"
	.string "KALOS$"

BaseRocketHoenn_Potencial_Alola::
lock
msgbox BaseRocketHoenn_Potencial_Alola_Texto, MSGBOX_SIGN   
end

BaseRocketHoenn_Potencial_Alola_Texto:
	.string "ZONA DE INVESTIGACIÓN DE LOS\n"
	.string "POKÉMON MAS PODEROSOS DE CADA\l"
	.string "REGIÓN:\p"
	.string "ALOLA$"

BaseRocketHoenn_Potencial_Galar::
lock
msgbox BaseRocketHoenn_Potencial_Galar_Texto, MSGBOX_SIGN   
end

BaseRocketHoenn_Potencial_Galar_Texto:
	.string "ZONA DE INVESTIGACIÓN DE LOS\n"
	.string "POKÉMON MAS PODEROSOS DE CADA\l"
	.string "REGIÓN:\p"
	.string "GALAR$"

