MahoganyTown_NinjaBase_MapScripts::
	.byte 0

NinjaBase1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Detrás de ese póster está el botón\n"
.string "que abre la entrada secreta, señor.$"



NinjaBase2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Llega en el momento justo, señor.\n"
.string "He oído que GIOVANNI iba a avisar\l"
.string "a los otros ADMIN.JEFE, pero con\l"
.string "usted aquí no será necesario.$"



NinjaBase3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Pues esos CARAMELOSFURIA no tienen\n"
.string "mala pinta, la verdad[.]$"



NinjaBase4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "Esos ninjas[.]\n"
.string "Con las trampas que han puesto, es\l"
.string "imposible adentrarse en la BASE[.]$"
