RocketHideout_7F_MapScripts::
	.byte 0

RocketHideout7F_1::
lock     
faceplayer     
msgbox RocketHideout7F_Text_1, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_1:
.string "De 600 a 680 STATS BASE hay un\n"
.string "gran salto, seguro que muchos\l"
.string "Pokémon tienen el potencial para\l"
.string "poder entrar en ese amplio rango.$"



RocketHideout7F_2::
lock     
faceplayer     
msgbox RocketHideout7F_Text_2, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_2:
.string "Tenemos constancia de un culto que\n"
.string "en esta región defiende la\l"
.string "inexistencia de un Pokémon de 680\l"
.string "STATS BASE con la no manifestación\l"
.string "del verdadero poder latente de\l"
.string "MEW, al que rinden culto, un poder\l"
.string "que en caso de manifestarse, según\l"
.string "ellos, rebasaría esa barrera\l"
.string "histórica de 680 de base.$"



RocketHideout7F_3::
lock     
faceplayer     
msgbox RocketHideout7F_Text_3, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_3:
.string "Las cifras de poder que aquí se\n"
.string "manejan les vienen grandes al 99%\l"
.string "de los entrenadores, espero que tú\l"
.string "formes parte del 1% restante.$"



RocketHideout7F_4::
lock     
faceplayer     
msgbox RocketHideout7F_Text_4, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_4:
.string "El resto de regiones ve a KANTO\n"
.string "como una potencia tecnológica en\l"
.string "cuanto al desarrollo de Pokémon\l"
.string "artificiales: PORYGON, MEWTWO,\l"
.string "DITTO o incluso PORYGON2 han sido\l"
.string "desarrollados en nuestra región,\l"
.string "suelen acreditarle a SILPH el\l"
.string "mérito de estos avances, ¡lo que\l"
.string "no saben es que aquí vamos mucho\l"
.string "más allá!$"



RocketHideout7F_5::
lock     
faceplayer     
msgbox RocketHideout7F_Text_5, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_5:
.string "Lo sentimos {PLAYER}, pero este\n"
.string "lugar está aún en fase\l"
.string "experimental, solo nuestros\l"
.string "mejores científicos tienen acceso.$"



RocketHideout7F_6::
lock     
faceplayer     
msgbox RocketHideout7F_Text_6, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_6:
.string "Lo sentimos {PLAYER}, pero este\n"
.string "lugar está aún en fase\l"
.string "experimental, solo nuestros\l"
.string "mejores científicos tienen acceso.$"



RocketHideout7F_7::
lock     
faceplayer     
msgbox RocketHideout7F_Text_7, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_7:
.string "Lo sentimos {PLAYER}, pero este\n"
.string "lugar está aún en fase\l"
.string "experimental, solo nuestros\l"
.string "mejores científicos tienen acceso.$"



RocketHideout7F_8::
lock     
faceplayer     
msgbox RocketHideout7F_Text_8, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_8:
.string "A pesar de que es la región con\n"
.string "mayor número de legendarios, es de\l"
.string "la que menos información\l"
.string "disponemos dada su lejanía y poca\l"
.string "conexión, pero muchos de los\l"
.string "Pokémon con los que cuenta son\l"
.string "realmente interesantes, parece ser\l"
.string "que el -150- es la estadística\l"
.string "estrella de los legendarios de\l"
.string "dicha región, se repite en el\l"
.string "Ataque de GROUDON, el Ataque\l"
.string "Especial de KYOGRE, las defensas\l"
.string "de REGISTEEL, la Velocidad de\l"
.string "DEOXYS o ambos ataques en\l"
.string "RAYQUAZA, como una especie de\l"
.string "símbolo, -cualquiera con esta\l"
.string "cifra cuenta con una cualidad\l"
.string "descomunal-, y así es.$"



RocketHideout7F_9::
lock     
faceplayer     
msgbox RocketHideout7F_Text_9, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_9:
.string "La cantidad de Pokémon fuertes que\n"
.string "atesora HOENN no conoce igual,\l"
.string "según nuestras investigaciones,\l"
.string "las condiciones de su terreno han\l"
.string "propiciado la aparición de una\l"
.string "fauna y flora única.$"



RocketHideout7F_10::
lock     
faceplayer     
msgbox RocketHideout7F_Text_10, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_10:
.string "Lo cierto es que existe otro\n"
.string "Pokémon que podría entrar de lleno\l"
.string "en la lista de los Pokémon con\l"
.string "mejores STATS BASE de HOENN y\l"
.string "ocupar incluso los primeros\l"
.string "puestos: SLAKING, con 670 STATS\l"
.string "BASE, no obstante, aquí\l"
.string "consideramos un insulto y una\l"
.string "broma de mal gusto la existencia\l"
.string "de un Pokémon con tales números y\l"
.string "una habilidad tan asquerosamente\l"
.string "lastrante, por ello decidimos\l"
.string "ignorar a la excepción que\l"
.string "confirma la regla, como castigo\l"
.string "por su incompetencia como Pokémon.$"



RocketHideout7F_11::
lock     
faceplayer     
msgbox RocketHideout7F_Text_11, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_11:
.string "Si pudiéramos reunir en un solo\n"
.string "Pokémon los PS de BLISSEY, las\l"
.string "defensas de SHUCKLE y la ofensiva\l"
.string "de DEOXYS, tendríamos al Pokémon\l"
.string "más potente que jamás pueda\l"
.string "existir, obviamente no existe ni\l"
.string "de lejos un cuerpo que pueda\l"
.string "resistir todas esas virtudes\l"
.string "combinadas, ¡el coste de\l"
.string "oportunidad es duro chico!$"



RocketHideout7F_12::
lock     
faceplayer     
msgbox RocketHideout7F_Text_12, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_12:
.string "Todo lo que ves aquí es resultado\n"
.string "de décadas de recopilación de\l"
.string "datos para obtener información\l"
.string "privilegiada sobre todos los\l"
.string "legendarios y Pokémon más fuertes\l"
.string "conocidos, espero que seas\l"
.string "consciente de lo afortunado que\l"
.string "eres de estar aquí.$"



RocketHideout7F_13::
lock     
faceplayer     
msgbox RocketHideout7F_Text_13, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_13:
.string "JOHTO cuenta con mucha más\n"
.string "historia y tradición que KANTO,\l"
.string "las dos torres de CIUDAD IRIS son\l"
.string "milenarias.$"



RocketHideout7F_14::
lock     
faceplayer     
msgbox RocketHideout7F_Text_14, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_14:
.string "Dicen que ENTEI, SUICUNE y RAIKOU\n"
.string "son en realidad un FLAREON,\l"
.string "VAPOREON y JOLTEON que el\l"
.string "mismísimo HO-OH rescató de un\l"
.string "devastador incendio en CIUDAD\l"
.string "IRIS, reencarnándolos en los tres\l"
.string "legendarios errantes, esta leyenda\l"
.string "no solo se refuerza con la\l"
.string "coincidencia entre sus tipos y\l"
.string "parecidos, casualmente FLAREON y\l"
.string "ENTEI cuentan con potentes ataques\l"
.string "físicos, SUICUNE y VAPOREON se\l"
.string "inclinan más por estadísticas\l"
.string "defensivas, y por último tanto\l"
.string "JOLTEON como RAIKOU cuentan con un\l"
.string "Ataque Especial, Velocidad e\l"
.string "incluso Defensa Especial\l"
.string "sospechosamente parecidas.$"



RocketHideout7F_15::
lock     
faceplayer     
msgbox RocketHideout7F_Text_15, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_15:
.string "No creímos que en la naturaleza\n"
.string "pudiera existir tal Pokémon que\l"
.string "igualara a MEWTWO en poder puro,\l"
.string "pero resulta que JOHTO cuenta con\l"
.string "dos de esas características, hemos\l"
.string "intentado múltiples veces hallar\l"
.string "el paradero de LUGIA y HO-OH, pero\l"
.string "sin éxito.$"



RocketHideout7F_16::
lock     
faceplayer     
msgbox RocketHideout7F_Text_16, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_16:
.string "Algunos juran que KINGDRA nunca\n"
.string "tuvo tal habilidad como Adaptable,\l"
.string "lo cierto es que la heredó de un\l"
.string "tal DRAGALGE proveniente de una\l"
.string "región lejana.$"



RocketHideout7F_17::
lock     
faceplayer     
msgbox RocketHideout7F_Text_17, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_17:
.string "Si pudiéramos reunir en un solo\n"
.string "Pokémon los PS de BLISSEY, las\l"
.string "defensas de SHUCKLE y la ofensiva\l"
.string "de DEOXYS, tendríamos al Pokémon\l"
.string "más potente que jamás pueda\l"
.string "existir, obviamente no existe ni\l"
.string "de lejos un cuerpo que pueda\l"
.string "resistir todas esas virtudes\l"
.string "combinadas, ¡el coste de\l"
.string "oportunidad es duro chico!$"



RocketHideout7F_18::
lock     
faceplayer     
msgbox RocketHideout7F_Text_18, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_18:
.string "No sabemos dónde está el límite de\n"
.string "poder base alcanzable por un\l"
.string "POKÉMON, pero si sabemos dónde no\l"
.string "está…$"



RocketHideout7F_19::
end



RocketHideout7F_21::
lock     
faceplayer     
msgbox RocketHideout7F_Text_21, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_21:
.string "Esa DEVON en HOENN está creciendo\n"
.string "cada vez más, pero no tiene nada\l"
.string "que hacer ante una SILPH y un TEAM\l"
.string "ROCKET unidos, o acepta nuestras\l"
.string "condiciones o será borrada del\l"
.string "tablero.$"



RocketHideout7F_22::
lock     
faceplayer     
msgbox RocketHideout7F_Text_22, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_22:
.string "¡Usted no para señor!\n"
.string "¡A este paso viajará por todas las\l"
.string "regiones del mundo POKÉMON!$"



RocketHideout7F_23::
lock     
faceplayer     
msgbox RocketHideout7F_Text_23, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_23:
.string "Estos documentos eran una\n"
.string "quimera para toda la comunidad\l"
.string "científica hace apenas unos años,\l"
.string "y mira ahora…\l"
.string "Aquí están…\l"
.string "Son reales…$"



RocketHideout7F_24::
lock     
faceplayer     
msgbox RocketHideout7F_Text_24, MSGBOX_DEFAULT
release     
end

RocketHideout7F_Text_24:
.string "La gente común se sorprende al ver\n"
.string "POKÉMON de más de 500 STATS BASE,\l"
.string "y se echa las manos a la cabeza\l"
.string "con cualquier PSEUDOLEGENDARIO o\l"
.string "LEGENDARIO MENOR de 580 de BASE,\l"
.string "no creo que estén preparados para\l"
.string "ver POKÉMON que se ríen de estos\l"
.string "números, sus cabezas no lo\l"
.string "asimilarían, ya que están\l"
.string "acostumbradas a aceptar únicamente\l"
.string "la realidad del mundo que se les\l"
.string "presenta.$"
