FuchsiaCity_House2_MapScripts::
	.byte 0

FuchsiaCityHouse2_1::
lock     
faceplayer     
msgbox FuchsiaCity_House2_Text_1, MSGBOX_DEFAULT
release     
end

FuchsiaCity_House2_Text_1:
.string "¿Hmm?\n"
.string "¿Has conocido a BILL?\l"
.string "¡Es mi nieto!\l"
.string "Siempre le ha gustado coleccionar\l"
.string "cosas, desde que es un niño ve a\l"
.string "los POKÉMON como trofeos…$"



FuchsiaCityHouse2_2::
lock     
faceplayer     
msgbox FuchsiaCity_House2_Text_2, MSGBOX_DEFAULT
release     
end

FuchsiaCity_House2_Text_2:
.string "BILL guarda los datos de sus\n"
.string "Pokémon en su PC.\l"
.string "¿Te los enseñó?$"



FuchsiaCityHouse2_3::
lock     
faceplayer     
msgbox FuchsiaCity_House2_Text_3, MSGBOX_DEFAULT
release     
end

FuchsiaCity_House2_Text_3:
.string "El guardia de la ZONA SAFARI es\n"
.string "mayor, pero aún es muy activo.$"
