MtEmber_B5F_MapScripts::
	.byte 0

MtEmber1FPath_3::
end

MtEmber_B5F_Encuentro_Magno::
msgbox MtEmber_B5F_Encuentro_Magno_Texto_1 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_2 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_3 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_4 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_5 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_6 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_7 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_8 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_9 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_10 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_11 MSGBOX_AUTOCLOSE
msgbox MtEmber_B5F_Encuentro_Magno_Texto_12 MSGBOX_AUTOCLOSE
release
end

MtEmber_B5F_Encuentro_Magno_Texto_1:
.string "MAGNO: Este es el lugar, la\n"
	.string "ubicación del RUBY no engaña,\l"
	.string "detrás de estas paredes\l"
	.string "descansa GROUDON.$"

MtEmber_B5F_Encuentro_Magno_Texto_2:
.string "...$"

MtEmber_B5F_Encuentro_Magno_Texto_3:
.string "Ese estúpido científico del CENTRO\n"
	.string "POKÉMON de esta isla que se hace\l"
	.string "llamar CELIO quería obtener el\l"
	.string "RUBÍ para usarlo en ese burdo\l"
	.string "proyecto de conexión entre\l"
	.string "regiones, semejante sacrilegio\l"
	.string "solo hubiera estado a la altura de\l"
	.string "su ignorancia.$"

MtEmber_B5F_Encuentro_Magno_Texto_4:
.string "Afortunadamente este RUBÍ ha caído\n"
	.string "en las manos adecuadas, le daremos\l"
	.string "el verdadero uso, el propósito,\l"
	.string "por el que fue creado, ¡observad!$"

MtEmber_B5F_Encuentro_Magno_Texto_5:
.string "Si juntamos ambos objetos, la\n"
	.string "ESFERA ROJA y el RUBÍ, dentro de\l"
	.string "este lugar, la reacción es la\l"
	.string "siguiente...$"

MtEmber_B5F_Encuentro_Magno_Texto_6:
.string "Al fin, ya queda poco GROUDON, tu\n"
	.string "poder ha sido contenido por mucho\l"
	.string "tiempo, pero ya no más...$"

MtEmber_B5F_Encuentro_Magno_Texto_7:
.string "MAGNO: Tú otra vez, ya te avisé\n"
	.string "una vez, y no volveré a hacerlo,\l"
	.string "tengo cosas más importantes que\l"
	.string "hacer que ocuparme de ti.\l"
	.string "¡ALTO RANGO KAREN!\l"
	.string "¡Que no pase de este lugar!$"

MtEmber_B5F_Encuentro_Magno_Texto_8:
.string "AR KAREN: No permitiré que le\n"
	.string "ponga la mano encima señor.$"

MtEmber_B5F_Encuentro_Magno_Texto_9:
.string "MAGNO: Ahí te quedas, GROUDON\n"
	.string "espera, aún pudiendo llegar hasta\l"
	.string "mi, para cuando lo hicieres ya\l"
	.string "sería demasiado tarde.$"

MtEmber_B5F_Encuentro_Magno_Texto_10:
.string "Todo ha salido tal y como\n"
	.string "planeamos, llegados a este punto\l"
	.string "nadie puede hacer nada por impedir\l"
	.string "el despertar de GROUDON, tienes\l"
	.string "dos opciones: o salir corriendo de\l"
	.string "aquí antes de que todo explote, ¡o\l"
	.string "ser el primero en ponerse como\l"
	.string "carne de cañón para cuando GROUDON\l"
	.string "despierte!$"

MtEmber_B5F_Encuentro_Magno_Texto_11:
.string "Mi derrota ha servido para asegurar\n"
	.string "nuestra victoria final.$"

MtEmber_B5F_Encuentro_Magno_Texto_12:
.string "No hay marcha atrás, pronto el\n"
	.string "mundo será testigo del poder de\l"
	.string "GROUDON, y tú un mero espectador\l"
	.string "más.$"

MtEmber_B5F_Encuentro_Magno_Move_1:
face_left
step_end

MtEmber_B5F_Encuentro_Magno_Move_2:
emote_exclamation_mark
step_end

MtEmber_B5F_Encuentro_Magno_Move_3:
walk_left
walk_left
walk_left
walk_left
walk_up
walk_up
walk_up
walk_up
step_end

MtEmber_B5F_Encuentro_Magno_Move_4:
walk_up
step_end

MtEmber_B5F_Encuentro_Magno_Move_5:
walk_in_place_up
step_end

MtEmber_B5F_Encuentro_Magno_Move_6:
walk_down
walk_down
walk_down
walk_down
walk_right
walk_right
walk_right
walk_right
step_end

MtEmber_B5F_Encuentro_Magno_Move_7:
walk_left
walk_left
walk_left
walk_up
walk_up
walk_left
walk_in_place_up
step_end

MtEmber_B5F_Encuentro_Magno_Move_8:
emote_exclamation_mark
face_down
step_end

MtEmber_B5F_Encuentro_Magno_Move_9:
face_down
step_end

MtEmber_B5F_Encuentro_Magno_Move_10:
walk_left
walk_in_place_down
step_end

MtEmber_B5F_Encuentro_Magno_Move_11:
face_up
step_end

MtEmber_B5F_Encuentro_Magno_Move_12:
walk_up
walk_right
walk_up
step_end

MtEmber_B5F_Encuentro_Magno_Move_13:
walk_in_place_down
step_end
