NeoLavandaPueblo_MapScripts::
	.byte 0

NeoLavandaPueblo_1::
lock     
faceplayer     
msgbox NeoLavandaPueblo_Text_1, MSGBOX_DEFAULT
release     
end

NeoLavandaPueblo_Text_1:
.string "Menudo edificio, ¿eh? Aún así, la SEDE\n"
.string "SILPH, y la antigua TORRE POKÉMON, son\l"
.string "más altos.$"




NeoLavandaPueblo_2::
lock     
faceplayer     
msgbox NeoLavandaPueblo_Text_2, MSGBOX_DEFAULT
release     
end

NeoLavandaPueblo_Text_2:
.string "JOHTO nos lleva la delantera, sus\n"
.string "programas de radio son muy buenos.\l"
.string "¿Podrá KANTO hacerlo tan bien?$"




NeoLavandaPueblo_3::
lock     
faceplayer     
msgbox NeoLavandaPueblo_Text_3, MSGBOX_DEFAULT
release     
end

NeoLavandaPueblo_Text_3:
.string "Los programas de radio que aquí se\n"
.string "emitirán nos tienen a todos\l"
.string "expectantes, ¿cómo lo harán en los\l"
.string "pisos de arriba?$"




NeoLavandaPueblo_4::
lock     
faceplayer     
msgbox NeoLavandaPueblo_Text_4, MSGBOX_DEFAULT
release     
end

NeoLavandaPueblo_Text_4:
.string "Viene gente de todas partes a rendir\n"
.string "homenaje a las almas que han partido.$"
