PastoriaCity_MapScripts::
	.byte 0


Pastoria_Gimnasio::
lock
msgbox Pastoria_Gimnasio_Texto_1, MSGBOX_SIGN
release
end

Pastoria_Gimnasio_Texto_1:
	.string "GIMNASIO POKÉMON de CIUDAD PRADERA\n"
	.string "LÍDER: MANANTI, el destructor\l"
	.string "maestro torrencial enmascarado$"


Pastoria_Cartel::
lock
msgbox Pastoria_Cartel_Texto_1, MSGBOX_SIGN
release
end

Pastoria_Cartel_Texto_1:
	.string "CIUDAD PRADERA\n"
	.string "La ciudad de los pantanos$"


Pastoria_Safari::
lock
msgbox Pastoria_Safari_Texto_1, MSGBOX_SIGN
release
end

Pastoria_Safari_Texto_1:
	.string "¡Aventúrate en el SAFARI\n"
	.string "del GRAN PANTANO!$"


Pastoria_Primer_NPC::
lock     
faceplayer     
msgbox Pastoria_Primer_NPC_Texto_1, MSGBOX_NPC
release     
end

Pastoria_Primer_NPC_Texto_1:
.string "He venido a ver el GRAN PANTANO.\n"
.string "Me alojo en el hotel que está junto\l"
.string "al lago.$"


Pastoria_Segundo_NPC::
lock     
faceplayer     
msgbox Pastoria_Segundo_NPC_Texto_1, MSGBOX_NPC
release     
end

Pastoria_Segundo_NPC_Texto_1:
.string "Inventar diálogo$"


Pastoria_Tercer_NPC::
lock     
faceplayer     
msgbox Pastoria_Tercer_NPC_Texto_1, MSGBOX_NPC
release     
end

Pastoria_Tercer_NPC_Texto_1:
.string "Algunos entrenadores evitan que sus\n"
.string "POKÉMON evolucionen a propósito…\p"
.string "Así, al subir de nivel aprenden\n"
.string "movimientos determinados.$"


Pastoria_Cuarto_NPC::
lock     
faceplayer     
msgbox Pastoria_Cuarto_NPC_Texto_1, MSGBOX_NPC
release     
end

Pastoria_Cuarto_NPC_Texto_1:
.string "El LÍDER de GIMNASIO es impresionante.\p"
.string "He oído que compite en combates de\n"
.string "lucha profesional.$"


Pastoria_Quinto_NPC::
lock     
faceplayer     
msgbox Pastoria_Quinto_NPC_Texto_1, MSGBOX_NPC
release     
end

Pastoria_Quinto_NPC_Texto_1:
.string "Inventar diálogo$"


Pastoria_Sexto_NPC::
lock     
faceplayer     
msgbox Pastoria_Sexto_NPC_Texto_1, MSGBOX_NPC
release     
end

Pastoria_Sexto_NPC_Texto_1:
.string "Mírame, justo en el centro de todo,\n"
.string "ahí es donde debo estar.$"


Pastoria_Septimo_NPC::
lock     
faceplayer     
msgbox Pastoria_Septimo_NPC_Texto_1, MSGBOX_NPC
release     
end

Pastoria_Septimo_NPC_Texto_1:
.string "¿Has estado en la MANSIÓN POKÉMON?\n"
.string "Está en la RUTA 212\p"
.string "Al dueño, el SR.FORTUNY, le gusta\n"
.string "presumir de los POKÉMON tan poco\l"
.string "habituales que tiene.$"


Pastoria_Octavo_NPC::
lock     
faceplayer     
msgbox Pastoria_Octavo_NPC_Texto_1, MSGBOX_NPC
release     
end

Pastoria_Octavo_NPC_Texto_1:
.string "Gracias al GRAN PANTANO, aquí no hace\n"
.string "mucho calor en verano.\p"
.string "Por eso, esta es una buena ciudad para\n"
.string "POKÉMON de TIPO AGUA.$"


Pastoria_Noveno_NPC::
lock     
faceplayer     
msgbox Pastoria_Noveno_NPC_Texto_1, MSGBOX_NPC
release     
end

Pastoria_Noveno_NPC_Texto_1:
.string "Me dedico a estudiar POKÉMON que solo\n"
.string "se encuentran en el GRAN PANTANO.$"

