PokemonLeague_3F_MapScripts::
	.byte 0

PokemonLeague_3F_Combate_Agatha::
msgbox PokemonLeague_3F_Combate_Agatha_Texto_1 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_3F_Combate_Agatha_Texto_2 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_3F_Combate_Agatha_Texto_4 MSGBOX_AUTOCLOSE
release
end

PokemonLeague_3F_Combate_Agatha_Texto_1:
.string "No he visto tanto talento junto\n"
	.string "desde esa época gloriosa donde se\l"
	.string "debatieron el título OAK y GIOV...\l"
	.string "Una lástima que todos vayáis a\l"
	.string "caer miserablemente, no debería de\l"
	.string "decirte esto {PLAYER}, pero los\l"
	.string "intereses políticos han atravesado\l"
	.string "también estos muros, LANCE es\l"
	.string "CAMPEÓN y DICTADOR de KANTO al\l"
	.string "mismo tiempo, jamás cederá su\l"
	.string "título de CAMPEÓN ante alguien que\l"
	.string "pueda comprometer su reinado,\l"
	.string "sabido esto pasa a la siguiente\l"
	.string "sala, aún tienes la oportunidad de\l"
	.string "hacer que tu equipo POKÉMON hable\l"
	.string "en el campo.$"


PokemonLeague_3F_Combate_Agatha_Texto_2:
.string "¿Pero qué tenemos aquí?\n"
	.string "No me gusta esta moda de vestir\l"
	.string "así chaval, ¿no te importa que te\l"
	.string "lo diga verdad?\l"
	.string "Soy AGATHA del ALTO MANDO,\l"
	.string "especialista en el tipo FANTASMA,\l"
	.string "un tipo con muchos misterios aún\l"
	.string "por resolver, y cuyo potencial aún\l"
	.string "desconocemos, a pesar de ello,\l"
	.string "gracias a mis décadas de\l"
	.string "experiencia y duro entrenamiento\l"
	.string "he logrado entender mucho mejor a\l"
	.string "este tipo.\l"
	.string "¿{PLAYER}?\l"
	.string "¡Te mostraré cómo lucha un\l"
	.string "ENTRENADOR de verdad!$"

PokemonLeague_3F_Combate_Agatha_Texto_4:
.string "Vaya, otro chiquillo más que tiene\n"
	.string "algo especial.$"
