SsAnne_11F_MapScripts::
	.byte 0

SsAnne11F_1::
end



SsAnne11F_2::
lock     
faceplayer     
msgbox SsAnne11F_Text_2, MSGBOX_DEFAULT
release     
end

SsAnne11F_Text_2:
.string "Woooooo!\n"
.string "Safari Zone, here I come!$"



SsAnne11F_3::
lock     
faceplayer     
msgbox SsAnne11F_Text_3, MSGBOX_DEFAULT
release     
end

SsAnne11F_Text_3:
	.string "Some of the other guests have behaved\n"
	.string "terribly on this cruise, like spoiled\l"
	.string "brats. I'm proud to say I've raised my\l"
	.string "daughter better than that.$"
