CeladonCity_House1_3F_MapScripts::
	.byte 0

CeladonMansion3F_1::
lock     
faceplayer     
msgbox CeladonCity_House1_3F_Text_1, MSGBOX_DEFAULT
release     
end

CeladonCity_House1_3F_Text_1:
.string "Gefällt dir das Spiel?\p"
    .string "Ich habe das Spiel gestaltet!\p"
	.string "Auch wenn es sehr mühsam ist, den\n"
	.string "POKéDEX zu erstellen: Gib nicht auf!\p"
	.string "Zeige ihn mir, wenn er komplett ist!$"



CeladonMansion3F_2::
lock     
faceplayer     
msgbox CeladonCity_House1_3F_Text_2, MSGBOX_DEFAULT
release     
end

CeladonCity_House1_3F_Text_2:
.string "Ich?\n"
    .string "Ich bin der Programmierer!$"



CeladonMansion3F_3::
lock     
faceplayer     
msgbox CeladonCity_House1_3F_Text_3, MSGBOX_DEFAULT
release     
end

CeladonCity_House1_3F_Text_3:
.string "Ich bin der Grafiker!\n"
    .string "Ich habe dies alles gezeichnet!$"



CeladonMansion3F_4::
lock     
faceplayer     
msgbox CeladonCity_House1_3F_Text_4, MSGBOX_DEFAULT
release     
end

CeladonCity_House1_3F_Text_4:
	.string "Die Geschichte stammt von mir!\p"
	.string "Ist ERIKA nicht süß? Aber MISTY\n"
	.string "mag ich auch gerne!\p"
	.string "Und nicht zu vergessen, SABRINA!$"



CeladonMansion3FDocumento_100::
msgbox CeladonMansion3FDocumento_Text_100, MSGBOX_SIGN   
end

CeladonMansion3FDocumento_Text_100:
.string "GAME FREAK Entwicklungs-Abteilung$"

CeladonMansion3FDocumento_101::
msgbox CeladonMansion3FDocumento_Text_101, MSGBOX_SIGN   
end

CeladonMansion3FDocumento_Text_101:
.string "Das Drehbuch!\n"
.string "Ich schaue mir das Ende besser nicht an!$"

CeladonMansion3FDocumento_102::
msgbox CeladonMansion3FDocumento_Text_102, MSGBOX_SIGN   
end

CeladonMansion3FDocumento_Text_102:
    .string "Dort spielt jemand, anstatt zu arbeiten!$"

CeladonMansion3FDocumento_103::
msgbox CeladonMansion3FDocumento_Text_103, MSGBOX_SIGN   
end

CeladonMansion3FDocumento_Text_103:
.string "Der Programmcode!\n"
    .string "Davon sollte man besser die Finger lassen!$"
