CeladonCity_House1_3F_MapScripts::
	.byte 0

CeladonMansion3F_1::
lock     
faceplayer     
msgbox CeladonCity_House1_3F_Text_1, MSGBOX_DEFAULT
release     
end

CeladonCity_House1_3F_Text_1:
.string "Is that right?\p"
    .string "I'm the game designer!\p"
    .string "Filling up your POKéDEX is tough,\n"
    .string "but don't quit!\p"
    .string "When you finish, come tell me!$"



CeladonMansion3F_2::
lock     
faceplayer     
msgbox CeladonCity_House1_3F_Text_2, MSGBOX_DEFAULT
release     
end

CeladonCity_House1_3F_Text_2:
.string "Me?\n"
    .string "I'm the programmer!$"



CeladonMansion3F_3::
lock     
faceplayer     
msgbox CeladonCity_House1_3F_Text_3, MSGBOX_DEFAULT
release     
end

CeladonCity_House1_3F_Text_3:
.string "I'm the graphic artist!\n"
    .string "But I don't drew you!$"



CeladonMansion3F_4::
lock     
faceplayer     
msgbox CeladonCity_House1_3F_Text_4, MSGBOX_DEFAULT
release     
end

CeladonCity_House1_3F_Text_4:
.string "I wrote the story!\n"
    .string "Isn't ERIKA cute?\p"
    .string "I like MISTY a lot, too!\n"
    .string "Oh, and SABRINA, I like her!$"



CeladonMansion3FDocumento_100::
msgbox CeladonMansion3FDocumento_Text_100, MSGBOX_SIGN   
end

CeladonMansion3FDocumento_Text_100:
.string "GAME FREAK Development Room$"

CeladonMansion3FDocumento_101::
msgbox CeladonMansion3FDocumento_Text_101, MSGBOX_SIGN   
end

CeladonMansion3FDocumento_Text_101:
.string "It's the script!\n"
    .string "Better not look at the ending!$"

CeladonMansion3FDocumento_102::
msgbox CeladonMansion3FDocumento_Text_102, MSGBOX_SIGN   
end

CeladonMansion3FDocumento_Text_102:
.string "Someone's playing a game instead of\n"
    .string "working!$"

CeladonMansion3FDocumento_103::
msgbox CeladonMansion3FDocumento_Text_103, MSGBOX_SIGN   
end

CeladonMansion3FDocumento_Text_103:
.string "It's the game program! Messing with\n"
    .string "it could bug out the game!$"
