RocketHideoutViridian_MapScripts::
	.byte 0

RocketHideoutViridian4::
end



RocketHideoutViridian5::
end



RocketHideoutViridian6::
end



RocketHideoutViridian7::
end



RocketHideoutViridian8::
end



RocketHideoutViridian9::
end



RocketHideoutViridian10::
end



RocketHideoutViridian11::
end



RocketHideoutViridian12::
end



RocketHideoutViridian13::
end



RocketHideoutViridian14::
end



RocketHideoutViridian15::
end
