FiveIsland_House2_MapScripts::
	.byte 0

FiveIslandHouse2_1::
lock     
faceplayer     
msgbox FiveIsland_House2_Text_1, MSGBOX_DEFAULT
release     
end

FiveIsland_House2_Text_1:
	.string "Die Weide östlich von hier ist schon\n"
	.string "seit Generationen im Besitz meiner\l"
	.string "Familie. Ich hätte dort eine große Villa\l"
	.string "bauen sollen, als ich es noch konnte.\p"
	.string "Dann müsste ich mich nicht länger mit\n"
	.string "dir und deiner verruchten Organisation\l"
	.string "rumschlagen!$"


