Cianwood_House3_MapScripts::
	.byte 0

CianwoodHouse3-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "He oído que planean hacer otra\n"
.string "ZONA SAFARI por aquí cerca,\l"
.string "¿afectará eso a nuestra ciudad?$"



CianwoodHouse3-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "No hay nada como ORQUÍDEA,\n"
.string "¡créeme!\l"
.string "¡Esta ciudad está bendecida con\l"
.string "los frutos del mar!$"



CianwoodHouse3-3::
end
