ThreeIsland_House2_MapScripts::
	.byte 0

ThreeIslandHouse2_1::
lock     
faceplayer     
msgbox ThreeIsland_House2_Text_1, MSGBOX_DEFAULT
release     
end

ThreeIsland_House2_Text_1:
.string "Urrrrrrrrgggghhhh…\n"
    .string "Kwaaaaah!\p"
    .string "…It's useless! I can't make this\n"
    .string "spoon bend with my mind.\p"
    .string "Maybe I really don't have any\n"
    .string "psychic powers.$"



ThreeIslandHouse2_2::
lock     
faceplayer     
msgbox ThreeIsland_House2_Text_2, MSGBOX_DEFAULT
release     
end

ThreeIsland_House2_Text_2:
.string "You know about a girl GYM LEADER\n"
    .string "in SAFFRON CITY?\p"
    .string "She uses PSYCHIC-type POKÉMON,\n"
    .string "right?\p"
    .string "I admire her, I really do.\p"
    .string "I've heard that she's one cool\n"
    .string "customer and beautiful, too.$"
