ThreeIsland_House2_MapScripts::
	.byte 0

ThreeIslandHouse2_1::
lock     
faceplayer     
msgbox ThreeIsland_House2_Text_1, MSGBOX_DEFAULT
release     
end

ThreeIsland_House2_Text_1:
.string "¡Urrrrrrrrgggg!…\n"
.string "¡Fffwaaaaah!\p"
.string "¡Nada!… ¡No hay manera!\n"
.string "¡No consigo doblar la cuchara\l"
.string "con la mente!\p"
.string "A ver si va a resultar que no\n"
.string "tengo poderes psíquicos…$"



ThreeIslandHouse2_2::
lock     
faceplayer     
msgbox ThreeIsland_House2_Text_2, MSGBOX_DEFAULT
release     
end

ThreeIsland_House2_Text_2:
.string "¿Sabes algo de la LÍDER del\n"
.string "GIMNASIO de AZAFRÁN?\p"
.string "Usa POKéMON del tipo PSÍQUICO,\n"
.string "¿no?\p"
.string "Yo la admiro, la verdad.\p"
.string "He oído que es guay y, además,\n"
.string "muy mona.$"
