Cherry_House3_MapScripts::
	.byte 0

CherryHouse3_1::
lock     
faceplayer     
msgbox CherryHouse3_Text_1, MSGBOX_DEFAULT
release     
end

CherryHouse3_Text_1:
.string "No hay mucho que hacer por aquí, y\n"
.string "precisamente esa es la virtud de\l"
.string "este lugar. Sin ruido y estímulos\l"
.string "de fuera, tienes todo el tiempo\l"
.string "del mundo para conocerte mejor y\l"
.string "ver todo de lo que eres capaz en\l"
.string "plena naturaleza.$"



CherryHouse3_2::
lock     
faceplayer     
msgbox CherryHouse3_Text_2, MSGBOX_DEFAULT
release     
end

CherryHouse3_Text_2:
.string "¿Cómo?\n"
.string "¿PUEBLO PRIMAVERA?\l"
.string "¡En 50 años viviendo aquí jamás he\l"
.string "oído hablar de ese lugar!$"
