CinnabarIsland_House1_MapScripts::
	.byte 0

CinnabarIslandHouse1-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Aquí no hacemos intercambios con\n"
.string "ROCKETS chico, no queremos a\l"
.string "vuestros POKÉMON robados y\l"
.string "obtenidos de forma ilegítima,\l"
.string "jamás dejaremos que los nuestros\l"
.string "sean criados por gente así.$"



CinnabarIslandHouse1-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "¡Encontré este FÓSIL tan raro\n"
.string "en el MT. MOON!\p"
.string "¡Creo que es un POKéMON\n"
.string "prehistórico y raro!$"



CinnabarIslandHouse1-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "¡Heee!\n"
.string "¡Deja en paz a mis POKÉMON o\l"
.string "llamaré a las autoridades!$"
