Route16_MapScripts::
	.byte 0

Route16-1::
end


Route16-2::
end


Route16-3::
end


Route16-4::
end


Route16-5::
end


Route16-6::
end


Route16-7::
end


Route16-8::
end


Route16-9::
end


Route16-10::
end


Route16-11::
lock     
faceplayer     
msgbox Text_11, MSGBOX_DEFAULT
release     
end

Text_11:
.string "Ese HITMONLEE pegaba durísimo[.]$"


Route16-12::
lock     
faceplayer     
msgbox Text_12, MSGBOX_DEFAULT
release     
end

Text_12:
.string "Ha acabado con nosotros 4 usando\n"
.string "solo a 2 POKÉMON[.]$"



Route16-13::
lock     
faceplayer     
msgbox Text_13, MSGBOX_DEFAULT
release     
end

Text_13:
.string "Ilusos[.]\n"
.string "Nadie que desafíe a un miembro de\l"
.string "la ÉLITE 4 puede salir bien\l"
.string "parado[.]$"


Route16-14::
lock     
faceplayer     
msgbox Text_14, MSGBOX_DEFAULT
release     
end

Text_14:
.string "Así que este es el poder de la\n"
.string "ÉLITE 4[.]$"

Route16-15::
lock     
faceplayer     
msgbox Text_15, MSGBOX_DEFAULT
release     
end

Text_15:
.string "Solo os queda hablar[.]o ir a\n"
.string "prisión.$"


Route16-16::
lock     
faceplayer     
msgbox Text_16, MSGBOX_DEFAULT
release     
end

Text_16:
.string "Ya los tenemos donde queríamos[.]$"
