Route33_MapScripts::
	.byte 0

Route33_1::
end



Route33_2::
end



Route33_3::
end



Route33_4::
end



Route33_5::
lock     
faceplayer     
msgbox Route33_Text_5, MSGBOX_DEFAULT
release     
end

Route33_Text_5:
.string "Esa leyenda que habla de un raro y\n"
.string "fuerte POKÉMON en las\l"
.string "profundidades de CUEVA UNIÓN atrae\l"
.string "a muchos entrenadores por los\l"
.string "alrededores.$"
