SSGiovanni_Rescate_MapScripts::
	.byte 0


SSGiovanni_Rescate_Escena::
lock
msgbox SSGiovanni_Rescate_Escena_Texto_1 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_2 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_3 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_4 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_5 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_6 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_7 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_8 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_9 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_10 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_11 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_12 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_13 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_14 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_15 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_16 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_17 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_18 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_19 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_20 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_21 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_22 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_23 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_24 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_25 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_26 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_27 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_28 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_29 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_30 MSGBOX_AUTOCLOSE
msgbox SSGiovanni_Rescate_Escena_Texto_31 MSGBOX_AUTOCLOSE
release
end

SSGiovanni_Rescate_Escena_Texto_1:
	.string "ARIANA: ¡Dijiste que te ocuparías de\n"
	.string "PLATA!$"

SSGiovanni_Rescate_Escena_Texto_2:
	.string "GIOVANNI: Eso dije, pero en última\n"
	.string "instancia, debo respetar su voluntad.$"

SSGiovanni_Rescate_Escena_Texto_3:
	.string "ARIANA: ¡Por todos los dioses de KANTO!\n"
	.string "¡Tiene 10 años!$"

SSGiovanni_Rescate_Escena_Texto_4:
	.string "GIOVANNI: Hoy en día, edad más que\n"
	.string "suficiente para iniciar una fantástica\l"
	.string "aventura junto con sus POKÉMON, lejos\l"
	.string "de nuestros problemas.$"

SSGiovanni_Rescate_Escena_Texto_5:
	.string "No puedes juzgar las acciones de uno\n"
	.string "sin entender el mundo que le rodea.$"

SSGiovanni_Rescate_Escena_Texto_6:
	.string "Hasta hace poco… tú misma tenías una\n"
	.string "visión totalmente alejada de la\l"
	.string "realidad respecto a HOENN y DEVON, ¿no\l"
	.string "es así?$"

SSGiovanni_Rescate_Escena_Texto_7:
	.string "ARIANA: … …$"

SSGiovanni_Rescate_Escena_Texto_8:
	.string "GIOVANNI: Sé lo que pretenden, ¿sabes\n"
	.string "por qué? Porque nosotros hicimos lo\l"
	.string "mismo para desbancar a LANCE: ocultar\l"
	.string "gran parte de nuestra realidad.$"

SSGiovanni_Rescate_Escena_Texto_9:
	.string "La cuestión es, ¿qué harás tú, ARIANA?$"

SSGiovanni_Rescate_Escena_Texto_10:
	.string "¿Regresarás al TEAM ROCKET, o\n"
	.string "esperarás sin más a que DEVON ajuste\l"
	.string "cuentas contigo?$"

SSGiovanni_Rescate_Escena_Texto_11:
	.string "Ya no tienes nada que temer. La guerra\n"
	.string "terminó hace años.$"

SSGiovanni_Rescate_Escena_Texto_12:
	.string "ARIANA: No para ti. En tu posición,\n"
	.string "siempre habrá una guerra por librar. Tú\l"
	.string "lo sabes bien.$"

SSGiovanni_Rescate_Escena_Texto_13:
	.string "Pero, como de costumbre, me dejas sin\n"
	.string "elección: Volveré al TEAM ROCKET.$"

SSGiovanni_Rescate_Escena_Texto_14:
	.string "GIOVANNI: No esperaba menos.$"

SSGiovanni_Rescate_Escena_Texto_15:
	.string "{PLAYER}, pasa.$"

SSGiovanni_Rescate_Escena_Texto_16:
	.string "Gracias a vuestra actuación, ahora\n"
	.string "sabemos que uno de los objetivos de\l"
	.string "DEVON es REGIGIGAS.$"

SSGiovanni_Rescate_Escena_Texto_17:
	.string "Lo hemos investigado a fondo.\n"
	.string "Aparentemente está en una forma muy\l"
	.string "limitada pero, a pesar de ello, sus\l"
	.string "números son ya de LEGENDARIO MAYOR.$"

SSGiovanni_Rescate_Escena_Texto_18:
	.string "Deberemos estar pendientes a un poder\n"
	.string "de esa magnitud; tratar de prever el\l"
	.string "próximo movimiento de DEVON pasará a\l"
	.string "ser una prioridad.$"

SSGiovanni_Rescate_Escena_Texto_19:
	.string "Solo se me ocurre una persona que pueda\n"
	.string "aportar información valiosa… ANDRA.$"

SSGiovanni_Rescate_Escena_Texto_20:
	.string "Ella ha viajado por todo HOENN,\n"
	.string "encontró y derrotó a cada uno de los\l"
	.string "REGIS.$"

SSGiovanni_Rescate_Escena_Texto_21:
	.string "Sé que lleva meses sin dar señales de\n"
	.string "vida, pero…$"

SSGiovanni_Rescate_Escena_Texto_22:
	.string "Su FICHA de ENTRENADORA sigue\n"
	.string "vinculada a nuestra base de datos.$"

SSGiovanni_Rescate_Escena_Texto_23:
	.string "{PAUSE 25}…{PAUSE 25} …{PAUSE 25}$"

SSGiovanni_Rescate_Escena_Texto_24:
	.string "Esto es lo que quería comprobar{PAUSE 25}…{PAUSE 25} el\n"
	.string "número de MEDALLAS de HOENN se ha ido\l"
	.string "actualizando en su FICHA.$"

SSGiovanni_Rescate_Escena_Texto_25:
	.string "ARRECÍPOLIS, ALGARIA{PAUSE 25}…{PAUSE 25} esta última de\n"
	.string "hace solo unos días…$"

SSGiovanni_Rescate_Escena_Texto_26:
	.string "Únicamente le queda una MEDALLA por\n"
	.string "ganar en HOENN: la de CIUDAD ARBORADA.\l"
	.string "Es muy probable que pase por ese lugar\l"
	.string "en los próximos días.$"

SSGiovanni_Rescate_Escena_Texto_27:
	.string "¡{PLAYER}! Tu próximo destino es\n"
	.string "claro. Debes llegar a CIUDAD ARBORADA\l"
	.string "antes que ANDRA.$"

SSGiovanni_Rescate_Escena_Texto_28:
	.string "Esperarla ahí, y pedirle ayuda.$"

SSGiovanni_Rescate_Escena_Texto_29:
	.string "ARIANA: Es suficiente. {PLAYER} y yo\n"
	.string "necesitamos descansar.$"

SSGiovanni_Rescate_Escena_Texto_30:
	.string "Si te soy sincera{PAUSE 25}…{PAUSE 25} estoy expectante\n"
	.string "por volver a ver KANTO.$"

SSGiovanni_Rescate_Escena_Texto_31:
	.string "GIOVANNI: Ha cambiado desde entonces,\n"
	.string "pero sigue siendo reconocible.$"

SSGiovanni_Rescate_Dialogo_Giovanni::
lock
faceplayer
msgbox SSGiovanni_Rescate_Dialogo_Giovanni_Texto_1 MSGBOX_NPC
release
end

SSGiovanni_Rescate_Dialogo_Giovanni_Texto_1:
	.string "Deberías descansar también,\n"
	.string "{PLAYER}. Quedan muchas horas hasta\l"
	.string "llegar a HOENN. Así, cuando llegues\l"
	.string "estarás ya fresco para emprender rumbo\l"
	.string "a ARBORADA.$"

SSGiovanni_Rescate_Dialogo_Ariana::
lock
msgbox SSGiovanni_Rescate_Dialogo_Ariana_Texto_1 MSGBOX_SIGN
release
end

SSGiovanni_Rescate_Dialogo_Ariana_Texto_1:
	.string "Está durmiendo. Parece estar\n"
	.string "especialmente tranquila.$"

SSGiovanni_Rescate_Primer_Recluta::
lock
faceplayer
msgbox SSGiovanni_Rescate_Primer_Recluta_Texto_1 MSGBOX_AUTOCLOSE
release
end

SSGiovanni_Rescate_Primer_Recluta_Texto_1:
	.string "Haremos de guardia personal mientras\n"
	.string "usted descansa, SIR. No tiene nada que\l"
	.string "temer.$"

SSGiovanni_Rescate_Segundo_Recluta::
lock
faceplayer
msgbox SSGiovanni_Rescate_Segundo_Recluta_Texto_1 MSGBOX_AUTOCLOSE
release
end

SSGiovanni_Rescate_Segundo_Recluta_Texto_1:
	.string "Esa conversación entre ARIANA y\n"
	.string "GIOVANNI iba a ocurrir antes o después.\l"
	.string "No puedo evitar escucharla.$"

SSGiovanni_Rescate_Tercer_Recluta::
lock
faceplayer
msgbox SSGiovanni_Rescate_Tercer_Recluta_Texto_1 MSGBOX_AUTOCLOSE
release
end

SSGiovanni_Rescate_Tercer_Recluta_Texto_1:
	.string "¡SIR, se ha vengado de ANDRA\n"
	.string "derrotando al ADMIN.AMATISTA! …\l"
	.string "¿Cómo? ¿No estaba usando sus POKÉMON\l"
	.string "más fuertes? Oh…$"


SSGiovanni_Rescate_Cuarto_Recluta::
lock
faceplayer
msgbox SSGiovanni_Rescate_Cuarto_Recluta_Texto_1 MSGBOX_AUTOCLOSE
release
end

SSGiovanni_Rescate_Cuarto_Recluta_Texto_1:
	.string "Llegaremos a HOENN en unas 8 horas, ¡le\n"
	.string "da tiempo para recargar energías!$"

SSGiovanni_Rescate_Quinto_Recluta::
lock
faceplayer
msgbox SSGiovanni_Rescate_Quinto_Recluta_Texto_1 MSGBOX_AUTOCLOSE
release
end

SSGiovanni_Rescate_Quinto_Recluta_Texto_1:
	.string "¡Es usted increíble! Infiltrarse en el\n"
	.string "SUBMARINO de DEVON y perseguirlos\l"
	.string "hasta SINNOH, ¡su aventura será\l"
	.string "recordada por todos!$"
