Olivine_House3_MapScripts::
	.byte 0

OlivineHouse3_1::
lock     
faceplayer     
msgbox OlivineCity_House3_Text_1, MSGBOX_DEFAULT
release     
end

OlivineCity_House3_Text_1:
.string "Mi novio está obsesionado con los\n"
.string "POKÉMON TIPO VOLADOR, dice que el\l"
.string "LÍDER CROM cuenta con uno inmune a\l"
.string "los ataques ELÉCTRICOS.\l"
.string "¡Eso es imposible!\l"
.string "Debería hacer como yo y entrenar a\l"
.string "cualquier POKÉMON mientras sea\l"
.string "fuerte…$"



OlivineHouse3_2::
lock     
faceplayer     
msgbox OlivineCity_House3_Text_2, MSGBOX_DEFAULT
release     
end

OlivineCity_House3_Text_2:
.string "En mis más de 10 años aquí solo\n"
.string "ocurrió una vez, pude ver en\l"
.string "directo al POKÉMON más fuerte de\l"
.string "CROM. Una enorme ave cubierta de\l"
.string "acero, ningún ataque ELÉCTRICO le\l"
.string "afectaba, tenía la VELOCIDAD de un\l"
.string "DODRIO, la agresividad de un\l"
.string "STARAPTOR…Y sus defensas eran\l"
.string "impenetrables, ¡era magnífico!$"
