Olivine_House3_MapScripts::
	.byte 0

OlivineHouse3_1::
lock     
faceplayer     
msgbox OlivineCity_House3_Text_1, MSGBOX_DEFAULT
release     
end

OlivineCity_House3_Text_1:
	.string "My boyfriend is obsessed with\n"
	.string "FLYING-TYPE POKÉMON; he says that the\l"
	.string "LEADER CROM has one immune to ELECTRIC\l"
	.string "attacks. That's impossible! He should\l"
	.string "do it like me and train any POKÉMON as\l"
	.string "long as it's strong…$"



OlivineHouse3_2::
lock     
faceplayer     
msgbox OlivineCity_House3_Text_2, MSGBOX_DEFAULT
release     
end

OlivineCity_House3_Text_2:
	.string "In my living over a decade here, it only\n"
	.string "happened once-I got to see CROM's\l"
	.string "strongest POKÉMON in person. An\l"
	.string "enormous bird covered in steel. No\l"
	.string "ELECTRIC attacks affected it-it had\l"
	.string "the SPEED of a DODRIO and the\l"
	.string "aggressiveness of a STARAPTOR… And its\l"
	.string "DEFENSEs were impenetrable. It was\l"
	.string "magnificent!$"
