SaffronCity_House4_MapScripts::
	.byte 0

SaffronCityHouse4-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "A mí me parece que no hay nada\n"
.string "más guay que ver luchar a los\l"
.string "ENTRENADORES.\p"
.string "¿No te parece?$"



SaffronCityHouse4-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Qué guay es BILL, ¿verdad?\n"
.string "Me gusta hasta su forma de hablar.\p"
.string "¡Me encantaría que viniera alguna\n"
.string "vez por aquí!$"



SaffronCityHouse4-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "¿Mm?\n"
.string "¿Y tú quién eres?\p"
.string "¿Vienes a apuntarte al CLUB?$"



SaffronCityHouse4-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "¡BROCK es mi héroe!\n"
.string "No hay otro como él.\p"
.string "¡Lo admiro tanto que le he\n"
.string "pedido a mi madre que me borde\l"
.string "su nombre en los pantalones, je!$"



SaffronCityHouse4-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "Quien ha estado en boca de todos\n"
.string "últimamente es AGATHA.\p"
.string "Lucha de una manera...\n"
.string "Como a mí me gusta, vaya.$"



SaffronCityHouse4-6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "La verdad es que LORELEI\n"
.string "impone... A mí me encanta.\p"
.string "¿Soy yo la única que percibe el\n"
.string "aura de solemnidad que le rodea?$"



SaffronCityHouse4-7::
lock     
faceplayer     
msgbox Text_7, MSGBOX_DEFAULT
release     
end

Text_7:
.string "¡Hiyah! Sólo tengo respeto por\n"
.string "un ENTRENADOR.\p"
.string "Por mi MAESTRO. No hay nadie\n"
.string "como él sobre el DOJO.\p"
.string "Deberías hacerte su fan, como yo.\n"
.string "¡Hiyah!$"



SaffronCityHouse4-8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "No pienso dejar nunca a SABRINA.\n"
.string "¡Aunque sea su única fan!.\p"
.string "Mi sueño es llegar a ser como\n"
.string "ella; dulce, pero guay a la vez.\p"
.string "¡Y dominar los poderes psíquicos,\n"
.string "como ella!$"
