CultoS3_MapScripts::
	.byte 0


CultoS3_EventScript_Medium::
	trainerbattle_single TRAINER_AURON, CultoS3_Text_MediumIntro, CultoS3_Text_MediumDefeated
	msgbox CultoS3_Text_MediumPostBattle, MSGBOX_AUTOCLOSE
	end



CultoS3_EventScript_Medium2::
	trainerbattle_single TRAINER_KELVIN, CultoS3_Text_Medium2Intro, CultoS3_Text_Medium2Defeated
	msgbox CultoS3_Text_Medium2PostBattle, MSGBOX_AUTOCLOSE
	end



CultoS3_EventScript_Exorcista::
	trainerbattle_single TRAINER_HECTOR, CultoS3_Text_ExorcistaIntro, CultoS3_Text_ExorcistaDefeated
	msgbox CultoS3_Text_ExorcistaPostBattle, MSGBOX_AUTOCLOSE
	end



CultoS3_EventScript_Exorcista2::
	trainerbattle_single TRAINER_EDWIN_1, CultoS3_Text_Exorcista2Intro, CultoS3_Text_Exorcista2Defeated
	msgbox CultoS3_Text_Exorcista2PostBattle, MSGBOX_AUTOCLOSE
	end



CultoS3_EventScript_Medium3::
	trainerbattle_single TRAINER_REYNA, CultoS3_Text_Medium3Intro, CultoS3_Text_Medium3Defeated
	msgbox CultoS3_Text_Medium3PostBattle, MSGBOX_AUTOCLOSE
	end



CultoS3_EventScript_Medium4::
	trainerbattle_single TRAINER_CONOR, CultoS3_Text_Medium4Intro, CultoS3_Text_Medium4Defeated
	msgbox CultoS3_Text_Medium4PostBattle, MSGBOX_AUTOCLOSE
	end



CultoS3_EventScript_Medium5::
	trainerbattle_single TRAINER_HUDSON, CultoS3_Text_Medium5Intro, CultoS3_Text_Medium5Defeated
	msgbox CultoS3_Text_Medium5PostBattle, MSGBOX_AUTOCLOSE
	end
