ViridianCity_House1_MapScripts::
	.byte 0

ViridianCityHouse1_1::
lock     
faceplayer     
msgbox ViridianCity_House1_Text_1, MSGBOX_DEFAULT
release     
end

ViridianCity_House1_Text_1:
.string "Ponerle motes a los Pokémon es\n"
.string "divertido, pero a veces no es\l"
.string "fácil.\l"
.string "Está bien poner motes elaborados,\l"
.string "pero los más simples son los más\l"
.string "fáciles de recordar.$"



ViridianCityHouse1_2::
lock     
faceplayer     
msgbox ViridianCity_House1_Text_2, MSGBOX_DEFAULT
release     
end

ViridianCity_House1_Text_2:
.string "A mi padre también le encantan los\n"
.string "Pokémon.$"



ViridianCityHouse1_3::
end
