BlackthornCity_Shop_MapScripts::
	.byte 0

BlackthornCityShop1::
end



BlackthornCityShop2::
lock     
faceplayer     
msgbox BlackthornCity_Shop_Text_2, MSGBOX_DEFAULT
release     
end

BlackthornCity_Shop_Text_2:
	.string "Oh… There's nothing like training a\n"
	.string "DRATINI from scratch. It's slow and\l"
	.string "costly, but seeing it grow little by\l"
	.string "little until it unlocks all that\l"
	.string "potential is priceless. That's how great\l"
	.string "POKÉMON are forged.$"



BlackthornCityShop3::
lock     
faceplayer     
msgbox BlackthornCity_Shop_Text_3, MSGBOX_DEFAULT
release     
end

BlackthornCity_Shop_Text_3:
	.string "Aren't LUGIA and HO-OH the strongest\n"
	.string "POKÉMON in JOHTO? Or is there a dragon\l"
	.string "that surpasses them? I should ask the\l"
	.string "DRAGON MASTER, he surely knows.$"



BlackthornCityShop4::
lock     
faceplayer     
msgbox BlackthornCity_Shop_Text_4, MSGBOX_DEFAULT
release     
end

BlackthornCity_Shop_Text_4:
	.string "I'm debating whether to descend into\n"
	.string "the southern gorge or not. It's been\l"
	.string "quite a journey to reach BLACKTHORN\l"
	.string "CITY, and I don't have any FLYING\l"
	.string "POKÉMON to return with…$"
