PalletTown_ProfessorLab_MapScripts::
	.byte 0

PalletTownProfessorLab1::
lock     
faceplayer     
msgbox PalletTown_ProfessorLab_Text_1, MSGBOX_DEFAULT
release     
end

PalletTown_ProfessorLab_Text_1:
.string "Los mejores entrenadores de la\n"
.string "región provienen de este lugar, la\l"
.string "curiosidad mató al gato chico,\l"
.string "espero que me hayas entendido.$"



PalletTownProfessorLab2::
lock     
faceplayer     
msgbox PalletTown_ProfessorLab_Text_2, MSGBOX_DEFAULT
release     
end

PalletTown_ProfessorLab_Text_2:
.string "¿Es que no ves que OAK no está\n"
.string "aquí?\l"
.string "¡Si sigues insistiendo llamaremos\l"
.string "a la POLICÍA!$"



PalletTownProfessorLab3::
lock     
faceplayer     
msgbox PalletTown_ProfessorLab_Text_3, MSGBOX_DEFAULT
release     
end

PalletTown_ProfessorLab_Text_3:
.string "Este lugar te queda muy grande, te\n"
.string "recomiendo largarte antes de que\l"
.string "el profesor decida acabar contigo.$"



PalletTownProfessorLabDocumento_100::
msgbox PalletTownProfessorLabDocumento_Text_100, MSGBOX_SIGN   
end

PalletTownProfessorLabDocumento_Text_100:
.string "¡Presiona Start para abrir el\n"
	.string "Menú!$"



PalletTownProfessorLabDocumento_101::
msgbox PalletTownProfessorLabDocumento_Text_101, MSGBOX_SIGN   
end

PalletTownProfessorLabDocumento_Text_101:
	.string "Todos los Pokémon cuentan con\n"
	.string "fortalezas y debilidades frente a\l"
	.string "otros.$"



PalletTownProfessorLabDocumento_102::
msgbox PalletTownProfessorLabDocumento_Text_102, MSGBOX_SIGN   
end

PalletTownProfessorLabDocumento_Text_102:
	.string "Hay un mensaje por e-mail abierto.\n"
	.string "...\l"
	.string "¡Por fin!\l"
	.string "¡Los mejores entrenadores de la\l"
	.string "LIGA POKÉMON están listos para\l"
	.string "derrotarlos a todos!\l"
	.string "¡Traed a vuestros mejores Pokémon\l"
	.string "y probaremos vuestra valía como\l"
	.string "entrenadores!\l"
	.string "CG de la LIGA POKÉMON.\l"
	.string "Prof.Oak, ¡visítenos por favor!$"
