Route27_MapScripts::
	.byte 0

Route27-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "La RUTA 26 ha sido abierta de\n"
.string "nuevo, pero ve con cuidado, los\l"
.string "POKÉMON salvajes tienen que\l"
.string "acostumbrarse a ver ENTRENADORES.$"



Route27-2::
end



Route27-3::
end



Route27-4::
end



Route27-5::
end



Route27-6::
end



Route27-7::
end



Route27-8::
end



Route27-9::
end



Route27-10::
end



Route27-11::
end
