CinnabarIsland_PokemonCenter_1F_MapScripts::
	.byte 0

CinnabarIslandPokemonCenter1::
end



CinnabarIslandPokemonCenter2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "A veces es conveniente no\n"
.string "evolucionar demasiado pronto a un\l"
.string "POKÉMON, ya que en sus formas\l"
.string "preevolucionadas aprenden antes\l"
.string "buenos movimientos, a veces\l"
.string "incluso movimientos que no pueden\l"
.string "aprender una vez evolucionados.$"



CinnabarIslandPokemonCenter3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Los ROCKET no sois bienvenidos\n"
.string "por aquí, nuestro LÍDER de\l"
.string "GIMNASIO nunca dejaría que este\l"
.string "lugar se infecte con vuestra\l"
.string "presencia.$"



CinnabarIslandPokemonCenter4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "Quería entrar en el GIMNASIO de\n"
.string "CANELA, pero la puerta está\l"
.string "cerrada a cal y canto.\l"
.string "Debe de haber una LLAVE en algún\l"
.string "sitio.\l"
.string "¿Estará en la MANSIÓN quemada esa?\l"
.string "Dicen que está habitada por un\l"
.string "amigo del LÍDER del GIMNASIO.$"
