BlackthornCity_DragonsdenHouse_MapScripts::
	.byte 0

DragonsdenHouse1::
end



DragonsdenHouse2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "[.]$"



DragonsdenHouse3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "[.]$"



DragonsdenHouse4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "[.]$"



DragonsdenHouse5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "[.]$"
