Goldenrod_ShopCenterP2_MapScripts::
	.byte 0

GoldenrodShopCenterP2-1::
end



GoldenrodShopCenterP2-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Ese niño mimado del piso de\n"
.string "abajo[.]\l"
.string "Todos los POKÉMON que tiene son\l"
.string "comprados[.]\l"
.string "Espero que pierda todos sus\l"
.string "combates por tenerlos a 0 en\l"
.string "puntos de esfuerzo[.]$"



GoldenrodShopCenterP2-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Nunca sabes lo que puedes\n"
.string "encontrarte cuando vas de compras.\l"
.string "¡Por eso me encanta estar aquí!$"
