FuchsiaCity_House3_MapScripts::
	.byte 0

FuchsiaCityHouse3_1::
end



FuchsiaCityHouse3_3::
lock
faceplayer
msgbox FuchsiaCityHouse3_3_Texto_1 MSGBOX_NPC
release
end

FuchsiaCityHouse3_3_Texto_1:
.string "Todo se basa en contactos, yo me llevo\n"
	.string "bien con el mismísimo OAK y le hago\l"
	.string "favores. El GURÚ de FUCSIA es famoso\l"
	.string "en todo el mundo gracias a mis\l"
	.string "influencias, el mundo funciona así. Los\l"
	.string "que no tienen nada que ofrecer, como\l"
	.string "tú, son borrados de la historia.$"



FuchsiaCityHouseDocumento_100::
msgbox FuchsiaCityHouseDocumento_Text_100, MSGBOX_SIGN   
end

FuchsiaCityHouseDocumento_Text_100:
.string "Fotos y fósiles de POKéMON.$"



FuchsiaCityHouseDocumento_101::
msgbox FuchsiaCityHouseDocumento_Text_101, MSGBOX_SIGN   
end

FuchsiaCityHouseDocumento_Text_101:
.string "¡Viejos objetos de los POKéMON!$"



FuchsiaCityHouseDocumento_102::
msgbox FuchsiaCityHouseDocumento_Text_102, MSGBOX_SIGN   
end

FuchsiaCityHouseDocumento_Text_102:
.string "POKéMON JOURNAL\p"
	.string "Special Feature: FUCHSIA GYM\n"
	.string "LEADER KOGA!\p"
	.string "KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"
