SsAnne_6F_MapScripts::
	.byte 0

SsAnne6F_1::
end



SsAnne6F_2::
end



SsAnne6F_3::
end



SsAnne6F_4::
end



SsAnne6F_5::
lock     
faceplayer     
msgbox SsAnne5F_Text_5, MSGBOX_DEFAULT
release     
end

SsAnne5F_Text_5:
.string "Soy de los que les gusta\n"
.string "presenciar esta clase de eventos\l"
.string "como un mero observador, puedes\l"
.string "saber más de una persona\l"
.string "observando su actitud en fiestas\l"
.string "así que hablando horas con ella.$"



SsAnne6F_6::
lock     
faceplayer     
msgbox SsAnne5F_Text_6, MSGBOX_DEFAULT
release     
end

SsAnne5F_Text_6:
.string "¡JAJAJA!\n"
.string "¡Camarero!\l"
.string "¡Otro licor de SHUCKLE!$"



SsAnne6F_7::
lock     
faceplayer     
msgbox SsAnne5F_Text_7, MSGBOX_DEFAULT
release     
end

SsAnne5F_Text_7:
.string "¡JA, JA!\n"
.string "¿Sabías por qué a la gente le\l"
.string "gusta tanto la fiesta?\l"
.string "…\l"
.string "¡Porque por unas horas les\l"
.string "evade de todos los problemas y\l"
.string "carencias que sus míseras vidas\l"
.string "tienen!\l"
.string "¡JA!\l"
.string "¡Camarero, otro licor de SHUCKLE!$"



SsAnne6F_8::
lock     
faceplayer     
msgbox SsAnne5F_Text_8, MSGBOX_DEFAULT
release     
end

SsAnne5F_Text_8:
.string "Entonces después de tanto esfuerzo\n"
.string "y disciplina se suponía que este\l"
.string "era el premio final, irónicamente\l"
.string "he sido más dichoso entrenando\l"
.string "para llegar aquí que una vez\l"
.string "llegado aquí.\l"
.string "¡Los viernes siempre decepcionan\l"
.string "chico!$"



SsAnne6F_9::
lock     
faceplayer     
msgbox SsAnne5F_Text_9, MSGBOX_DEFAULT
release     
end

SsAnne5F_Text_9:
.string "Todo iba perfecto hasta que\n"
.string "apareció esa parejita con sus\l"
.string "ñoñerías, ¡me han estropeado el\l"
.string "paisaje!$"



SsAnne6F_10::
lock     
faceplayer     
msgbox SsAnne5F_Text_10, MSGBOX_DEFAULT
release     
end

SsAnne5F_Text_10:
.string "Puafff…\n"
.string "Ni se te ocurra aceptar el licor\l"
.string "extraño que sirve ese camarero de\l"
.string "ahí, creo que voy a vomitar…$"



SsAnne6F_11::
lock     
faceplayer     
msgbox SsAnne5F_Text_11, MSGBOX_DEFAULT
release     
end

SsAnne5F_Text_11:
.string "La incertidumbre del momento,\n"
.string "dejarse llevar por la intuición…\l"
.string "Aún no logro comprender cuál es la\l"
.string "esencia última que me proporcione\l"
.string "la fórmula exacta para exprimir al\l"
.string "máximo eventos así…$"



SsAnne6F_12::
end



SsAnne6F_13::
end
