Route25_MapScripts::
	.byte 0

Route25_1::
lock     
faceplayer     
msgbox Route25_Text_1, MSGBOX_DEFAULT
release     
end

Route25_Text_1:
.string "Este cabo es un buen lugar para\n"
.string "venir en pareja.\l"
.string "MISTY, nuestra LÍDER DE GIMNASIO,\l"
.string "suele pasarse por aquí.$"


Route25_2::
lock     
faceplayer     
msgbox Route25_Text_2, MSGBOX_DEFAULT
release     
end

Route25_Text_2:
.string "¿Cómo?\n"
.string "¿Vienes solo al CABO CELESTE?\l"
.string "…\l"
.string "…\l"
.string "Bueno, se supone que a este lugar\l"
.string "se viene en pareja…$"


Route25_3::
end

Route25_4::
end


Route25_5::
end

Route25_6::
end

Route25_7::
end

Route25_8::
end

Route25_9::
end

Route25_10::
end

Route25_11::
end

Route25_12::
end

Route25_13::
end
