FourIsland_Mart_MapScripts::
	.byte 0

FourIslandMart1::
end



FourIslandMart2::
lock     
faceplayer     
msgbox FourIsland_Mart_Text_2, MSGBOX_DEFAULT
release     
end

FourIsland_Mart_Text_2:
.string "We've had a great and powerful\n"
    .string "TRAINER grow up on this island.\p"
    .string "I bet even you'd know her.\n"
    .string "It's LORELEI of the ELITE FOUR!\p"
    .string "When LORELEI was just a tyke,\n"
    .string "I taught her about POKÉMON.$"



FourIslandMart3::
lock     
faceplayer     
msgbox FourIsland_Mart_Text_3, MSGBOX_DEFAULT
release     
end

FourIsland_Mart_Text_3:
.string "The SEVII ISLANDS are in a warm\n"
    .string "region overall.\p"
    .string "But there is one exception you\n"
    .string "need to know about.\p"
    .string "The ICEFALL CAVE is frigid because\n"
    .string "of the POKÉMON that live in it.$"
