Ecruteak_House2_MapScripts::
	.byte 0

EcruteakHouse2-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Sucedió cuando era joven.\n"
.string "El cielo se oscureció de repente.\l"
.string "Un enorme POKÉMON estaba tapando\l"
.string "el sol.\l"
.string "Me pregunto qué sería ese POKÉMON,\l"
.string "mezcla de pájaro y dragón.$"



EcruteakHouse2-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "¿Existe un POKÉMON tan grande?\n"
.string "Si existe, debe de ser muy fuerte.$"
