Route53_MapScripts::
	.byte 0

Route53-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "AZAFRÁN está absurdamente lejos,\n"
.string "la peor parte será cuando tengamos\l"
.string "que atravesar las montañas de RUTA\l"
.string "26 y 27.$"



Route53-2::
end



Route53-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "No es muy común ver a gente de tu\n"
.string "estatus bajar a la arena para\l"
.string "mancharse los pantalones como uno\l"
.string "más.\l"
.string "¡Esa es la actitud!$"



Route53-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "El MAGNETOTREN supondrá un antes y\n"
.string "un después en la conversión de\l"
.string "JOHTO en potencia tecnológica,\l"
.string "pero para que ocurra, gente\l"
.string "como yo tiene que pringar bajo\l"
.string "este sol abrasador.\l"
.string "¡Todo tiene un precio!$"



Route53-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "¡Que TRIGAL y AZAFRÁN acaben\n"
.string "unidas por el MAGNETOTREN es\l"
.string "inevitable!\l"
.string "¡En dos años todo estará\l"
.string "dispuesto!$"



Route53-6::
end



Route53-7::
end



Route53-8::
end



Route53-9::
end
