Azalea_PkmnCenter_MapScripts::
	.byte 0

AzaleaPkmnCenter1::
end



AzaleaPkmnCenter2::
lock     
faceplayer     
msgbox AzaleaPkmnCenter_Text_2, MSGBOX_DEFAULT
release     
end

AzaleaPkmnCenter_Text_2:
.string "CÉSAR no quiere reconocerlo, pero\n"
.string "es con diferencia el mayor\l"
.string "especialista del TIPO BICHO que\l"
.string "hay en JOHTO. A diferencia de ese\l"
.string "jóven ANTÓN, prefiere mantener sus\l"
.string "dotes como ENTRENADOR en el\l"
.string "anonimato.$"



AzaleaPkmnCenter3::
lock     
faceplayer     
msgbox AzaleaPkmnCenter_Text_3, MSGBOX_DEFAULT
release     
end

AzaleaPkmnCenter_Text_3:
.string "Algún día, KANTO y JOHTO volverán a\n"
.string "estar unidas.\l"
.string "¡Se verá!$"



AzaleaPkmnCenter4::
end
