WaterPath_MapScripts::
	.byte 0

WatherPath1::
end


WatherPath2::
end


WatherPath3::
end


WatherPath4::
end


WatherPath5::
end


WatherPath6::
end


WatherPath7::
end


WatherPath8::
end


WatherPath9::
end


WatherPath10::
lock     
faceplayer     
msgbox Text_9, MSGBOX_DEFAULT
release     
end

Text_9:
.string "¡Buen día camarada!\n"
.string "ATLAS ya nos ha informado de\l"
.string "vuestra misión en CASA CÓNSUL, tu\l"
.string "compañera ya está dentro al\l"
.string "parecer, deberías de entrar cuanto\l"
.string "antes a ayudarla.$"



WatherPath11::
lock     
faceplayer     
msgbox Text_11, MSGBOX_DEFAULT
release     
end

Text_11:
.string "DONPHAN es del tipo TIERRA puro,\n"
.string "por ello parte con ventaja al\l"
.string "enfrentar a los ROCA y TIERRA dual\l"
.string "clásicos, además es tan rudo como\l"
.string "el que más con 120 de base tanto\l"
.string "en DEFENSA como ATAQUE.$"
