Route49_MazeP2_MapScripts::
	.byte 0

Route49_MazeP2_2::
lock     
faceplayer     
msgbox Route49_MazeP2_Text2, MSGBOX_DEFAULT
release     
end

Route49_MazeP2_Text2:
.string "La emoción decide, y la razón justifica.\n"
.string "¡Crees que fue obra de tu voluntad y no\l"
.string "es más que una ilusión!$"



Route49_MazeP2_3::
lock     
faceplayer     
msgbox Route49_MazeP2_Text3, MSGBOX_DEFAULT
release     
end

Route49_MazeP2_Text3:
.string "Agota más hacer el esfuerzo para dejar\n"
.string "de hacer algo que estabas haciendo que\l"
.string "seguir haciendo algo que ya estabas\l"
.string "haciendo.$"



Route49_MazeP2_4::
lock     
faceplayer     
msgbox Route49_MazeP2_Text4, MSGBOX_DEFAULT
release     
end

Route49_MazeP2_Text4:
.string "Bajo el pretexto de la igualdad, los\n"
.string "esclavos se agrupan en comunas de\l"
.string "poder para arrastrar a los superiores\l"
.string "hacia la mediocridad.$"



Route49_MazeP2_6::
lock     
faceplayer     
msgbox Route49_MazeP2_Text6, MSGBOX_DEFAULT
release     
end

Route49_MazeP2_Text6:
.string "Hace tiempo que perdimos todo contacto\n"
.string "con el resto de JOHTO. Incluso con las\l"
.string "otras dos pagodas. Antes, esta era\l"
.string "considerada la primera de las 4 pagodas\l"
.string "de la región, cuando TORRE LATÓN aún\l"
.string "estaba en pie.$"
