NeoLavandaCasa1_MapScripts::
	.byte 0

NeoLavandaCasa1_1::
lock     
faceplayer     
msgbox NeoLavandaCasa1_Text_1, MSGBOX_DEFAULT
release     
end

NeoLavandaCasa1_Text_1:
.string "Algunas personas son tan crueles que\n"
.string "abandonan a su POKÉMON. El abuelo\l"
.string "recoge aquellos que no tienen hogar y\l"
.string "los cuida.$"



NeoLavandaCasa1_2::
lock     
faceplayer     
msgbox NeoLavandaCasa1_Text_2, MSGBOX_DEFAULT
release     
end

NeoLavandaCasa1_Text_2:
.string "El SR.FUJI vive aquí, pero ahora no está\n"
.string "en casa. Debe de estar en el\l"
.string "CEMENTERIO.$"
