Olivine_Boat2_MapScripts::
	.byte 0

OlivineBoat2-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "¿Podemos dejar de hablar del TIPO\n"
.string "LUCHA aunque sea por un momento?\l"
.string "¿Has visto a WEEZING?\l"
.string "Con esa DEFENSA aguanta todos\l"
.string "vuestros golpes.$"



OlivineBoat2-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Dijeron que ANÍBAL iba a asistir a\n"
.string "la fiesta. Lo sabía, seguro que\l"
.string "está entrenando.$"



OlivineBoat2-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "¿La ACADEMIA de PETRA?\n"
.string "¡Qué aburrimiento!\l"
.string "¡Prefiero que los científicos de\l"
.string "SILPH me den clases!\l"
.string "¡Ellos sí que saben de POKÉMON\l"
.string "fuertes y de cómo manipularlos!\l"
.string "¡Mira ese BILL!$"



OlivineBoat2-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "Hace 50 años, en esta ciudad no\n"
.string "había más de 4 o 5 familias de\l"
.string "humildes pescadores. Míranos\l"
.string "ahora.$"



OlivineBoat2-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "Cómo ha cambiado CIUDAD OLIVO. Y\n"
.string "lo que nos queda por ver, ¿verdad,\l"
.string "querida?$"



OlivineBoat2-6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "¿Has oído?\n"
.string "En un par de meses, la línea\l"
.string "OLIVO-PORTUAL estará lista. Irás\l"
.string "a CIUDAD FÉRRICA a estudiar en la\l"
.string "ACADEMIA de PETRA.$"



OlivineBoat2-7::
lock     
faceplayer     
msgbox Text_7, MSGBOX_DEFAULT
release     
end

Text_7:
.string "¿Conoces las ISLAS REMOLINO?\n"
.string "Los barcos evitan acercarse a\l"
.string "ellas, no solo por todas las rocas\l"
.string "que sobresalen la superficie,\l"
.string "también por las fuertes mareas que\l"
.string "las rodean.$"



OlivineBoat2-8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "El CAPITÁN está en el acto que\n"
.string "inaugura la ampliación del PUERTO\l"
.string "a otras regiones. Hasta que no\l"
.string "regrese nadie puede entrar a su\l"
.string "camarote.$"



OlivineBoat2-9::
end



OlivineBoat2-10::
lock     
faceplayer     
msgbox Text_10, MSGBOX_DEFAULT
release     
end

Text_10:
.string "Sí que hay acuerdo, aunque tú no\n"
.string "te beneficiarás de él. Yo siempre\l"
.string "gano, de un modo u otro.\l"
.string "[.]\l"
.string "[.]\l"
.string "Oh, perdona, creí que eras otra\l"
.string "persona.$"



OlivineBoat2-11::
end



OlivineBoat2-12::
lock     
faceplayer     
msgbox Text_12, MSGBOX_DEFAULT
release     
end

Text_12:
.string "Después de CIUDAD CARMÍN,\n"
.string "estableceremos la conexión con\l"
.string "CIUDAD PORTUAL, en HOENN. NORMAN y\l"
.string "su familia se mudarán allí en\l"
.string "cuanto esté disponible la línea.$"



OlivineBoat2-13::
lock     
faceplayer     
msgbox Text_13, MSGBOX_DEFAULT
release     
end

Text_13:
.string "Lo sé, un CAZABICHOS como yo no\n"
.string "pinta nada en una fiesta como\l"
.string "esta. Solo vine porque corren\l"
.string "rumores de que el CAPITÁN cuenta\l"
.string "con un TIPO BICHO extremadamente\l"
.string "fuerte y raro en su equipo. ¿Algún\l"
.string "problema?$"



OlivineBoat2-14::
end
