Goldenrod_RadioTowerP8_MapScripts::
	.byte 0

Goldenrod_RadioTowerP8_NPC2::
lock
msgbox Goldenrod_RadioTowerP8_NPC2_Texto_1 MSGBOX_NPC
release
end

Goldenrod_RadioTowerP8_NPC2_Texto_1:
	.string "La gente solía llevar ropa normal entre\n"
	.string "semana y atuendo formal los domingos.\l"
	.string "Hoy sucede exactamente lo contrario.$"

Goldenrod_RadioTowerP8_NPC3::
lock
msgbox Goldenrod_RadioTowerP8_NPC3_Texto_1 MSGBOX_NPC
delay 10
msgbox Goldenrod_RadioTowerP8_NPC3_Texto_2 MSGBOX_NPC
release
end

Goldenrod_RadioTowerP8_NPC3_Texto_1:
	.string "Reté a esa chica pelirroja; me\n"
	.string "sorprendió ver que alguien tan joven\l"
	.string "formaba parte de los de arriba.$"

Goldenrod_RadioTowerP8_NPC3_Texto_2:
	.string "Al pelear con ella lo comprendí, se me\n"
	.string "han quitado las ganas de retar a nadie\l"
	.string "más…$"

Goldenrod_RadioTowerP8_NPC4::
lock
msgbox Goldenrod_RadioTowerP8_NPC4_Texto_1 MSGBOX_NPC
delay 10
msgbox Goldenrod_RadioTowerP8_NPC4_Texto_2 MSGBOX_NPC
delay 10
msgbox Goldenrod_RadioTowerP8_NPC4_Texto_3 MSGBOX_NPC
delay 10
msgbox Goldenrod_RadioTowerP8_NPC4_Texto_4 MSGBOX_NPC
release
end

Goldenrod_RadioTowerP8_NPC4_Texto_1:
	.string "Estamos estudiando la viabilidad de un\n"
	.string "lejano POKÉMON para reforzar la\l"
	.string "seguridad. Puedo darte un pequeño\l"
	.string "ejemplar de muestra. Toma.$"

Goldenrod_RadioTowerP8_NPC4_Texto_2:
.string "¡OBTUVISTE UN LILLIPUP AL NV.15!$"

Goldenrod_RadioTowerP8_NPC4_Texto_3:
	.string "Se ha demostrado que STOUTLAND es un\n"
	.string "fantástico POKÉMON para nuestros\l"
	.string "policías, el problema es que solemos ser\l"
	.string "reticentes a lo nuevo.$"

Goldenrod_RadioTowerP8_NPC4_Texto_4:
	.string "POKÉMON como MANECTRIC o ARCANINE son\n"
	.string "más fáciles de integrar en JOHTO debido\l"
	.string "a la cercanía con esas regiones.$"

Goldenrod_RadioTowerP8_NPC5::
lock
msgbox Goldenrod_RadioTowerP8_NPC5_Texto_1 MSGBOX_NPC
delay 10
msgbox Goldenrod_RadioTowerP8_NPC5_Texto_2 MSGBOX_NPC
delay 10
msgbox Goldenrod_RadioTowerP8_NPC5_Texto_3 MSGBOX_NPC
release
end

Goldenrod_RadioTowerP8_NPC5_Texto_1:
	.string "Estás en el Piso 7. Aquí nos encargamos\n"
	.string "de optimizar el rendimiento de las ondas\l"
	.string "de radio.$"

Goldenrod_RadioTowerP8_NPC5_Texto_2:
	.string "Puedes ver en los letreros la función\n"
	.string "destinada a cada piso.$"

Goldenrod_RadioTowerP8_NPC5_Texto_3:
	.string "Gracias a nuestras investigaciones,\n"
	.string "directivos poderosos y trajeados como\l"
	.string "tú podrán tener POKÉMON cada vez más\l"
	.string "fuertes solo con apretar un botón, ¿no\l"
	.string "es genial?$"

