Route10_MapScripts::
	.byte 0

Route10-1::
end



Route10-2::
end


Route10-3::
end


Route10-4::
end


Route10-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "¿Tienes idea de lo que dices?\n"
.string "¡No hay ningún KANGASKHAN en este\l"
.string "lugar!\l"
.string "¿Sabes lo que ello implicaría?\l"
.string "¡La ZONA SAFARI cerraría, y no\l"
.string "solo eso, la gente se pondría a\l"
.string "investigar de dónde ha salido, un\l"
.string "POKÉMON así no sale de la nada!$"



Route10-6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "¡Te digo que he visto un\n"
.string "KANGASKHAN aquí dentro!$"


Route10-7::
lock     
faceplayer     
msgbox Text_7, MSGBOX_DEFAULT
release     
end

Text_7:
.string "La CENTRAL ENERGÍA ha sido\n"
.string "considerada patrimonio de nuestra\l"
.string "región, a partir de ahora será\l"
.string "protegida por las fuerzas del\l"
.string "orden y no estará abierta a la\l"
.string "exploración. Más te vale no\l"
.string "intentar ninguna estupidez, o el\l"
.string "peso de la justicia se cernirá\l"
.string "sobre ti.$"



Route10-8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "La CENTRAL ENERGÍA ha sido\n"
.string "considerada patrimonio de nuestra\l"
.string "región, a partir de ahora será\l"
.string "protegida por las fuerzas del\l"
.string "orden y no estará abierta a la\l"
.string "exploración. Más te vale no\l"
.string "intentar ninguna estupidez, o el\l"
.string "peso de la justicia se cernirá\l"
.string "sobre ti.$"


Route10-9::
end


Route10-10::
end


Route10-11::
end


Route10-12::
end


Route10-13::
end
