RockTunnel_1F_MapScripts::
	.byte 0

RockTunnel1F-1::
end



RockTunnel1F-2::
end



RockTunnel1F-3::
end



RockTunnel1F-4::
end



RockTunnel1F-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "La rareza de KANGASKHAN está a la\n"
.string "altura de los FÓSILES DOMO y\l"
.string "HELIX, DRATINI o el extinto\l"
.string "AERODACTYL, los de la ZONA SAFARI\l"
.string "producen tan pocos que atrapar uno\l"
.string "allí es casi imposible, ¡un\l"
.string "POKEMANÍACO que se precie no puede\l"
.string "dejar pasar esta oportunidad!$"



RockTunnel1F-6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "Ese KANGASKHAN va a ser nuestro,\n"
.string "ningún ENTRENADOR GUAY será tan\l"
.string "guay como nosotros después de\l"
.string "atrapar a esa rareza.$"



RockTunnel1F-7::
end



RockTunnel1F-8::
end



RockTunnel1F-9::
end



RockTunnel1F-10::
end



RockTunnel1F-11::
end



RockTunnel1F-12::
end



RockTunnel1F-13::
end
