Goldenrod_RadioTower_MapScripts::
	.byte 0

RadioTower-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Bienvenido a TORRE RADIO\n"
.string "caballero. La LOTERÍA POKÉMON aún\l"
.string "no está disponible.$"



RadioTower-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Bienvenido a TORRE RADIO\n"
.string "caballero. La LOTERÍA POKÉMON aún\l"
.string "no está disponible.$"



RadioTower-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "La TORRE RADIO es grande, pero es\n"
.string "difícil perderse en ella, todo\l"
.string "está muy bien organizado.$"



RadioTower-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "SILPH no ha tenido ningún problema\n"
.string "en proporcionarnos una legión de\l"
.string "GROWLITHE para nuestras unidades.\l"
.string "Gestos como ese ayudan mucho a\l"
.string "devolver la confianza entre\l"
.string "regiones.$"



RadioTower-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "Hemos aprendido de lo que le\n"
.string "ocurrió a SILPH. Un asalto como el\l"
.string "que se dió allí no se dará en un\l"
.string "lugar como éste.\l"
.string "¡Y menos a manos de esos ROCKET!$"



RadioTower-6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "¿Has oído hablar de la ZONA\n"
.string "SAFARI?\l"
.string "Es genial, pero al parecer quieren\l"
.string "cerrarla pronto.$"



RadioTower-7::
lock     
faceplayer     
msgbox Text_7, MSGBOX_DEFAULT
release     
end

Text_7:
.string "Los programas de radio[.]\n"
.string "La HORA POKÉMON[.]\l"
.string "Las canciones de no sé qué DJ[.]\l"
.string "Todo eso es pura fachada, créeme.\l"
.string "En este edificio se trata con\l"
.string "cosas mucho más importantes que\l"
.string "todas esas ñoñerías que no sirven\l"
.string "para nada.$"



RadioTower-8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "Las acciones de TORRE RADIO\n"
.string "subirán exponencialmente en los\l"
.string "próximos dos años, créeme.\l"
.string "¡Invierte en ellas!$"



RadioTower-9::
lock     
faceplayer     
msgbox Text_9, MSGBOX_DEFAULT
release     
end

Text_9:
.string "Dicen que en KANTO hay una TIENDA\n"
.string "DE BICIS que las vende a 1 MILLÓN\l"
.string "de POKÉS.\l"
.string "Me gustaría ir allí a comprarme\l"
.string "una, eso me distinguiría de los\l"
.string "demás.$"



RadioTower-11::
lock     
faceplayer     
msgbox Text_11, MSGBOX_DEFAULT
release     
end

Text_11:
.string "A pesar de que JOHTO ganó la\n"
.string "guerra, KANTO está\l"
.string "tecnológicamente más desarrollada.\l"
.string "Este edificio es un claro ejemplo\l"
.string "de ello, pues imita gran parte de\l"
.string "la estética y recursos con los que\l"
.string "cuenta el mayor símbolo financiero\l"
.string "de KANTO: SILPH.$"
