SaffronCity_House1_1F_MapScripts::
	.byte 0

SaffronCityHouse11F_1::
lock     
faceplayer     
msgbox SafariZone_House11F_Text_1, MSGBOX_DEFAULT
release     
end

SafariZone_House11F_Text_1:
	.string "Meine Tochter ahmt gerne Leute nach.\p"
	.string "Wegen ihres Mienenspiels nennt man sie\n"
	.string "die NACHAHMERIN!$"



SaffronCityHouse11F_2::
lock     
faceplayer     
msgbox SafariZone_House11F_Text_2, MSGBOX_DEFAULT
release     
end

SafariZone_House11F_Text_2:
	.string "Meine Tochter ist furchtbar\n"
	.string "schüchtern! Sie hat nur wenige Freunde!$"



SaffronCityHouse11F_3::
end
