SaffronCity_House1_1F_MapScripts::
	.byte 0

SaffronCityHouse11F-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "A mi hija le gusta imitar a la\n"
.string "gente.\p"
.string "¡Y por eso la gente de por aquí\n"
.string "le llama la COPIONA!$"



SaffronCityHouse11F-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "¡Mi hija está tan metida en sí\n"
.string "misma que tiene muy pocos amigos!$"



SaffronCityHouse11F-3::
end
