PokemonTower_5F_MapScripts::
	.byte 0

PokemonTower5F-1::
end



PokemonTower5F-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Todas las almas pueden ser\n"
.string "reconducidas.\l"
.string "Descansa aquí ROCKET y tal vez eso\l"
.string "te haga recapacitar sobre tus\l"
.string "actos pecaminosos.$"



PokemonTower5F-3::
end



PokemonTower5F-4::
end



PokemonTower5F-5::
end



PokemonTower5F-6::
end



PokemonTower5F-7::
end
