SafariZone_House3_MapScripts::
	.byte 0

SafariZoneHouse3-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Dirígete al ZONA más profunda del\n"
.string "SAFARI. ¡Ganarás un premio!$"



SafariZoneHouse3-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "La ZONA del SAFARI es gigante,\n"
.string "¿no te parece?\p"
.string "El LÍDER del GIMNASIO de FUCSIA,\n"
.string "KOGA, viene con mucha frecuencia\l"
.string "por esta zona.\p"
.string "Gracias a él, podemos jugar aquí\n"
.string "sin miedo.$"



SafariZoneHouse3-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Puedes quedarte con cualquier\n"
.string "objeto encontrado en esta zona.\p"
.string "¡Pero te quedarás sin tiempo si\n"
.string "intentas coger todos a la vez!$"



SafariZoneHouse3-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "¡Mi EEVEE evolucionó y\n"
.string "se transformó en un FLAREON!\p"
.string "¡Pero el EEVEE de un amigo se\n"
.string "transformó en un VAPOREON!\l"
.string "¿Por qué?$"
