Route31_MapScripts::
	.byte 0

Route31-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "El acceso a la cueva en estos\n"
.string "momentos está cortado, ha habido\l"
.string "un pequeño desprendimiento en su\l"
.string "interior y estamos asegurándonos\l"
.string "de que está todo en orden.\l"
.string "Disculpe las molestias.$"



Route31-2::
end



Route31-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Tú no eres de por aquí, ¿verdad?\n"
.string "¿Vienes de CIUDAD OLIVO?\l"
.string "¿¡KANTO!?\l"
.string "¡¿Cómo hiciste para pasar las\l"
.string "fronteras?!$"



Route31-4::
end



Route31-5::
end



Route31-6::
end



Route31-7::
end



Route31-8::
end



Route31-9::
end



Route31-10::
lock     
faceplayer     
msgbox Text_10, MSGBOX_DEFAULT
release     
end

Text_10:
.string "Al oeste está CIUDAD MALVA,\n"
.string "conocida por su TORRE BELLSPROUT,\l"
.string "el lugar más antiguo y espiritual\l"
.string "de JOHTO, después, claro, de las\l"
.string "enormes pagodas de CIUDAD IRIS.$"



Route31-11::
end
