MahoganyTown_NinjaBaseS3_MapScripts::
	.byte 0

NinjaBaseS3-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Dicen que FREDO cuenta con una\n"
.string "forma única de ARTICUNO, su forma\l"
.string "primigenia por así decirlo.\l"
.string "¿Existirán sus equivalentes para\l"
.string "ZAPDOS y MOLTRES?$"



NinjaBaseS3-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "Si te digo la verdad[.]\n"
.string "No entiendo nada de estos planos[.]$"



NinjaBaseS3-3::
end



NinjaBaseS3-4::
end



NinjaBaseS3-5::
end



NinjaBaseS3-7::
end



NinjaBaseS3-8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "El progreso en cuanto STATS BASE\n"
.string "de los POKÉMON en el último medio\l"
.string "año ha sido espectacular.\l"
.string "¿Crees que POKÉMON como NIDOKING o\l"
.string "NIDOQUEEN dejarán de ser\l"
.string "considerados fuertes después de\l"
.string "elevar tanto el estándar?$"



NinjaBaseS3-9::
lock     
faceplayer     
msgbox Text_9, MSGBOX_DEFAULT
release     
end

Text_9:
.string "Nadie es tan poderoso como el TEAM\n"
.string "ROCKET.\l"
.string "Tres bases en KANTO, dos bases en\l"
.string "JOHTO, una en HOENN, ¡y otra en\l"
.string "ISLAS SETE!\l"
.string "¡Somos omnipresentes!$"



NinjaBaseS3-10::
end



NinjaBaseS3-11::
end



NinjaBaseS3-12::
end



NinjaBaseS3-15::
end
