Olivine_Lighthouse_MapScripts::
	.byte 0

OliivineLighthouse1::
end



OliivineLighthouse2::
end



OliivineLighthouse3::
end



OliivineLighthouse4::
lock     
faceplayer     
msgbox OlivineCity_LightHouse_Text_4, MSGBOX_DEFAULT
release     
end

OlivineCity_LightHouse_Text_4:
.string "Los CHINCHOU fueron los primeros\n"
.string "POKÉMON en servir como guía a los\l"
.string "marineros. Este FARO se construyó\l"
.string "en honor a ellos.$"



OliivineLighthouse5::
end



OliivineLighthouse6::
lock     
faceplayer     
msgbox OlivineCity_LightHouse_Text_6, MSGBOX_DEFAULT
release     
end

OlivineCity_LightHouse_Text_6:
.string "NOCTOWL es un POKÉMON común entre\n"
.string "los marineros de JOHTO, su gran\l"
.string "sentido de la orientación y visión\l"
.string "nocturna nos es de gran ayuda.$"



OliivineLighthouse7::
end



OliivineLighthouse8::
end



OliivineLighthouse9::
lock     
faceplayer     
msgbox OlivineCity_LightHouse_Text_9, MSGBOX_DEFAULT
release     
end

OlivineCity_LightHouse_Text_9:
.string "Me encantaría poder ver en persona\n"
.string "al poderoso POKÉMON que ilumina el\l"
.string "FARO, pero no sé cómo subir hasta\l"
.string "arriba…$"



OliivineLighthouse10::
end



OliivineLighthouse11::
end



OliivineLighthouse12::
end



OliivineLighthouse13::
lock     
faceplayer     
msgbox OlivineCity_LightHouse_Text_13, MSGBOX_DEFAULT
release     
end

OlivineCity_LightHouse_Text_13:
.string "La ruta marítima OLIVO-TRIGAL\n"
.string "está llena de rocas, lo que\l"
.string "la hace innavegable. Si no, hace\l"
.string "tiempo que TRIGAL hubiera\l"
.string "dispuesto un enorme puerto para\l"
.string "ampliar aún más sus\l"
.string "conexiones.$"



OliivineLighthouse14::
end



OliivineLighthouse15::
end



OliivineLighthouse16::
end



OliivineLighthouse17::
end



OliivineLighthouse18::
end



OliivineLighthouse19::
end



OliivineLighthouse20::
end
