LakeofRage_MapScripts::
	.byte 0

LakeofRage2::
end



LakeofRage4::
end



LakeofRage6::
end



LakeofRage8::
lock     
faceplayer     
msgbox LakeofRage_Text_8, MSGBOX_DEFAULT
release     
end

LakeofRage_Text_8:
.string "Ese GURÚ de KANTO, que vive en\n"
.string "FUCSIA, lo único que hizo fue\l"
.string "capturar 3 GYARADOS aquí, cuando\l"
.string "había a montones, y mudarse a otra\l"
.string "región donde escasean. Ahora vive\l"
.string "de la fama que esos 3 GYARADOS le\l"
.string "dieron.$"



LakeofRage9::
lock     
faceplayer     
msgbox LakeofRage_Text_9, MSGBOX_DEFAULT
release     
end

LakeofRage_Text_9:
.string "¿AGUA/VOLADOR GYARADOS?\n"
.string "¿En qué mundo vives?\l"
.string "¡Como si GYARADOS pudiera volar!$"



LakeofRage10::
end



LakeofRage11::
end



LakeofRage12::
end



LakeofRage13::
end



LakeofRage14::
end



LakeofRage15::
end
