SunyshoreCity_MapScripts::
	.byte 0


Marina_Cartel::
lock
msgbox Marina_Cartel_Texto_1, MSGBOX_SIGN
release
end

Marina_Cartel_Texto_1:
	.string "CIUDAD MARINA\n"
	.string "¡Con energía solar!$"


Marina_Publicidad::
lock
msgbox Marina_Publicidad_Texto_1, MSGBOX_SIGN
release
end

Marina_Publicidad_Texto_1:
	.string "Espacio disponible…\n"
	.string "¡Inserte aquí su publicidad!$"


Marina_Faro::
lock
msgbox Marina_Faro_Texto_1, MSGBOX_SIGN
release
end

Marina_Faro_Texto_1:
	.string "FARO VISIÓN\n"
	.string "La luz que ilumina SINNOH$"


Marina_Mercado::
lock
msgbox Marina_Mercado_Texto_1, MSGBOX_SIGN
release
end

Marina_Mercado_Texto_1:
	.string "MERCADO MARINO\n"
	.string "¡Gran variedad de sellos del mundo!$"


Marina_Cintas::
lock
msgbox Marina_Cintas_Texto_1, MSGBOX_SIGN
release
end

Marina_Cintas_Texto_1:
	.string "Casa de OLGA\n"
	.string "Hermosas CINTAS para POKÉMON$"


Marina_Roca::
lock
msgbox Marina_Roca_Texto_1, MSGBOX_SIGN
release
end

Marina_Roca_Texto_1:
	.string "Roca POKÉMON\n"
	.string "Legado cultural de CIUDAD MARINA$"


Marina_Gimnasio::
lock
msgbox Marina_Gimnasio_Texto_1, MSGBOX_SIGN
release
end

Marina_Gimnasio_Texto_1:
	.string "GIMNASIO POKÉMON de CIUDAD MARINA\n"
	.string "LÍDER: LECTRO\l"
	.string "La estrella brillante e impactante$"


Marina_Primer_NPC::
lock     
faceplayer     
msgbox Marina_Primer_NPC_Texto_1, MSGBOX_NPC
release     
end

Marina_Primer_NPC_Texto_1:
.string "Esta es una importante ciudad\n"
.string "costera y…\p"
.string "la antesala de la LIGA\n"
.string "POKÉMON.$"


Marina_Segundo_NPC::
lock     
faceplayer     
msgbox Marina_Segundo_NPC_Texto_1, MSGBOX_NPC
release     
end

Marina_Segundo_NPC_Texto_1:
.string "La ciudad usa mucha electricidad,\n"
.string "sobre todo el FARO y el GIMNASIO.\p"
.string "Por eso se decidió convertir parte de\n"
.string "las calles de la ciudad en paneles\n"
.string "solares gigantes.\p"
.string "CIUDAD MARINA es muy soleada, así que\n"
.string "el sistema funciona perfectamente.$"


Marina_Tercer_NPC::
lock     
faceplayer     
msgbox Marina_Tercer_NPC_Texto_1, MSGBOX_NPC
release     
end

Marina_Tercer_NPC_Texto_1:
.string "Las personas y los POKÉMON se\n"
.string "adaptan a cualquier entorno.\p"
.string "Todos lo hacemos para sobrevivir.$"


Marina_Cuarto_NPC::
lock     
faceplayer     
msgbox Marina_Cuarto_NPC_Texto_1, MSGBOX_NPC
release     
end

Marina_Cuarto_NPC_Texto_1:
.string "Esa roca gigante…\n"
.string "¿No es un POKÉMON en realidad?$"


Marina_Quinto_NPC::
lock     
faceplayer     
msgbox Marina_Quinto_NPC_Texto_1, MSGBOX_NPC
release     
end

Marina_Quinto_NPC_Texto_1:
.string "¡El LÍDER del GIMNASIO utiliza\n"
.string "demasiada electricidad!\p"
.string "¡Tiene que pensar también en\n"
.string "las necesidades de la ciudad!$"
