LagoFuria5_MapScripts::
	.byte 0

EventoLagoFuria5_Combate_Final::
msgbox EventoLagoFuria5_Combate_Final_Texto_1 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_2 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_3 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_4 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_5 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_6 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_7 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_8 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_9 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_10 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_11 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_12 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_13 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_14 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_15 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_16 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_17 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_18 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_19 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_20 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_21 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_22 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_23 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_24 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_25 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_26 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_27 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_28 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_29 MSGBOX_AUTOCLOSE
msgbox EventoLagoFuria5_Combate_Final_Texto_30 MSGBOX_AUTOCLOSE
release
end

EventoLagoFuria5_Combate_Final_Texto_1:
.string "PESCADOR: Te lo dije, aquí no hay nada.$"

EventoLagoFuria5_Combate_Final_Texto_2:
.string "????: No, debe de estar aquí, este es el\n"
	.string "fin de la caverna subterránea. La\l"
	.string "pequeña parcela de agua debe de\l"
	.string "conectar con el resto del LAGO por un\l"
	.string "estrecho túnel.$"

EventoLagoFuria5_Combate_Final_Texto_3:
.string "Una vez aparezca, mis POKÉMON le\n"
	.string "someterán, nos lo llevaremos para\l"
	.string "estudiarlo en profundidad.$"

EventoLagoFuria5_Combate_Final_Texto_4:
.string "PESCADOR: ¡No puedes hacer eso con un\n"
	.string "POKÉMON así!$"

EventoLagoFuria5_Combate_Final_Texto_5:
.string "????: Entonces admites que existe,\n"
	.string "debería dejarte aquí y dejar que\l"
	.string "volvieras solo, seguro que con tus\l"
	.string "mediocres POKÉMON no serías capaz de…$"

EventoLagoFuria5_Combate_Final_Texto_6:
.string "Hablando de POKÉMON mediocres, no\n"
	.string "pareces precisamente el caso.$"

EventoLagoFuria5_Combate_Final_Texto_7:
.string "Ya he oído hablar de esos ENTRENADORES\n"
	.string "legendarios en JOHTO, que se hacen\l"
	.string "llamar MAESTROS, tú eres demasiado\l"
	.string "joven para ser uno de ellos, y sin\l"
	.string "embargo estás aquí.$"

EventoLagoFuria5_Combate_Final_Texto_8:
.string "Pero careces de las herramientas para\n"
	.string "hacer frente a mis POKÉMON.$"

EventoLagoFuria5_Combate_Final_Texto_9:
.string "¡Necesitarás algo más que vagar por los\n"
	.string "pueblos y rutas de esta primitiva\l"
	.string "región para derrotar a uno de los\l"
	.string "EJECUTIVOS de la todopoderosa DEVON!$"

EventoLagoFuria5_Combate_Final_Texto_10:
.string "¿Quién eres tú? ¡Ningún entrenador de\n"
	.string "ruta en esta región podría derrotarme!$"

EventoLagoFuria5_Combate_Final_Texto_11:
.string "Esos POKÉMON… Han vivido algo más que\n"
	.string "vagar sin rumbo por rutas y pueblos,\l"
	.string "son…una mezcla de nuestra tecnología,\l"
	.string "pero también del vínculo con los\l"
	.string "POKÉMON que caracteriza a esta región.$"

EventoLagoFuria5_Combate_Final_Texto_12:
.string "Tú… ¡Debes pertencer a alguna clase de\n"
	.string "organizac…!$"

EventoLagoFuria5_Combate_Final_Texto_13:
.string "¡El POKÉMON salvaje quiere luchar\n"
	.string "contigo!$"

EventoLagoFuria5_Combate_Final_Texto_14:
.string "...$"

EventoLagoFuria5_Combate_Final_Texto_15:
.string "¡El POKÉMON salvaje desapareció!$"

EventoLagoFuria5_Combate_Final_Texto_16:
.string "PESCADOR: S..Si que eran ciertas las\n"
	.string "leyendas.$"

EventoLagoFuria5_Combate_Final_Texto_17:
.string "????: Debo darte las gracias,\n"
	.string "ENTRENADOR, has hecho el trabajo por\l"
	.string "nosotros. Gracias a tu combate con la\l"
	.string "bestia del LAGO, hemos podido reunir\l"
	.string "sus datos fundamentales.$"

EventoLagoFuria5_Combate_Final_Texto_18:
.string "Así que 82 de BASE en VELOCIDAD… Debe\n"
	.string "haber evolucionado durante millones de\l"
	.string "años, hasta convertirse en un\l"
	.string "depredador de GYARADOS, su sólida\l"
	.string "DEFENSA y unos STATS BASE totales 1\l"
	.string "solo punto superiores a GYARADOS MEGA\l"
	.string "refuerzan este hecho…$"

EventoLagoFuria5_Combate_Final_Texto_19:
.string "Mmm… Se trata de un POKÉMON a medio\n"
	.string "camino entre un LEGENDARIO MENOR, y un\l"
	.string "LEGENDARIO MAYOR, al menos en cuanto a\l"
	.string "poder. Sus abundantes PS podrían\l"
	.string "implicar algún parentesco lejano con\l"
	.string "LAPRAS, también…$"

EventoLagoFuria5_Combate_Final_Texto_20:
.string "Expectativas cumplidas, con esto\n"
	.string "tenemos suficiente. Una pena que\l"
	.string "hayas espantado al monstruo, ni tú ni\l"
	.string "yo podremos tenerlo al fin y al cabo,\l"
	.string "pero nosotros al menos tenemos los\l"
	.string "datos que queríamos.$"

EventoLagoFuria5_Combate_Final_Texto_21:
.string "Que tengáis un buen día, espero por tu\n"
	.string "bien que no nos volvamos a ver, de no\l"
	.string "ser así, tu destino será completamente\l"
	.string "distinto a lo ocurrido aquí hoy.$"

EventoLagoFuria5_Combate_Final_Texto_22:
.string "PESCADOR: Me has salvado.\n"
	.string "¿{PLAYER}?. Te debo un gran favor,\l"
	.string "quién sabe lo que esos tipos me\l"
	.string "hubieran hecho una vez obtenido lo que\l"
	.string "querían.$"

EventoLagoFuria5_Combate_Final_Texto_23:
.string "Aunque tenía razón en lo que dijo, ese\n"
	.string "POKÉMON parece hecho a medida para\l"
	.string "derrotar a GYARADOS, su fuerza y\l"
	.string "velocidad son mayores, deben quedar\l"
	.string "poquísimos ejemplares, de lo contrario\l"
	.string "no quedarían GYARADOS en el LAGO. Me\l"
	.string "pregunto si este será el último\l"
	.string "ejemplar vivo que qued…$"

EventoLagoFuria5_Combate_Final_Texto_24:
.string "¡Espera!$"

EventoLagoFuria5_Combate_Final_Texto_25:
.string "¡Parece que el POKÉMON ha dejado un\n"
	.string "HUEVO!$"

EventoLagoFuria5_Combate_Final_Texto_26:
.string "Entonces, ¿no es LEGENDARIO? ¿Contará\n"
	.string "con una línea evolutiva igual que el\l"
	.string "resto de POKÉMON normales?$"

EventoLagoFuria5_Combate_Final_Texto_27:
.string "No creo que a esos tipos les agrade\n"
	.string "haber ignorado esta información, ¿no\l"
	.string "crees?$"

EventoLagoFuria5_Combate_Final_Texto_28:
.string "Si alguien debe de tener este HUEVO,\n"
	.string "eres tú, has demostrado cuidar de tus\l"
	.string "POKÉMON como lo haría el más sabio de\l"
	.string "nuestros maestros en JOHTO.$"

EventoLagoFuria5_Combate_Final_Texto_29:
.string "¡OBTUVISTE UN HUEVO MISTERIOSO!$"

EventoLagoFuria5_Combate_Final_Texto_30:
.string "Te estaré siempre agradecido, si\n"
	.string "quieres visitar mi casa del LAGO,\l"
	.string "estaré encantado de hablar contigo.\l"
	.string "¿Quieres volver al exterior conmigo?$"
