CeruleanCity_MapScripts::
	.byte 0

CeruleanCity1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Esta es la CUEVA CELESTE.\n"
.string "Un POKÉMON terriblemente fuerte\l"
.string "reside aquí.\l"
.string "La entrada está prohibida para\l"
.string "toda la población de KANTO, sólo\l"
.string "la ÉLITE 4 tiene el permiso para\l"
.string "entrar aquí.\l"
.string "¡Imagínate el permiso que tienes\l"
.string "tú, ROCKET!\l"
.string "¡Más te vale guardar las\l"
.string "distancias!$"


CeruleanCity2::
end


CeruleanCity3::
end


CeruleanCity4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "¡Eres increíble, {PLAYER}!\n"
.string "¿Viste su cara cuando tumbaste\l"
.string "facilmente a sus supuestos POKÉMON\l"
.string "de élite con EXCAVAR?\l"
.string "Espero que nuestra recompensa haya\l"
.string "sido de tu agrado, yo me quedaré\l"
.string "un rato más por aquí. ¡Tranquilo,\l"
.string "nadie va a quitarme ya esta MT\l"
.string "EXCAVAR!$"


CeruleanCity5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "¿Eres un ROCKET?\n"
.string "Robar, defraudar, extorsionar y\l"
.string "mentir, ¡qué vida tan dura la\l"
.string "vuestra!$"


CeruleanCity6::
end


CeruleanCity7::
end


CeruleanCity8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "¿Quieres todos los POKÉMON y todo\n"
.string "el dinero del mundo para ti?\l"
.string "Interesante.$"


CeruleanCity9::
lock     
faceplayer     
msgbox Text_9, MSGBOX_DEFAULT
release     
end

Text_9:
.string "Quiero una bici roja nueva.\n"
.string "La mantendré en casa para que no\l"
.string "se ensucie.$"
