Violet_House1_MapScripts::
	.byte 0

VioletHouse1-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "El LÍDER de CIUDAD MALVA, PEGASO\n"
.string "padre, hizo hace poco una\l"
.string "demostración de sus habilidades.\l"
.string "Es un privilegio tener a un\l"
.string "ENTRENADOR como él por aquí. Cada\l"
.string "vez que vuelve de sus largos\l"
.string "viajes toda la ciudad le recibe\l"
.string "con los brazos abiertos.$"



VioletHouse1-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "¡Los he visto!\n"
.string "¡He visto los POKÉMON TIPO VOLADOR\l"
.string "del padre de PEGASO!\l"
.string "¡Uno de ellos era capaz de\l"
.string "absorber los ataques del TIPO\l"
.string "ELÉCTRICO!$"
