Violet_House1_MapScripts::
	.byte 0

VioletHouse1_1::
lock     
faceplayer     
msgbox VioletCity_House1_Text_1, MSGBOX_DEFAULT
release     
end

VioletCity_House1_Text_1:
	.string "Recently, FALKNER SR., the LEADER of\n"
	.string "VIOLET CITY, demonstrated his skills.\l"
	.string "It's a privilege to have a TRAINER of\l"
	.string "his caliber here. Whenever he returns\l"
	.string "from his lengthy journeys, the entire\l"
	.string "city welcomes him with open arms.$"



VioletHouse1_2::
lock     
faceplayer     
msgbox VioletCity_House1_Text_2, MSGBOX_DEFAULT
release     
end

VioletCity_House1_Text_2:
	.string "I've seen FALKNER SR.'s FLYING POKÉMON!\n"
	.string "One of them was able to absorb\l"
	.string "ELECTRIC attacks!$"
