CeruleanCity_House3_MapScripts::
	.byte 0

CeruleanCityHouse3_1::
lock     
faceplayer     
msgbox CeruleanCity_House3_Text_1, MSGBOX_DEFAULT
release     
end

CeruleanCity_House3_Text_1:
.string "Be careful with what you're doing,\n"
	.string "ROCKET. Here in CERULEAN CITY, we have\l"
	.string "the police just around the corner.$"



CeruleanCityHouse3_2::
lock     
faceplayer     
msgbox CeruleanCity_House3_Text_2, MSGBOX_DEFAULT
release     
end

CeruleanCity_House3_Text_2:
.string "Long ago, far away from here, in FLOE\n"
	.string "ISLAND, you could capture JYNX inside\l"
	.string "the ICEFALL CAVE. Now, I would trade\l"
	.string "one of those for a POLIWHIRL. I know\l"
	.string "it's a bad deal, but I no longer have the\l"
	.string "energy to capture a POLIWAG and evolve\l"
	.string "it on my own {PAUSE 15}…{PAUSE 15}…{PAUSE 15} …{PAUSE 15} How? You? I would\l"
	.string "never do business with a ROCKET!$"
