Ecruteak_TinTowerP8_MapScripts::
	.byte 0

TinTowerP8-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Evitar dar señales de debilidad\n"
.string "es señal de debilidad.$"



TinTowerP8-2::
end



TinTowerP8-3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "La verdad triunfa por sí misma, la\n"
.string "mentira necesita siempre\l"
.string "complicidad.$"



TinTowerP8-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "El único problema del que ríe el\n"
.string "último es que el ganador tiene que\l"
.string "reir solo.$"



TinTowerP8-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "Lo importante no es lo que una\n"
.string "persona tiene o no tiene, sino lo\l"
.string "que teme perder.$"



TinTowerP8-6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "En las adversidades sale a la luz\n"
.string "la virtud.$"
