VermilionCity_PokemonCenter_1F_MapScripts::
	.byte 0

VermilionCityPokemonCenter1::
end



VermilionCityPokemonCenter2::
lock     
faceplayer     
msgbox VermilionCity_PokemonCenter_Text_2, MSGBOX_DEFAULT
release     
end

VermilionCity_PokemonCenter_Text_2:
.string "¿Cómo?\n"
.string "¿El BUSCAPELEA?\l"
.string "¡Yo no hago regalos a ladrones de\l"
.string "tu calaña!$"



VermilionCityPokemonCenter3::
lock     
faceplayer     
msgbox VermilionCity_PokemonCenter_Text_3, MSGBOX_DEFAULT
release     
end

VermilionCity_PokemonCenter_Text_3:
.string "La sanidad es considerada como\n"
.string "esencial en cualquier región, es\l"
.string "por eso que vosotros, los\l"
.string "ROCKET, podéis entrar libremente a\l"
.string "curar en los CENTROS POKÉMON\l"
.string "públicos.$"



VermilionCityPokemonCenter4::
lock     
faceplayer     
msgbox VermilionCity_PokemonCenter_Text_4, MSGBOX_DEFAULT
release     
end

VermilionCity_PokemonCenter_Text_4:
.string "¡Mi POKÉMON fue envenenado!\n"
.string "¡Se debilitó mientras iba de\l"
.string "camino hacia el CENTRO POKÉMON!$"



VermilionCityPokemonCenter5::
lock     
faceplayer     
msgbox VermilionCity_PokemonCenter_Text_5, MSGBOX_DEFAULT
release     
end

VermilionCity_PokemonCenter_Text_5:
.string "Es cierto que un POKéMON de un\n"
.string "nivel superior es más fuerte.\p"
.string "Pero todos los POKéMON son\n"
.string "vulnerables ante ciertos tipos.\p"
.string "Es decir, que no hay POKéMON\n"
.string "invulnerables.$"
