SafariZone_1F_MapScripts::
	.byte 0

SafariZone1F_1::
end



SafariZone1FDocumento_100::
msgbox SafariZone1FDocumento_Text_100, MSGBOX_SIGN   
end

SafariZone1FDocumento_Text_100:
.string "PISTAS ENTRENADOR\p"
	.string "¡Pulsa START para saber cuánto\n"
	.string "tiempo te queda!$"



SafariZone1FDocumento_101::
msgbox SafariZone1FDocumento_Text_101, MSGBOX_SIGN   
end

SafariZone1FDocumento_Text_101:
.string "CASA DE REPOSO$"



SafariZone1FDocumento_102::
msgbox SafariZone1FDocumento_Text_102, MSGBOX_SIGN   
end

SafariZone1FDocumento_Text_102:
.string "ZONA CENTRAL$"
