ViridianCity_MapScripts::
	.byte 0

ViridianCity2::
end


ViridianCity3::
lock     
faceplayer     
msgbox ViridianCity_Text3, MSGBOX_DEFAULT
release     
end


ViridianCity_Text3:
.string "Nadie sabe la identidad del LÍDER\n"
.string "DE GIMNASIO de esta ciudad, pero\l"
.string "espero que vuelva para daros una\l"
.string "buena lección.$"


ViridianCity4::
end


ViridianCity5::
lock     
faceplayer     
msgbox ViridianCity_Text5, MSGBOX_DEFAULT
release     
end

ViridianCity_Text5:
.string "¿Cómo?\n"
.string "¿Enseñarte a atrapar POKÉMON?\l"
.string "¡Para así aprender a robarlos más\l"
.string "rápido, eh!\l"
.string "¡Jamás, ROCKET!$"


ViridianCity6::
lock     
faceplayer     
msgbox ViridianCity_Text6, MSGBOX_DEFAULT
release     
end

ViridianCity_Text6:
.string "Esas POKE BALL de tu cinturón…\n"
.string "¡Seguro que las has robado!$"


ViridianCity7::
end


ViridianCity8::
end


ViridianCity9::
lock     
faceplayer     
msgbox ViridianCity_Text9, MSGBOX_DEFAULT
release     
end

ViridianCity_Text9:
.string "¡Espero que nuestro LÍDER\n"
.string "misterioso vuelva pronto y os eche\l"
.string "a patadas de la ciudad!$"
