Ecruteak_TinTowerP7_MapScripts::
	.byte 0

TinTowerP7-1::
lock     
faceplayer     
msgbox Text_1, MSGBOX_DEFAULT
release     
end

Text_1:
.string "Más que nuestras habilidades, son\n"
.string "nuestras elecciones las que\l"
.string "muestran quiénes somos.$"



TinTowerP7-2::
end



TinTowerP7-3::
end



TinTowerP7-4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "El mañana valdrá la pena porque el\n"
.string "hoy vale la pena.$"



TinTowerP7-5::
end



TinTowerP7-6::
lock     
faceplayer     
msgbox Text_6, MSGBOX_DEFAULT
release     
end

Text_6:
.string "Lo peor que le puede ocurrir a\n"
.string "cualquiera es que se le comprenda\l"
.string "por completo.$"
