Silph_6F_MapScripts::
	.byte 0

Silph6F_1::
end



Silph6F_2::
end



Silph6F_3::
end



Silph6F_4::
end



Silph6F_5::
end



Silph6F_6::
end



Silph6F_7::
end



Silph6F_8::
end



Silph6F_9::
end



Silph6F_10::
end



Silph6F_EventScript_Policia::
	trainerbattle_single TRAINER_ISAIAH_4, Silph6F_Text_PoliciaIntro, Silph6F_Text_PoliciaDefeated
	msgbox Silph6F_PoliciaPostBattle, MSGBOX_AUTOCLOSE
	end



Silph6F_EventScript_Policia2::
	trainerbattle_single TRAINER_ISAIAH_5, Silph6F_Text_Policia2Intro, Silph6F_Text_Policia2Defeated
	msgbox Silph6F_Policia2PostBattle, MSGBOX_AUTOCLOSE
	end
