Route36_MapScripts::
	.byte 0

Route36-1::
end



Route36-2::
end



Route36-3::
end



Route36-4::
end



Route36-5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "A mi NIDORINO le encanta pasear\n"
.string "por estas rutas, a veces vamos al\l"
.string "ENCINAR a relajarnos.$"



Route36-6::
end



Route36-7::
lock     
faceplayer     
msgbox Text_7, MSGBOX_DEFAULT
release     
end

Text_7:
.string "Al parecer hay varios POKÉMON, de\n"
.string "los que se pensaba que no podían\l"
.string "evolucionar, que sí lo hacen, como\l"
.string "GLIGAR o AIPOM.\l"
.string "¿Qué más POKÉMON podrán\l"
.string "evolucionar sin saberlo la\l"
.string "mayoría?$"



Route36-8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "Me encanta PINSIR. A diferencia de\n"
.string "SCYTHER o HERACROSS, es un BICHO\l"
.string "puro de verdad, rápido, con un\l"
.string "gran ATAQUE y sólida DEFENSA. Lo\l"
.string "único que le falla es la\l"
.string "DEF.ESPECIAL[.]$"



Route36-9::
end



Route36-10::
end



Route36-11::
end
