Silph_8F_MapScripts::
	.byte 0

Silph8F-1::
end



Silph8F-2::
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2:
.string "¡Vuestro JEFE es un cruel\n"
.string "dictador!\l"
.string "¡Solo usa a los POKÉMON como armas\l"
.string "para lograr sus fines!\l"
.string "¡Alguien así nunca se hará con el\l"
.string "mando de SILPH!$"



Silph8F-3::
end



Silph8F-4::
end



Silph8F-5::
end



Silph8F-6::
end
