CeladonCity_MapScripts::
	.byte 0

CeladonCity1::
end


CeladonCity2::
end


CeladonCity3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "Este es mi fiel compañero,\n"
.string "POLIWRATH.\l"
.string "Evolucionó de POLIWHIRL cuando usé\l"
.string "una PIEDRA AGUA.$"


CeladonCity4::
lock     
faceplayer     
msgbox Text_4, MSGBOX_DEFAULT
release     
end

Text_4:
.string "¡Destruiremos a todo el que ose\n"
.string "interponerse en nuestro camino!$"


CeladonCity5::
lock     
faceplayer     
msgbox Text_5, MSGBOX_DEFAULT
release     
end

Text_5:
.string "Ejem[.]\n"
.string "¿No habrás sido tú el gracioso que\l"
.string "nos ha robado un ejemplar de SCOPE\l"
.string "SILPH, verdad?$"


CeladonCity6::
end


CeladonCity7::
lock     
faceplayer     
msgbox Text_7, MSGBOX_DEFAULT
release     
end

Text_7:
.string "¿Qué hay de nuevo camarada?\n"
.string "¿Mucho ajetreo con esas misiones?$"


CeladonCity8::
lock     
faceplayer     
msgbox Text_8, MSGBOX_DEFAULT
release     
end

Text_8:
.string "¡Ayyy! ¡Lo he perdido todo\n"
.string "en las tragaperras!\p"
.string "¡Debería haber cambiado todas\n"
.string "mis fichas por premios!$"


CeladonCity9::
end


CeladonCity10::
lock     
faceplayer     
msgbox Text_10, MSGBOX_DEFAULT
release     
end

Text_10:
.string "¡Aaaagh, ayyyy...!\n"
.string "¡Me he achicharrado la lengua!\p"
.string "La ancianita tan agradable que hay\n"
.string "en la MANSIÓN, me ha dado un TÉ.\p"
.string "¡Pero está hirviendo!\n"
.string "Voy a esperar a ver si se enfría...$"


CeladonCity11::
end


CeladonCity12::
end


CeladonCity13::
lock     
faceplayer     
msgbox Text_13, MSGBOX_DEFAULT
release     
end

Text_13:
.string "Conseguí a mi KOFFING en ISLA\n"
.string "CANELA.\l"
.string "Normalmente es muy bueno, pero\l"
.string "suelta veneno cuando se enfada.$"


CeladonCity14::
lock     
faceplayer     
msgbox Text_14, MSGBOX_DEFAULT
release     
end

Text_14:
.string "Nadie os quiere aquí ROCKETS.\n"
.string "¡Estáis destruyendo con vuestro\l"
.string "estúpido CASINO todos nuestros\l"
.string "intentos por mantener limpia esta\l"
.string "ciudad!$"
