NeoLavandaPkmnCenter_MapScripts::
	.byte 0


NeoLavandaPkmnCenter_2::
lock     
faceplayer     
msgbox NeoLavandaPkmnCenter_Text_2, MSGBOX_DEFAULT
release     
end

NeoLavandaPkmnCenter_Text_2:
.string "La CENTRAL ENERGÍA ha sido restaurada,\n"
.string "de ella ahora dependen el MAGNETOTRÉN\l"
.string "y la TORRE RADIO.$"



NeoLavandaPkmnCenter_3::
lock     
faceplayer     
msgbox NeoLavandaPkmnCenter_Text_3, MSGBOX_DEFAULT
release     
end

NeoLavandaPkmnCenter_Text_3:
.string "Vi a varios CUBONE en el TÚNEL ROCA,\n"
.string "deben de ser los que huyeron de TORRE\l"
.string "POKÉMON cuando se derrumbó.$"




NeoLavandaPkmnCenter_4::
lock     
faceplayer     
msgbox NeoLavandaPkmnCenter_Text_4, MSGBOX_DEFAULT
release     
end

NeoLavandaPkmnCenter_Text_4:
.string "Van a emitir programas de radio, dicen\n"
.string "que uno de ellos simula el sonido de una\l"
.string "POKÉ FLAUTA. ¡Qué guay!$"
