NeoLavandaPkmnCenter_MapScripts::
	.byte 0


NeoLavandaPkmnCenter_2::
lock     
faceplayer     
msgbox NeoLavandaPkmnCenter_Text_2, MSGBOX_DEFAULT
release     
end

NeoLavandaPkmnCenter_Text_2:
.string "La CENTRAL ENERGÍA ha sido restaurada,\n"
.string "de ella ahora dependen el MAGNETOTRÉN\l"
.string "y la TORRE RADIO.$"



NeoLavandaPkmnCenter_3::
lock     
faceplayer     
msgbox NeoLavandaPkmnCenter_Text_3, MSGBOX_DEFAULT
release     
end

NeoLavandaPkmnCenter_Text_3:
	.string "I saw several CUBONE in the ROCK\n"
	.string "TUNNEL; they must be the ones who fled\l"
	.string "from POKÉMON TOWER when it collapsed.$"




NeoLavandaPkmnCenter_4::
lock     
faceplayer     
msgbox NeoLavandaPkmnCenter_Text_4, MSGBOX_DEFAULT
release     
end

NeoLavandaPkmnCenter_Text_4:
	.string "It is said that there will be a radio\n"
	.string "program that plays POKÉ FLUTE music. So\l"
	.string "cool!$"
