PokemonLeague_6F_MapScripts::
	.byte 0

PokemonLeague_6F_Final::
msgbox PokemonLeague_6F_Final_Texto_1 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_2 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_3 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_4 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_5 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_6 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_7 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_8 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_9 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_10 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_11 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_12 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_13 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_14 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_15 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_16 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_17 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_18 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_19 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_20 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_21 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_22 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_23 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_24 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_25 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_26 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_27 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_28 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_29 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_30 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_31 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_32 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_33 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_34 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_35 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_36 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_37 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_38 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_39 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_40 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_41 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_42 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_43 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_44 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_45 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_46 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_47 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_48 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_49 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_50 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_51 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_52 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_53 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_54 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_55 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_56 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_57 MSGBOX_AUTOCLOSE
msgbox PokemonLeague_6F_Final_Texto_58 MSGBOX_AUTOCLOSE
release
end

PokemonLeague_6F_Final_Texto_1:
.string "(OAK terminó de registrar los\n"
	.string "datos de ROJO en el HALL DE LA\l"
	.string "FAMA).$"

PokemonLeague_6F_Final_Texto_2:
.string "OAK: Ya es oficial, eres el nuevo\n"
	.string "CAMPEÓN, has cumplido con el\l"
	.string "propósito por el que fuiste\l"
	.string "creado.$"

PokemonLeague_6F_Final_Texto_3:
.string "OAK: ...$"

PokemonLeague_6F_Final_Texto_4:
.string "OAK: Sé porqué estás aquí ROCKET,\n"
	.string "crees que coronándote CAMPEÓN\l"
	.string "ganarás la influencia suficiente\l"
	.string "como para limpiar la imagen del\l"
	.string "TEAM ROCKET y devolver el poder a\l"
	.string "la población de KANTO.$"

PokemonLeague_6F_Final_Texto_5:
.string "Conozco bien a tu LÍDER, quiso\n"
	.string "salvar la región a su manera y no\l"
	.string "trajo más que ruina.$"

PokemonLeague_6F_Final_Texto_6:
.string "De lo que no se dieron cuenta él y\n"
	.string "su estúpido séquito es de que\l"
	.string "enfocaron todo de la forma\l"
	.string "equivocada, crear un POKÉMON con\l"
	.string "un poder desmedido e incontrolable\l"
	.string "lleva precisamente a eso: a que no\l"
	.string "puedas controlarlo.$"

PokemonLeague_6F_Final_Texto_7:
.string "En cambio, dejamos sin explotar la\n"
	.string "parte más importante dentro de la\l"
	.string "ecuación que permite ganar\l"
	.string "combates.$"

PokemonLeague_6F_Final_Texto_8:
.string "Un ENTRENADOR invencible, capaz de\n"
	.string "tomar por sí mismo las mejores\l"
	.string "decisiones posibles en cuanto a\l"
	.string "captura de POKÉMON, estrategia en\l"
	.string "batalla, entrenamiento y\l"
	.string "asignación de objetos y\l"
	.string "movimientos, capaz de exprimir al\l"
	.string "máximo un equipo de 6 POKÉMON con\l"
	.string "los recursos de los que dispone.$"

PokemonLeague_6F_Final_Texto_9:
.string "¿Acaso no es eso mucho mejor que\n"
	.string "contar con un único POKÉMON\l"
	.string "hiperpoderoso, que aún será\l"
	.string "manejado por las torpes manos de\l"
	.string "un humano susceptible de error?$"

PokemonLeague_6F_Final_Texto_10:
.string "A los ojos del resto de mortales\n"
	.string "ROJO será visto como inalcanzable,\l"
	.string "puesto que él es el limite, yo me\l"
	.string "he encargado personalmente de que\l"
	.string "cubra hasta los topes todas las\l"
	.string "variables que influyen en un\l"
	.string "combate, es la combinación\l"
	.string "perfecta entre tecnología y\l"
	.string "humanidad, y los más importante...$"

PokemonLeague_6F_Final_Texto_11:
.string "A diferencia de MEWTWO, todo su\n"
	.string "potencial, las posibilidades que\l"
	.string "ofrece y sus recursos carecen de\l"
	.string "propósito, no hará preguntas, ROJO\l"
	.string "no es más que una cáscara vacía,\l"
	.string "lista para ser cubierta por\l"
	.string "cualquiera, adquiriendo así ROJO\l"
	.string "el propósito de aquel que lo\l"
	.string "maneja como una simple marioneta.$"

PokemonLeague_6F_Final_Texto_12:
.string "Comprenderás pues, la importancia\n"
	.string "de contar con un ser de estas\l"
	.string "características, en un mundo donde\l"
	.string "absolutamente todos como principio\l"
	.string "básico universal se callan la boca\l"
	.string "frente a ti si eres capaz de\l"
	.string "vencerles en un combate, y en el\l"
	.string "que llegar a ser CAMPEÓN de ese\l"
	.string "estúpido juego tiene el mismo peso\l"
	.string "que el propio GOBERNADOR, quien\l"
	.string "maneje a ROJO tiene el poder de\l"
	.string "cambiarlo todo, de adaptarse a\l"
	.string "cualquier situación y al final del\l"
	.string "día salir vencedor, no hay\l"
	.string "posibilidad de escape.$"

PokemonLeague_6F_Final_Texto_13:
.string "¿No te das cuenta?\n"
	.string "Nadie, ni LANCE, puede a largo\l"
	.string "plazo ante un ROJO expuesto al\l"
	.string "estímulo suficiente como para\l"
	.string "perfeccionar a su equipo.$"

PokemonLeague_6F_Final_Texto_14:
.string "¿Crees que no quiero emplearlo\n"
	.string "para salvar a KANTO de las manos\l"
	.string "de LANCE?\l"
	.string "¿Sino para dar comienzo a mi\l"
	.string "propia dictadura?$"

PokemonLeague_6F_Final_Texto_15:
.string "Siquiera dios tiene respuesta para\n"
	.string "eso, ROCKET, no tendrás forma de\l"
	.string "saberlo.$"

PokemonLeague_6F_Final_Texto_16:
.string "Entonces quieres detenerme, aún\n"
	.string "con todo lo que acabas de oír.$"

PokemonLeague_6F_Final_Texto_17:
.string "Muy propio de criminales como tú,\n"
	.string "se creen libres, con capacidad de\l"
	.string "elección y un mundo de\l"
	.string "posibilidades a sus pies, hasta\l"
	.string "que la realidad los tumba de un\l"
	.string "plumazo sin siquiera darles tiempo\l"
	.string "a asimilar qué ha ocurrido, de\l"
	.string "igual forma que el insecto\l"
	.string "que es aplastado en décimas de\l"
	.string "segundo.$"

PokemonLeague_6F_Final_Texto_18:
.string "Tendrás que disculpar a ROJO, el\n"
	.string "entrar al HALL DE LA FAMA era su\l"
	.string "razón de ser, más allá de ello, y\l"
	.string "una vez logrado su propósito, nada\l"
	.string "de lo que ocurra después podrá\l"
	.string "recordarlo, simplemente no existe\l"
	.string "para él, aún así, conserva\l"
	.string "intactas sus funciones de combate.$"


PokemonLeague_6F_Final_Texto_19:
.string "Nadie ha estado siquiera cerca\n"
	.string "de derrotarle, si así lo quieres\l"
	.string "tendrás lo que buscas, solo eres\l"
	.string "otro monigote más al que tendré\l"
	.string "que silenciar atendiendo a nuestro\l"
	.string "estúpido código del combate.$"

PokemonLeague_6F_Final_Texto_20:
.string "Adelante ROCKET.\n"
	.string "¡Enfrenta a la pared que jamás\l"
	.string "podrás sobrepasar por mayores que\l"
	.string "sean tus esfuerzos!$"

PokemonLeague_6F_Final_Texto_21:
.string "ROJO: ...$"

PokemonLeague_6F_Final_Texto_22:
.string "¡...!$"

PokemonLeague_6F_Final_Texto_23:
.string "¡NO!\n"
	.string "¡IMPOSIBLE!\l"
	.string "¡INCONCEBIBLE!$"

PokemonLeague_6F_Final_Texto_24:
.string "¡No puedes haber ganado!\n"
	.string "¡ROJO está hecho específicamente\l"
	.string "para este juego!\l"
	.string "¡No hay forma posible por la que\l"
	.string "tú hayas podido derrotarlo con los\l"
	.string "recursos de los que dispones y con\l"
	.string "los POKÉMON que puedes atrapar en\l"
	.string "KANTO!$"

PokemonLeague_6F_Final_Texto_25:
.string "¡No hay otra explicación posible!\n"
	.string "¡TÚ!\l"
	.string "¡Tú...!$"

PokemonLeague_6F_Final_Texto_26:
.string "????: Teníamos un trato, OAK.$"

PokemonLeague_6F_Final_Texto_27:
.string "OAK: Oh, LANCE...\n"
	.string "Y-yo...\l"
	.string "Estab...$"

PokemonLeague_6F_Final_Texto_28:
.string "LANCE: -Un ENTRENADOR inabordable,\n"
	.string "imbatible para cualquiera, capaz\l"
	.string "de asegurarnos un CAMPEÓN afín a\l"
	.string "nuestros intereses, imposible de\l"
	.string "desbancar y que mantendrá dicho\l"
	.string "puesto todo el tiempo del que\l"
	.string "gustemos-.$"

PokemonLeague_6F_Final_Texto_29:
.string "Esas fueron tus palabras OAK,\n"
	.string "cuando me convenciste de abrir de\l"
	.string "nuevo la opción de luchar por el\l"
	.string "título de la LIGA.$"

PokemonLeague_6F_Final_Texto_30:
.string "Me lo vendiste como una forma de\n"
	.string "devolver la ilusión y la esperanza\l"
	.string "a KANTO, además de un modo de\l"
	.string "obtener esa fidelidad y confianza\l"
	.string "en el sistema tan difícil de\l"
	.string "lograr, una estrategia brillante\l"
	.string "OAK, con la que obtendríamos lo\l"
	.string "que queremos sin comprometernos,\l"
	.string "pues el campeonato de la LIGA\l"
	.string "sería poco más que un espejismo\l"
	.string "para cualquier ciudadano, de por\l"
	.string "sí abrumado por el trabajo\l"
	.string "excesivo impidiéndole alcanzar la\l"
	.string "excelencia en cualquier cosa ajena\l"
	.string "a su vida cotidiana, más aún con\l"
	.string "un ENTRENADOR como ROJO, símbolo\l"
	.string "de la perfección y el tope en\l"
	.string "cuanto a combate se refiere, una\l"
	.string "hazaña estadísticamente imposible\l"
	.string "de lograr en esta región.$"

PokemonLeague_6F_Final_Texto_31:
.string "Resulta, OAK, que siquiera ha sido\n"
	.string "un ciudadano quien ha desbancado a\l"
	.string "tu obra maestra.\l"
	.string "¡HA SIDO UN ROCKET OAK!\l"
	.string "¡UN ROCKET!\l"
	.string "¡Tal vez subestimaste los efectos\l"
	.string "de ese trabajo excesivo del que\l"
	.string "hablaste como inhibidor del\l"
	.string "rendimiento, al menos para los\l"
	.string "capaces de sobrevivir a el y\l"
	.string "reconducirlo en la dirección\l"
	.string "adecuada!$"

PokemonLeague_6F_Final_Texto_32:
.string "OAK: Déjeme explicarle LANCE, ROJO\n"
	.string "aún no estaba listo, necesita\l"
	.string "exponerse a...$"

PokemonLeague_6F_Final_Texto_33:
.string "LANCE: Ya estoy harto de oirte\n"
	.string "hablar OAK, no quiero\l"
	.string "suposiciones, quiero resultados,\l"
	.string "haremos esto a mi manera.$"

PokemonLeague_6F_Final_Texto_34:
.string "LANCE: Debí advertir que algo así\n"
	.string "podría ocurrir contigo, cuando\l"
	.string "empleé un equipo de un nivel algo\l"
	.string "superior a lo que hize con los\l"
	.string "otros 3 competidores para quitarte\l"
	.string "rápidamente del medio, y aún así\l"
	.string "saliste ileso, ya me olía que algo\l"
	.string "como esto podría ocurrir, pero no\l"
	.string "te preocupes, no volveré a cometer\l"
	.string "ese error.$"

PokemonLeague_6F_Final_Texto_35:
.string "OAK: ¿Q-qué va a hacer?$"

PokemonLeague_6F_Final_Texto_36:
.string "OAK: E-estamos perdidos...\n"
	.string "Va...\l"
	.string "A...\l"
	.string "Volver a soltar las best...$"

PokemonLeague_6F_Final_Texto_37:
.string "LANCE: CAMPEÓN, GOBERNADOR, son\n"
	.string "solo palabras, quien tiene el\l"
	.string "poder controla el mundo.$"

PokemonLeague_6F_Final_Texto_38:
.string "¿Por qué crees que la gente adora\n"
	.string "y venera a los POKÉMON LEGENDARIOS\l"
	.string "y PSEUDOLEGENDARIOS?\l"
	.string "Así es, nos da igual de dónde\l"
	.string "provengan, lo único que nos\l"
	.string "interesa de ellos es que\l"
	.string "comparados con el resto de POKÉMON\l"
	.string "cuentan con un poder único y\l"
	.string "excepcional.$"

PokemonLeague_6F_Final_Texto_39:
.string "Ahí es donde radica su magia, en\n"
	.string "lo desconocido de ese poder, y en\l"
	.string "este caso inaccesible para el\l"
	.string "resto, que yo sepa la ciencia\l"
	.string "todavía no ha logrado reproducir\l"
	.string "la milagrosa combinación capaz de\l"
	.string "dar lugar a un POKÉMON LEGENDARIO.$"

PokemonLeague_6F_Final_Texto_40:
.string "Tantos años de duro trabajo para\n"
	.string "poder encontrar en la misma\l"
	.string "naturaleza frutos mejores OAK,\l"
	.string "fuiste un estúpido al creer que\l"
	.string "podrías jugar con las reglas del\l"
	.string "juego mejor que la propia\l"
	.string "creadora de dichas reglas.$"

PokemonLeague_6F_Final_Texto_41:
.string "Voy a hacer lo que debí haber\n"
	.string "hecho desde el principio, gobernar\l"
	.string "con puño de hierro esta región,\l"
	.string "quién mejor que yo, LANCE, el\l"
	.string "mayor especialista en el tipo más\l"
	.string "sagrado y poderoso que existe: el\l"
	.string "DRAGÓN, para ocupar ese cargo.$"

PokemonLeague_6F_Final_Texto_42:
.string "En cuanto a ti, después de\n"
	.string "aplastarte como a un vulgar\l"
	.string "insecto expondré públicamente lo\l"
	.string "que quede de ti y tu equipo, como\l"
	.string "ejemplo y aviso de lo que le\l"
	.string "espera a todo aquel que ose\l"
	.string "insubordinarse lo más mínimo en\l"
	.string "contra de mi gobierno.$"

PokemonLeague_6F_Final_Texto_43:
.string "Mira el lado bueno ROCKET, pasarás\n"
	.string "a la historia como aquel que\l"
	.string "obligó a LANCE I a hacer uso de\l"
	.string "sus sagrados POKÉMON justo antes\l"
	.string "de que diera inicio la nueva fase\l"
	.string "de su reinado...$"

PokemonLeague_6F_Final_Texto_44:
.string "LANCE: ...$"

PokemonLeague_6F_Final_Texto_45:
.string "LANCE: No hay honor en acabar con\n"
	.string "un rival menguado por el duro\l"
	.string "camino que le ha llevado hasta\l"
	.string "aquí, quiero que veas cómo aplasto\l"
	.string "a tu equipo en su apogeo, vas a\l"
	.string "entender de una vez por todas que\l"
	.string "existen poderes ante los que\l"
	.string "mortales como tú solo pueden\l"
	.string "arrodillarse.$"

PokemonLeague_6F_Final_Texto_46:
.string "¡¡YO SOY EL ESTADO!!$"

PokemonLeague_6F_Final_Texto_47:
.string "¡Mis dragones!\n"
	.string "¡Mis bestias sagradas!\l"
	.string "¿Cómo?$"

PokemonLeague_6F_Final_Texto_48:
.string "LANCE: Esto es imposible, nadie\n"
	.string "había opuesto resistencia a mis\l"
	.string "mejores POKÉMON, ¡son los mejores\l"
	.string "que existen!\l"
	.string "¡No puede encontrarse nada mejor\l"
	.string "que esto en todo KANTO!$"

PokemonLeague_6F_Final_Texto_49:
.string "????: Te equivocas LANCE.$"

PokemonLeague_6F_Final_Texto_50:
.string "GIOVANNI: Tu orgullo y tu\n"
	.string "arrogancia han sido tu perdición,\l"
	.string "mientras te dormías en los\l"
	.string "laureles de la seguridad que te\l"
	.string "proporcionaba un poder del que\l"
	.string "desconocías su origen, otros\l"
	.string "trabajábamos sin descanso,\l"
	.string "sabiendo cual era tu límite y\l"
	.string "tratando día a día de ir forjando\l"
	.string "un poder aún mayor.$"

PokemonLeague_6F_Final_Texto_51:
.string "Sin una necesidad que alimentara a\n"
	.string "tu poder, se ha debilitado,\l"
	.string "mientras tanto no había mayor\l"
	.string "estímulo para nosotros que el de\l"
	.string "tratar de desbancar tu tiranía, es\l"
	.string "hora de que le devuelvas a la\l"
	.string "tierra lo que le pertenece.$"

PokemonLeague_6F_Final_Texto_52:
.string "LANCE: ¡ENTEI, RAIKOU, SUICUNE!$"

PokemonLeague_6F_Final_Texto_53:
.string "GIOVANNI: ¡{PLAYER}!\n"
	.string "¡Jamás imaginé que pudieras llegar\l"
	.string "tan lejos!\l"
	.string "¡En cuanto ANDRA me avisó de la\l"
	.string "situación y de tu entrada al HALL\l"
	.string "DE LA FAMA decidí venir en persona\l"
	.string "aún a riesgo de atraer la atención\l"
	.string "mediática!\l"
	.string "¡Les has demostrado el\l"
	.string "incalculable valor de unos POKÉMON\l"
	.string "bien entrenados, sin importar su\l"
	.string "origen, has hecho de ellos unos\l"
	.string "campeones capaces de superar\l"
	.string "cualquier adversidad!$"

PokemonLeague_6F_Final_Texto_54:
.string "GIOVANNI: Aquellos que creían\n"
	.string "tener el control de todo cuanto\l"
	.string "les rodea, reduciendo todo a una\l"
	.string "simple ecuación.$"

PokemonLeague_6F_Final_Texto_55:
.string "OAK: ...$"

PokemonLeague_6F_Final_Texto_56:
.string "Y aquellos que jugaban a ser\n"
	.string "dioses, creyéndose superiores al\l"
	.string "resto por el mero hecho de serlo\l"
	.string "de nacimiento.$"

PokemonLeague_6F_Final_Texto_57:
.string "GIOVANNI: Has demostrado que en\n"
	.string "última instancia nada supera a la\l"
	.string "acción movida por una\l"
	.string "inquebrantable voluntad de lograr\l"
	.string "un objetivo.$"

PokemonLeague_6F_Final_Texto_58:
.string "GIOVANNI: ¡{PLAYER}!\n"
	.string "¡Nadie más que tú merece entrar a\l"
	.string "los anales de la historia quedando\l"
	.string "registrado en el HALL DE LA FAMA!\l"
	.string "¡Después de esto nada volverá a\l"
	.string "ser igual!$"

PokemonLeague_6F_Final_Move_1:
emote_exclamation_mark
step_end

PokemonLeague_6F_Final_Move_2:
walk_up
walk_up
walk_up
walk_up
walk_up
step_end

PokemonLeague_6F_Final_Move_3:
face_left
step_end

PokemonLeague_6F_Final_Move_4:
walk_slow_down
walk_in_place_down
step_end

PokemonLeague_6F_Final_Move_5:
walk_in_place_up
delay_1
delay_2
face_down
step_end

PokemonLeague_6F_Final_Move_6:
walk_slow_up
face_down
step_end

PokemonLeague_6F_Final_Move_7:
face_down
step_end

PokemonLeague_6F_Final_Move_8:
face_up
step_end

PokemonLeague_6F_Final_Move_9:
walk_in_place_down
step_end

PokemonLeague_6F_Final_Move_10:
walk_slow_down
walk_in_place_down
step_end

PokemonLeague_6F_Final_Move_11:
walk_fast_down
walk_fast_left
walk_in_place_down
step_end

PokemonLeague_6F_Final_Move_12:
walk_up
face_down
step_end

PokemonLeague_6F_Final_Move_13:
emote_exclamation_mark
face_down
step_end

PokemonLeague_6F_Final_Move_14:
walk_up
walk_up
walk_up
walk_up
step_end

PokemonLeague_6F_Final_Move_15:
slide_left
walk_in_place_down
step_end

PokemonLeague_6F_Final_Move_16:
walk_slow_up
walk_in_place_up
step_end

PokemonLeague_6F_Final_Move_17:
walk_slow_right
walk_in_place_right
step_end

PokemonLeague_6F_Final_Move_18:
walk_left
walk_in_place_up
step_end

PokemonLeague_6F_Final_Move_19:
walk_slow_up
walk_slow_up
step_end

PokemonLeague_6F_Final_Move_20:
walk_right
walk_up
walk_up
walk_up
step_end

PokemonLeague_6F_Final_Move_21:
walk_right
walk_in_place_up
step_end

PokemonLeague_6F_Final_Move_22:
walk_left
walk_in_place_down
step_end

PokemonLeague_6F_Final_Move_23:
walk_slow_down
walk_slow_down
walk_slow_down
walk_slow_down
step_end

PokemonLeague_6F_Final_Move_24:
walk_slow_right
walk_slow_right
walk_slow_up
walk_slow_right
walk_slow_up
walk_slow_up
step_end


PokemonLeague_6F_Final_Move_25:
walk_up
walk_left
walk_left
walk_left
walk_in_place_left
step_end

PokemonLeague_6F_Final_Move_26:
emote_exclamation_mark
face_right
step_end

PokemonLeague_6F_Final_Move_27:
walk_slow_down
walk_slow_down
walk_slow_left
walk_slow_down
walk_slow_left
walk_slow_left
walk_slow_down
walk_in_place_left
step_end

PokemonLeague_6F_Final_Move_28:
face_right
step_end

PokemonLeague_6F_Final_Move_29:
walk_slow_down
walk_in_place_left
step_end

PokemonLeague_6F_Final_Move_30:
walk_in_place_left
step_end

PokemonLeague_6F_Final_Move_31:
walk_up
step_end

PokemonLeague_6F_Final_Move_32:
walk_in_place_up
step_end

PokemonLeague_6F_Final_Move_33:
walk_slow_up
walk_slow_right
walk_slow_up
walk_in_place_up
step_end
