Ecruteak_BurnedTowerS1_MapScripts::
	.byte 0

BurnedTowerS1_2::
lock     
faceplayer     
msgbox Ecruteak_BurnedTower_Text_2, MSGBOX_DEFAULT
release     
end

Ecruteak_BurnedTower_Text_2:
.string "No pudimos hacer nada…$"



BurnedTowerS1_3::
lock     
faceplayer     
msgbox Ecruteak_BurnedTower_Text_3, MSGBOX_DEFAULT
release     
end

Ecruteak_BurnedTower_Text_3:
.string "Como esto siga así, terminará\n"
.string "por derrumbar lo que queda de TORRE\l"
.string "QUEMADA…$"



BurnedTowerS1_6::
lock     
faceplayer     
msgbox Ecruteak_BurnedTower_Text_6, MSGBOX_DEFAULT
release     
end

Ecruteak_BurnedTower_Text_6:
.string "Ese tipo…\n"
.string "Ha arrasado con todos nuestros\l"
.string "POKÉMON sin ningún esfuerzo…$"



BurnedTowerS1_7::
lock     
faceplayer     
msgbox Ecruteak_BurnedTower_Text_7, MSGBOX_DEFAULT
release     
end

Ecruteak_BurnedTower_Text_7:
.string "Jamás he visto tamaña fuerza\n"
.string "bruta, ¿será un LEGENDARIO de\l"
.string "alguna región lejana?$"
