PalletTown_MapScripts::
	.byte 0

PalletTown2::     
lock     
faceplayer     
msgbox Text_2, MSGBOX_DEFAULT
release     
end

Text_2: 
.string "El acceso a la tecnología debería\n"
.string "de estar prohibido para gente como\l"
.string "vosotros.$" 


PalletTown3::
lock     
faceplayer     
msgbox Text_3, MSGBOX_DEFAULT
release     
end

Text_3:
.string "¿Un ROCKET por aquí?\n"
.string "¿Qué estás tramando?$"
