Route38_MapScripts::
	.byte 0

Route38_1::
end



Route38_2::
lock     
faceplayer     
msgbox Route37_Text_2, MSGBOX_DEFAULT
release     
end

Route37_Text_2:
.string "DODRIO es mi ave preferida, me\n"
.string "encanta porque ataca sin ningún\l"
.string "miedo, sin mirar atrás. Su\l"
.string "combinación ATAQUE-VELOCIDAD es\l"
.string "única entre las aves.$"



Route38_3::
end



Route38_4::
end



Route38_5::
lock     
faceplayer     
msgbox Route37_Text_5, MSGBOX_DEFAULT
release     
end

Route37_Text_5:
.string "El comportamiento de los TAUROS y\n"
.string "MILTANK en estado salvaje es\l"
.string "fascinante.$"



Route38_6::
end
