Goldenrod_ShopCenterP5_MapScripts::
	.byte 0

GoldenrodShopCenterP5_1::
lock     
faceplayer     
msgbox Goldenrod_ShopP5_Text_1, MSGBOX_DEFAULT
release     
end

Goldenrod_ShopP5_Text_1:
	.string "In this city, there are some overly\n"
	.string "competitive trainers; I think they\l"
	.string "should relax and enjoy all the\l"
	.string "possibilities that GOLDENROD allows,\l"
	.string "and that's all. But we have the complete\l"
	.string "opposite with the snobs who have\l"
	.string "ruined the GYM, of course…$"



GoldenrodShopCenterP5_2::
lock     
faceplayer     
msgbox Goldenrod_ShopP5_Text_2, MSGBOX_DEFAULT
release     
end

Goldenrod_ShopP5_Text_2:
	.string "I'm going to have an amazing camping\n"
	.string "trip in the ILEX FOREST. I've been\l"
	.string "spending the last half hour just taking\l"
	.string "out sodas and lemonades one by one to\l"
	.string "save money!$"



GoldenrodShopCenterP5Documento_100::
msgbox GoldenrodShopCenterP5Documento_Text_100, MSGBOX_SIGN   
end

GoldenrodShopCenterP5Documento_Text_100:
.string "Take a Break from Shopping!\n"
	.string "6F TRANQUIL SQUARE$"
